# Generated by Django 5.2.16 on 2026-07-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_owner_capability_defaults'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(fields=['phone', 'consumed', '-created_at'], name='accounts_ot_phone_d78ea5_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyuser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='uniq_active_membership_per_user'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('phone',), name='uniq_user_phone_when_set'),
        ),
    ]
