# Generated by Django 5.2.16 on 2026-07-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_security_hardening_batch1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='can_view_financial_reports',
            field=models.BooleanField(default=False),
        ),
    ]
