# Generated by Django 5.2.16 on 2026-08-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staff_financial_reports_default_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='aato_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='einvoice_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='eway_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='eway_threshold_amount',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=14),
        ),
        migrations.AddField(
            model_name='company',
            name='gsp_credentials_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='gsp_provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='gstin_legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='gstin_raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='gstin_verification_status',
            field=models.CharField(blank=True, default='UNVERIFIED', max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='gstin_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
