# Generated by Django 5.2.16 on 2026-08-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_phase2_gst_returns_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ai_features_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_monthly_token_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='daily_summary_email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='opening_cash_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='opening_cash_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='can_use_ai_assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='can_view_ai_insights',
            field=models.BooleanField(default=False),
        ),
    ]
