# Generated by Django 5.2.16 on 2026-08-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_phase6_ai_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accounting_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='auto_match_bank_exact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='block_expired_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='inventory_valuation_method',
            field=models.CharField(choices=[('WAVG', 'Weighted Average'), ('FIFO', 'FIFO')], default='WAVG', max_length=8),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_gateway_credentials_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_gateway_provider',
            field=models.CharField(blank=True, default='razorpay', max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_gateway_test_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='require_payment_reference',
            field=models.BooleanField(default=False),
        ),
    ]
