# Generated by Django 5.2.16 on 2026-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_fifo_valuation_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stock_on_delivery_challan',
            field=models.BooleanField(default=False),
        ),
    ]
