# Generated by Django 5.2.16 on 2026-08-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_so_confirmed_reservation_challan_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner/Admin'), ('SALES_STAFF', 'Sales Staff'), ('ACCOUNTANT', 'Accountant'), ('VIEWER', 'Viewer')], default='SALES_STAFF', max_length=16),
        ),
    ]
