# Generated by Django 5.2.16 on 2026-08-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_document_line_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='payment_gateway_test_mode',
            field=models.BooleanField(default=False),
        ),
    ]
