# Generated by Django 5.2.16 on 2026-08-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_wave2_capability_defaults_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='can_post_journals',
            field=models.BooleanField(default=False),
        ),
    ]
