# Generated by Django 5.2.16 on 2026-08-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_wave13_ai_features_default_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inventory_valuation_method',
            field=models.CharField(choices=[('WAVG', 'Weighted Average'), ('FIFO', 'FIFO')], default='WAVG', help_text='WAVG uses blended remaining unit cost. FIFO consumes InventoryCostLayer rows in creation order for outbound COGS.', max_length=8),
        ),
    ]
