# Generated by Django 5.2.16 on 2026-08-04 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_wave16_gl_fifo_gstr2b'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGstin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gstin', models.CharField(max_length=15)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gstins', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'gstin'],
                'constraints': [models.UniqueConstraint(fields=('company', 'gstin'), name='uniq_company_gstin')],
            },
        ),
    ]
