# Generated by Django 5.2.16 on 2026-08-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_sprint1_invite_jti'),
    ]

    operations = [
        migrations.AddField(
            model_name='companygstin',
            name='address',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='companygstin',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='companygstin',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
