# Generated by Django 5.2.17 on 2026-08-28 09:21

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_custom_field_defs_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pan',
            field=models.CharField(blank=True, max_length=10, validators=[core.validators.validate_pan]),
        ),
        migrations.AlterField(
            model_name='company',
            name='udyam',
            field=models.CharField(blank=True, max_length=32, validators=[core.validators.validate_udyam]),
        ),
    ]
