# Generated by Django 5.2.17 on 2026-08-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_company_pan_alter_company_udyam'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='books_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
