# Generated by Django 5.2.17 on 2026-08-29 17:00
# R1-013: make document-number series scoping an explicit per-company policy.

from django.db import migrations, models


def lock_in_current_scope(apps, schema_editor):
    """A company that already has any CompanyGstin row is, under the old code,
    allocating from GSTIN+FY series — preserve that. Everyone else stays on the
    legacy company-wide series."""
    Company = apps.get_model("accounts", "Company")
    CompanyGstin = apps.get_model("accounts", "CompanyGstin")
    gstin_company_ids = set(
        CompanyGstin.objects.values_list("company_id", flat=True).distinct()
    )
    if gstin_company_ids:
        Company.objects.filter(id__in=gstin_company_ids).update(doc_number_scope="GSTIN_FY")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_company_books_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='doc_number_scope',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('GSTIN_FY', 'Gstin Fy')], default='COMPANY', max_length=16),
        ),
        migrations.RunPython(lock_in_current_scope, migrations.RunPython.noop),
    ]
