# Generated by Django 5.2.17 on 2026-09-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_one_primary_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='require_open_period_for_posting',
            field=models.BooleanField(default=False),
        ),
    ]
