# Generated by Django 5.2.17 on 2026-09-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_b8_036_valuation_flag_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_sandbox',
            field=models.BooleanField(default=False),
        ),
    ]
