# Generated by Django 5.2.17 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_b6_006_is_sandbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="sandbox_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
