# Generated by Django 5.2.17 on 2026-09-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_company_sandbox_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner/Admin'), ('MANAGER', 'Manager'), ('SALES_STAFF', 'Sales Staff'), ('INVENTORY_STAFF', 'Inventory Staff'), ('ACCOUNTANT', 'Accountant'), ('AUDITOR', 'Auditor'), ('VIEWER', 'Viewer')], default='SALES_STAFF', max_length=16),
        ),
    ]
