# Generated by Django 5.2.17 on 2026-09-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_companyuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantErasureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('requested_by_email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.TextField(blank=True)),
                ('export_sha256', models.CharField(blank=True, max_length=64)),
                ('erased_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-erased_at'],
            },
        ),
    ]
