# Generated by Django 5.2.17 on 2026-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_tenanterasurelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='erased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenanterasurelog',
            name='mode',
            field=models.CharField(default='hard', max_length=16),
        ),
        migrations.AddField(
            model_name='tenanterasurelog',
            name='retained_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
