# Generated by Django 5.2.17 on 2026-09-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_company_erased_at_tenanterasurelog_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_credit_hold_on_severe_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
