# Generated by Django 5.2.17 on 2026-09-11 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_company_auto_credit_hold_on_severe_overdue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStatutoryLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('licence_type', models.CharField(choices=[('DRUG_20B', 'Drug Licence — Form 20B (wholesale, non-Schedule X)'), ('DRUG_21B', 'Drug Licence — Form 21B (wholesale, Schedule X)'), ('FSSAI', 'FSSAI Licence/Registration')], max_length=16)),
                ('licence_number', models.CharField(max_length=64)),
                ('premises_address', models.CharField(blank=True, max_length=512)),
                ('premises_state', models.CharField(blank=True, max_length=64)),
                ('premises_city', models.CharField(blank=True, max_length=64)),
                ('premises_pincode', models.CharField(blank=True, max_length=10)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_upto', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_licences', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['licence_type', 'licence_number'],
                'constraints': [models.UniqueConstraint(fields=('company', 'licence_type', 'licence_number'), name='uniq_company_licence_type_number')],
            },
        ),
    ]
