# Generated by Django 5.2.17 on 2026-09-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_companystatutorylicence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link_code',
            field=models.CharField(blank=True, db_default='', default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
