# Generated by Django 5.2.17 on 2026-09-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_telegram_chat_id_db_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpchallenge',
            name='email',
            field=models.CharField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='otpchallenge',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(fields=['email', 'consumed', '-created_at'], name='accounts_ot_email_f4c31b_idx'),
        ),
    ]
