# Generated by Django 5.2.17 on 2026-09-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_otpchallenge_email_alter_otpchallenge_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_custom_field_defs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='party_custom_field_defs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='show_empty_signature_box',
            field=models.BooleanField(default=False),
        ),
    ]
