# Generated by Django 5.2.17 on 2026-09-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_whatsapp_webhook_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='can_manage_policies',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companystatutorylicence',
            name='licence_type',
            field=models.CharField(choices=[('DRUG_20B', 'Drug Licence — Form 20B (wholesale, non-Schedule X)'), ('DRUG_21B', 'Drug Licence — Form 21B (wholesale, Schedule X)'), ('FSSAI', 'FSSAI Licence/Registration'), ('POSP', 'POSP licence'), ('AGENCY', 'Insurance agency licence')], max_length=16),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner/Admin'), ('MANAGER', 'Manager'), ('SALES_STAFF', 'Sales Staff'), ('INVENTORY_STAFF', 'Inventory Staff'), ('ACCOUNTANT', 'Accountant'), ('AUDITOR', 'Auditor'), ('VIEWER', 'Viewer'), ('POLICY_DESK', 'Policy desk')], default='SALES_STAFF', max_length=16),
        ),
    ]
