# Generated by Django 5.2.17 on 2026-10-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_user_session_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bank_account',
            field=models.TextField(blank=True),
        ),
    ]
