import { readFileSync } from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import { describe, expect, it } from 'vitest';

/**
 * Frontend/backend contract test — guards against `domain.ts` silently
 * drifting from the real API shape (a renamed/removed backend field would
 * otherwise only surface as a runtime `undefined` deep in some page).
 *
 * `docs/openapi-snapshot.json` is generated by `manage.py spectacular
 * --format openapi-json` and diff-checked in CI (`.github/workflows/
 * ci.yml`'s `backend` job) — it's already guaranteed fresh relative to the
 * backend's actual serializers. Its property names are snake_case (drf-
 * spectacular introspects serializers directly); real API responses are
 * camelCase (`core/renderers.py`'s `EnvelopeJSONRenderer` wraps
 * `CamelCaseJSONRenderer`) — matching `domain.ts`. Convert before comparing.
 *
 * This only asserts domain.ts's declared fields are a SUBSET of the schema's
 * — many interfaces deliberately narrow to what the UI actually uses, so the
 * reverse (schema ⊆ domain.ts) is not required.
 *
 * To extend: add an entry to CONTRACT_ENTITIES. `schemaName` is only needed
 * when it differs from the TS interface name.
 */

const CONTRACT_ENTITIES: Array<{
  tsName: string;
  schemaName?: string;
  /**
   * Fields domain.ts declares that the backend genuinely does not return
   * today. Each entry here should point at a tracked follow-up, not be a
   * silent permanent exemption.
   */
  knownGaps?: string[];
}> = [
  { tsName: 'Customer' },
  {
    tsName: 'Product',
    // Only StockBalance (inventory/serializers.py) actually returns these;
    // Product never does. formatProductOptionLabel.ts falls back to them
    // when its explicit availableQty arg is omitted, which every real call
    // site avoids — harmless dead fallback, not a live-data bug.
    knownGaps: ['onHand', 'reserved', 'available'],
  },
  { tsName: 'CustomerReceipt' },
  { tsName: 'PaymentAllocation' },
  { tsName: 'AccountingAccount', schemaName: 'Account' },
  { tsName: 'PaymentLink' },
  { tsName: 'BankAccount' },
  { tsName: 'JournalEntry' },
];

const schemaPath = path.resolve(__dirname, '../../../docs/openapi-snapshot.json');
const schema = JSON.parse(readFileSync(schemaPath, 'utf-8')) as {
  components: { schemas: Record<string, { properties?: Record<string, unknown> }> };
};

function snakeToCamel(s: string): string {
  return s.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

function schemaFieldsFor(schemaName: string): Set<string> {
  const props = schema.components.schemas[schemaName]?.properties ?? {};
  return new Set(Object.keys(props).map(snakeToCamel));
}

/** Direct (non-nested) property names of a named `interface` in domain.ts. */
function domainInterfaceFields(sourceText: string, interfaceName: string): string[] {
  const sourceFile = ts.createSourceFile('domain.ts', sourceText, ts.ScriptTarget.Latest, true);
  let fields: string[] | null = null;

  sourceFile.forEachChild((node) => {
    if (ts.isInterfaceDeclaration(node) && node.name.text === interfaceName) {
      fields = node.members
        .filter(ts.isPropertySignature)
        .map((m) => m.name.getText(sourceFile));
    }
  });

  if (fields === null) {
    throw new Error(`interface ${interfaceName} not found in domain.ts`);
  }
  return fields;
}

const domainSource = readFileSync(path.resolve(__dirname, 'domain.ts'), 'utf-8');

describe('domain.ts matches the real API shape (docs/openapi-snapshot.json)', () => {
  for (const { tsName, schemaName, knownGaps = [] } of CONTRACT_ENTITIES) {
    it(`${tsName} fields exist on the backend`, () => {
      const declared = domainInterfaceFields(domainSource, tsName);
      const backendFields = schemaFieldsFor(schemaName ?? tsName);
      const missing = declared.filter((f) => !backendFields.has(f) && !knownGaps.includes(f));
      expect(missing, `domain.ts declares fields the backend doesn't return: ${missing.join(', ')}`).toEqual([]);
    });
  }
});
