# Generated by Django 5.2.16 on 2026-07-19 07:02

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('taxable_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('purchase_type', models.CharField(choices=[('GST', 'Gst'), ('NON_GST', 'Non Gst')], default='GST', max_length=8)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('supplier_bill_number', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.fileasset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='masters.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='masters.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('taxable_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('return_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchases.purchaseinvoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='masters.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='masters.product')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['company', 'status', 'invoice_date'], name='purchases_p_company_8a4f66_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('company', 'number'), name='uniq_purchase_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['company', 'status', 'return_date'], name='purchases_p_company_ca8052_idx'),
        ),
    ]
