# Generated by Django 5.2.16 on 2026-08-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_phase1_document_completeness'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecreditnoteitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='purchasecreditnoteitem',
            name='unit_name',
            field=models.CharField(blank=True, default='PCS', max_length=32),
        ),
        migrations.AddField(
            model_name='purchasecreditnoteitem',
            name='uqc_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='purchasedebitnoteitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='purchasedebitnoteitem',
            name='unit_name',
            field=models.CharField(blank=True, default='PCS', max_length=32),
        ),
        migrations.AddField(
            model_name='purchasedebitnoteitem',
            name='uqc_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='is_reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='price_mode',
            field=models.CharField(choices=[('EXCLUSIVE', 'Tax exclusive'), ('INCLUSIVE', 'Tax inclusive')], default='EXCLUSIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='rcm_cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='rcm_igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='rcm_sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='rcm_taxable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='uqc_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
