# Generated by Django 5.2.16 on 2026-08-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_purchaseinvoice_warehouse_purchaseitem_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
