# Generated by Django 5.2.16 on 2026-08-03 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_document_line_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecreditnote',
            name='purchase_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='purchases.purchasereturn'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='is_opening_balance',
            field=models.BooleanField(default=False),
        ),
    ]
