# Generated by Django 5.2.16 on 2026-08-03 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0014_wave10_opening_and_purchase_return_cn'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecreditnote',
            name='rcm_cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasecreditnote',
            name='rcm_igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasecreditnote',
            name='rcm_sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasecreditnote',
            name='rcm_taxable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasecreditnoteitem',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_items', to='purchases.purchaseitem'),
        ),
        migrations.AddField(
            model_name='purchasedebitnote',
            name='rcm_cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasedebitnote',
            name='rcm_igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasedebitnote',
            name='rcm_sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasedebitnote',
            name='rcm_taxable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
