# Generated by Django 5.2.16 on 2026-08-04 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stocktransferline_serial_numbers'),
        ('purchases', '0015_wave12c_gst_accounting_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.batchlot'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='purchasecreditnote',
            name='reason',
            field=models.CharField(choices=[('SALES_RETURN', 'Goods return'), ('PURCHASE_RETURN', 'Purchase return'), ('POST_SALE_DISCOUNT', 'Post-purchase discount'), ('DEFICIENCY_IN_SERVICE', 'Deficiency in service'), ('CORRECTION_OF_INVOICE', 'Correction of invoice'), ('OTHERS', 'Others')], default='CORRECTION_OF_INVOICE', max_length=32),
        ),
        migrations.AlterField(
            model_name='purchasedebitnote',
            name='reason',
            field=models.CharField(choices=[('SALES_RETURN', 'Goods return'), ('PURCHASE_RETURN', 'Purchase return'), ('POST_SALE_DISCOUNT', 'Post-purchase discount'), ('DEFICIENCY_IN_SERVICE', 'Deficiency in service'), ('CORRECTION_OF_INVOICE', 'Correction of invoice'), ('OTHERS', 'Others')], default='CORRECTION_OF_INVOICE', max_length=32),
        ),
    ]
