# Generated by Django 5.2.16 on 2026-08-05 03:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0016_wave13_return_batch_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecreditnote',
            name='cess_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasecreditnoteitem',
            name='cess',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasecreditnoteitem',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasedebitnote',
            name='cess_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasedebitnoteitem',
            name='cess',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasedebitnoteitem',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='cess_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='itc_eligibility',
            field=models.CharField(choices=[('CLAIMABLE', 'Claimable'), ('INELIGIBLE', 'Ineligible'), ('REVERSED', 'Reversed')], default='CLAIMABLE', help_text='Wave 18B: manual ITC eligibility — ineligible/reversed excluded from 3B claimable.', max_length=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='cess',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cess_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='cess',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='cess_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='cess',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
