# Generated by Django 5.2.17 on 2026-08-31 04:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0025_alter_purchasecreditnoteitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecreditnoteitem',
            name='applied_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasecreditnoteitem',
            name='rate_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasecreditnoteitem',
            name='rate_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchasecreditnoteitem',
            name='rate_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='purchasedebitnoteitem',
            name='applied_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasedebitnoteitem',
            name='rate_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasedebitnoteitem',
            name='rate_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchasedebitnoteitem',
            name='rate_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='applied_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='rate_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='rate_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='rate_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='applied_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='rate_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='rate_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='rate_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='applied_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='rate_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='rate_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='rate_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
