# Generated by Django 5.2.17 on 2026-09-03 04:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_company_require_open_period_for_posting'),
        ('masters', '0014_seed_hsn_rate_catalog'),
        ('purchases', '0028_alter_purchasecreditnote_round_off_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boe_number', models.CharField(db_index=True, max_length=32)),
                ('boe_date', models.DateField(default=django.utils.timezone.localdate)),
                ('port_code', models.CharField(blank=True, max_length=12)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('assessable_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('bcd_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('itc_eligibility', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('INELIGIBLE', 'Ineligible')], default='ELIGIBLE', max_length=12)),
                ('itc_period', models.CharField(blank=True, help_text='YYYY-MM period in which the import ITC is availed (defaults to boe_date month).', max_length=7)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills_of_entry', to='masters.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-boe_date', '-id'],
                'indexes': [models.Index(fields=['company', 'status', 'boe_date'], name='purchases_b_company_1a628d_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'boe_number'), name='uniq_bill_of_entry_number_per_company'), models.CheckConstraint(condition=models.Q(('igst_amount__gte', 0), ('cess_amount__gte', 0), ('bcd_amount__gte', 0)), name='bill_of_entry_amounts_non_negative')],
            },
        ),
    ]
