# Generated by Django 5.2.17 on 2026-09-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0029_billofentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofentry',
            name='icegate_verified',
            field=models.BooleanField(default=False),
        ),
    ]
