# Generated by Django 5.2.17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0030_billofentry_icegate_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseinvoice",
            name="bill_of_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_invoices",
                to="purchases.billofentry",
            ),
        ),
    ]
