# Generated by Django 5.2.17 on 2026-09-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0034_goodsreceipt_goodsreceiptitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ship_from',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ship_from_address',
            field=models.TextField(blank=True),
        ),
    ]
