from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import (
    CancelledDocumentNumbersView,
    CashBookView,
    Cmp08View,
    CustomerSalesView,
    DashboardView,
    ExportView,
    GstCaPackView,
    GstFilingSandboxView,
    GstHealthView,
    GstRateExposureView,
    GstPeriodView,
    Gstr1View,
    Gstr2bIngestViewSet,
    Gstr3bView,
    Gstr4View,
    Gstr6View,
    Gstr7View,
    Gstr8View,
    Gstr9View,
    InventorySummaryView,
    ProductSalesView,
    PurchaseRegisterView,
    SalesRegisterView,
    TcsWorksheetView,
    TdsWorksheetView,
)

router = DefaultRouter()
router.register("reports/gstr2b", Gstr2bIngestViewSet, basename="gstr2b")

urlpatterns = [
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("reports/sales-register/", SalesRegisterView.as_view(), name="sales-register"),
    path("reports/purchase-register/", PurchaseRegisterView.as_view(), name="purchase-register"),
    path("reports/inventory-summary/", InventorySummaryView.as_view(), name="inventory-summary"),
    path("reports/product-sales/", ProductSalesView.as_view(), name="product-sales"),
    path("reports/customer-sales/", CustomerSalesView.as_view(), name="customer-sales"),
    path("reports/cash-book/", CashBookView.as_view(), name="cash-book"),
    path("reports/gstr1/", Gstr1View.as_view(), name="gstr1"),
    path("reports/gstr3b/", Gstr3bView.as_view(), name="gstr3b"),
    path("reports/gstr9/", Gstr9View.as_view(), name="gstr9"),
    path("reports/cmp08/", Cmp08View.as_view(), name="cmp08"),
    path("reports/gstr4/", Gstr4View.as_view(), name="gstr4"),
    path("reports/gstr6/", Gstr6View.as_view(), name="gstr6"),
    path("reports/gstr7/", Gstr7View.as_view(), name="gstr7"),
    path("reports/gstr8/", Gstr8View.as_view(), name="gstr8"),
    path("reports/gst-filing-sandbox/", GstFilingSandboxView.as_view(), name="gst-filing-sandbox"),
    path("reports/cancelled-document-numbers/", CancelledDocumentNumbersView.as_view(), name="cancelled-document-numbers"),
    path("reports/gst-health/", GstHealthView.as_view(), name="gst-health"),
    path("reports/gst-rate-exposure/", GstRateExposureView.as_view(), name="gst-rate-exposure"),
    path("reports/gst-ca-pack/", GstCaPackView.as_view(), name="gst-ca-pack"),
    path("reports/gst-period/", GstPeriodView.as_view(), name="gst-period"),
    path("reports/tds-worksheet/", TdsWorksheetView.as_view(), name="tds-worksheet"),
    path("reports/tcs-worksheet/", TcsWorksheetView.as_view(), name="tcs-worksheet"),
    path("exports/<str:report>/", ExportView.as_view(), name="exports"),
] + router.urls
