# Generated by Django 5.2.17 on 2026-08-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscription',
            new_name='billing_sub_status_626969_idx',
            old_name='billing_sub_status_trial_idx',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended')], default='trial', max_length=16),
        ),
    ]
