# Generated by Django 5.2.17 on 2026-09-05 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_sub01_grandfather_pre_billing_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='billing.plan'),
        ),
    ]
