# Generated by Django 5.2 — plan quotas + dead-letter events

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_subscription_pending_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="monthly_complete_limit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="0 = unlimited completed sales+purchase invoices per calendar month.",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="storage_bytes_limit",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="0 = unlimited user-uploaded bytes (attachments/imports/logos).",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="api_rate_per_minute",
            field=models.PositiveIntegerField(
                default=0,
                help_text="0 = no extra per-tenant cap beyond global DRF throttles.",
            ),
        ),
        migrations.CreateModel(
            name="DeadLetterEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(db_index=True, max_length=64)),
                ("event_id", models.CharField(db_index=True, max_length=128)),
                ("payload", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("replayed", "Replayed"),
                            ("discarded", "Discarded"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("replayed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_dead_letters",
                        to="accounts.company",
                    ),
                ),
                (
                    "replayed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replayed_dead_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["provider", "status", "created_at"], name="billing_dlq_prov_st_ca_idx"),
                ],
            },
        ),
    ]
