# Generated by Django 5.2 — expand-only SaaS dunning cadence fields (8.5)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_plan_quotas_deadletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_dunning_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="last_dunning_step",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
