# Generated by Django 5.2.17 on 2026-10-04 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_planwave_remaining'),
        ('billing', '0012_trial_plan_narrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformGstInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=32)),
                ('capture_id', models.CharField(max_length=128)),
                ('number', models.CharField(blank=True, max_length=32)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('place_of_supply', models.CharField(blank=True, max_length=64)),
                ('platform_gstin', models.CharField(blank=True, max_length=15)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'provider', 'capture_id'), name='uniq_platform_gst_capture')],
            },
        ),
    ]
