/**
 * Complete-gate catalog (CG-01…CG-37).
 *
 * Source of truth for IDs: docs/COMPLETE_GATE_VISIBILITY_PLAN.md
 * `gated` rows must be cited in `testFile`. `gap` rows are planned, not yet UI-gated.
 */
export type CompleteGateKind = 'disabled' | 'click-fail' | 'contrast' | 'meta';
export type CompleteGateStatus = 'gated' | 'gap';

export interface CompleteGateCase {
  id: `CG-${string}`;
  surface: 'sales' | 'purchase' | 'notes' | 'pos' | 'shell' | 'order' | 'returns' | 'ops';
  kind: CompleteGateKind;
  status: CompleteGateStatus;
  /** Party + ≥1 line already set; this is the extra Complete blocker. */
  title: string;
  /** Path relative to repo root. Required when status is gated. */
  testFile: string | null;
}

export const COMPLETE_GATES: CompleteGateCase[] = [
  {
    id: 'CG-01',
    surface: 'sales',
    kind: 'disabled',
    status: 'gated',
    title: 'GST invoice, customer has no state and no GSTIN (place of supply unknown)',
    testFile: 'web/e2e/sales/complete-gates.spec.ts',
  },
  {
    id: 'CG-02',
    surface: 'sales',
    kind: 'disabled',
    status: 'gated',
    title: 'Regular GST company with empty company GSTIN',
    testFile: 'web/e2e-golden/gstin-prompt.spec.ts',
  },
  {
    id: 'CG-03',
    surface: 'sales',
    kind: 'disabled',
    status: 'gated',
    title: 'Negative-stock BLOCK and qty above available in the selected godown',
    testFile: 'web/e2e/sales/complete-gates.spec.ts',
  },
  {
    id: 'CG-04',
    surface: 'sales',
    kind: 'disabled',
    status: 'gated',
    title: 'Tax preview still in flight (no error) — Complete off with a named reason',
    testFile: 'web/src/completeGates/completeBlockers.test.ts',
  },
  {
    id: 'CG-05',
    surface: 'sales',
    kind: 'disabled',
    status: 'gated',
    title: 'Line exists but quantity is 0',
    testFile: 'web/e2e/sales/complete-gates.spec.ts',
  },
  {
    id: 'CG-06',
    surface: 'sales',
    kind: 'disabled',
    status: 'gated',
    title: 'Sales RCM on, confirm checkbox unticked',
    testFile: 'web/e2e/sales/complete-gates.spec.ts',
  },
  {
    id: 'CG-07',
    surface: 'sales',
    kind: 'disabled',
    status: 'gated',
    title: 'Customer on credit hold / stop-credit',
    testFile: 'web/e2e/sales/complete-gates.spec.ts',
  },
  {
    id: 'CG-08',
    surface: 'sales',
    kind: 'disabled',
    status: 'gated',
    title: 'Credit limit exceeded',
    testFile: 'web/e2e/sales/complete-gates.spec.ts',
  },
  {
    id: 'CG-09',
    surface: 'sales',
    kind: 'disabled',
    status: 'gated',
    title: 'Serial-tracked line: serial count ≠ qty',
    testFile: 'web/e2e/sales/complete-gates.spec.ts',
  },
  {
    id: 'CG-10',
    surface: 'sales',
    kind: 'contrast',
    status: 'gated',
    title: 'Batch-tracked sales line left blank stays Complete-enabled (FEFO)',
    testFile: 'web/e2e/sales/complete-gates.spec.ts',
  },
  {
    id: 'CG-11',
    surface: 'sales',
    kind: 'click-fail',
    status: 'gated',
    title: 'Invoice date in a closed GST period',
    testFile: 'web/e2e-golden/complete-gates-golden.spec.ts',
  },
  {
    id: 'CG-12',
    surface: 'sales',
    kind: 'click-fail',
    status: 'gated',
    title: 'Duplicate-bill / confirm-no-RCM / GSTIN tax-recompute confirms',
    testFile: 'web/src/completeGates/clickFailContracts.test.ts',
  },
  {
    id: 'CG-13',
    surface: 'sales',
    kind: 'disabled',
    status: 'gated',
    title: 'Subscription writes blocked',
    testFile: 'web/src/components/billing/DocumentEditorShell.test.tsx',
  },
  {
    id: 'CG-14',
    surface: 'sales',
    kind: 'disabled',
    status: 'gated',
    title: 'Completed e-invoice IRN lock, non-owner save',
    testFile: 'web/src/completeGates/clickFailContracts.test.ts',
  },
  {
    id: 'CG-15',
    surface: 'purchase',
    kind: 'disabled',
    status: 'gated',
    title: 'GST purchase, supplier has no state and no GSTIN',
    testFile: 'web/e2e/purchases/purchase-complete-gates.spec.ts',
  },
  {
    id: 'CG-16',
    surface: 'purchase',
    kind: 'disabled',
    status: 'gated',
    title: 'Batch-tracked purchase line with empty batch number',
    testFile: 'web/e2e/purchases/purchase-batch-complete.spec.ts',
  },
  {
    id: 'CG-17',
    surface: 'purchase',
    kind: 'disabled',
    status: 'gated',
    title: 'Serial-tracked purchase line missing serials or count ≠ qty',
    testFile: 'web/e2e/purchases/purchase-complete-gates.spec.ts',
  },
  {
    id: 'CG-18',
    surface: 'purchase',
    kind: 'disabled',
    status: 'gated',
    title: 'Purchase tax preview still in flight',
    testFile: 'web/src/completeGates/completeBlockers.test.ts',
  },
  {
    id: 'CG-19',
    surface: 'purchase',
    kind: 'disabled',
    status: 'gated',
    title: 'Purchase line quantity is 0',
    testFile: 'web/e2e/purchases/purchase-complete-gates.spec.ts',
  },
  {
    id: 'CG-20',
    surface: 'purchase',
    kind: 'disabled',
    status: 'gated',
    title: 'Regular GST company empty GSTIN — purchase FE-disables Complete (aligned with sales)',
    testFile: 'web/e2e/purchases/purchase-complete-gates.spec.ts',
  },
  {
    id: 'CG-21',
    surface: 'purchase',
    kind: 'click-fail',
    status: 'gated',
    title: 'Supplier has no GSTIN and RCM is off (confirm-no-RCM)',
    testFile: 'web/e2e-golden/complete-gates-golden.spec.ts',
  },
  {
    id: 'CG-22',
    surface: 'purchase',
    kind: 'click-fail',
    status: 'gated',
    title: 'Duplicate supplier bill number confirm',
    testFile: 'web/e2e-golden/complete-gates-golden.spec.ts',
  },
  {
    id: 'CG-23',
    surface: 'purchase',
    kind: 'click-fail',
    status: 'gated',
    title: 'Purchase date in a closed period',
    testFile: 'web/e2e-golden/complete-gates-golden.spec.ts',
  },
  {
    id: 'CG-24',
    surface: 'purchase',
    kind: 'disabled',
    status: 'gated',
    title: 'Subscription writes blocked on purchase',
    testFile: 'web/src/components/billing/DocumentEditorShell.test.tsx',
  },
  {
    id: 'CG-25',
    surface: 'notes',
    kind: 'disabled',
    status: 'gated',
    title: 'Credit/debit note preview pending or error — fallback banner, do not strand',
    testFile: 'web/e2e/notes/note-preview-complete.spec.ts',
  },
  {
    id: 'CG-26',
    surface: 'notes',
    kind: 'disabled',
    status: 'gated',
    title: 'Note lines all have quantity 0',
    testFile: 'web/e2e/notes/note-preview-complete.spec.ts',
  },
  {
    id: 'CG-27',
    surface: 'notes',
    kind: 'disabled',
    status: 'gated',
    title: 'Note line quantity above source document cap',
    testFile: 'web/e2e/notes/note-preview-complete.spec.ts',
  },
  {
    id: 'CG-28',
    surface: 'pos',
    kind: 'disabled',
    status: 'gated',
    title: 'POS cart has items but pay disabled (writes blocked / UPI pending / busy)',
    testFile: 'web/e2e/pos/pos-complete-gates.spec.ts',
  },
  {
    id: 'CG-29',
    surface: 'pos',
    kind: 'disabled',
    status: 'gated',
    title: 'POS batch-tracked line with no lot',
    testFile: 'web/e2e/pos/pos-complete-gates.spec.ts',
  },
  {
    id: 'CG-30',
    surface: 'pos',
    kind: 'click-fail',
    status: 'gated',
    title: 'POS serial-tracked line missing or mismatched serials',
    testFile: 'web/e2e/pos/pos-complete-gates.spec.ts',
  },
  {
    id: 'CG-31',
    surface: 'pos',
    kind: 'disabled',
    status: 'gated',
    title: 'POS stock BLOCK shortfall at pay',
    testFile: 'web/e2e/pos/pos-complete-gates.spec.ts',
  },
  {
    id: 'CG-32',
    surface: 'shell',
    kind: 'disabled',
    status: 'gated',
    title: 'Primary save pending (saving) greys Complete',
    testFile: 'web/src/components/billing/DocumentEditorShell.test.tsx',
  },
  {
    id: 'CG-33',
    surface: 'shell',
    kind: 'meta',
    status: 'gated',
    title: 'When Complete is disabled, tooltip is page-specific not generic party/item',
    testFile: 'web/src/components/billing/DocumentEditorShell.test.tsx',
  },
  {
    id: 'CG-34',
    surface: 'order',
    kind: 'disabled',
    status: 'gated',
    title: 'Sales/purchase order line quantity is 0 — Save names the reason',
    testFile: 'web/e2e/sales/extra-complete-gates.spec.ts',
  },
  {
    id: 'CG-35',
    surface: 'sales',
    kind: 'disabled',
    status: 'gated',
    title: 'Delivery challan zero qty disables Complete with a named reason',
    testFile: 'web/e2e/sales/extra-complete-gates.spec.ts',
  },
  {
    id: 'CG-36',
    surface: 'returns',
    kind: 'disabled',
    status: 'gated',
    title: 'Sales/purchase return Complete names missing line / permission / writes-blocked',
    testFile: 'web/e2e/sales/extra-complete-gates.spec.ts',
  },
  {
    id: 'CG-37',
    surface: 'ops',
    kind: 'disabled',
    status: 'gated',
    title: 'Payroll pay-run and work-order Complete name writes-blocked',
    testFile: 'web/src/completeGates/clickFailContracts.test.ts',
  },
];
