# Generated by Django 5.2.17 on 2026-10-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_roadmap_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='target_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
