# Generated by Django 5.2.16 on 2026-08-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_wave4_tenancy_rbac_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
