# Generated by Django 5.2.16 on 2026-08-04 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_wave12c_gst_accounting_fixes'),
        ('accounts', '0018_wave_c_can_post_journals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('company', 'number'), name='uniq_journal_number_per_company'),
        ),
    ]
