# Generated by Django 5.2.16 on 2026-08-04 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_wave15_depreciation_error'),
        ('accounts', '0020_wave16_gl_fifo_gstr2b'),
        ('masters', '0005_wave4_tenancy_rbac_constraints'),
        ('payments', '0008_wave16_gl_fifo_gstr2b'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='masters.customer'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='masters.supplier'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['company', 'customer', 'account'], name='jl_company_customer_acct_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['company', 'supplier', 'account'], name='jl_company_supplier_acct_idx'),
        ),
    ]
