# Generated by Django 5.2.17 on 2026-09-03 04:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_acc08_payrun_source_type_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='block_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='method',
            field=models.CharField(choices=[('SLM', 'Straight line'), ('WDV', 'Written down value')], default='SLM', max_length=3),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='salvage_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='wdv_annual_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
