# Generated by Django 5.2.17 on 2026-09-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_phase7_tally'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='provider',
            field=models.CharField(choices=[('TALLY', 'Tally'), ('WHATSAPP', 'Whatsapp'), ('BUSY', 'Busy'), ('ZOHO', 'Zoho'), ('SHOPIFY', 'Shopify')], max_length=32),
        ),
        migrations.AlterField(
            model_name='integrationsyncrun',
            name='kind',
            field=models.CharField(choices=[('TALLY_IMPORT', 'Tally Import'), ('TALLY_EXPORT', 'Tally Export'), ('TALLY_MIGRATE', 'Tally Migrate'), ('SHOPIFY_WEBHOOK', 'Shopify Webhook')], max_length=32),
        ),
    ]
