"""Render docs/PRODUCT_QUALITY_BACKLOG.md from qos/backlog/*.yaml.

Deterministic: stable sort keys, no timestamps in the body. Run twice -> identical.
`lint.py` check L7 fails CI if the committed doc is not this output.
"""

from __future__ import annotations

from _common import (
    BACKLOG_DOC,
    CATEGORIES,
    CATEGORY_EMOJI,
    CATEGORY_LABEL,
    OPEN_STATES,
    REPO_ROOT,
    enable_utf8_stdout,
    load_items,
)
import dashboard
import frontier

PRIORITY_ORDER = ["P0", "P0-confirm", "P1", "P1-investigate", "P2", "P3"]


def _prio_key(p: str) -> int:
    return PRIORITY_ORDER.index(p) if p in PRIORITY_ORDER else len(PRIORITY_ORDER)


def _rel(path) -> str:
    return "../qos/backlog/" + path.name


def render(items: dict[str, dict]) -> str:
    out: list[str] = []
    out.append("# Product Quality Backlog")
    out.append("")
    out.append(
        "> GENERATED by `qos/tools/build_backlog.py` from `qos/backlog/*.yaml` - "
        "**do not hand-edit**. Edit the item YAML and regenerate."
    )
    out.append(">")
    out.append(
        "> Method: [`Q-OS_QUALITY_PIPELINE_PLAN.md`](Q-OS_QUALITY_PIPELINE_PLAN.md) · "
        "Build: [`Q-OS_IMPLEMENTATION_RUNBOOK.md`](Q-OS_IMPLEMENTATION_RUNBOOK.md) · "
        "Scoring: [`../qos/RUBRIC.md`](../qos/RUBRIC.md) · "
        "Traceability: [`../qos/backlog/_SOURCE_MAP.md`](../qos/backlog/_SOURCE_MAP.md)"
    )
    out.append("")
    out.append(dashboard.render_block(items, with_trend=False))
    out.append("")
    out.append(frontier.render_md(frontier.compute(items)))
    out.append("")

    non_terminal = [
        it for it in items.values()
        if it.get("lifecycle") not in ("accepted_wontfix",)
    ]

    for idx, cat in enumerate(CATEGORIES, 1):
        rows = sorted(
            (it for it in non_terminal if it["category"] == cat),
            key=lambda it: (_prio_key(it["priority"]), it["id"]),
        )
        open_n = sum(1 for it in rows if it.get("lifecycle") in OPEN_STATES)
        out.append(f"## {idx}. {CATEGORY_EMOJI[cat]} {CATEGORY_LABEL[cat]}  ({open_n} open / {len(rows)} tracked)")
        out.append("")
        if not rows:
            out.append("_None._")
            out.append("")
            continue
        if cat == "INNOVATION":
            out.append("| id | title | why now / why us | expected value | effort | lifecycle |")
            out.append("|---|---|---|---|---|---|")
            for it in rows:
                why = it.get("priority_rationale", "").strip().replace("\n", " ")
                out.append(
                    f"| [{it['id']}]({_rel(it['_path'])}) | {it['title']} | {why} | "
                    f"{it.get('business_metric', 'none')} | {it['effort']} | {it['lifecycle']} |"
                )
            out.append("")
            continue
        out.append("| id | title | persona | journey | priority | effort | evidence | impact | owner | lifecycle |")
        out.append("|---|---|---|---|---|---|---|---|---|---|")
        for it in rows:
            out.append(
                f"| [{it['id']}]({_rel(it['_path'])}) | {it['title']} | "
                f"{','.join(it['persona'])} | {it['journey']} | {it['priority']} | "
                f"{it['effort']} | {it['evidence']['strength']} | "
                f"{it['scoring']['impact_band']} | {it['owner']} | {it['lifecycle']} |"
            )
        out.append("")

    wontfix = sorted(
        (it for it in items.values() if it.get("lifecycle") == "accepted_wontfix"),
        key=lambda it: it["id"],
    )
    out.append(f"## Accepted / won't-fix  ({len(wontfix)})")
    out.append("")
    out.append("> Deliberately out of scope. Rationale carried from `FREEZE_SCOPE.md` §B/§C. "
               "Do not re-raise without a scope change.")
    out.append("")
    if wontfix:
        out.append("| id | title | category | why | source |")
        out.append("|---|---|---|---|---|")
        for it in wontfix:
            why = (it.get("wontfix_rationale") or "").strip().replace("\n", " ")
            src = "; ".join(it["evidence"]["source"][:2])
            out.append(f"| [{it['id']}]({_rel(it['_path'])}) | {it['title']} | {it['category']} | {why} | {src} |")
        out.append("")
    else:
        out.append("_None yet._")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    enable_utf8_stdout()
    items, errors = load_items()
    if errors:
        for path, err in errors:
            print(f"cannot build: {path}: {err}")
        return 1
    BACKLOG_DOC.write_text(render(items), encoding="utf-8")
    print(f"wrote {BACKLOG_DOC.relative_to(REPO_ROOT)} ({len(items)} items)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
