# Generated by Django 5.2.17 on 2026-08-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_sprint_b_lead_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
