# Generated by Django 5.2.17 on 2026-09-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_address_lead_gstin_lead_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
