# Generated by Django 5.2.17 on 2026-09-24 18:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_whatsapp_webhook_token'),
        ('crm', '0007_lead_ingest_job_running'),
        ('masters', '0020_customer_pincode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reward_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='probability',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('DIGITAL', 'Digital'), ('REFERRAL', 'Referral'), ('EVENT', 'Event'), ('MARKET_VISIT', 'Market Visit')], max_length=16)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('target_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expected_outcome', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crm.campaign')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.campaign'),
        ),
        migrations.CreateModel(
            name='OpportunityLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.opportunity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_lines', to='masters.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16)),
                ('reward_type', models.CharField(choices=[('FLAT', 'Flat'), ('PERCENT', 'Percent')], default='FLAT', max_length=16)),
                ('reward_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('referrer_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_codes', to='masters.customer')),
                ('referrer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_codes', to='accounts.companyuser')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='referral_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.referralcode'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'campaign'], name='crm_lead_company_campaign_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'referral_code'], name='crm_lead_company_referral_idx'),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_rewards', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_rewards', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='referral_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to='crm.referralcode'),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['company', 'parent'], name='crm_camp_co_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['company', 'status'], name='crm_camp_co_status_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityline',
            index=models.Index(fields=['company', 'opportunity'], name='crm_opline_company_opp_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['company', 'referrer_customer'], name='crm_refcode_company_cust_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['company', 'referrer_user'], name='crm_refcode_company_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralcode',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='crm_referral_code_company_uniq'),
        ),
        migrations.AddConstraint(
            model_name='referralcode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('referrer_customer__isnull', False), ('referrer_user__isnull', True)), models.Q(('referrer_customer__isnull', True), ('referrer_user__isnull', False)), _connector='OR'), name='crm_referral_code_exactly_one_referrer'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['company', 'reward_status'], name='crm_refrew_co_status_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['company', 'referral_code'], name='crm_refreward_company_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralreward',
            constraint=models.UniqueConstraint(fields=('company', 'opportunity'), name='crm_referral_reward_opp_uniq'),
        ),
    ]
