# Generated by Django 5.2.17 on 2026-09-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_growth_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_touched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage_move_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
