# Generated by Django 5.2.17 on 2026-08-29 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stocktransferline_company'),
        ('manufacturing', '0007_alter_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.batchlot'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='batch_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='workorder',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderline',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
