# Generated by Django 5.2.17 on 2026-09-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_company_require_open_period_for_posting'),
        ('inventory', '0017_alter_stockmovement_unit_cost'),
        ('manufacturing', '0008_workorder_batch_workorder_batch_no_and_more'),
        ('masters', '0015_fix_hsn_cess_unresolved_post_cutover'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='bomline_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='workorderline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='workorderline_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='workorderline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_per_unit__gt', 0)), name='workorderline_qty_per_unit_gt_0'),
        ),
    ]
