# Generated by Django 5.2.16 on 2026-07-25 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_security_hardening_batch1'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('gstin', ''), _negated=True), fields=('company', 'gstin'), name='uniq_customer_gstin_per_company'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('company', 'barcode'), name='uniq_product_barcode_per_company'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('gstin', ''), _negated=True), fields=('company', 'gstin'), name='uniq_supplier_gstin_per_company'),
        ),
    ]
