# Generated by Django 5.2.16 on 2026-08-02 06:55

from django.db import migrations, models


def backfill_unit_uqc(apps, schema_editor):
    Unit = apps.get_model("masters", "Unit")
    aliases = {
        "PCS": "PCS", "PC": "PCS", "NOS": "NOS", "NO": "NOS",
        "KG": "KGS", "KGS": "KGS", "GMS": "GMS", "GM": "GMS",
        "LTR": "LTR", "L": "LTR", "MTR": "MTR", "M": "MTR",
        "BOX": "BOX", "CTN": "CTN", "BAG": "BAG", "SET": "SET",
    }
    for unit in Unit.objects.all():
        key = (unit.short_name or unit.name or "").strip().upper()
        code = aliases.get(key, "")
        if code and not unit.uqc_code:
            unit.uqc_code = code
            unit.save(update_fields=["uqc_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_concurrency_and_uniqueness_batch2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gstin_legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='gstin_raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gstin_verification_status',
            field=models.CharField(blank=True, default='UNVERIFIED', max_length=16),
        ),
        migrations.AddField(
            model_name='customer',
            name='gstin_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gstin_legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gstin_raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gstin_verification_status',
            field=models.CharField(blank=True, default='UNVERIFIED', max_length=16),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gstin_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='uqc_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.RunPython(backfill_unit_uqc, migrations.RunPython.noop),
    ]
