# Generated by Django 5.2.16 on 2026-08-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_wave4_tenancy_rbac_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='taxpayer_type',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('SEZWP', 'SEZ with payment'), ('SEZWOP', 'SEZ without payment'), ('EXPWP', 'Export with payment'), ('EXPWOP', 'Export without payment'), ('DEXP', 'Deemed export'), ('COMPOSITION', 'Composition'), ('UNREGISTERED', 'Unregistered')], default='REGULAR', max_length=16),
        ),
        migrations.AddField(
            model_name='supplier',
            name='taxpayer_type',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('SEZWP', 'SEZ with payment'), ('SEZWOP', 'SEZ without payment'), ('EXPWP', 'Export with payment'), ('EXPWOP', 'Export without payment'), ('DEXP', 'Deemed export'), ('COMPOSITION', 'Composition'), ('UNREGISTERED', 'Unregistered')], default='REGULAR', max_length=16),
        ),
    ]
