# Generated by Django 5.2.17 on 2026-08-23 19:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_expensecategory_paymentmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alternate_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_products', to='masters.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='default_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('GOODS', 'Goods'), ('SERVICE', 'Service')], db_index=True, default='GOODS', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_tax_inclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_tax_inclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
    ]
