# Generated by Django 5.2.17 on 2026-08-31 04:03

from datetime import date
from decimal import Decimal

import core.validators
from django.db import migrations, models


def seed_starter_rates(apps, schema_editor):
    HsnRate = apps.get_model("masters", "HsnRate")
    rows = [
        ("1905", Decimal("18"), date(2017, 7, 1), date(2025, 9, 21), "pre-gst2.0"),
        ("1905", Decimal("5"), date(2025, 9, 22), None, "gst2.0-2025-09-22"),
        ("2402", Decimal("28"), date(2017, 7, 1), date(2025, 9, 21), "pre-gst2.0"),
        ("2402", Decimal("40"), date(2025, 9, 22), None, "gst2.0-2025-09-22"),
    ]
    for hsn, rate, valid_from, valid_to, version in rows:
        HsnRate.objects.get_or_create(
            hsn_sac=hsn,
            version=version,
            defaults={
                "rate": rate,
                "cess": Decimal("0"),
                "valid_from": valid_from,
                "valid_to": valid_to,
                "source_ref": "starter-table",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0009_product_wholesale_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="HsnRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hsn_sac", models.CharField(db_index=True, max_length=8)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, validators=[core.validators.validate_gst_rate]
                    ),
                ),
                ("cess", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=5)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("version", models.CharField(max_length=64)),
                ("source_ref", models.CharField(blank=True, default="", max_length=128)),
            ],
            options={
                "ordering": ["hsn_sac", "-valid_from"],
                "indexes": [models.Index(fields=["hsn_sac", "valid_from"], name="masters_hsn_hsn_sac_ac953a_idx")],
            },
        ),
        migrations.RunPython(seed_starter_rates, migrations.RunPython.noop),
    ]
