# Generated by Django 5.2.17 on 2026-09-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_company_require_open_period_for_posting'),
        ('masters', '0015_fix_hsn_cess_unresolved_post_cutover'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.CheckConstraint(condition=models.Q(('min_qty__gt', 0)), name='pricelistitem_min_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='pricelistitem_unit_price_gte_0'),
        ),
    ]
