# Generated by Django 5.2.17 on 2026-09-09 17:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_pricelistitem_pricelistitem_min_qty_gt_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cess_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='product',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
