# Generated by Django 5.2.17 on 2026-09-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_product_cess_amount_product_cess_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='regulated_category',
            field=models.CharField(choices=[('NONE', 'Not regulated'), ('DRUG', 'Drug / pharmaceutical'), ('FOOD', 'Food (FSSAI)')], default='NONE', max_length=8),
        ),
    ]
