# Generated by Django 5.2.17 on 2026-10-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0024_supplier_specified_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
