# Generated by Django 5.2.17 on 2026-10-04 17:48

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_pur_open_defects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'base_manager_name': 'all_objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'base_manager_name': 'all_objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'base_manager_name': 'all_objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'base_manager_name': 'all_objects', 'ordering': ['name']},
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pricelist',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='supplier',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='drug_schedule',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='rack_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='salt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
