# Generated by Django 5.2.17 on 2026-10-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0026_planwave_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='gstin_cancelled_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
