# Generated by Django 5.2.17 on 2026-10-05 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_planwave_remaining'),
        ('masters', '0029_party_bank_account_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='uniq_customer_gstin_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='pricelist',
            name='uniq_price_list_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product_sku_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product_barcode_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='supplier',
            name='uniq_supplier_gstin_per_company',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('gstin', ''), _negated=True), ('is_deleted', False)), fields=('company', 'gstin'), name='uniq_customer_gstin_per_company'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'name'), name='uniq_price_list_per_company'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('sku', ''), _negated=True), ('is_deleted', False)), fields=('company', 'sku'), name='uniq_product_sku_per_company'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('barcode', ''), _negated=True), ('is_deleted', False)), fields=('company', 'barcode'), name='uniq_product_barcode_per_company'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('gstin', ''), _negated=True), ('is_deleted', False)), fields=('company', 'gstin'), name='uniq_supplier_gstin_per_company'),
        ),
    ]
