"""Generate docs/EVENT_MATRIX.md and the CROSS_FLOW summary table (P2-T2/T5).

    python validation/tools/build_event_matrix.py
    python validation/tools/build_event_matrix.py --selftest
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import jsonschema

from _common import (
    CROSS_FLOW_DOC,
    EVENT_DOC,
    EVENT_MATRIX_YAML,
    EVENT_SCHEMA,
    EVENTS_YAML,
    dump_yaml,
    load_json,
    load_yaml,
)

_BEGIN = "<!-- BEGIN GENERATED EVENT SUMMARY -->"
_END = "<!-- END GENERATED EVENT SUMMARY -->"

_IMPACT_COLS = (
    "stock",
    "gl",
    "ar_ap",
    "gst",
    "reports",
    "attention",
    "dashboard",
    "badge_ui",
    "channel",
    "historical_period",
)

_CORE_VERBS = {
    "complete",
    "cancel",
    "return",
    "credit_note",
    "debit_note",
    "allocate",
    "reverse_allocation",
    "void",
    "amend",
    "close_period",
    "stock_count",
    "stock_transfer",
}


def load_events() -> list[dict]:
    data = load_yaml(EVENTS_YAML) or {}
    events = list(data.get("events") or [])
    for ev in events:
        imp = ev.get("impacts") or {}
        for key, val in list(imp.items()):
            if val is True:
                imp[key] = "yes"
            elif val is False:
                imp[key] = "no"
        ev["impacts"] = imp
    return events


def validate_events(events: list[dict]) -> list[str]:
    schema = load_json(EVENT_SCHEMA)
    v = jsonschema.Draft202012Validator(schema)
    errors: list[str] = []
    seen = set()
    for ev in events:
        for e in sorted(v.iter_errors(ev), key=str):
            loc = "/".join(str(p) for p in e.path) or "(root)"
            errors.append(f"{ev.get('verb')}: {loc}: {e.message}")
        verb = ev.get("verb")
        if verb in seen:
            errors.append(f"duplicate verb: {verb}")
        seen.add(verb)
        if verb == "otp_login":
            errors.append("otp_login is not a catalog verb")
        if "pdf" in (ev.get("impacts") or {}):
            errors.append(f"{verb}: PDF is a named non-identity — do not add a pdf column")
    missing = _CORE_VERBS - seen
    if missing:
        errors.append(f"missing core verbs: {sorted(missing)}")
    return errors


def expand_rows(events: list[dict]) -> list[dict]:
    rows = []
    for ev in events:
        for doc in ev.get("document_types") or ["-"]:
            rows.append({
                "verb": ev["verb"],
                "document_type": doc,
                "extended": bool(ev.get("extended")),
                "g_ids": list(ev.get("g_ids") or []),
                "note": ev.get("note") or "",
                **ev["impacts"],
            })
    return rows


def render_matrix(events: list[dict]) -> str:
    rows = expand_rows(events)
    header = (
        "| Verb | Document | "
        + " | ".join(
            c.replace("_", " ") for c in _IMPACT_COLS
        )
        + " | G-ids |"
    )
    sep = "|" + "|".join(["---"] * (3 + len(_IMPACT_COLS))) + "|"
    lines = [
        "# Event impact matrix (Graph 2)",
        "",
        "> GENERATED by `validation/tools/build_event_matrix.py` — **do not hand-edit**. "
        "Edit `validation/catalog/events.yaml`. Per-field prose stays in "
        "`CROSS_FLOW_IMPACT_MAP.md` (this file is the summary table only).",
        "",
        "`historical_period = required` means a write dated into a closed period must be rejected (G-21/G-22).",
        "`channel` includes `/pay/:token`. There is **no PDF column** — PDF is a snapshot (B2), not a live projection.",
        "",
        header,
        sep,
    ]
    for row in rows:
        g = ", ".join(row["g_ids"]) or "—"
        cells = " | ".join(str(row[c]) for c in _IMPACT_COLS)
        lines.append(f"| `{row['verb']}` | `{row['document_type']}` | {cells} | {g} |")
    lines += [
        "",
        "## Core vs extended",
        "",
        "Core verbs (12): complete, cancel, return, credit_note, debit_note, allocate, "
        "reverse_allocation, void, amend, close_period, stock_count, stock_transfer.",
        "",
        "Extended: import, flag_flip, invite. `otp_login` is excluded.",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_cross_flow_block(events: list[dict]) -> str:
    lines = [
        _BEGIN,
        "",
        "**Generated event × projection summary** (P2-T5). Full grid: [`EVENT_MATRIX.md`](EVENT_MATRIX.md). "
        "Do not hand-edit this block.",
        "",
        "| Verb | Docs | stock | GL | AR/AP | GST | reports | attention | dash | badge | channel | closed-period |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for ev in events:
        docs = ", ".join(f"`{d}`" for d in ev["document_types"][:3])
        if len(ev["document_types"]) > 3:
            docs += ", …"
        imp = ev["impacts"]
        lines.append(
            f"| `{ev['verb']}` | {docs} | {imp['stock']} | {imp['gl']} | {imp['ar_ap']} | "
            f"{imp['gst']} | {imp['reports']} | {imp['attention']} | {imp['dashboard']} | "
            f"{imp['badge_ui']} | {imp['channel']} | {imp['historical_period']} |"
        )
    lines += ["", _END]
    return "\n".join(lines)


def patch_cross_flow(events: list[dict]) -> None:
    text = CROSS_FLOW_DOC.read_text(encoding="utf-8")
    block = render_cross_flow_block(events)
    if _BEGIN in text and _END in text:
        start = text.index(_BEGIN)
        end = text.index(_END) + len(_END)
        text = text[:start] + block + text[end:]
    else:
        needle = "## Quick index\n"
        idx = text.find(needle)
        if idx == -1:
            raise SystemExit("CROSS_FLOW_IMPACT_MAP.md has no Quick index heading")
        insert_at = text.find("\n---\n", idx)
        if insert_at == -1:
            text = text.rstrip() + "\n\n" + block + "\n"
        else:
            text = text[:insert_at] + "\n" + block + "\n" + text[insert_at:]
    CROSS_FLOW_DOC.write_text(text, encoding="utf-8")


def write_outputs(events: list[dict]) -> None:
    rows = expand_rows(events)
    dump_yaml({"rows": rows}, EVENT_MATRIX_YAML)
    EVENT_DOC.write_text(render_matrix(events), encoding="utf-8")
    patch_cross_flow(events)


def _selftest() -> int:
    events = load_events()
    errs = validate_events(events)
    if errs:
        print("FAIL events.yaml:")
        for e in errs:
            print(f"  {e}")
        return 1
    if any("pdf" in (e.get("impacts") or {}) for e in events):
        print("FAIL pdf column present")
        return 1
    if any(e.get("verb") == "otp_login" for e in events):
        print("FAIL otp_login present")
        return 1
    core = {e["verb"] for e in events if not e.get("extended")}
    if core != _CORE_VERBS:
        print(f"FAIL core verbs: {core}")
        return 1
    print("ok    12 core verbs, no pdf column, no otp_login")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    if args.selftest:
        return _selftest()
    events = load_events()
    errs = validate_events(events)
    if errs:
        print("events.yaml invalid:")
        for e in errs:
            print(f"  {e}")
        return 1
    write_outputs(events)
    print(f"wrote {EVENT_DOC} ({len(expand_rows(events))} verb×document rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
