# Generated by Django 5.2.16 on 2026-07-19 07:02

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('reserved', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='accounts.company')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balance', to='masters.product')),
            ],
            options={
                'unique_together': {('company', 'product')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('PURCHASE_RETURN', 'Purchase Return'), ('SALES_RETURN', 'Sales Return'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=64)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='masters.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'product', 'created_at'], name='inventory_s_company_0ef626_idx'), models.Index(fields=['company', 'movement_type'], name='inventory_s_company_339f3b_idx')],
            },
        ),
    ]
