# Generated by Django 5.2.16 on 2026-07-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockbalance',
            options={'ordering': ['product__name']},
        ),
    ]
