# Generated by Django 5.2.16 on 2026-08-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockbalance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferline',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
