# Generated by Django 5.2.16 on 2026-08-04 18:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_wave16_gl_fifo_gstr2b'),
        ('inventory', '0004_stocktransferline_serial_numbers'),
        ('masters', '0005_wave4_tenancy_rbac_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_remaining', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventory.batchlot')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='masters.product')),
                ('source_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_layers', to='inventory.stockmovement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['company', 'warehouse', 'product'], name='fifo_layer_lookup_idx')],
            },
        ),
    ]
