# Generated by Django 5.2.16 on 2026-08-05 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_sprint3_fifo_gstin_series'),
        ('inventory', '0006_manufacture_movement_types'),
        ('masters', '0006_wave17a_taxpayer_gstin_stamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='serialnumber',
            name='uniq_serial_per_company',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('PURCHASE_RETURN', 'Purchase Return'), ('SALES_RETURN', 'Sales Return'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('MANUFACTURE_ISSUE', 'Manufacture Issue'), ('MANUFACTURE_RECEIPT', 'Manufacture Receipt')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='serialnumber',
            constraint=models.UniqueConstraint(fields=('company', 'product', 'serial_number'), name='uniq_serial_per_company_product'),
        ),
    ]
