# Generated by Django 5.2.16 on 2026-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_sprint3_fifo_gstin_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='layer_peels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
