# Generated by Django 5.2.17 on 2026-08-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stocktransferline_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='import_job_ref',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
