# Generated by Django 5.2.17 on 2026-09-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_inv_move_co_prod_date_idx_inventory_s_company_c4a51e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('PURCHASE_RETURN', 'Purchase Return'), ('SALES_RETURN', 'Sales Return'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('MANUFACTURE_ISSUE', 'Manufacture Issue'), ('MANUFACTURE_RECEIPT', 'Manufacture Receipt')], max_length=32),
        ),
    ]
