# Generated by Django 5.2.17 on 2026-09-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_movement_type_maxlen_32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
