# Generated by Django 5.2.17 on 2026-09-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_reorder_lead_time_safety_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcountline',
            name='held_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
