# Generated by Django 5.2.17 on 2026-10-04 17:48

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_stockcountsession_blind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'base_manager_name': 'all_objects', 'ordering': ['name']},
        ),
        migrations.AlterModelManagers(
            name='warehouse',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
