# Generated by Django 5.2.17 on 2026-10-05 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_planwave_remaining'),
        ('inventory', '0026_backfill_transfer_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='uniq_warehouse_code_per_company',
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'code'), name='uniq_warehouse_code_per_company'),
        ),
    ]
