"""Answers to the 63 pre-implementation questions (2026-10-04), shared by build_plan.py and plan_to_md.py.

Status: Decided = settled by this plan; Confirm = default chosen, founder must confirm before the item starts;
External = needs a CA, pharmacist, hosting provider or other outside input; Dropped = removed from the plan.
Repo facts for MFA, the credit hold, the seal alert, the pilot gateway and cart expiry were checked in code on 2026-10-04.
"""

DECIDED, CONFIRM, EXTERNAL, DROPPED = "Decided", "Confirm", "External", "Dropped"

QA = [
 # ---- blockers
 (1, "Team and parallelism", "All", CONFIRM,
  "Plan for one human owner plus agents. Two agent lanes run in parallel only on independent items, each in its own git worktree and its own Postgres database. The human decides, reviews and signs. Start moves to Monday 12 Oct 2026, not 5 Oct. If the real team is larger, change DEVS in build_plan.py and regenerate.",
  "Developers 3 to 2 lanes; start 12 Oct; owners Agent 1, Agent 2, Human reviewer."),
 (2, "Feature freeze", "WI-027, 029-032, 060, 061", DECIDED,
  "The plan does not override the freeze. Everything touching live NIC, GSTR-2B API, Tally and WhatsApp Cloud is built behind its existing flag, default off, against a fake adapter and offline inputs. Flipping a flag is a separate freeze exception and is not part of any item. WI-027 becomes an in-app token; WI-029-031 become stub actions plus stored fields; WI-032 computes validity from entered distance only; PIN-to-PIN lookup is deferred.",
  "Scope of WI-027, 029, 030, 031, 032, 060, 061 rewritten; flags stay off."),
 (3, "Second reviewer", "All", CONFIRM,
  "Rule: the author never signs their own Review. Agent-built work gets an agent code-review pass first, then the human signs. Human-built work gets an agent review, then the human signs after a day's gap. Compliance items also need the CA, pharmacy items a licensed pharmacist. If you want a named human second reviewer, add them as Owner on the Review stage.",
  "Definition of done: reviewer rule added to Plan guide."),
 (4, "Source-of-truth workbook", "All", DECIDED,
  "Bizboard_Product_Task_Universe_Master.xlsx is the source of truth and the file register_sync.py updates by default. Bizboard_Master_Task_Register_Enhanced.xlsx is a mirror written by recalc_xlsx.ps1 -Mirror. Archives are read-only. The _UPDATED file is renamed over the Master once Excel releases it.",
  "Plan guide states the rule."),
 (5, "Other open plans", "All", DECIDED,
  "Production bugs jump the queue, capped at 20% of capacity, and each interrupt is logged in the change log. This plan preempts the bug-remediation, UX, FMEA and ISO 25010 plans for new work, but any item in those plans that duplicates a work item here is merged into it rather than done twice.",
  "20% interrupt allowance noted in Plan guide."),
 (6, "Postgres host and backup keys", "WI-007", EXTERNAL,
  "Recommended default: managed Postgres in an India region with built-in point-in-time recovery, RPO 5 minutes, RTO 1 hour for the pilot. Backup encryption keys live in the provider's key service, administered by the founder, with a sealed break-glass copy held separately. WI-007 cannot be designed until you pick the provider, so a new decision item DEC-HOST comes first and WI-007 depends on it.",
  "New item DEC-HOST (owner Founder); WI-007 depends on it."),
 (7, "Chartered accountant for Rule 11(g)", "WI-003, 004", EXTERNAL,
  "Build the coverage map now and sign later. A new external item CA-SIGN follows WI-003. If no CA is named by 2 Nov 2026, M1 still closes technically but is marked 'pilot with documented residual: Rule 11(g) sign-off pending'. The same CA reviews the tax rule tables in WI-016 to WI-020, so a new item DEC-CA (engage the CA) precedes them.",
  "New items DEC-CA and CA-SIGN."),
 # ---- definition of done
 (8, "Item-specific pass conditions", "All", DECIDED,
  "Every item now has its own pass condition and rejecting case, written in the plan, and the definition of done depends on the item's kind: feature, web, performance, infrastructure drill, decision or process gate. The four pasted lines are gone.",
  "Acceptance criteria rewritten per item; new Kind column."),
 (9, "Frontend tests and register sync", "WI-043, 052-057", DECIDED,
  "Web items are done on Vitest component tests, a Playwright flow where there is a flow, tsc -b, ESLint with zero errors and an accessibility check. They do not need the backend suite. register_sync.py is extended to read Vitest and Playwright JUnit output (new item REG-WEB, first in the plan), and web test references become real file paths.",
  "New item REG-WEB; web items depend on it; test globs replaced with files."),
 (10, "WI-002 and WI-004", "WI-002, 004", DECIDED,
  "Yes. Their remaining work is Review plus the register update. Evidence is the parent item's tests (WI-001 and WI-003). Design, Build and Tests stay N/A.",
  "Done condition for these items: parent Done and register row updated."),
 (11, "Items with no register task", "WI-033, 035, 058, 067", DECIDED,
  "Verification gates have no register row and are done when their checklist passes. WI-033 gets a new register row (next free X- number) created when the item starts, so it can be scored.",
  "Done condition by kind; WI-033 gets a register row at start."),
 (12, "Test file for SEC-0624", "WI-010", DECIDED,
  "The existing test_mfa.py stays as the regression base. A new test_mfa_mandatory.py covers enforcement and first-login enrolment. The strict xfail test in test_register_integrity_gaps.py becomes a normal passing test. WI-005 keeps test_register_integrity_gaps.py for the invariant tests only.",
  "Planned test files corrected."),
 (13, "When the full suite runs", "All", DECIDED,
  "Each pull request runs the tests for the apps it touches plus lint and type checks. The full backend suite on Postgres runs nightly and at each verification gate (WI-035, 058, 067). Performance tests run on their own schedule, never in the pull-request run.",
  "Plan guide states the rule."),
 # ---- schedule
 (14, "Wave overlap", "WI-036", DECIDED,
  "Not intended. Every wave 2 item now depends on VER-1 and every wave 3 item on VER-2, so no later wave starts before the earlier gate closes.",
  "Dependencies added; dates rescheduled."),
 (15, "Holidays", "All", CONFIRM,
  "Treated as non-working: 20 Oct, 9 Nov, 11 Nov, 24 Nov, 25 Dec 2026 and 26 Jan 2027. Edit the HOLIDAYS list in build_plan.py to match your calendar.",
  "Scheduler skips the listed holidays."),
 (16, "Slack and slips", "All", DECIDED,
  "Item estimates carry a 20% buffer. Each milestone date also has one extra week before it is called. Any item more than 2 working days late triggers a re-plan, and every wave 1 item has a cut-line rank so the lowest-ranked can move to wave 2 instead of moving M1.",
  "Milestone date +7 days; Cut line column added."),
 (17, "Estimates that cannot meet scope", "WI-010, 028, 044, 050, 061", DECIDED,
  "Re-estimated: 2FA 1.5 to 4 days; POS latency split into a 2-day benchmark harness and a separate timeboxed 5-day optimisation; printer work narrowed to network printer plus keyboard-wedge scanner at 6 days with Bluetooth and browser camera deferred; Tally 10 to 25 days for TallyPrime masters, opening balances and one financial year of vouchers; signup 1 to 3 days. Every wave's estimates are re-checked with a one-day spike before that wave starts.",
  "Estimates changed; WI-028 split; spike rule in Plan guide."),
 # ---- already in repo
 (18, "Admin 2FA", "WI-010", DECIDED,
  "Gap-fill, not a rebuild. Checked 2026-10-04: MFA_ENFORCE_FOR_MONEY_ROLES defaults on in production and staging, and enrolment_required already blocks a session until TOTP is enrolled. user_has_money_role covers only OWNER and ACCOUNTANT. There is no separate Admin role: OWNER is labelled Owner/Admin, and there is no can_manage_users flag (invites are an owner action). The gap is MANAGER, whose defaults include can_post_journals and who is not enforced today. Extend enforcement to OWNER, ACCOUNTANT and any membership with can_post_journals (MANAGER by default). Do not add SALES_STAFF: they can create sales and payments, and cashiers and salespeople stay out. Recovery codes already exist.",
  "WI-010 scope names the real roles after the repo check."),
 (19, "Audit trail gap", "WI-001", DECIDED,
  "Gap-fill only. Add an audit event with actor, IP and before/after values to: sales invoice complete, cancel and amend; sales return; credit and debit notes; purchase invoice complete (books on and off); purchase return; customer receipt; supplier payment; journal post and reverse; stock adjustment, transfer and goods receipt; payroll finalise; period lock and reopen. Remove the xfails.",
  "WI-001 scope lists the actions."),
 (20, "Encryption scope", "WI-013", DECIDED,
  "New work covers bank account numbers and tax-portal secrets, with existing gateway credentials moved from Fernet to AES-256-GCM. IFSC is not secret and stays searchable. Existing plaintext rows are migrated in batches with a reversible step, storing the last four digits for display. Keys come from the host's secret store, carry a key id for rotation, and never live in the repo.",
  "WI-013 scope rewritten."),
 (21, "Nightly seal alert", "WI-034", DECIDED,
  "Checked 2026-10-04. core-seal-audit-chain is already on the Celery beat at 02:40 daily (config/settings.py). A verify failure only calls logger.error; the task comment says Sentry picks that up. There is no missed-night detector, no ops-metric for the seal, and no email. Nightly invariant failures notify the Owner in-app via NotificationService, not by email (email is the console backend unless EMAIL_HOST is set). WI-034 adds a missed-run check and alerts the same way: logger.error plus an in-app notification to the Owner. It does not add a new email path.",
  "WI-034 channel set from the code: log plus in-app Owner notification."),
 # ---- wave 1 behaviour
 (22, "Trial-balance worker", "WI-005", DECIDED,
  "Invariants: trial balance zero; every journal balanced; AR and AP control accounts equal customer and supplier outstanding; stock ledger equals the sum of movements; allocations never exceed payments; output tax in the ledger equals invoice tax. Quarantine flags the batch, blocks period close and GST export until cleared, and does not block billing. Alert goes to Owner, Accountant and the ops mailbox.",
  "WI-005 scope rewritten."),
 (23, "Soft delete", "WI-006", DECIDED,
  "is_deleted on Customer, Supplier, Product, Warehouse and PriceList. Ledger accounts keep their existing guard. Transactions are cancelled or voided, never soft-deleted. Owner and Admin can restore. Where a foreign key cascades onto transactional rows, it becomes PROTECT; existing child rows are not touched, and the migration first prints an orphan report.",
  "WI-006 scope rewritten."),
 (24, "Rate limiting", "WI-008", DECIDED,
  "Public routes: login, OTP request and verify, register, password reset, portal links, webhooks. Limits: login 10 per minute per IP and 5 per minute per account; OTP 3 per minute and 10 per hour per target; register 5 per hour per IP; portal 60 per minute per token; authenticated API 600 per minute per tenant with burst 100; webhooks verified by signature with a separate higher limit. If Redis is down, login and OTP fail closed on a strict in-process fallback limit and the general API fails open, with an alert.",
  "WI-008 scope rewritten."),
 (25, "Cost and margin masking", "WI-009", DECIDED,
  "Visible to Owner, Admin, Accountant, Purchase Manager and Inventory Manager. Hidden from Cashier, Salesperson and Godown custodian. In API, exports and PDFs the field is omitted, not blanked or zeroed, because a zero reads as a real cost. The POS screen shows selling price and a below-cost warning computed on the server, never the cost.",
  "WI-009 scope rewritten."),
 (26, "Session revocation", "WI-011", DECIDED,
  "Both access and refresh tokens are revoked. Mechanism: a per-user session version checked on every request (Redis with a database fallback), plus the existing refresh blacklist. Whether a websocket layer exists is checked at item start; if there is none, the next API call is enough.",
  "WI-011 scope rewritten."),
 (27, "Input sanitising", "WI-012", DECIDED,
  "Both: HTML tags are stripped on save from plain-text fields (notes, descriptions, names, addresses, remarks, complaint text, imported cells), and output is escaped on render and in PDF templates. SQL injection is already handled by the ORM, so the new test is a guard that fails the build on string-built raw SQL; no new SQL sanitiser.",
  "WI-012 scope rewritten."),
 (28, "Invoice snapshots", "WI-014", DECIDED,
  "Snapshot legal name, trade name, billing and shipping address, and GSTIN at completion, for sales invoices, credit and debit notes, and purchase bills (supplier details). Backfill marks every copied row snapshot_source = backfill_from_master and flags it for review; where the audit history shows a rename, the name as of the invoice date is used instead of today's master. Old invoices are never silently rewritten.",
  "WI-014 scope rewritten."),
 (29, "Schedule H and X register", "WI-015", EXTERNAL,
  "Behind a per-tenant pharmacy flag, off by default. For Schedule H, H1 and X items a sale cannot complete without patient and prescriber name and registration number; Schedule X also keeps a prescription copy. Inspector layout: date, patient, prescriber and registration no., drug, batch, quantity, invoice no., printable as PDF and CSV. Retention default 3 years, configurable. A licensed pharmacist must review the layout and retention before any pharmacy goes live (default taken from my recollection of the Drugs Rules, so verify).",
  "WI-015 scope rewritten; pharmacist review added."),
 (30, "Section 16(2) checklist", "WI-016", EXTERNAL,
  "Mixed. The system proves invoice held (bill exists), goods received (GRN link) and the 180-day payment rule (from payments). 'Supplier paid the tax' and 'return filed' are attested by the user, because GSTR-2B is out of the freeze. A failed or unconfirmed check warns on the bill and excludes it from the claimable ITC summary; it does not block posting the bill or the ledger. CA reviews the wording.",
  "WI-016 scope rewritten."),
 (31, "Section 16(4) time bar", "WI-017", EXTERNAL,
  "60 and 7 days are warnings before the statutory deadline (30 November following the financial year of the invoice, or the annual return date if earlier). TIME_BARRED applies after the deadline to unclaimed ITC and excludes it from the claimable summary. ITC already claimed is flagged for CA review, not reversed automatically. CA to confirm relief provisions for older years.",
  "WI-017 scope rewritten."),
 (32, "Section 17(5) list", "WI-018", EXTERNAL,
  "Implement the full blocked-credit list as a data table with effective dates (motor vehicles, food and beverages, outdoor catering, beauty and health services, club membership, employee travel benefits, works contract and construction of immovable property, personal consumption, goods lost, stolen or destroyed, gifts and free samples, and the rest). Match on HSN/SAC plus expense category; keywords only suggest. On a block, GST posts to the expense or asset account, not ITC receivable. Owner and Accountant can override with a reason, audited. CA approves the table.",
  "WI-018 scope rewritten."),
 (33, "GSTR-2B scope in WI-019", "WI-019", DECIDED,
  "WI-019 only adds the blocked-credit classification to the reconciliation data that already exists, using uploaded 2B files. It builds no new reconciliation and calls no GSTN API, so it stays inside the freeze.",
  "WI-019 scope narrowed."),
 (34, "Section 50 interest", "WI-020", EXTERNAL,
  "Rates held in a table with effective dates: 18% a year on tax paid late, 24% on undue or excess ITC claimed. Basis: net cash liability where the return was filed late (Rule 88B), and the unpaid amount where tax was paid late after filing. Output is a worksheet plus CSV. It posts no journal. CA confirms the table and the basis.",
  "WI-020 scope rewritten."),
 (35, "Chronic defaulter rule", "WI-021", CONFIRM,
  "New rule, still to confirm: per company, any invoice more than 60 days overdue and an over-60-day total of at least Rs 5,000. The block stops credit-sale completion, sales-order confirmation and delivery challans; cash and prepaid sales still go through. Unlock is a single-use code valid 24 hours, issued by the Owner or a credit-override role, with a reason. Existing rule, checked 2026-10-04, stays and the stricter of the two wins. Always on: sales invoice complete blocks when credit_limit > 0 and exposure plus the invoice exceeds it (sales/services.py). Opt-in, default off (company.auto_credit_hold_on_severe_overdue): the same complete path also blocks when collection status is stop_credit (outstanding above the credit limit) or overdue_severe (any overdue and either a 90-plus-day bucket or average payment delay over 21 days), from payments/dunning.py customer_risk_snapshot. That opt-in does not run on sales-order confirmation or delivery challans.",
  "WI-021 now states the existing hold instead of 'read the code first'."),
 (36, "Cheque dishonour split", "WI-022, 023", DECIDED,
  "WI-022 owns reversal, bank fee and owner alert. WI-023 owns only the section 138 notice draft. The '5 days' is replaced by configurable dates taken from the bank's return memo. The notice follows the statutory sequence (written demand within 30 days of the memo, 15 days to pay) and carries the disclaimer that it is a draft for an advocate to review. Default fee is the amount from the bank memo, suggested Rs 500. Whether GST applies to the recovery is a CA decision; it is a configurable flag, default off.",
  "WI-022 and WI-023 scopes separated."),
 (37, "Cancelled supplier GSTIN", "WI-024", DECIDED,
  "Status comes from whatever feeds the existing alert plus a manual flag; no GSTN pull. New ITC is blocked for invoices dated on or after the cancellation effective date. ITC already availed is flagged for the CA, not reversed. The payment hold can be overridden by Owner or Accountant with a reason, audited.",
  "WI-024 scope rewritten."),
 (38, "Approval queue", "WI-025", DECIDED,
  "Actions: credit-limit override, stock adjustment above threshold, invoice cancel or amend after completion, discount above threshold, return or credit note above threshold, backdated posting or period reopen, supplier payment above threshold, bad-debt write-off, bulk import commit. Default approver is the Owner, configurable per action by role. A requester cannot approve their own request; an Owner with no other approver can, flagged as self-approved with a reason. Requests expire after 72 hours and count as rejected.",
  "WI-025 scope rewritten."),
 (39, "Stock adjustment approval", "WI-026", DECIDED,
  "Either test triggers it: value at cost of Rs 10,000 or more, or quantity of 10% or more of on-hand. Both are configurable per company. Dual approval needs two different users; a single-user company gets the Owner exception from WI-025.",
  "WI-026 scope rewritten."),
 (40, "Credit override token", "WI-027", DECIDED,
  "In-app one-time token for MVP; WhatsApp is added when the freeze flag is flipped. Single use, 15-minute expiry, bound to the invoice batch and requester. If the owner does not respond, the over-limit invoices stay in 'Awaiting approval', the others proceed, expiry counts as rejected, and nothing is ever auto-approved.",
  "WI-027 scope rewritten."),
 (41, "Checkout latency", "WI-028", DECIDED,
  "Target: 95th percentile 200 ms server-side for checkout complete including tax, stock and ledger, on a 2 vCPU 4 GB container with local Postgres, a 20,000-SKU catalogue and a 3-line cart. The benchmark runs outside the normal suite on its own nightly job and compares against a recorded baseline. The item splits into WI-028 (harness and baseline, 2 days) and a new WI-028b (optimise, timeboxed 5 days).",
  "WI-028 split; WI-028b added."),
 (42, "E-way bill actions", "WI-029-032", DECIDED,
  "Stub actions against the GSP adapter interface with a fake provider, plus stored fields for vehicle history, extension and multi-vehicle split, all behind GSP_LIVE_ENABLED=0. Live calls need NIC or GSP sandbox credentials from you and a freeze exception. WI-032 computes validity from the entered distance using a configurable slab table with effective dates that the CA confirms (the bands have changed over time). PIN-to-PIN distance lookup is deferred.",
  "WI-029-032 scopes rewritten; PIN lookup deferred."),
 (43, "Concurrent customer edits", "WI-033", DECIDED,
  "Both mechanisms. PATCH merges changed fields under a row lock, so concurrent edits of different fields both persist. PUT requires a version and a stale write is rejected with 409 and the current value. A register row is created when the item starts.",
  "WI-033 scope rewritten."),
 # ---- waves 2 and 3
 (44, "Salt, composition, manufacturer", "WI-036", DECIDED,
  "Optional fields, shown and searchable for every tenant but expected mainly by pharmacies. Billing search must stay inside the WI-028 latency budget (trigram index and a query-budget test).",
  "WI-036 scope rewritten."),
 (45, "Bulk invoice CSV", "WI-037", DECIDED,
  "Columns: invoice ref, customer, invoice date, due date, item SKU or barcode, quantity, rate, discount %, warehouse, notes; tax is computed. Mode: dry run validates everything first, then commits per invoice atomically; an invoice with any bad row is rejected whole and reported by row. Cap 2,000 rows (about 500 invoices) per file; the file hash makes re-upload idempotent.",
  "WI-037 scope rewritten."),
 (46, "In-transit stock", "WI-038", DECIDED,
  "In transit is a real location per transfer. Stock moves source to in-transit on dispatch and in-transit to destination on receipt. Partial receipt is allowed with a shortage or damage reason. No ledger entry for same-company, same-GSTIN transfers.",
  "WI-038 scope rewritten."),
 (47, "Multi-shop dashboard", "WI-039", DECIDED,
  "Warehouses within one company only; multi-company GSTIN stays out of scope. The view must stay inside the dashboard's query budget, with a test.",
  "WI-039 scope rewritten."),
 (48, "Overdue interest and bad-debt risk", "WI-040", CONFIRM,
  "Report only, no posting. Interest rate per company, default 18% a year simple. Suggested provision by age: 0 to 60 days 0%, 61 to 90 days 5%, 91 to 180 days 25%, 181 to 365 days 50%, over 365 days 100%. Confirm the buckets with your accountant.",
  "WI-040 scope rewritten."),
 (49, "Warehouse users and contacts", "WI-041", DECIDED,
  "Users map to many warehouses with one default. Contact person and phone are required; email is optional.",
  "WI-041 scope rewritten."),
 (50, "Printer and scanner scope", "WI-044, 045", CONFIRM,
  "Pilot scope: network ESC/POS printer and USB keyboard-wedge scanner. Bluetooth and the browser camera scanner are deferred; the mobile app's camera scan already works. Verification devices: a network ESC/POS printer such as an Epson TM-T82 and any keyboard-wedge scanner; you need to buy or name them. Tests: Vitest for logic plus a manual device checklist.",
  "WI-044 and WI-045 rescoped; tests are web files."),
 (51, "Subscription invoices", "WI-046", DECIDED,
  "Bizboard's own GST invoice to the tenant, with our GSTIN and place of supply from the tenant's state, generated and emailed on a captured-payment event. Freeze decision D3 names the pilot gateways: Cashfree or PayU, sandbox only, at least one configured (ENABLE_CASHFREE and ENABLE_PAYU on). The invoice generator listens to that captured-payment event and does not call a gateway SDK. Razorpay stays as it is: billing.tasks.reconcile_saas_subscriptions_task reconciles local Subscription rows and is not the source of these tax invoices.",
  "WI-046 names Cashfree or PayU from the freeze; Razorpay recon is left alone."),
 (52, "Journey tests", "WI-047-049", DECIDED,
  "They test flows that already work. If one fails, fixing it is in scope up to one day; anything larger becomes a separate item. Rejecting cases: duplicate submission, wrong-tenant access, missing permission, and a credit note created exactly once.",
  "WI-047-049 pass and reject cases added."),
 (53, "Signup load test", "WI-050", DECIDED,
  "20 concurrent signups out of 50 total, 95th percentile provisioning at most 10 seconds, no duplicate tenants. Runs on a nightly or manual job, not in the pull-request run. Item is 3 days.",
  "WI-050 estimate and criteria changed."),
 (54, "Cart reservation release", "WI-051", CONFIRM,
  "Checked 2026-10-04: there is no cart session and no timeout. POS drafts are device-local, wiped on sign-out (freeze C5), and do not reserve stock. The only stock hold with no expiry is a confirmed sales-order reservation, released on cancel, convert or invoice complete. WI-051 adds a company-configurable expiry, default 24 hours, on that reservation and on POS holds once WI-053 creates them: release the allocation and mark the hold expired, keeping the row so it can be restored if stock is free. Confirm the 24-hour default before the item starts.",
  "WI-051 scope states that no cart timeout exists; default TTL 24 hours, still to confirm."),
 (55, "WI-053 dependency", "WI-053", DECIDED,
  "Not real. The dependency on keyboard-only POS is removed.",
  "Dependency removed."),
 (56, "Rupee mask vs role masking", "WI-057", DECIDED,
  "Yes, separate. The mask is a personal on-screen toggle for people allowed to see the figures; it is not a security control.",
  "WI-057 scope rewritten."),
 (57, "Cash-flow simulation", "WI-059", DECIDED,
  "Per debtor, bootstrap from the days-late of the last 12 settled invoices, shrunk toward the customer-segment average; 1,000 runs; show p10, p50 and p90. With fewer than 5 settled invoices, fall back to the ageing heuristic and show a 'low confidence, based on N invoices' badge.",
  "WI-059 scope rewritten."),
 (58, "Fuzzy invoice matching", "WI-060", DECIDED,
  "Score 0.95 or higher with equal GSTIN and tax within tolerance links automatically; 0.80 to 0.95 suggests a match for a person to confirm; below 0.80 shows nothing. It runs on uploaded 2B data after WI-019; nothing calls GSTN.",
  "WI-060 scope rewritten; depends on WI-019."),
 (59, "Tally migration", "WI-061", DECIDED,
  "TallyPrime only for now. Ledger masters, stock items, opening balances and one financial year of vouchers, with a mandatory mapping step for ledgers and stock items. Turning ENABLE_TALLY on is a separate freeze exception, not part of this item. Estimate 25 days; multi-year history and Tally.ERP 9 come later.",
  "WI-061 scope and estimate changed."),
 (60, "Non-filer higher TDS/TCS", "WI-062, 063", DROPPED,
  "Dropped pending CA confirmation. To my knowledge sections 206AB and 206CCA were omitted from 1 April 2025, which would make both items obsolete. If the CA says otherwise: use an uploaded specified-person list rather than stored taxpayer credentials, valid for the financial year, applied to new documents only.",
  "WI-062 and WI-063 removed from the plan."),
 (61, "Anomaly detector", "WI-064", DECIDED,
  "Review queue only; it never blocks a bill. Unusual means a discount above 3 times the item's median discount, or a bill above both a rupee floor and 3 times the customer's median bill. Thresholds are per company and configurable.",
  "WI-064 scope rewritten."),
 (62, "Section 128A", "WI-065", DROPPED,
  "Dropped from the plan, kept in the register as On request. The scheme window has closed, so a live tracker has no use, and a historical reconciliation is only worth building for a pilot customer who has declarations. CA to confirm.",
  "WI-065 removed."),
 (63, "Section 171 anti-profiteering", "WI-066", DROPPED,
  "Dropped from the plan, kept in the register as On request, because enforcement has been wound down as far as I know. CA to confirm. If it comes back: count rate-cut notifications as events, with the last price before the cut as the baseline.",
  "WI-066 removed."),
]
