"""Findings of the 2026-10-05 deep code review and what happened to each.

Status: Fixed = changed and covered by a passing test; Fixed (no test) = changed, covered only by existing suites;
Open = not changed; Reverted = tried, an existing pinned test showed the product wants the opposite.
(area, severity, finding, status, how / why)
"""

F = [
 ("Infra", "Critical", "Celery task routes sent OTP, webhooks, refunds, PDFs and reporting to queues no worker consumed", "Fixed (no test)", "Workers now start with -Q celery,high_priority,media_heavy,reports in compose, staging and CI"),
 ("Config", "High", "PLANWAVE_DATA_KEY never read from the environment: every bank-number save would fail in production", "Fixed (no test)", "Loaded and validated at boot in settings.py; MFA key format also validated at boot"),
 ("Core", "High", "Nightly invariants and seal alert ran outside rls_bypass; one company's failure aborted the sweep", "Fixed (no test)", "core/tasks.py wraps writes in rls_bypass with a per-company try; open quarantine constrained to one row per company (planwave 0004)"),
 ("Security", "High", "Refresh cookie alone issued an MFA enrol token (stolen cookie could bind attacker's authenticator)", "Fixed", "Refresh now returns 401; password login issues the enrol token. tests/test_mfa.py updated"),
 ("Security", "High", "Certification endpoint trusted a chain_ok query flag and was open to any member", "Fixed", "Verifies the audit chain server-side, owner/manager/accountant only. test_code_review_2026_10_05.py"),
 ("Planwave", "High", "Credit hold, overdue report and cash-flow forecast summed grand_total, not the outstanding balance", "Fixed", "Use LedgerService.sales_invoice_outstanding. test_a_paid_old_invoice_does_not_hold_credit"),
 ("Planwave", "High", "Party snapshot backfill overwrote as-issued snapshots", "Fixed", "Snapshots are write-once. test_a_backfill_never_overwrites_an_issued_snapshot"),
 ("Planwave", "High", "ITC deadline status written once at bill completion and never refreshed; 180-day test hard-coded false", "Fixed (no test)", "refresh_itc_status recomputes from bills and supplier payments on read"),
 ("Planwave", "Medium", "Approvals: no lock on decide, blank token redeemed ordinary approvals, cancel burned the approval on failure", "Fixed", "Row lock + atomic; token action/blank checks; consume+cancel in one transaction"),
 ("Planwave", "Medium", "Rate limiter: OTP buckets lockable by anyone, junk Authorization bypass, list body 500, unbounded fallback memory", "Fixed", "Canonical OTP target, IP buckets, dict guard, pruned fallback"),
 ("Planwave", "Medium", "Seal() wrapped an unopenable sealed blob in a second layer", "Fixed", "Structurally valid unopenable blobs are left unchanged. test_a_sealed_value_that_cannot_be_opened_is_left_alone"),
 ("Planwave", "Medium", "Sanitiser deleted text like '<5000 and >100'", "Fixed", "Only real tags/comments are stripped. test_the_sanitiser_strips_tags_but_keeps_comparisons"),
 ("Planwave", "Medium", "Pharmacy register rows created on every completion attempt and stamped onto other invoices", "Fixed", "Check-only on validate, record once with invoice number and batch. test_checking_a_pharmacy_sale_records_nothing"),
 ("Planwave", "Medium", "Bulk invoice commit not locked; marked committed with rejects; ambiguous customer; leaked exception text", "Fixed (no test)", "Batch row lock, created refs skipped on re-run, unambiguous customer, generic error"),
 ("Planwave", "Medium", "Approval, ITC, pharmacy, warehouse access views open to any member; 500s on bad input", "Fixed", "Role gates, action allowlist, 400s. test_unknown_approval_action_and_bad_dates_are_400_not_500"),
 ("Money", "High", "Customer payment-link capture issued a Bizboard platform GST invoice for the tenant's own customer money", "Fixed (no test)", "Call removed from finalize_gateway_capture"),
 ("Money", "High", "Live e-way adapter silently faked Part B update and validity extension", "Fixed", "Refuses when the live provider cannot send. test_a_live_eway_provider_refuses_a_part_b_update_it_cannot_send"),
 ("Money", "High", "Batch POS sync bypassed subscription and payment-permission gates", "Fixed (no test)", "SubscriptionWritesAllowed and CanCreatePayments added to PosBatchSyncView"),
 ("Money", "Medium", "Partial order conversion counters never reversed; partly converted drafts could not be edited", "Fixed", "release_order_conversion on draft delete / draft challan cancel; cap against other live drafts. test_code_review_2026_10_05_b.py"),
 ("Money", "Medium", "payment_status filter ignored settlement discount and counted cancelled invoices", "Fixed", "Discount share subquery and status filter. test_payment_status_filter_agrees_with_the_ledger_on_settlement_discount"),
 ("Money", "Medium", "Failed delivery stop could release the order's stock twice", "Fixed (no test)", "stock_released_at marker (sales 0063)"),
 ("Money", "Medium", "Delivery OTP stayed valid after use; same person could verify cash handover", "Fixed", "OTP hash cleared on success; verifier must differ unless owner/manager. test_delivery_otp_locks_after_repeated_wrong_codes"),
 ("Money", "Medium", "Exact UTR in narration bound a credit to a receipt of a different amount", "Fixed", "Amount tolerance required. test_a_matching_reference_with_a_different_amount_does_not_bind"),
 ("Money", "Medium", "AA ingest returned 400 on renewed consent with only old expired rows", "Fixed (no test)", "Raise only when no open consent exists"),
 ("Money", "Medium", "Below-cost check ignored unit conversion; platform staff could override", "Fixed (no test)", "Base-unit comparison; owner of this company only"),
 ("Money", "Low", "Cheque bounce 500 on bad bank charge; supplier-payment datetime TypeError; credit-note cancel could fail on re-allocated receipt", "Fixed (no test)", "Validation, date normalisation, savepoint around slice restore"),
 ("Money", "Medium", "Webhook dedup claimed after success (refund branch race)", "Open", "Deliberate FMEA-003 design; refund path protected by refund keys. Not changed"),
 ("Money", "Medium", "COD cash collected on delivery routes is not recorded as a receipt", "Open", "Needs a decision on how cash becomes receipts"),
 ("Purchases", "High", "3-way match blocked bills when a product appeared on several GRN or PO lines", "Fixed (no test)", "Per-product sums and any-agreed-rate comparison"),
 ("Purchases", "Medium", "Second price amend posted no GL variance journal", "Fixed", "Journal purpose carries the revision count. test_bug_open_pur updated"),
 ("Purchases", "Medium", "Existing serial numbers silently skipped on bill complete", "Fixed (no test)", "Sold or unavailable serials are refused"),
 ("Inventory", "Medium", "Transfer receipt dated and period-gated at the dispatch date", "Fixed", "Receipt uses today. test_bug_inv_010 updated"),
 ("Inventory", "Medium", "Cancel after a short receipt overdrew the destination and stranded transit stock", "Fixed", "test_cancel_after_a_short_receipt_restores_stock_and_clears_transit"),
 ("Inventory", "High", "transfer_date migration stamped the migration day on historical transfers (period-lock bypass)", "Fixed (no test)", "inventory 0026 resets dates to the creation day"),
 ("Accounting", "High", "Payroll advance recovery left the journal unbalanced", "Fixed (no test)", "Credit to new account 1260 Employee Advances"),
 ("Accounting", "High", "Cancel and re-complete of a pay run compounded arrears and bonus", "Fixed (no test)", "Start from salary when components exist"),
 ("Accounting", "Medium", "Schedule III balance sheet missing the unclosed profit; P&L section total meaningless", "Fixed", "test_schedule_iii_balance_sheet_balances_with_the_surplus_line"),
 ("Accounting", "Low", "Rollup refresh not atomic; manual journal post left the checkpoint fresh", "Fixed (no test)", "Atomic refresh; checkpoint dropped on post"),
 ("Accounting", "Medium", "AccountBalanceRollup missing from RLS", "Fixed (no test)", "core 0051; rls coverage test now sees one-to-one keys"),
 ("Accounting", "Low", "Any payment-capable user could close another cashier's till", "Fixed (no test)", "Cashier or manager only"),
 ("Accounting", "Medium", "206AB rates for company vendors look wrong", "Open", "Needs the accountant"),
 ("Masters", "High", "Soft-deleted rows still blocked reuse of SKU, GSTIN, price-list name, warehouse code", "Fixed", "Conditional constraints (masters 0030, inventory 0027). test_a_deleted_product_does_not_block_its_sku"),
 ("Masters", "Medium", "Supplier soft delete skipped the referenced check; customer PUT version check outside the lock", "Fixed (no test)", "Referenced guard; version re-checked under the row lock"),
 ("Masters", "Low", "Bank account shown in full to every role", "Fixed (no test)", "Masked for non owner/accountant; masked echo never overwrites"),
 ("Security", "Medium", "Existing plaintext bank numbers not sealed", "Fixed (no test)", "manage.py seal_bank_accounts"),
 ("Accounts", "Medium", "Stale active company made the first login fail", "Fixed (no test)", "Repaired at sign-in; getter write kept (pinned by test_bug_sec_017)"),
 ("Accounts", "Medium", "Accept-invite had no wrong-code limit; password change and logout-all left access tokens valid", "Fixed", "Shared MFA fail counter; session_version bump. test_access_token_dies_when_sessions_are_revoked"),
 ("Core", "Low", "Idempotency prune deleted stale in-flight money keys", "Fixed", "test_prune_keeps_stale_in_flight_money_keys_but_removes_other_scopes"),
 ("Core", "Medium", "Idempotency reclaim for *_complete scopes", "Open", "Design decision pinned by comment; not changed"),
 ("Core", "Low", "RequestId context leaked on exception; ops webhook compare_digest TypeError; flag command picked an arbitrary company", "Fixed (no test)", "try/except clear, byte compare, --company-id"),
 ("Infra", "Medium", "App role is a superuser in compose so RLS is bypassed; pg_dump fails once the role is fixed", "Fixed (no test)", "backup.sh accepts BACKUP_DB_USER; role change itself is an ops decision, startup warnings kept"),
 ("Core", "Low", "WhatsApp opt-in gate is a tautology", "Open", "Cloud WhatsApp is off in the freeze; needs the consent source"),
 ("Banking", "Low", "Consent status is client-supplied on AA ingest", "Open", "Needs provider-side verification step"),
 ("Reporting", "Low", "'Invoice possessed' forced true at complete; 16(4) cut-off uses today", "Reverted", "Existing tests pin both behaviours; left as designed"),
 ("Imports", "Medium", "'Rate' alias moved to purchase price", "Reverted", "test_bug_pur_014 pins the current alias"),
 ("Web", "High", "Bank reconciliation auto-confirmed matches on page load", "Fixed (no test)", "Effect removed; person confirms or uses accept-exact"),
 ("Web", "High", "Payment dialog idempotency key reused across changed bodies", "Fixed (no test)", "Key carries a fingerprint of the body"),
 ("Web", "High", "Raw i18n keys shown (common.none, billing.billingAddress, inventory.writeoffNoBatch, offlineOutbox.thermalWarn)", "Fixed", "Keys added in en and hi; web/src/i18n/keyUsage.test.ts guards every literal t() call"),
 ("Web", "High", "Forced MFA enrolment discarded the recovery codes; StrictMode lost the enrol token", "Fixed (no test)", "Codes shown with an acknowledgement; token kept in a ref"),
 ("Web", "High", "GST settings save silently did nothing for unregistered businesses; billing checkout gated on the wrong gateway", "Fixed (no test)", "Confirmation only for a new or changed GSTIN; gateway query removed"),
 ("Web", "High", "'Save draft & new' overwrote the invoice being edited", "Fixed (no test)", "Disabled in edit mode and when it cannot save"),
 ("Web", "High", "Close-period e2e selectors stale, accountant assertion vacuous", "Fixed (no test)", "Selectors updated; assertion made after the table renders"),
 ("Web", "Medium", "Items filters and CSV stock only covered the current page", "Fixed", "Whole catalogue under a filter; ProductsPage.test.tsx"),
 ("Web", "Medium", "POS Discard wiped every held bill; name-only sale ignored the typed name; hold/recall lost or duplicated carts", "Fixed (no test)", "Active bill only; flag respected; per-user key, swap on recall"),
 ("Web", "Medium", "Walk-in cache merged different customers; UPI '+' encoding; privacy mask storage crash; command palette ignored feature flags", "Fixed", "flushPosCheckout, upi, PrivacyMask, CommandPalette; tests updated"),
 ("Web", "Medium", "Error banner stayed hidden after a repeated failure; MFA could not be disabled with a recovery code", "Fixed", "DocumentEditorShell.test.tsx new case"),
 ("Web", "Low", "Many lower-severity web items", "Open", "Item-level list kept in the review reports; none block release"),
 ("Tests", "High", "Stale race test, vacuous PDF byte search, two vacuous or conditional tests", "Fixed", "Rewritten against behaviour"),
 ("Tests", "Medium", "Wall-clock SLA tests skip or fail by machine speed", "Open", "Decision: skip or fail on a slow database"),
]
