from django.urls import path

from .mfa_views import (
    MfaConfirmView,
    MfaDisableView,
    MfaLoginVerifyView,
    MfaRecoveryCodesView,
    MfaSetupView,
    MfaStatusView,
)
from .views import (
    AcceptInviteView,
    ChangePasswordView,
    CookieTokenRefreshView,
    CsrfCookieView,
    LoginView,
    LogoutAllView,
    LogoutView,
    MeView,
    MembershipsListView,
    RegisterView,
    RequestOtpView,
    RequestRegisterOtpView,
    RequestPasswordResetView,
    ConfirmPasswordResetView,
    SwitchCompanyView,
    VerifyOtpView,
)

urlpatterns = [
    path("register/", RegisterView.as_view(), name="auth-register"),
    path("register/otp/request/", RequestRegisterOtpView.as_view(), name="auth-register-otp-request"),
    path("login/", LoginView.as_view(), name="auth-login"),
    path("csrf/", CsrfCookieView.as_view(), name="auth-csrf"),
    path("refresh/", CookieTokenRefreshView.as_view(), name="auth-refresh"),
    path("logout/", LogoutView.as_view(), name="auth-logout"),
    path("logout-all/", LogoutAllView.as_view(), name="auth-logout-all"),
    path("change-password/", ChangePasswordView.as_view(), name="auth-change-password"),
    path("invite/accept/", AcceptInviteView.as_view(), name="auth-invite-accept"),
    path("otp/request/", RequestOtpView.as_view(), name="auth-otp-request"),
    path("otp/verify/", VerifyOtpView.as_view(), name="auth-otp-verify"),
    path("password/reset/", RequestPasswordResetView.as_view(), name="auth-password-reset"),
    path("password/reset/confirm/", ConfirmPasswordResetView.as_view(), name="auth-password-reset-confirm"),
    path("mfa/status/", MfaStatusView.as_view(), name="auth-mfa-status"),
    path("mfa/setup/", MfaSetupView.as_view(), name="auth-mfa-setup"),
    path("mfa/confirm/", MfaConfirmView.as_view(), name="auth-mfa-confirm"),
    path("mfa/disable/", MfaDisableView.as_view(), name="auth-mfa-disable"),
    path("mfa/recovery-codes/", MfaRecoveryCodesView.as_view(), name="auth-mfa-recovery-codes"),
    path("mfa/verify/", MfaLoginVerifyView.as_view(), name="auth-mfa-verify"),
    path("me/", MeView.as_view(), name="auth-me"),
    path("memberships/", MembershipsListView.as_view(), name="auth-memberships"),
    path("switch-company/", SwitchCompanyView.as_view(), name="auth-switch-company"),
]
