# Generated by Django 5.2.16 on 2026-07-19 07:02

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('taxable_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONVERTED', 'Converted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('invoice_type', models.CharField(choices=[('GST', 'GST Invoice'), ('TAX', 'Tax Invoice'), ('RETAIL', 'Retail Invoice'), ('NON_GST', 'Non-GST Invoice')], default='GST', max_length=8)),
                ('quotation_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='masters.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quotation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='masters.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('taxable_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='DRAFT', max_length=12)),
                ('invoice_type', models.CharField(choices=[('GST', 'GST Invoice'), ('TAX', 'Tax Invoice'), ('RETAIL', 'Retail Invoice'), ('NON_GST', 'Non-GST Invoice')], default='GST', max_length=8)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('pdf_status', models.CharField(choices=[('NONE', 'None'), ('QUEUED', 'Queued'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='NONE', max_length=8)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='masters.customer')),
                ('pdf_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.fileasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='converted_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotations', to='sales.salesinvoice'),
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='masters.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('taxable_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('return_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='masters.customer')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.salesinvoice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_items', to='masters.product')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'status', 'invoice_date'], name='sales_sales_company_66c389_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('company', 'number'), name='uniq_sales_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['company', 'status', 'return_date'], name='sales_sales_company_9b15d7_idx'),
        ),
    ]
