# Generated by Django 5.2.16 on 2026-07-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0002_salesitem_line_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='additional_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='auto_round_off',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='include_bank_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='include_payment_qr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='include_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.fileasset'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='terms_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='batch_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
