# Generated by Django 5.2.16 on 2026-07-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_create_parity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='include_payment_qr',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='include_terms',
            field=models.BooleanField(default=True),
        ),
    ]
