# Generated by Django 5.2.16 on 2026-08-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_phase1_document_completeness'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='eway_bill_no',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='eway_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='eway_status',
            field=models.CharField(choices=[('NONE', 'None'), ('READY', 'Ready'), ('GENERATED', 'Generated'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='NONE', max_length=12),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='eway_valid_upto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='ack_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='ack_no',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='einvoice_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='einvoice_qr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='einvoice_status',
            field=models.CharField(choices=[('NONE', 'None'), ('READY', 'Ready'), ('GENERATED', 'Generated'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='NONE', max_length=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='eway_bill_no',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='eway_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='eway_status',
            field=models.CharField(choices=[('NONE', 'None'), ('READY', 'Ready'), ('GENERATED', 'Generated'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='NONE', max_length=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='eway_valid_upto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='irn',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
