# Generated by Django 5.2.16 on 2026-08-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_phase2_einvoice_eway'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='transport_distance_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='transporter_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='salescreditnoteitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='salescreditnoteitem',
            name='unit_name',
            field=models.CharField(blank=True, default='PCS', max_length=32),
        ),
        migrations.AddField(
            model_name='salescreditnoteitem',
            name='uqc_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='salesdebitnoteitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='salesdebitnoteitem',
            name='unit_name',
            field=models.CharField(blank=True, default='PCS', max_length=32),
        ),
        migrations.AddField(
            model_name='salesdebitnoteitem',
            name='uqc_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='filing_party_gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='filing_place_of_supply',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='price_mode',
            field=models.CharField(choices=[('EXCLUSIVE', 'Tax exclusive'), ('INCLUSIVE', 'Tax inclusive')], default='EXCLUSIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='transport_distance_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='transporter_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='uqc_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
