# Generated by Django 5.2.16 on 2026-08-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_phase2_gst_returns_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='unit_price_inclusive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
