# Generated by Django 5.2.16 on 2026-08-02 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockbalance_unique_together_and_more'),
        ('sales', '0011_phase2_gap_line_hsn_uqc_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='inventory.batchlot'),
        ),
    ]
