# Generated by Django 5.2.16 on 2026-08-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesinvoice_warehouse_salesitem_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
