# Generated by Django 5.2.16 on 2026-08-02 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_otp_hash'),
        ('core', '0002_fileasset_pdf_kinds'),
        ('masters', '0004_product_track_batch_product_track_serial_pricelist_and_more'),
        ('sales', '0014_salesinvoice_cost_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deliverychallan',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('company', 'number'), name='uniq_delivery_challan_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('company', 'number'), name='uniq_quotation_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='salescreditnote',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('company', 'number'), name='uniq_sales_credit_note_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='salesdebitnote',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('company', 'number'), name='uniq_sales_debit_note_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('company', 'number'), name='uniq_sales_order_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('company', 'number'), name='uniq_sales_return_number_per_company'),
        ),
    ]
