# Generated by Django 5.2.16 on 2026-08-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_wave3_salescreditnote_sales_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='converted_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_challans', to='sales.salesinvoice'),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='stock_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CONVERTED', 'Converted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12),
        ),
    ]
