# Generated by Django 5.2.16 on 2026-08-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_wave2_manual_irn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='is_opening_balance',
            field=models.BooleanField(default=False),
        ),
    ]
