# Generated by Django 5.2.16 on 2026-08-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_wave_d_manual_ewb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallanitem',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
