# Generated by Django 5.2.16 on 2026-08-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_wave13_return_batch_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='supply_type',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('SEZWP', 'SEZ with payment'), ('SEZWOP', 'SEZ without payment'), ('EXPWP', 'Export with payment'), ('EXPWOP', 'Export without payment'), ('DEXP', 'Deemed export')], default='B2B', max_length=8),
        ),
    ]
