# Generated by Django 5.2.16 on 2026-08-04 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_wave17_multi_company_feature_flags'),
        ('sales', '0023_wave16d_supply_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='company_gstin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='accounts.companygstin'),
        ),
    ]
