# Generated by Django 5.2.16 on 2026-08-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_sprint3_fifo_gstin_series'),
        ('sales', '0025_wave18_cess_itc'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challans', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='ack_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='ack_no',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='einvoice_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='einvoice_qr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='einvoice_status',
            field=models.CharField(choices=[('NONE', 'None'), ('READY', 'Ready'), ('QUEUED', 'Queued'), ('GENERATED', 'Generated'), ('MANUAL_IRN', 'Manual Irn'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='irn',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesdebitnote',
            name='ack_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdebitnote',
            name='ack_no',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='salesdebitnote',
            name='einvoice_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesdebitnote',
            name='einvoice_qr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesdebitnote',
            name='einvoice_status',
            field=models.CharField(choices=[('NONE', 'None'), ('READY', 'Ready'), ('QUEUED', 'Queued'), ('GENERATED', 'Generated'), ('MANUAL_IRN', 'Manual Irn'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='salesdebitnote',
            name='irn',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='is_reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='einvoice_status',
            field=models.CharField(choices=[('NONE', 'None'), ('READY', 'Ready'), ('QUEUED', 'Queued'), ('GENERATED', 'Generated'), ('MANUAL_IRN', 'Manual Irn'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='NONE', max_length=16),
        ),
    ]
