# Generated by Django 5.2.16 on 2026-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_sprint2_note_freeze_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='sub_supply_type',
            field=models.CharField(default='8', max_length=8),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='trans_mode',
            field=models.CharField(default='1', max_length=8),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sub_supply_type',
            field=models.CharField(default='1', max_length=8),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='trans_mode',
            field=models.CharField(default='1', max_length=8),
        ),
    ]
