# Generated by Django 5.2.17 on 2026-08-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_tax12_cess_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnitem',
            name='condition',
            field=models.CharField(choices=[('SELLABLE', 'Sellable'), ('DAMAGED', 'Damaged')], default='SELLABLE', max_length=16),
        ),
    ]
