# Generated by Django 5.2.17 on 2026-08-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_tcs_in_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescreditnote',
            name='charges_gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='charges_hsn',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='tcs_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='tcs_in_grand_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salescreditnoteitem',
            name='supply_nature',
            field=models.CharField(choices=[('TAXABLE', 'Taxable'), ('NIL', 'Nil rated'), ('EXEMPT', 'Exempt'), ('NON_GST', 'Non-GST')], default='TAXABLE', max_length=12),
        ),
        migrations.AddField(
            model_name='salesdebitnote',
            name='charges_gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesdebitnote',
            name='charges_hsn',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='salesdebitnote',
            name='tcs_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesdebitnote',
            name='tcs_in_grand_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesdebitnoteitem',
            name='supply_nature',
            field=models.CharField(choices=[('TAXABLE', 'Taxable'), ('NIL', 'Nil rated'), ('EXEMPT', 'Exempt'), ('NON_GST', 'Non-GST')], default='TAXABLE', max_length=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='charges_gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='charges_hsn',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='supply_nature',
            field=models.CharField(choices=[('TAXABLE', 'Taxable'), ('NIL', 'Nil rated'), ('EXEMPT', 'Exempt'), ('NON_GST', 'Non-GST')], default='TAXABLE', max_length=12),
        ),
    ]
