# Generated by Django 5.2.17 on 2026-08-31 04:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_sales_rcm_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallanitem',
            name='applied_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='rate_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='rate_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='rate_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='applied_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='rate_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='rate_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='rate_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='salescreditnoteitem',
            name='applied_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salescreditnoteitem',
            name='rate_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salescreditnoteitem',
            name='rate_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salescreditnoteitem',
            name='rate_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='salesdebitnoteitem',
            name='applied_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salesdebitnoteitem',
            name='rate_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesdebitnoteitem',
            name='rate_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesdebitnoteitem',
            name='rate_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='applied_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='rate_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='rate_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='rate_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='applied_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='rate_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='rate_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='rate_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='applied_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='rate_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='rate_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='rate_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
