# Generated by Django 5.2.17 on 2026-09-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_one_primary_gstin'),
        ('sales', '0042_c05_tcs_amount_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='additional_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='auto_round_off',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='charges_gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='charges_hsn',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company_gstin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='accounts.companygstin'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='invoice_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='invoice_discount_mode',
            field=models.CharField(choices=[('AFTER_TAX', 'Cash discount (after tax)'), ('BEFORE_TAX', 'Discount (reduces GST)')], default='AFTER_TAX', max_length=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supply_type',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('SEZWP', 'SEZ with payment'), ('SEZWOP', 'SEZ without payment'), ('EXPWP', 'Export with payment'), ('EXPWOP', 'Export without payment'), ('DEXP', 'Deemed export')], default='B2B', max_length=8),
        ),
        migrations.AddField(
            model_name='quotation',
            name='terms_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='supply_nature',
            field=models.CharField(blank=True, default='TAXABLE', max_length=12),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit_price_inclusive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='charges_gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='charges_hsn',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='company_gstin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='accounts.companygstin'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='supply_type',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('SEZWP', 'SEZ with payment'), ('SEZWOP', 'SEZ without payment'), ('EXPWP', 'Export with payment'), ('EXPWOP', 'Export without payment'), ('DEXP', 'Deemed export')], default='B2B', max_length=8),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='eway_status',
            field=models.CharField(choices=[('NONE', 'None'), ('READY', 'Ready'), ('QUEUED', 'Queued'), ('GENERATED', 'Generated'), ('MANUAL_EWB', 'Manual Ewb'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='NONE', max_length=12),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='eway_status',
            field=models.CharField(choices=[('NONE', 'None'), ('READY', 'Ready'), ('QUEUED', 'Queued'), ('GENERATED', 'Generated'), ('MANUAL_EWB', 'Manual Ewb'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='NONE', max_length=12),
        ),
    ]
