# Generated by Django 5.2.17 on 2026-09-04 06:54

from django.db import migrations, models


def backfill_anchor_day(apps, schema_editor):
    # B2-009: seed anchor_day from the current next_run_at day for existing
    # schedules — cannot recover the original intent if it was already clamped,
    # but this stops further backward drift.
    Sched = apps.get_model("sales", "RecurringInvoiceSchedule")
    for s in Sched.objects.filter(anchor_day__isnull=True).iterator():
        if s.next_run_at:
            s.anchor_day = s.next_run_at.day
            s.save(update_fields=["anchor_day"])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_alter_deliverychallan_round_off_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringinvoiceschedule',
            name='anchor_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_anchor_day, migrations.RunPython.noop),
    ]
