# Generated by Django 5.2.17 on 2026-09-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_recurringinvoiceschedule_anchor_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='eway_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='eway_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
