# Generated by Django 5.2.17 on 2026-09-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_eway_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringinvoiceschedule',
            name='additional_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='recurringinvoiceschedule',
            name='invoice_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='recurringinvoiceschedule',
            name='invoice_discount_mode',
            field=models.CharField(choices=[('AFTER_TAX', 'Cash discount (after tax)'), ('BEFORE_TAX', 'Discount (reduces GST)')], default='AFTER_TAX', max_length=12),
        ),
        migrations.AddField(
            model_name='recurringinvoiceschedule',
            name='price_mode',
            field=models.CharField(choices=[('EXCLUSIVE', 'Tax exclusive'), ('INCLUSIVE', 'Tax inclusive')], default='EXCLUSIVE', max_length=12),
        ),
    ]
