# Generated by Django 5.2.17 on 2026-09-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_cft_quotation_converted_qty_amend_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringinvoicerun',
            name='delivery_challan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_runs', to='sales.deliverychallan'),
        ),
        migrations.AddField(
            model_name='recurringinvoicerun',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_runs', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='recurringinvoiceschedule',
            name='stop_stage',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('SALES_ORDER', 'Sales Order'), ('DELIVERY_CHALLAN', 'Delivery Challan')], default='INVOICE', help_text='Where a generated run stops: draft invoice (default), sales order, or draft delivery challan.', max_length=20),
        ),
    ]
