# Generated by Django 5.2.17 on 2026-09-21 17:34

import core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_sales_purchase_ux_plan'),
        ('masters', '0019_sales_purchase_ux_plan'),
        ('payroll', '0009_employee_tax_regime_payslip_edli_charges_and_more'),
        ('sales', '0050_recurring_stop_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='expected_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_channel',
            field=models.CharField(blank=True, choices=[('WALK_IN', 'Walk-in'), ('ONLINE', 'Online'), ('DISTRIBUTOR', 'Distributor')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='quotation',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='payroll.employee'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='expected_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_channel',
            field=models.CharField(blank=True, choices=[('WALK_IN', 'Walk-in'), ('ONLINE', 'Online'), ('DISTRIBUTOR', 'Distributor')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='payroll.employee'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='expected_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.CreateModel(
            name='DeliveryChallanReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('taxable_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cess_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('return_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.deliverychallan')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challan_returns', to='masters.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryChallanReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[core.validators.validate_gst_rate])),
                ('applied_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('rate_version', models.CharField(blank=True, default='', max_length=64)),
                ('rate_override', models.BooleanField(default=False)),
                ('rate_override_reason', models.CharField(blank=True, default='', max_length=255)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cess', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('challan_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.deliverychallanreturn')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challan_return_items', to='masters.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('route_date', models.DateField(default=django.utils.timezone.localdate)),
                ('vehicle_number', models.CharField(blank=True, max_length=32)),
                ('driver_name', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=12)),
                ('estimated_logistics_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('actual_logistics_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_routes', to='payroll.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-route_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETURNED', 'Returned')], default='PENDING', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='sales.deliveryroute')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='sales.salesorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='deliverychallanreturn',
            index=models.Index(fields=['company', 'status', 'return_date'], name='sales_deliv_company_2a1edb_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverychallanreturn',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('company', 'number'), name='uniq_dc_return_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='deliveryroute',
            index=models.Index(fields=['company', 'status', 'route_date'], name='sales_deliv_company_3217a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryroute',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('company', 'number'), name='uniq_delivery_route_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='deliveryroutestop',
            constraint=models.UniqueConstraint(fields=('route', 'sales_order'), name='uniq_route_stop_order'),
        ),
    ]
