# Generated by Django 5.2.17 on 2026-09-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_whatsapp_webhook_token'),
        ('sales', '0054_credit_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescreditnote',
            name='gst_guard_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='gst_guard_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.companyuser'),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='gst_guard_override_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='gst_guard_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='gst_guard_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.companyuser'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='gst_guard_override_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
