# Generated by Django 5.2.17 on 2026-09-26 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_whatsapp_webhook_token'),
        ('sales', '0055_gst_guard_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroute',
            name='completion_source',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='deliveryroutestop',
            name='completion_source',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='deliveryroutestop',
            name='otp_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='deliveryroutestop',
            name='pod_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recurringinvoiceschedule',
            name='auto_complete',
            field=models.BooleanField(default=False, help_text='When true, an INVOICE run is completed unedited. Default stays a draft for review.'),
        ),
        migrations.AddField(
            model_name='salesdebitnote',
            name='gst_guard_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdebitnote',
            name='gst_guard_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.companyuser'),
        ),
        migrations.AddField(
            model_name='salesdebitnote',
            name='gst_guard_override_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
