# Generated by Django 5.2.17 on 2026-09-26 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rls_gst_period_filing'),
        ('payments', '0032_paymentpromise'),
        ('sales', '0056_track_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroutestop',
            name='customer_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pod_stops', to='payments.customerreceipt'),
        ),
        migrations.AddField(
            model_name='deliveryroutestop',
            name='pod_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pod_stops', to='core.fileasset'),
        ),
        migrations.AddField(
            model_name='deliveryroutestop',
            name='received_by_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
