# Generated by Django 5.2.17 on 2026-10-04 16:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_user_session_version'),
        ('sales', '0061_salesinvoice_customer_status_date_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroutestop',
            name='collected_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='deliveryroutestop',
            name='collected_upi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='deliveryroutestop',
            name='delivery_otp_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='deliveryroutestop',
            name='upi_reference',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='sales.salesitem'),
        ),
        migrations.AlterField(
            model_name='deliveryroutestop',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='PENDING', max_length=12),
        ),
        migrations.CreateModel(
            name='RouteCashHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('VARIANCE', 'Variance')], max_length=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('expected_upi', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('counted_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('counted_upi', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_handover', to='sales.deliveryroute')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
