# Generated by Django 5.2.17 on 2026-10-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0062_open_sales_defects'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroutestop',
            name='stock_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
