# Generated by Django 5.2.17 on 2026-10-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0066_invoice_public_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
