# Generated by Django 5.2.17 on 2026-10-10 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_planwave_remaining'),
        ('masters', '0031_customer_is_pos_walk_in'),
        ('sales', '0067_invoice_cancel_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='quotation',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status_before_conversion',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12),
        ),
        migrations.CreateModel(
            name='QuotationConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target', models.CharField(choices=[('ORDER', 'Sales order'), ('INVOICE', 'Sales invoice'), ('UNKNOWN', 'Unknown (backfilled)')], max_length=8)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, choices=[('DRAFT_DELETED', 'Draft Deleted'), ('ORDER_CANCELLED', 'Order Cancelled'), ('INVOICE_CANCELLED', 'Invoice Cancelled'), ('MANUAL_REOPEN', 'Manual Reopen')], default='', max_length=24)),
                ('backfilled', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='sales.quotation')),
                ('quotation_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='sales.quotationitem')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_conversions', to='sales.salesinvoice')),
                ('sales_invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.salesitem')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_conversions', to='sales.salesorder')),
                ('sales_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.salesorderitem')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['company', 'quotation'], name='sales_quota_company_968441_idx'), models.Index(fields=['sales_order'], name='sales_quota_sales_o_b443fd_idx'), models.Index(fields=['sales_invoice'], name='sales_quota_sales_i_1fe99a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quote_conversion_qty_positive')],
            },
        ),
        migrations.CreateModel(
            name='QuotationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='sales.quotation')),
            ],
            options={
                'ordering': ['-revision'],
                'constraints': [models.UniqueConstraint(fields=('quotation', 'revision'), name='uniq_quotation_revision')],
            },
        ),
    ]
