# -*- coding: utf-8 -*-
"""Wave 19 issue definitions (imported by _wave19_reaudit_append.py)."""

ISSUES: list[dict] = []


def add(**kwargs):
    ISSUES.append(kwargs)


# ── CRITICAL ────────────────────────────────────────────────────────────────
add(
    title="ALLOWED_HOSTS '*' is classified as a local host — DEBUG and DJANGO_ENV gates bypassed",
    category="Security",
    subcategory="Configuration",
    severity="Critical",
    priority="P0",
    module="Core",
    feature="Boot / host validation",
    files="backend/config/settings.py _is_local_allowed_host",
    problem="_is_local_allowed_host treats literal '*' as local. Deploying ALLOWED_HOSTS=* (or including *) skips the explicit DJANGO_ENV requirement and the DEBUG-on-non-local refuse. A mis-set wildcard host boots with DEBUG default and weak SECRET_KEY checks that only fire for production/staging labels.",
    evidence="settings.py: return h in {'localhost', '127.0.0.1', 'testserver', '*'} or h.endswith('.localhost')",
    root_cause="Wildcard host was special-cased for local convenience without excluding it from production safety predicates.",
    business="Public DEBUG/stack traces and unsigned JWT/Fernet material if ops set ALLOWED_HOSTS=*.",
    technical="Fail-closed host gates become fail-open.",
    customer="Tenant data and secrets exposure.",
    security="Critical configuration bypass.",
    performance="N/A",
    scalability="N/A",
    compliance="Fails basic SaaS hardening / SOC2 config hygiene.",
    risk="One env typo disables every host-based safety rail.",
    fix_immediate="Remove '*' from _is_local_allowed_host. Refuse ALLOWED_HOSTS containing * outside DEBUG+explicit local DJANGO_ENV.",
    fix_short="Split settings_prod.py with no host wildcards.",
    fix_long="Vault-injected ALLOWED_HOSTS; boot self-test in CI against malicious host lists.",
    effort="0.5d",
    tests="Boot with ALLOWED_HOSTS=* and DJANGO_DEBUG=1 must ImproperlyConfigured.",
    acceptance="Wildcard hosts never count as local.",
    refs="BB-000001 residual; BB-000249; Wave19 NEW",
)
add(
    title="Postgres RLS SET LOCAL in middleware is a no-op under autocommit — policies never see app.company_id",
    category="Security",
    subcategory="Tenant isolation",
    severity="Critical",
    priority="P0",
    module="Core",
    feature="Postgres RLS",
    files="backend/core/rls.py; backend/core/middleware.py PostgresRlsMiddleware; backend/config/settings.py conn_max_age=600; backend/core/migrations/0005_wave16_postgres_rls.py; 0008_wave19_rls_all_tenant_tables.py",
    problem="set_rls_company runs SELECT set_config('app.company_id', %s, true) (is_local=true). Under Django autocommit each statement is its own transaction, so SET LOCAL is discarded before the view query runs. conn_max_age=600 pools connections. Enabling POSTGRES_RLS_ENABLED therefore either hides all rows (GUC empty → policy false) or, with a superuser DB role, silently bypasses FORCE RLS. Wave 19 migration + Celery prerun do not fix the transaction scope.",
    evidence="rls.py set_config(..., true); middleware calls set_rls_company then get_response; settings DATABASES conn_max_age=600; no atomic() wrapping the request.",
    root_cause="Classic Django+Postgres RLS mistake: SET LOCAL outside the request transaction.",
    business="Cannot safely turn on the isolation control advertised as Wave 16/19 hardening.",
    technical="RLS theater. Enabling the flag bricks the app or does nothing for superuser.",
    customer="False sense of defense-in-depth; cross-tenant risk if role is superuser.",
    security="Critical tenant-isolation control is non-functional.",
    performance="N/A",
    scalability="Shared-DB 10k-tenant story blocked.",
    compliance="Multi-tenant isolation claim unsupported.",
    risk="Ops enables POSTGRES_RLS_ENABLED in staging/prod and either outage or silent bypass.",
    fix_immediate="Keep flag default off. Document unsafe. Do not market RLS as shipped.",
    fix_short="Use a connection-on-checkout hook with SET SESSION + RESET on return; wrap requests in atomic(); reject superuser DB roles.",
    fix_long="Separate DB roles per pool; FORCE RLS + NOBYPASSRLS; pgBouncer transaction pooling design.",
    effort="5-8d",
    tests="With RLS on + non-superuser role: middleware GUC visible to next SELECT in same request; second tenant cannot read invoices. Superuser boot refused.",
    acceptance="RLS either works end-to-end in CI on Postgres or the flag cannot be set.",
    refs="BB-000178 residual; Wave19 NEW",
)
add(
    title="Compose Postgres role is a superuser — FORCE ROW LEVEL SECURITY is silently bypassed",
    category="Security",
    subcategory="Database roles",
    severity="Critical",
    priority="P0",
    module="DevOps",
    feature="Postgres RLS",
    files="docker-compose.yml db service POSTGRES_USER; backend/core/migrations/0008_wave19_rls_all_tenant_tables.py FORCE ROW LEVEL SECURITY",
    problem="Official postgres image creates POSTGRES_USER as superuser. Superusers bypass RLS even with FORCE. App DATABASE_URL uses that same user. Wave 19 RLS expansion is inert in the documented deploy path.",
    evidence="docker-compose.yml POSTGRES_USER interpolated into DATABASE_URL; no NOSUPERUSER/NOBYPASSRLS migration or role split.",
    root_cause="RLS added without a least-privilege app role.",
    business="Tenant isolation marketing is false on the reference stack.",
    technical="FORCE RLS does not apply to the connecting role.",
    customer="Cross-tenant read/write if application filters fail.",
    security="Critical.",
    performance="N/A",
    scalability="Cannot share DB safely.",
    compliance="Fails isolation control objectives.",
    risk="Enabling RLS flag changes nothing on compose/prod overlay.",
    fix_immediate="Create bizboard_app NOSUPERUSER NOBYPASSRLS role; migrate grants; point DATABASE_URL at it; keep postgres for migrations only.",
    fix_short="CI job asserting current_user cannot bypass RLS.",
    fix_long="Migrator vs runtime role split in all envs.",
    effort="2d",
    tests="SET ROLE bizboard_app; SELECT from sales_salesinvoice without GUC returns 0 rows.",
    acceptance="Runtime role cannot bypass RLS.",
    refs="BB-000178; Wave19 RLS SET LOCAL sibling; Wave19 NEW",
)
add(
    title="Manufacturing/Payroll/CRM ViewSets allow any company member including VIEWER to mutate money and stock",
    category="Security",
    subcategory="RBAC",
    severity="Critical",
    priority="P0",
    module="Cross-cutting",
    feature="ERP module ACL",
    files="backend/manufacturing/views.py; backend/payroll/views.py complete_pay_run; backend/crm/views.py; backend/core/viewsets.py CompanyScopedViewSet; backend/core/permissions.py",
    problem="Sales/Purchase/Payment viewsets use CanCreate* / CanCancelDocuments. Manufacturing, Payroll, and CRM only use IsAuthenticated+HasCompany (+ feature assert). VIEWER and SALES_STAFF can POST work-order release (consumes stock as SALE), complete pay runs (posts Dr 5200 Cr 1100 cash), and CRUD leads. No can_manage_inventory / can_post_journals / IsOwner checks.",
    evidence="BomViewSet/WorkOrderViewSet permission_classes = [IsAuthenticated, HasCompany]; PayRunViewSet.complete calls complete_pay_run; CompanyScopedViewSet has no role gate on create/update/destroy.",
    root_cause="Wave 17 ERP MVPs bolted onto CompanyScopedViewSet without capability matrix.",
    business="Least-privilege staff can drain inventory and cash books.",
    technical="RBAC model inconsistent across modules.",
    customer="Internal fraud / accidental payroll complete.",
    security="Critical authorization hole when flags on.",
    performance="N/A",
    scalability="N/A",
    compliance="SoD failure for payroll and stock.",
    risk="First multi-role pilot with ENABLE_PAYROLL or ENABLE_MANUFACTURING is exploitable.",
    fix_immediate="Require IsOwner or dedicated caps on all ERP writes; block VIEWER entirely; block payroll complete without can_post_journals+Owner.",
    fix_short="Extend capability flags: can_manage_manufacturing, can_run_payroll, can_manage_crm.",
    fix_long="Central policy engine (action, resource, role) shared by FE RoleRoute and BE.",
    effort="3d",
    tests="VIEWER 403 on WO release, pay-run complete, lead create. Accountant cannot release WO.",
    acceptance="VIEWER cannot change stock, cash, or CRM records.",
    refs="BB-000018 residual; Wave19 NEW",
)
add(
    title="Work order release posts MovementType.SALE — pollutes sales qty, FIFO COGS, and inventory reports",
    category="Inventory",
    subcategory="Manufacturing movements",
    severity="Critical",
    priority="P0",
    module="Manufacturing",
    feature="Work order release",
    files="backend/manufacturing/services.py release_work_order; backend/inventory/models.py MovementType; backend/sales/cogs_service.py; backend/inventory/services.py _apply_cost_layers",
    problem="Component consumption uses MovementType.SALE. SALE is the sales-invoice/challan issue type: negative stock, FIFO layer consume, and any report/KPI filtering movement_type=SALE treats manufacturing issues as customer sales. No MANUFACTURE_ISSUE / WIP type exists.",
    evidence="release_work_order: InventoryService.post_movement(..., movement_type=MovementType.SALE, reference_type='work_order')",
    root_cause="MVP reused existing enum instead of extending the stock domain.",
    business="Sales quantity, COGS analytics, and statutory stock registers become wrong the moment manufacturing is used.",
    technical="Domain type confusion; FIFO layers consumed as if sold.",
    customer="Owners see fake sales and vanishing COGS integrity.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Inventory records not true and fair.",
    risk="Any manufacturing_enabled tenant corrupts operational metrics.",
    fix_immediate="Add MovementType.MANUFACTURE_ISSUE / MANUFACTURE_RECEIPT; stop using SALE/PURCHASE; backfill existing WO movements.",
    fix_short="WIP account + manufacturing variance journals.",
    fix_long="Full manufacturing valuation service (BOM cost rollup from layers).",
    effort="3-5d",
    tests="Release WO → zero new SALE movements; sales report qty unchanged; FIFO layers reduced with reference_type=work_order.",
    acceptance="Manufacturing never writes SALE or PURCHASE movement types.",
    refs="BB-000184 residual; Wave19 NEW",
)
add(
    title="Work order complete receipts FG as PURCHASE at component list purchase_price — not consumed FIFO cost",
    category="Accounting",
    subcategory="Manufacturing valuation",
    severity="Critical",
    priority="P0",
    module="Manufacturing",
    feature="Work order complete",
    files="backend/manufacturing/services.py complete_work_order",
    problem="FG receipt uses MovementType.PURCHASE and unit_cost = sum(component.purchase_price * bom_qty). Ignores actual FIFO/WAVG costs stamped on release issues. Inflates/deflates inventory valuation vs true consumption. Purchase registers that key on PURCHASE movements will treat factory output as vendor purchases.",
    evidence="complete_work_order unit_cost loop uses comp.purchase_price; post_movement movement_type=PURCHASE.",
    root_cause="No manufacturing costing model.",
    business="Balance sheet inventory and purchase analytics wrong; GST purchase aids may include FG receipts if any report uses movements.",
    technical="Valuation identity broken: issues ≠ receipts cost.",
    customer="Unusable stock valuation after first WO.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="AS-2 / Ind AS 2 inventory costing failure.",
    risk="accounting_enabled + manufacturing produces indefensible books.",
    fix_immediate="Value FG at sum of issue movement unit_costs; use MANUFACTURE_RECEIPT type.",
    fix_short="Post inventory GL: Dr FG / Cr WIP / Cr variance.",
    fix_long="Multi-level BOM rollup + standard vs actual.",
    effort="4d",
    tests="Buy RM @10, WO consume, complete FG unit_cost=10 not product.purchase_price.",
    acceptance="FG layer cost equals consumed layer cost.",
    refs="Wave19 WO SALE sibling; Wave19 NEW",
)
add(
    title="GSTR-1/3B/9 mix all company_gstin stamps into one return keyed off primary company.gstin",
    category="GST",
    subcategory="Multi-GSTIN filing",
    severity="Critical",
    priority="P0",
    module="Reporting",
    feature="GSTR builders",
    files="backend/reporting/gst_returns.py _gst_sales_invoices _inter_state; backend/sales/models.py SalesInvoice.company_gstin; web/src/pages/sales/NewInvoicePage.tsx",
    problem="Wave 17 added CompanyGstin + invoice.company_gstin stamp. Builders filter only company= and date/type. Interstate vs intra uses company.gstin/company.state, not the stamped branch GSTIN/state. FE invoice editor has no GSTIN picker (no companyGstin references). Multi-branch MSMEs file one blended GSTR under the wrong GSTIN and wrong POS split.",
    evidence="_gst_sales_invoices has no company_gstin filter; _inter_state(..., company_gstin=company.gstin); NewInvoicePage.tsx grep company_gstin/companyGstin = no matches.",
    root_cause="Stamp field added without filing dimension or UI.",
    business="Wrong GSTN upload → notices, interest, penalty.",
    technical="Multi-GSTIN data model is incomplete.",
    customer="CA cannot file per registration.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Critical CGST Rules — returns are GSTIN-scoped.",
    risk="Commercial launch of multi-branch/GSTIN is legally unsafe.",
    fix_immediate="Honesty: hide multi-GSTIN or force single active filing GSTIN; filter GSTR by stamp; fail if mixed stamps in period.",
    fix_short="Per-GSTIN series, POS, GSTR, e-invoice IRP creds.",
    fix_long="Branch org unit as first-class filing entity.",
    effort="8-12d",
    tests="Two GSTINs same company → two GSTR payloads; mixed period without filter fails closed.",
    acceptance="No GSTR payload contains invoices of another GSTIN.",
    refs="BB-000078 residual; Wave19 NEW",
)
add(
    title="OCR/LLM prompt forces gst_rate=18 when unknown — silent tax hallucination into purchase bills",
    category="GST",
    subcategory="OCR extraction",
    severity="Critical",
    priority="P0",
    module="Imports",
    feature="Purchase bill OCR",
    files="backend/core/services/llm.py EXTRACT_PROMPT; backend/imports/services.py apply_extraction / commit",
    problem="Prompt rule: 'gst_rate must be one of 0, 0.25, 3, 5, 12, 18, 28 when known; else 18.' Unknown HSN/rate becomes 18% with no rate_unknown flag. low_confidence_accepted gates overall confidence, not per-line tax certainty. Committing creates purchase tax lines and ITC that were never on the supplier invoice.",
    evidence="llm.py EXTRACT_PROMPT lines 34-36 else 18.",
    root_cause="Prompt optimized for JSON completeness over tax honesty.",
    business="Over/under ITC; GSTR-2B mismatches; vendor disputes.",
    technical="Garbage rates enter money fields.",
    customer="Books and GST aids lie after 'helpful' OCR.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="ITC claimed without tax invoice rate evidence.",
    risk="Every OCR-assisted purchase is a GST exposure.",
    fix_immediate="Default unknown rate to null/rate_unknown; block commit until user sets rate; never default 18.",
    fix_short="Per-line confidence + HSN master suggestion, not auto-fill tax.",
    fix_long="Human-in-the-loop extraction UI with supplier PDF overlay.",
    effort="2d",
    tests="Blank-rate image → preview gst_rate empty/unknown; commit 400 without explicit rate.",
    acceptance="OCR cannot invent a GST rate.",
    refs="BB-000488 family; Wave19 NEW",
)
add(
    title="Wave 18 Open==0 / PR 9.0 claim invalidated — residual P0s remain in live tree",
    category="Process",
    subcategory="Audit integrity",
    severity="Critical",
    priority="P0",
    module="Docs",
    feature="Launch gates",
    files="docs/reviews/01_EXECUTIVE_SUMMARY.md; docs/reviews/21_PRODUCTION_READINESS.md; docs/reviews/CHANGELOG.md Wave 18",
    problem="Wave 18 closed Deferred IDs and asserted MVP completeness / engineering scores ~9.0. Independent Wave 19 re-audit found multiple live P0 correctness/security defects (RLS theater, host bypass, WO SALE/PURCHASE, GSTR multi-GSTIN, OCR 18%, VIEWER payroll). Open==0 was a checklist artifact, not a launch gate — same failure mode as BB-000325/461.",
    evidence="CHANGELOG Wave 18; exec banner Wave 17/18 scores; live code citations in BB-000550–558.",
    root_cause="Closing historical IDs without adversarial residual tests on newly shipped ERP/RLS/GSTIN surfaces.",
    business="Leadership may greenlight commercial launch on false scores.",
    technical="Process bug.",
    customer="Pilots sold incomplete/unsafe modules.",
    security="Undocumented P0s.",
    performance="N/A",
    scalability="N/A",
    compliance="Governance failure.",
    risk="Repeat of Waves 8–14 false closures.",
    fix_immediate="Publish Wave 19 Open≠0; lower scores; block GA language.",
    fix_short="Semantic gates for RLS runtime, WO movement types, GSTR-per-GSTIN, VIEWER ERP 403, OCR no default rate.",
    fix_long="launch_approved ≠ register_open_zero.",
    effort="1d",
    tests="_wave19 residual probes fail on current tree until fixes land.",
    acceptance="No 10/10 or Open==0 claim while P0 Open exists.",
    refs="BB-000325; BB-000461; Wave19 NEW",
)

# ── HIGH ────────────────────────────────────────────────────────────────────
add(
    title="Nginx rewrites numeric Host to localhost — Django host/DEBUG/CSRF see a local request",
    category="Security",
    subcategory="Edge / Host header",
    severity="High",
    priority="P1",
    module="DevOps",
    feature="nginx default.conf",
    files="nginx/default.conf map $host $django_host",
    problem="Any request whose Host is a raw IPv4 is proxied to Django as Host: localhost. ALLOWED_HOSTS and DEBUG-local checks pass. Absolute URLs, password-reset hosts, and CSRF origin binding can be wrong. Same file is the edge config for all compose profiles including prod overlay (TLS still terminate upstream).",
    evidence="nginx/default.conf: ~^[0-9.]+$ localhost; proxy_set_header Host $django_host on /api/.",
    root_cause="LAN phone-testing convenience baked into shared edge config.",
    business="Host confusion / cookie domain issues on IP access; weakens host allowlist.",
    technical="Security middleware sees localhost for public IP hits.",
    customer="Broken links and possible auth weirdness on IP URLs.",
    security="High — host allowlist bypass for IP clients.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Prod accessed via IP skips non-local DEBUG protection if DEBUG slipped on.",
    fix_immediate="Limit IP→localhost map to development compose only; prod nginx must pass real Host and list IPs in ALLOWED_HOSTS explicitly or refuse.",
    fix_short="Separate nginx.dev.conf vs nginx.prod.conf.",
    fix_long="TLS hostname only; no IP serving in prod.",
    effort="1d",
    tests="Prod nginx fixture does not rewrite Host; Django DisallowedHost on unknown IP.",
    acceptance="Production never remaps Host to localhost.",
    refs="Wave19 NEW",
)
add(
    title="set_rls_company swallows all exceptions — RLS enablement fails open/closed without request failure",
    category="Security",
    subcategory="Fail-closed controls",
    severity="High",
    priority="P1",
    module="Core",
    feature="RLS helper",
    files="backend/core/rls.py",
    problem="except Exception: logger.exception; never raised. Combined with SET LOCAL no-op, operators cannot detect misconfiguration via 5xx. Celery prerun same helper.",
    evidence="rls.py: 'Failures are logged and never raised.'",
    root_cause="Availability bias over security fail-closed.",
    business="Silent isolation failure.",
    technical="No SLO/alert on GUC set failure.",
    customer="Cross-tenant or empty datasets without explanation.",
    security="High.",
    performance="N/A",
    scalability="N/A",
    compliance="Control not monitorable.",
    risk="Months of 'RLS on' without GUC.",
    fix_immediate="If POSTGRES_RLS_ENABLED, raise on set failure; fail request 503.",
    fix_short="Metrics + liveness probe selecting current_setting.",
    fix_long="Sidecar policy.",
    effort="0.5d",
    tests="Force set_config failure → 503 when flag on.",
    acceptance="RLS set errors are fatal when enabled.",
    refs="Wave19 RLS SET LOCAL sibling; Wave19 NEW",
)
add(
    title="Celery task_prerun resolves company_id by querying tenant tables before GUC is set",
    category="Security",
    subcategory="RLS + async",
    severity="High",
    priority="P1",
    module="Core",
    feature="Celery RLS",
    files="backend/config/celery.py set_rls_company_for_task _company_id_from_document",
    problem="To set RLS, Celery reads SalesInvoice/PurchaseInvoice.company_id. Those tables are RLS-protected. Without GUC (and with a non-superuser), the lookup returns None, set_rls_company no-ops, and PDF/email/import tasks see zero rows or fail opaquely. With superuser, lookup works and RLS never applies.",
    evidence="celery.py: SalesInvoice.objects.filter(pk=pk).values_list('company_id') then set_rls_company(company_id).",
    root_cause="Chicken-and-egg tenant bootstrap under RLS.",
    technical="Async jobs incompatible with the RLS design.",
    business="PDF/share/OCR jobs break when RLS is on.",
    customer="Missing invoice PDFs.",
    security="High if superuser continues to be used.",
    performance="N/A",
    scalability="Beat/worker fleet cannot be multi-tenant safe.",
    compliance="N/A",
    risk="Enabling RLS breaks statutory PDF generation.",
    fix_immediate="Pass company_id explicitly in every task signature; never look up tenant rows to discover it.",
    fix_short="Task base class requiring company_id kwarg.",
    fix_long="Outbox pattern with tenant context header.",
    effort="2d",
    tests="All shared tasks include company_id; prerun does not SELECT tenant tables.",
    acceptance="No tenant SELECT before GUC set.",
    refs="Wave19 RLS SET LOCAL sibling; Wave19 NEW",
)
add(
    title="BomLine, PaySlip, and StockTransferLine have no company_id — omitted from Wave 19 RLS table list",
    category="Database",
    subcategory="Tenancy defense-in-depth",
    severity="High",
    priority="P1",
    module="Database",
    feature="Child row tenancy",
    files="backend/manufacturing/models.py BomLine; backend/payroll/models.py PaySlip; backend/inventory/models.py StockTransferLine; backend/core/migrations/0008_wave19_rls_all_tenant_tables.py",
    problem="Wave 19 RLS lists manufacturing_bom, payroll_payrun, inventory_stocktransfer but not child line/slip tables. Those models lack company FK. Direct SQL or careless ORM on BomLine/PaySlip/StockTransferLine bypasses RLS and leaks BOM recipes, net salaries, and transfer quantities.",
    evidence="BomLine(models.Model) no company; PaySlip no company; StockTransferLine no company; TENANT_TABLES omits them.",
    root_cause="BB-000017 pattern reintroduced by Wave 17 ERP/inventory children.",
    business="Salary and costing leak across tenants if RLS relied upon.",
    technical="Incomplete tenancy schema.",
    customer="Privacy incident.",
    security="High under RLS-on or raw SQL admin.",
    performance="N/A",
    scalability="N/A",
    compliance="PII (payroll) without tenant key.",
    risk="Any reporting join on child tables is cross-tenant capable at SQL level.",
    fix_immediate="Denormalize company_id on all child tables; add to RLS list; backfill.",
    fix_short="CI check: every table with money/PII has company_id + RLS policy.",
    fix_long="CompanyScopedModel required for all persisted business rows.",
    effort="2d",
    tests="Migration adds company_id NOT NULL; RLS policy present.",
    acceptance="No business child table without company_id.",
    refs="BB-000017 residual; Wave19 NEW",
)
add(
    title="Feature-flag asserts check phantom company.manufacturing_enabled / payroll_enabled / crm_enabled — ignore feature_flags JSON",
    category="Authorization",
    subcategory="Feature flags",
    severity="High",
    priority="P1",
    module="Core",
    feature="Runtime flags",
    files="backend/manufacturing/permissions.py; backend/payroll/permissions.py; backend/crm/permissions.py; backend/accounts/models.py feature_flags; backend/core/services/feature_flags.py; backend/accounts/serializers.py CompanySerializer",
    problem="assert_*_enabled returns early if getattr(company, 'manufacturing_enabled', False) — field does not exist. Real per-company switch is feature_flags JSON, which is not on CompanySerializer (cannot be read/written via API) and is not consulted by asserts. Backend only honors global ENABLE_* env. FE can show module via JSON override while API 404s, or env-on exposes APIs to companies that 'opted out' in JSON.",
    evidence="No manufacturing_enabled on Company; feature_flags not in CompanySerializer.fields; assert ignores feature_flags.",
    root_cause="Two incomplete flag systems (env vs JSON vs phantom attrs).",
    business="Cannot sell per-tenant module SKUs; accidental global enablement.",
    technical="Flag divergence FE vs BE.",
    customer="Broken nav or unexpected module exposure.",
    security="High when env globally on.",
    performance="N/A",
    scalability="Plan/entitlement system blocked.",
    compliance="N/A",
    risk="ENABLE_PAYROLL=1 turns on payroll APIs for every tenant.",
    fix_immediate="Assert on build_feature_flags(company)[key]; expose read/write Owner API for flags with audit.",
    fix_short="Remove phantom getattr; single flag service.",
    fix_long="Billing entitlements service.",
    effort="2d",
    tests="Company JSON ENABLE_MANUFACTURING false + env true → 404; JSON true + env false → 404 unless entitlement allows.",
    acceptance="BE and FE flags identical; no phantom attributes.",
    refs="Wave 17G residual; Wave19 NEW",
)
add(
    title="Manufacturing stock movements post no GL when accounting_enabled — perpetual inventory books diverge",
    category="Accounting",
    subcategory="Dual ledger",
    severity="High",
    priority="P1",
    module="Manufacturing",
    feature="WO accounting",
    files="backend/manufacturing/services.py; backend/accounting/services.py",
    problem="Release/complete change on-hand qty and FIFO layers but never call PostingService. With accounting_enabled, trial balance inventory (1400) no longer matches stock valuation after any WO.",
    evidence="manufacturing/services.py has no accounting import; only inventory movements.",
    root_cause="ERP MVP ignored ADR-A02 (GL projection must succeed with document transition).",
    business="Unusable books for manufacturers.",
    technical="Dual-ledger divergence class of BB-000016 reintroduced.",
    customer="CA rejects trial balance.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Books not true and fair.",
    risk="accounting_enabled manufacturers silently corrupt GL.",
    fix_immediate="Block manufacturing when accounting_enabled until postings exist OR post WIP/FG/RM entries atomically with WO transitions.",
    fix_short="Full manufacturing journal matrix + cancel reverse.",
    fix_long="Inventory subledger reconciled to GL 1400 nightly.",
    effort="5d",
    tests="accounting_enabled WO complete → inventory GL movement equals valuation delta.",
    acceptance="Stock valuation == GL inventory after WO lifecycle.",
    refs="BB-000016 residual; Wave19 NEW",
)
add(
    title="Released work orders cannot be cancelled or reversed — component stock permanently issued",
    category="Inventory",
    subcategory="Status machine",
    severity="High",
    priority="P1",
    module="Manufacturing",
    feature="WO cancel",
    files="backend/manufacturing/services.py; backend/manufacturing/views.py; backend/manufacturing/models.py WorkOrder.Status",
    problem="Statuses DRAFT→RELEASED→COMPLETED only. No cancel action. Mistaken release consumes RM via SALE movements with no reverse path (would need SALES_RETURN semantics — also wrong).",
    evidence="WorkOrder.Status has no CANCELLED; views only release/complete actions.",
    root_cause="Incomplete state machine.",
    business="Operators cannot undo shop-floor mistakes.",
    technical="Orphan negative stock / FIFO consumption.",
    customer="Support escalations; physical vs system mismatch.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Audit trail of corrections missing.",
    risk="First mis-click permanently damages stock.",
    fix_immediate="Add cancel-from-RELEASED that posts reverse manufacture issue and restores layers.",
    fix_short="Cancel-from-COMPLETED with FG un-receipt if not sold.",
    fix_long="WO amendment + scrap/rework statuses.",
    effort="3d",
    tests="Release then cancel → RM on_hand restored; no SALE residue.",
    acceptance="Every non-terminal WO can be safely undone.",
    refs="Wave19 WO SALE sibling; Wave19 NEW",
)
add(
    title="Payroll posts gross=salary, deductions=0 — no PF, ESI, PT, TDS, EPF/EPS split, or Form 24Q artefacts",
    category="Compliance",
    subcategory="Statutory payroll",
    severity="High",
    priority="P1",
    module="Payroll",
    feature="Pay run",
    files="backend/payroll/services.py complete_pay_run; backend/payroll/models.py Employee",
    problem="Employee has only name/code/salary/status. complete_pay_run sets deductions=0, net=gross. GL Dr 5200 Cr 1100/2100 for net only. Product list claims Payroll implemented. Indian MSME payroll without PF/ESI/TDS is a compliance product, not a stub — launching it causes illegal salary processing.",
    evidence="Employee model fields; complete_pay_run deductions = Decimal('0').",
    root_cause="MVP labeled as module complete.",
    business="Cannot legally run payroll in India; mis-selling.",
    technical="Wrong GL (trade AP 2100 vs salary payable / statutory payable).",
    customer="PF/ESI default, TDS interest, employee disputes.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="EPF Act, ESIC, Income-tax TDS, state PT.",
    risk="Commercial 'Payroll ✓' claim is a legal liability.",
    fix_immediate="Honesty banner + flag default off; rename to 'salary voucher MVP'; block if registration implies statutory payroll.",
    fix_short="PF/ESI/PT/TDS engines + payable accounts 2110-2140.",
    fix_long="Full payroll product (attendance, LOP, Form 16, ECR).",
    effort="20-40d statutory MVP; honesty 0.5d",
    tests="Honesty gate; no 2100 trade AP for salary; deductions line items persist.",
    acceptance="Either statutory engines exist or UI/API refuse 'payroll' wording.",
    refs="BB-000035/455 residual honesty; Wave19 NEW",
)
add(
    title="Payroll journals credit cash 1100 or trade AP 2100 — salary payable and statutory payables unused",
    category="Accounting",
    subcategory="Chart of accounts misuse",
    severity="High",
    priority="P1",
    module="Payroll",
    feature="Payroll GL",
    files="backend/payroll/services.py complete_pay_run",
    problem="pay_from_cash True → Cr 1100 cash; else Cr 2100 (trade creditors). Salary is not vendor AP. No 2120 Salary Payable. Expense is net not gross (should Dr gross expense, Cr deductions liabilities, Cr net payable/cash).",
    evidence="PostingService._account(company, '1100' if pay_from_cash else '2100') with total_net only.",
    root_cause="Shortcut posting.",
    business="AP aging includes salaries; cash control wrong if pay_from_cash false then later paid via supplier payment.",
    technical="COA semantics violated.",
    customer="Misleading payables.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Incorrect books.",
    risk="accountants disable module after first month.",
    fix_immediate="Stop using 2100; add 2120; post gross/deduction/net split; do not hit cash unless payment voucher separate.",
    fix_short="Two-step: accrue then pay.",
    fix_long="Payroll subledger.",
    effort="3d",
    tests="Complete pay run → 2100 unchanged; 2120 credited; expense=gross.",
    acceptance="Trade AP unaffected by payroll.",
    refs="Wave19 payroll statutory sibling; Wave19 NEW",
)
add(
    title="GSTR-9 tables 6 and 7 remain stubs while table 18 was marked complete",
    category="GST",
    subcategory="GSTR-9",
    severity="High",
    priority="P1",
    module="Reporting",
    feature="GSTR-9 worksheet",
    files="backend/reporting/gst_returns.py build_gstr9",
    problem="Wave 19 gate only asserts table 18 aid_kind hsn_inward. Tables still include outward_nil_exempt_stub, itc_reversed_stub, other_itc_stub. Annual return worksheet is not filable. Closing BB-000049 as Resolved overstated completeness.",
    evidence="gst_returns.py aid_kind stubs around tables 6/7; disclaimer still 'Not a complete portal upload.'",
    root_cause="Partial table delivery treated as issue closure.",
    business="CA cannot prepare GSTR-9 from BizBoard alone.",
    technical="Schema honesty drift.",
    customer="Manual Excel continues.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="GSTR-9 incomplete.",
    risk="Marketing 'GSTR-9 shipped' after Wave 18.",
    fix_immediate="Reopen honesty: list stub tables in UI; do not claim GSTR-9 complete.",
    fix_short="Implement table 6 ITC / 7 reversals from 3B+2B+manual adjustments.",
    fix_long="Full GSTR-9/9C product.",
    effort="10-15d for tables 6-8 quality",
    tests="No aid_kind containing stub in published tables without UI watermark.",
    acceptance="Every GSTR-9 table is either computed or explicitly unavailable.",
    refs="BB-000049 residual; Wave19 NEW",
)
add(
    title="Document number series and uniqueness are per company, not per GSTIN",
    category="GST",
    subcategory="Invoice numbering",
    severity="High",
    priority="P1",
    module="Core",
    feature="DocumentSeries",
    files="backend/core/services/document_numbers.py; backend/core/models.py DocumentSeries; backend/sales/models.py uniq_sales_number_per_company",
    problem="GST invoice serials must be unique per GSTIN registration (and typically per FY). BizBoard unique constraint is (company, number). Two branches sharing a tenant collide on INV-0001 or interleave one series across GSTINs — both illegal.",
    evidence="DocumentSeries unique (company, doc_type); SalesInvoice UniqueConstraint company+number.",
    root_cause="Single-GSTIN assumption not updated when CompanyGstin shipped.",
    business="Invalid tax invoice numbering.",
    technical="Series service unaware of filing identity.",
    customer="GSTN/portal rejects or audit failure.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Rule 46 / invoice serial requirements.",
    risk="Multi-GSTIN stamp without series split is worse than no stamp.",
    fix_immediate="One series per (company, gstin, doc_type, FY); unique constraint includes gstin_id.",
    fix_short="FY reset; gap detection report.",
    fix_long="Configurable series per branch/doc type.",
    effort="4d",
    tests="Two GSTINs can both issue INV-0001; uniqueness enforced per GSTIN.",
    acceptance="No cross-GSTIN serial collision or shared counter.",
    refs="Wave19 multi-GSTIN GSTR sibling; Wave19 NEW",
)
add(
    title="Account Aggregator matcher assigns receipts by amount-only (±0.01) with no date/UTR/party check",
    category="Accounting",
    subcategory="Bank reconciliation",
    severity="High",
    priority="P1",
    module="Banking",
    feature="AA match",
    files="backend/banking/services.py match_aa_to_receipts",
    problem="First CustomerReceipt in amount band wins, newest date first, no customer/UTR/reference/date-window. Two ₹10,000 receipts cross-match. Prior payment-webhook amount-only bugs were supposedly closed; AA reintroduces the anti-pattern.",
    evidence="filter amount__gte/lte; order_by -receipt_date; no other predicates.",
    root_cause="Copy-paste recon heuristic.",
    business="Wrong settlement → AR distortion, customer statements wrong.",
    technical="Non-deterministic match under duplicates.",
    customer="Paid invoices still due / wrong customer credited.",
    security="Fraud obscuration.",
    performance="O(n*m) loop.",
    scalability="Breaks with volume.",
    compliance="Bank recon not auditable.",
    risk="AA-enabled tenants silently misallocate cash.",
    fix_immediate="Require UTR/reference equality or unique amount within date window; otherwise leave unmatched.",
    fix_short="Scoring + human confirm API.",
    fix_long="Double-entry bank ledger with suggested matches only.",
    effort="2d",
    tests="Two equal amounts do not auto-match; UTR match succeeds.",
    acceptance="No amount-only auto-match.",
    refs="BB-000196 family residual; Wave19 NEW",
)
add(
    title="WhatsApp Cloud credentials fall back to process-wide env token for every tenant",
    category="Security",
    subcategory="Multi-tenant secrets",
    severity="High",
    priority="P1",
    module="Integrations",
    feature="WhatsApp send",
    files="backend/core/services/whatsapp.py _resolve_whatsapp_credentials",
    problem="If company IntegrationConnection missing/unreadable, code uses settings.WHATSAPP_TOKEN / WHATSAPP_PHONE_NUMBER_ID. All tenants then send as BizBoard's number; inbound webhooks cannot be routed; one leaked env token impersonates platform. Decrypt exceptions are swallowed.",
    evidence="whatsapp.py: if not token: token = settings.WHATSAPP_TOKEN; except Exception: pass.",
    root_cause="Env convenience fallback in multi-tenant SaaS.",
    business="Meta policy violations; cross-tenant message attribution.",
    technical="No tenant isolation on messaging identity.",
    customer="Customers receive messages from unknown business number.",
    security="High — shared credential blast radius.",
    performance="N/A",
    scalability="Cannot onboard many WABA accounts.",
    compliance="DPDP / telecom identity.",
    risk="First WhatsApp-cloud customer shares identity with all others.",
    fix_immediate="Never fall back to global token in production; fail closed to wa.me link or error.",
    fix_short="Per-company WABA only; platform token only for BizBoard ops tenant.",
    fix_long="Secrets manager + rotation.",
    effort="1d",
    tests="No company creds + env token set → mode=link or 400, not cloud send.",
    acceptance="Global token cannot send on behalf of a tenant.",
    refs="BB-000026 residual; Wave19 NEW",
)
add(
    title="Invoice/POS IndexedDB outbox stores draft lines in plaintext on shared counter devices",
    category="Security",
    subcategory="Local storage",
    severity="High",
    priority="P1",
    module="Web",
    feature="Offline outbox",
    files="web/src/offline/invoiceDraftCache.ts",
    problem="OutboxDraft persists customerId, lines, prices, idempotency keys in IndexedDB (bizboard-invoice-outbox) scoped only by companyId:userId. No encryption at rest. MSME POS PCs are shared. Wave 19 gate only checks enqueueDraft/flushOutbox/indexedDB presence.",
    evidence="invoiceDraftCache.ts IDB_NAME; payload Record; no crypto.",
    root_cause="Offline MVP without threat model.",
    business="Competitor/staff data theft from the browser profile.",
    technical="PII + pricing on disk.",
    customer="Customer phone/names/prices leak.",
    security="High on shared Windows POS.",
    performance="N/A",
    scalability="N/A",
    compliance="DPDP reasonable security.",
    risk="Internet cafe / shared clerk login residue.",
    fix_immediate="Document risk; wipe on logout; session lock; exclude PII from outbox where possible.",
    fix_short="Encrypt IDB with session wrapping key; TTL.",
    fix_long="Device attestation + clerk PIN.",
    effort="3d",
    tests="Logout clears IDB; second user cannot read first user's drafts.",
    acceptance="Logout/user-switch purges outbox; threat documented in ONBOARDING.",
    refs="BB-000180 residual; Wave19 NEW",
)
add(
    title="Owner Company PATCH can still write gsp_credentials despite gated-settings policy",
    category="Security",
    subcategory="Secrets APIs",
    severity="High",
    priority="P1",
    module="Accounts",
    feature="GSP credentials",
    files="backend/accounts/serializers.py CompanySerializer.update; backend/accounts/views.py CompanyDetailView",
    problem="eway_enabled/gsp_provider are read_only (BB-000259/286) but gsp_credentials write-only JSON is processed in CompanySerializer.update and persists gsp_credentials_encrypted. Bypasses dedicated GSP settings ACL/audit path; easier to accidentally log request bodies.",
    evidence="fields include gsp_credentials; update() encrypt_gsp_credentials merge.",
    root_cause="Incomplete lock-down of CompanySerializer.",
    business="Uncontrolled IRP credential rotation.",
    technical="Two write paths for the same secret.",
    customer="Harder incident response.",
    security="High — secret sprawl.",
    performance="N/A",
    scalability="N/A",
    compliance="Secret handling control gap.",
    risk="Creds set without provider/test-mode invariants.",
    fix_immediate="Remove gsp_credentials from CompanySerializer; only gated endpoint.",
    fix_short="Audit every secret write; redacted logs.",
    fix_long="Secrets service + KMS.",
    effort="1d",
    tests="PATCH /company/ with gsp_credentials → 400/ignored; dedicated endpoint still works for Owner.",
    acceptance="Single write path for GSP secrets.",
    refs="BB-000259 residual; Wave19 NEW",
)
add(
    title="README, OpenAPI description, and KNOWN_LIMITATIONS contradict shipped Wave 17–18 modules",
    category="Documentation",
    subcategory="Product honesty",
    severity="High",
    priority="P1",
    module="Docs",
    feature="Public claims",
    files="README.md; backend/config/settings.py SPECTACULAR_SETTINGS; docs/reviews/KNOWN_LIMITATIONS_AND_TECH_DEBT.md",
    problem="README still says not claimed: WhatsApp beyond link, native mobile, RLS, FIFO, Manufacturing, Payroll, CRM, multi-company GSTIN, live Tally. SPECTACULAR DESCRIPTION says Manufacturing/Payroll/CRM/live NIC/WhatsApp Business out of scope while those apps are installed. KNOWN_LIMITATIONS table still says 'No Manufacturing / BOM / WO', 'No Payroll', 'FIFO incomplete'. Product audit prompt and Wave 18 changelog claim the opposite. Triple divergence guarantees mis-selling.",
    evidence="README lines 24-27; SPECTACULAR_SETTINGS DESCRIPTION; KNOWN_LIMITATIONS rows 9-23.",
    root_cause="Docs not updated when mega-MVPs merged; Wave 18 honesty note appended without rewriting tables.",
    business="Sales vs eng vs audit tell three stories.",
    technical="Onboarding and OpenAPI lie to integrators.",
    customer="Buy wrong product.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Advertising / consumer protection risk.",
    risk="Pilot contracts cite README scope while UI shows Payroll.",
    fix_immediate="Rewrite honesty matrix once: MVP vs flag vs not-built vs ops-gated.",
    fix_short="Generate module matrix from feature flags + code probes in CI.",
    fix_long="Product catalog service.",
    effort="1.5d",
    tests="CI grep fails if SPECTACULAR says out-of-scope while app in INSTALLED_APPS without watermark.",
    acceptance="Single canonical module matrix linked from README, OpenAPI, UI banners, audit docs.",
    refs="BB-000014; BB-000462 residual; Wave19 NEW",
)
add(
    title="Capacitor 'mobile app' is config-only — no ios/android projects, plugins, or store artefacts",
    category="Mobile",
    subcategory="Packaging",
    severity="High",
    priority="P1",
    module="Mobile",
    feature="Capacitor shell",
    files="mobile/capacitor.config.ts; mobile/package.json; mobile/README.md; web/public/manifest.webmanifest",
    problem="mobile/ contains only capacitor.config.ts pointing at ../web/dist. No android/, ios/, native plugins, push, secure storage, or camera OCR. PWA manifest has no service worker (web/src has zero serviceWorker references) so standalone display ≠ offline app. Product module list marks Mobile App implemented.",
    evidence="Glob mobile/** = 3 files; no SW registration.",
    root_cause="Shell accepted as BB-000179 Resolved.",
    business="Cannot ship Play Store / App Store build.",
    technical="Wrapper without a wrappee project.",
    customer="Install expectations fail.",
    security="WebView wrapping without hardening (SSL pin, JS bridge allowlist).",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Marketing screenshots of 'app' are a browser bookmark.",
    fix_immediate="Honesty: 'responsive web + optional PWA manifest'; unclaim mobile app.",
    fix_short="Generate android project + secure cookies + no mixed content; SW for shell cache only.",
    fix_long="True native or well-hardened Capacitor with offline sync protocol.",
    effort="Honesty 0.25d; real Android MVP 15-25d",
    tests="CI module matrix lists mobile as shell-only.",
    acceptance="No 'Mobile App ✓' without storeable binary.",
    refs="BB-000179 residual; Wave19 NEW",
)
add(
    title="No residual automated tests for VIEWER ERP ACL, WO movement types, GSTR-per-GSTIN, or RLS runtime",
    category="Testing",
    subcategory="Adversarial coverage",
    severity="High",
    priority="P1",
    module="CI",
    feature="Wave 19 tests",
    files="backend/tests/test_wave19.py; docs/reviews/_wave19_assert_gates.py",
    problem="test_wave19.py covers SO/PO cess, GSTR-9 table 18 shape, AT rate/POS, statutory list, rls helper import. Assert gates check string presence (cessRate, typedClient, migration SQL). None boot Postgres RLS with non-superuser, none assert WO movement_type, none assert VIEWER 403 on pay-run, none assert GSTR split by CompanyGstin. Gates go green on a dangerous tree.",
    evidence="test_wave19.py contents; _wave19_assert_gates.py string checks.",
    root_cause="Semantic gate theater (BB-000548 class).",
    business="False CI confidence.",
    technical="Regressions will merge.",
    customer="P0s reach pilot.",
    security="ACL holes untested.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Wave 20 repeats.",
    fix_immediate="Add residual pytest markers required in CI for the P0s in this wave.",
    fix_short="Expand assert gates to runtime probes (docker postgres role).",
    fix_long="launch_suite job distinct from unit suite.",
    effort="3d",
    tests="New tests fail on current HEAD (expected until fixes).",
    acceptance="CI red on BB-000550–558 class defects.",
    refs="BB-000548 residual; Wave19 NEW",
)

# ── MEDIUM ──────────────────────────────────────────────────────────────────
add(
    title="Offline outbox line type omits cessRate, discounts, serials, and supply_type",
    category="GST",
    subcategory="POS offline",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="Outbox draft schema",
    files="web/src/offline/invoiceDraftCache.ts InvoiceDraftLine",
    problem="InvoiceDraftLine only has productId/name/sku/qty/unitPrice/gstRate. Wave 19 added cess to SO/PO/DC editors but outbox/POS draft schema cannot round-trip cess, batch/serial, or supply type. Flushing drafts yields incomplete GST invoices.",
    evidence="InvoiceDraftLine interface fields.",
    root_cause="Schema not evolved with billing model.",
    business="Offline POS under-taxes cess goods.",
    technical="Two invoice DTOs.",
    customer="Wrong bills after reconnect.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Cess/serial statutory fields dropped.",
    risk="Tobacco/automobiles POS path wrong.",
    fix_immediate="Extend draft schema + migration from v2; block flush if cess product missing rate.",
    fix_short="Share DraftLine type with NewInvoicePage.",
    fix_long="Canonical invoice draft protobuf/JSON schema versioned on server.",
    effort="1.5d",
    tests="Enqueue cess line → flush preserves cess_total.",
    acceptance="Outbox round-trip equals online invoice payload.",
    refs="BB-000039 residual; Wave19 NEW",
)
add(
    title="fetchAllPagesMasters still used for customers, products, suppliers, stock balances, chart of accounts",
    category="Performance",
    subcategory="Client pagination",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="List loaders",
    files="web/src/api/legacy/masters.ts; inventory.ts; company.ts; misc.ts",
    problem="Money lists were capped but master fetch-all remains. Invoice screens pull every customer/product. 5k SKU tenants will freeze the SPA. VirtualizedTable exists but data layer still materializes full arrays.",
    evidence="listCustomers/listProducts/listSuppliers/listWarehouses/listAccounts → fetchAllPagesMasters.",
    root_cause="Wave 15 banned money fetch-all only.",
    business="Unusable at modest MSME scale.",
    technical="Memory blow-ups; main-thread parse cost.",
    customer="Slow billing UX.",
    security="N/A",
    performance="High client cost.",
    scalability="Hard cap well below 10k businesses × large catalogs.",
    compliance="N/A",
    risk="First growing wholesaler churns.",
    fix_immediate="Server-side search endpoints already exist — use them; stop fetch-all on invoice pages.",
    fix_short="Async select components only.",
    fix_long="CQRS read models / typesense already partially there (search app).",
    effort="3d",
    tests="Invoice page network log has no unbounded /customers/ loop.",
    acceptance="No fetchAllPagesMasters on money or invoice-critical paths.",
    refs="BB-000117 residual; Wave19 NEW",
)
add(
    title="typedClient / openapi-types adopted only by manufacturing — sales/purchases still untyped legacy barrel",
    category="API",
    subcategory="Client typing",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="OpenAPI client",
    files="web/src/api/typedClient.ts; web/src/api/resources.ts; web/src/api/legacy/sales.ts; web/src/api/manufacturing.ts",
    problem="Wave 19 gate requires manufacturing to import typedClient and resources.ts to re-export legacy/sales. Core money APIs remain any/legacy. OpenAPI drift will not be caught where it matters.",
    evidence="resources.ts export * from './legacy/sales'; manufacturing.ts uses typedClient.",
    root_cause="Incremental typing stopped at the newest module.",
    business="FE/BE contract bugs in billing.",
    technical="Two client stacks.",
    customer="Subtle invoice field mismatches.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="openapi-types becomes stale theater.",
    fix_immediate="Migrate create invoice + complete to typedClient.",
    fix_short="Forbid new legacy endpoints; eslint on resources.ts.",
    fix_long="Delete legacy barrel.",
    effort="5d",
    tests="Typecheck fails if SalesInvoice create body drifts.",
    acceptance="Sales and purchase writes are typed.",
    refs="BB-000108/190 residual; Wave19 NEW",
)
add(
    title="PWA manifest has no service worker — offline outbox cannot run as an installed app offline",
    category="Mobile",
    subcategory="PWA",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="PWA",
    files="web/public/manifest.webmanifest; web/src (no SW)",
    problem="display:standalone without a service worker means installable chrome bookmark only. Network loss still depends on the tab staying open and IDB helpers; no background sync. Wave 18 closed BB-000179/180 as PWA+outbox complete.",
    evidence="manifest without sw.js; no navigator.serviceWorker in src.",
    root_cause="Manifest-only PWA.",
    business="POS 'offline' claim overstated.",
    technical="No asset cache / no sync event.",
    customer="Install app, go offline, white screen.",
    security="N/A",
    performance="Repeat full downloads.",
    scalability="N/A",
    compliance="N/A",
    risk="Field sales demo fails offline.",
    fix_immediate="Honesty in UI: drafts saved locally only while tab alive/online shell required.",
    fix_short="Workbox precache app shell + background sync for outbox flush.",
    fix_long="True offline-first replica.",
    effort="4d",
    tests="Airplane mode after install still loads shell; outbox flush on reconnect.",
    acceptance="Installed PWA loads offline shell or banner explains limitation.",
    refs="BB-000179 residual; Wave19 NEW",
)
add(
    title="ai_features_enabled is Owner-writable on CompanySerializer without budget/ops gate",
    category="AI",
    subcategory="Data exfiltration",
    severity="Medium",
    priority="P2",
    module="Accounts",
    feature="AI enablement",
    files="backend/accounts/serializers.py CompanySerializer fields ai_features_enabled",
    problem="Owner PATCH can enable AI and send invoices/parties to third-party LLMs. accounting_enabled was locked read-only for a reason; AI has similar irreversible data-sharing impact plus token cost.",
    evidence="ai_features_enabled in writable fields list; not in read_only_fields.",
    root_cause="Inconsistent enablement policy.",
    business="Unexpected LLM bills and data processing.",
    technical="No DPA acknowledgement step.",
    customer="PII leaves India/region without notice.",
    security="Medium-High privacy.",
    performance="Token burn.",
    scalability="Budget exhaustion.",
    compliance="DPDP consent/notice gap.",
    risk="Owner toggle in UI quietly starts OCR/assistant calls.",
    fix_immediate="Make ai_features_enabled read-only; gated settings + confirmation copy.",
    fix_short="Per-feature consent + region pin.",
    fix_long="Enterprise DPA workflow.",
    effort="1d",
    tests="PATCH ai_features_enabled ignored/400 without gated endpoint.",
    acceptance="AI cannot be enabled via generic company profile.",
    refs="BB-000215 analog; Wave19 NEW",
)
add(
    title="CRM MVP has no activities, no GSTIN-aware convert-to-customer, and Opportunity WON does not create a quotation",
    category="Business Logic",
    subcategory="CRM pipeline",
    severity="Medium",
    priority="P2",
    module="CRM",
    feature="Leads/opportunities",
    files="backend/crm/models.py; backend/crm/views.py; web/src/pages (crm pages)",
    problem="Lead/Opportunity are status/stage fields only. No activity log, assignment, SLA, or conversion transaction that creates masters.Customer with GSTIN validation. WON does not spawn quotation/sales order. Calling this CRM versus Zoho/ERPNext mis-sets expectations (competitor gap).",
    evidence="crm/models.py fields only; no services.py conversion.",
    root_cause="CRUD scaffold labeled CRM.",
    business="Sales process not supported.",
    technical="Dead-end records.",
    customer="Double entry into Customers.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Churn vs Zoho CRM bundle.",
    fix_immediate="Honesty banner 'lead notebook MVP'.",
    fix_short="Convert-to-customer atomic API + activity timeline.",
    fix_long="Real CRM or integrate.",
    effort="Honesty 0.25d; convert API 3d",
    tests="Convert lead → customer GSTIN validated; lead status QUALIFIED linked.",
    acceptance="WON/convert documented as out of scope or implemented.",
    refs="BB-000035 residual; Wave19 NEW",
)
add(
    title="BOM has no versioning, effective dates, or scrap/yield — WO always uses live BOM lines",
    category="Manufacturing",
    subcategory="BOM integrity",
    severity="Medium",
    priority="P2",
    module="Manufacturing",
    feature="BOM",
    files="backend/manufacturing/models.py Bom BomLine; backend/manufacturing/services.py",
    problem="Editing an ACTIVE BOM changes historical WO intent if lines are read at release time from live rows (they are). No snapshot of BOM lines on the work order. No scrap factor. Costing and traceability fail audits.",
    evidence="release_work_order iterates bom.lines live; WorkOrder only FKs bom+qty.",
    root_cause="No manufacturing document snapshot pattern (sales items snapshot GST/HSN but WO does not snapshot BOM).",
    business="Cannot explain what was consumed last month after BOM edit.",
    technical="Non-immutable production document.",
    customer="Shop-floor vs system fights.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Traceability gap.",
    risk="ISO/customer audits fail.",
    fix_immediate="Snapshot BOM lines onto WO at release; freeze ACTIVE BOM edits or clone version.",
    fix_short="BOM version + effective dating.",
    fix_long="ECO workflow.",
    effort="3d",
    tests="Edit BOM after release does not change completed WO consumption records.",
    acceptance="WO consumption is immutable after release.",
    refs="Wave19 NEW",
)
add(
    title="SPECTACULAR API description still denies modules that are installed and routed",
    category="API",
    subcategory="OpenAPI honesty",
    severity="Medium",
    priority="P2",
    module="Core",
    feature="OpenAPI",
    files="backend/config/settings.py SPECTACULAR_SETTINGS",
    problem="DESCRIPTION string: 'Not a full ERP — Manufacturing, Payroll, CRM, live NIC GSP, and WhatsApp Business are out of scope.' while INSTALLED_APPS includes manufacturing, payroll, crm, integrations WhatsApp. Integrators following OpenAPI will miss endpoints or call them despite the disclaimer.",
    evidence="settings.py SPECTACULAR_SETTINGS vs INSTALLED_APPS list.",
    root_cause="Description not updated in Wave 17.",
    business="Partner integration errors.",
    technical="Docs ≠ routes.",
    customer="Support load.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="External developers build on stale contract narrative.",
    fix_immediate="Rewrite DESCRIPTION with flag-gated modules + honesty.",
    fix_short="Generate description from feature flag catalog.",
    fix_long="Split public vs pilot OpenAPI artifacts.",
    effort="0.5d",
    tests="Schema description contains 'MVP flag-gated' not blanket out-of-scope for installed apps.",
    acceptance="OpenAPI matches routed apps.",
    refs="Wave19 docs honesty sibling; Wave19 NEW",
)
add(
    title="docker-compose.yml API container still runs migrate on every start",
    category="DevOps",
    subcategory="Migrations",
    severity="Medium",
    priority="P2",
    module="DevOps",
    feature="Compose",
    files="docker-compose.yml api.command; docker-compose.prod.yml migrate profile",
    problem="BB-000124 fixed prod overlay only. Default compose (used by many 'just run compose up' pilots) still sh -c migrate && gunicorn. Concurrent api replicas race migrations; failed mid-migrate bricks boot loops.",
    evidence="docker-compose.yml api command migrate && gunicorn.",
    root_cause="Dev convenience left as default.",
    business="Flaky first boot for non-prod overlay users who still take payments.",
    technical="Migration races.",
    customer="Downtime.",
    security="N/A",
    performance="Slow/re-migrating start.",
    scalability="Cannot scale api replicas on base file.",
    compliance="N/A",
    risk="Staging cloned from base compose hits race.",
    fix_immediate="Document that base file is dev-only; fail if DJANGO_ENV=production on base file.",
    fix_short="Remove migrate from api command in all files; one-shot profile only.",
    fix_long="Init job in k8s.",
    effort="0.5d",
    tests="Base compose with DJANGO_ENV=production refuses boot or omits migrate.",
    acceptance="No implicit migrate on api process in any committed compose used for staging/prod.",
    refs="BB-000124 residual; Wave19 NEW",
)
add(
    title="SalesInvoiceViewSet.create shadows imported idempotency helpers with a local cache_key string",
    category="Quality",
    subcategory="Dead code / shadowing",
    severity="Medium",
    priority="P2",
    module="Sales",
    feature="Idempotency",
    files="backend/sales/views.py SalesInvoiceViewSet.create",
    problem="Imports cache_key, get_cached_response, store_response from core.idempotency then assigns cache_key = f'sales_invoice_idempotency:...' and uses django cache.get/set. Divergent idempotency implementations vs the shared helper; easy to miss TTL/hashing rules applied elsewhere.",
    evidence="views.py imports vs local cache_key variable and cache.set.",
    root_cause="Partial refactor.",
    business="Inconsistent duplicate-submit protection across resources.",
    technical="Dead imports; two libraries.",
    customer="Occasional duplicate invoices if helpers diverge.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Future helper improvements skipped by sales create.",
    fix_immediate="Use core.idempotency helpers only; delete shadowing.",
    fix_short="One idempotency mixin on CompanyScopedViewSet writes.",
    fix_long="Idempotency-Key middleware.",
    effort="0.75d",
    tests="Shared helper unit tests cover sales create path.",
    acceptance="No local cache key formatting in viewsets.",
    refs="BB-000189 residual; Wave19 NEW",
)
add(
    title="Request logs hash user/company ids but still emit exact paths that may include document numbers/PII query strings",
    category="Security",
    subcategory="Logging",
    severity="Medium",
    priority="P2",
    module="Core",
    feature="JSON request logs",
    files="backend/core/middleware.py RequestIdMiddleware",
    problem="JSON logs include method, path, status. Search endpoints often carry ?q=customername or phone. Path logging without query redaction reintroduces PII into log drains (BB-000372 claimed hashed IDs only).",
    evidence="logger.info json dumps path=request.path — query string may be in META separately; DRF search uses query params not logged here, but some routes encode identifiers in path. Also missing query redaction if path includes query via full path usage later.",
    root_cause="Incomplete PII hygiene.",
    business="Log vendor DPA issues.",
    technical="Observability vs privacy tension.",
    customer="Names in support Loki/ELK.",
    security="Medium.",
    performance="N/A",
    scalability="N/A",
    compliance="DPDP minimization.",
    risk="Log export = PII export.",
    fix_immediate="Allowlist path templates; drop querystring; scrub UUIDs optionally keep.",
    fix_short="Structured route_name instead of raw path.",
    fix_long="Central telemetry pipeline with PII filters.",
    effort="1d",
    tests="Request with ?q=secret does not appear in caplog.",
    acceptance="No free-text query values in default request logs.",
    refs="BB-000372 residual; Wave19 NEW",
)
add(
    title="Hindi i18n catalog does not cover manufacturing/payroll/CRM/POS strings — mixed-language ERP UI",
    category="UX",
    subcategory="i18n",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="Locale",
    files="web/src/i18n/hi.ts; web/src/pages/manufacturing; payroll; crm; pos",
    problem="Wave 18 closed BB-000119 as Hindi expanded. New ERP/POS surfaces mostly English keys falling back. MSME Hindi users see broken chrome.",
    evidence="New pages use t() keys likely missing in hi.ts (verify fallback).",
    root_cause="i18n not in module Definition of Done.",
    business="Adoption friction in Hindi-first MSMEs.",
    technical="Key drift.",
    customer="Unprofessional UI.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Support burden.",
    fix_immediate="Add hi strings for all nav.erp + POS + payroll.",
    fix_short="i18n lint: fail CI on missing hi keys used in src.",
    fix_long="Regional packs.",
    effort="2d",
    tests="i18n CI diff empty for used keys.",
    acceptance="No English fallback on hi locale for shipped routes.",
    refs="BB-000119 residual; Wave19 NEW",
)
add(
    title="Manufacturing/payroll dialogs lack accessible labels and keyboard complete-flow (a11y regression on new pages)",
    category="UX",
    subcategory="Accessibility",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="ERP UI a11y",
    files="web/src/pages/manufacturing/BomsPage.tsx; WorkOrdersPage.tsx; web/src/pages/payroll/PayRunsPage.tsx",
    problem="New MUI dialogs/icon-only DeleteIcon buttons without aria-label patterns used elsewhere. Wave 15 added axe CI on some flows; ERP pages likely unscoped. Keyboard users cannot safely complete pay runs.",
    evidence="BomsPage IconButton DeleteIcon without visible name in first 50 lines; pay run complete is a destructive money action.",
    root_cause="New pages skipped a11y DoD.",
    business="WCAG failure for public SaaS.",
    technical="Axe CI blind spot.",
    customer="Inaccessible payroll.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Accessibility regs / enterprise procurement.",
    risk="Enterprise deals blocked.",
    fix_immediate="aria-labels; axe include ERP routes.",
    fix_short="Shared DialogForm primitive.",
    fix_long="Design system a11y kit.",
    effort="1.5d",
    tests="axe CI on /manufacturing/boms and /payroll/runs.",
    acceptance="No serious axe violations on ERP routes.",
    refs="Wave15 a11y residual; Wave19 NEW",
)
add(
    title="KNOWN_LIMITATIONS and Architecture review still describe pre-Wave-17 product — audit docs rotting",
    category="Documentation",
    subcategory="Audit maintainability",
    severity="Medium",
    priority="P2",
    module="Docs",
    feature="docs/reviews freshness",
    files="docs/reviews/KNOWN_LIMITATIONS_AND_TECH_DEBT.md; docs/reviews/02_ARCHITECTURE_REVIEW.md; docs/reviews/18_COMPETITOR_ANALYSIS.md",
    problem="Limitations table denies existence of modules now in INSTALLED_APPS. Architecture diagram omits manufacturing/payroll/crm/banking/rls middleware. Competitor analysis not updated for false parity claims. Audit corpus is internally inconsistent, reducing trust in the register itself.",
    evidence="KNOWN_LIMITATIONS lines 9-23 vs live apps.",
    root_cause="Append-only changelog without refreshing living docs.",
    business="Internal planning errors.",
    technical="Onboarding auditors read stale truth.",
    customer="N/A directly.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Next audit wave re-discovers 'missing manufacturing' as if absent.",
    fix_immediate="Rewrite limitations to current honest MVP matrix (this wave).",
    fix_short="Quarterly doc freeze checklist.",
    fix_long="Generated architecture crib from code.",
    effort="1d",
    tests="Manual review checklist in CHANGELOG.",
    acceptance="No doc claims 'not in codebase' for installed apps.",
    refs="Wave19 NEW",
)
add(
    title="Competitor gap: Zoho/TallyPrime/ERPNext manufacturing+payroll+GSTIN branching still vastly ahead — BizBoard MVPs create false parity",
    category="Competitor",
    subcategory="Positioning",
    severity="Medium",
    priority="P2",
    module="Product",
    feature="Market positioning",
    files="docs/reviews/18_COMPETITOR_ANALYSIS.md; backend/manufacturing; backend/payroll; backend/reporting/gst_returns.py",
    problem="Shipping CRUD BOMs and salary vouchers does not close competitor gaps. TallyPrime has robust multi-GSTIN invoicing; Zoho Books has filing-grade GST + payroll statutory; ERPNext has real BOM trees/workstations. Selling 'Cloud ERP with Manufacturing+Payroll+GST Portal' against them on current code is a positioning defect with refund/legal risk.",
    evidence="Module depth vs competitor feature lists; this wave P0s.",
    root_cause="Checkbox feature shipping.",
    business="Win deals you cannot retain.",
    technical="Support burden explosion.",
    customer="Migration regret.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Misrepresentation.",
    risk="Brand damage in CA community.",
    fix_immediate="Position as GST billing + inventory + optional books; ERP modules = preview.",
    fix_short="Public comparison page with honest 'preview' badges.",
    fix_long="Pick 1-2 ERP domains to actually finish before claiming ERP.",
    effort="1d product + multi-quarter eng",
    tests="Marketing site review against module matrix.",
    acceptance="No competitor-parity claim without CA-signed feature list.",
    refs="Wave19 NEW",
)
add(
    title="No load/perf evidence that FIFO layer select_for_update scales under concurrent WO+invoice load",
    category="Performance",
    subcategory="Inventory concurrency",
    severity="Medium",
    priority="P2",
    module="Inventory",
    feature="FIFO layers",
    files="backend/inventory/services.py _apply_cost_layers; load/README.md",
    problem="FIFO consume locks layers by id order per product+warehouse+batch. Manufacturing SALE issues + sales invoices will contend on the same rows. k6 smoke exists as docs-only MVP (BB-000129). No scenario includes WO release vs invoice complete race.",
    evidence="_apply_cost_layers select_for_update order_by id; load/README.md smoke only.",
    root_cause="FIFO shipped without load model.",
    business="Checkout + production stalls.",
    technical="Lock convoy on hot SKUs.",
    customer="Timeouts at month-end billing.",
    security="N/A",
    performance="Medium-High under contention.",
    scalability="Single hot product bottleneck.",
    compliance="N/A",
    risk="Pilot with FIFO+POS+mfg collapses.",
    fix_immediate="Honesty: FIFO experimental; default WAVG in prod flags.",
    fix_short="k6 scenario mixed WO+sales; index/hotspot review.",
    fix_long="Partition layers / queue stock issues.",
    effort="3d",
    tests="Load scenario p95 < SLO with 20 concurrent issuers on one SKU.",
    acceptance="Published FIFO load numbers or flag off in GA.",
    refs="BB-000129 residual; Wave19 NEW",
)
add(
    title="Cross-module: delivery challan stock, SO reservation, WO issues, and invoice COGS all share SALE movement type — analytics cannot disambiguate",
    category="Architecture",
    subcategory="Stock domain model",
    severity="Medium",
    priority="P2",
    module="Inventory",
    feature="Movement taxonomy",
    files="backend/inventory/models.py MovementType; backend/sales/services.py; backend/manufacturing/services.py",
    problem="SALE means customer sale, challan issue, note stock, and now WO issue. Reporting/insights that aggregate SALE are semantically undefined. Architecture lacks a bounded context for inventory reasons.",
    evidence="Multiple callers of MovementType.SALE across sales and manufacturing.",
    root_cause="Anemic enum growth.",
    business="Dashboards lie.",
    technical="Cannot write correct stock analytics.",
    customer="Mistrust KPIs.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Register 9 / stock records ambiguous.",
    risk="Insights module amplifies wrong SALE totals.",
    fix_immediate="Add reason/reference_type required taxonomy + report filters.",
    fix_short="Split enums.",
    fix_long="Inventory posting DTO with business_event.",
    effort="4d",
    tests="Insights sales qty excludes WO and challan-only issues.",
    acceptance="Each movement type maps to one business event class.",
    refs="Wave19 WO SALE sibling; Wave19 NEW",
)

# ── LOW ─────────────────────────────────────────────────────────────────────
add(
    title="JWT SIMPLE_JWT ACCESS_TOKEN_LIFETIME set twice (60m then overwritten to env 15m) — comment drift",
    category="Maintainability",
    subcategory="Settings clarity",
    severity="Low",
    priority="P3",
    module="Config",
    feature="JWT TTL",
    files="backend/config/settings.py SIMPLE_JWT",
    problem="Initial SIMPLE_JWT dict sets 60 minutes; later overwritten from JWT_ACCESS_MINUTES default 15. Comments still mention both. Operators misread session length.",
    evidence="settings.py SIMPLE_JWT block vs later SIMPLE_JWT['ACCESS_TOKEN_LIFETIME']=timedelta(minutes=int(...15)).",
    root_cause="Layered settings edits.",
    business="Support confusion on session expiry.",
    technical="Dead initial value.",
    customer="Unexpected logouts vs docs.",
    security="Low — actual value is 15m which is safer.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Docs say 60m, product is 15m.",
    fix_immediate="Single assignment; delete the 60m default.",
    fix_short="Document TTL in ONBOARDING.",
    fix_long="Config service.",
    effort="0.2d",
    tests="N/A",
    acceptance="One source of truth for access TTL.",
    refs="Wave19 NEW",
)
add(
    title="Payroll/CRM/Manufacturing apps lack admin.py registration and verbose help_text on money fields",
    category="Maintainability",
    subcategory="Django admin / ops",
    severity="Low",
    priority="P3",
    module="Backend",
    feature="Admin",
    files="backend/payroll; backend/crm; backend/manufacturing",
    problem="Ops debugging via Django admin (when ADMIN_ENABLED) cannot see ERP models. No admin, no simple history. Increases production support time.",
    evidence="No admin.py under those apps (glob).",
    root_cause="MVP without ops affordances.",
    business="Slower incident response.",
    technical="Invisible tables in admin.",
    customer="Longer tickets.",
    security="N/A (admin still Owner/superuser gated).",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Support uses SQL against RLS-unaware superuser.",
    fix_immediate="Read-only admin ModelAdmins with company list filter.",
    fix_short="Audit log link.",
    fix_long="Support console distinct from django admin.",
    effort="0.75d",
    tests="Admin smoke when ADMIN_ENABLED.",
    acceptance="Support can view ERP rows without raw SQL.",
    refs="Wave19 NEW",
)
add(
    title="GSTR SUPECOM section remains unsupported without UI warning on e-commerce operator invoices",
    category="GST",
    subcategory="E-commerce",
    severity="Low",
    priority="P3",
    module="Reporting",
    feature="GSTR-1 SUPECOM",
    files="backend/reporting/gst_returns.py supecom aid_kind unsupported",
    problem="Section exists as unsupported honesty blob. If users sell via Amazon/Flipkart and still raise tax invoices in BizBoard, those supplies silently sit in B2B/B2CS without TCS/operator GSTIN. Low only because e-comm flag may be rare in current ICP — still a compliance trap.",
    evidence="aid_kind unsupported SUPECOM note.",
    root_cause="Out of MVP without sales-side guardrail.",
    business="Marketplace sellers misfile.",
    technical="Missing party role.",
    customer="TCS mismatch.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="GSTR-1 table 14/15 etc.",
    risk="Silent misclassification.",
    fix_immediate="Invoice-level ecommerce operator field; if set, exclude from B2B and show SUPECOM incomplete banner.",
    fix_short="SUPECOM worksheet.",
    fix_long="Full e-comm GST.",
    effort="3d",
    tests="Operator GSTIN set → not in b2b array.",
    acceptance="E-comm invoices cannot silently look like normal B2B.",
    refs="BB-000090 residual; Wave19 NEW",
)
add(
    title="Feature flag mock defaults in web featureFlags.ts force all advanced modules off — e2e cannot exercise ERP without custom stubs",
    category="Testing",
    subcategory="FE mocks",
    severity="Low",
    priority="P3",
    module="Web",
    feature="VITE_USE_MOCKS flags",
    files="web/src/config/featureFlags.ts MOCK_FLAGS",
    problem="MOCK_FLAGS disables manufacturing/payroll/crm/pos/accounting/ai. Mock-mode e2e (if any) never covers new routes. Low severity because prod mocks are banned.",
    evidence="MOCK_FLAGS all false.",
    root_cause="Conservative mock defaults.",
    business="N/A",
    technical="Coverage hole in mock storybook/e2e.",
    customer="N/A",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Regressions in ERP UI only caught manually.",
    fix_immediate="Optional mock flag overrides for e2e.",
    fix_short="Golden e2e with real API covering WO+payrun happy path.",
    fix_long="Contract tests.",
    effort="1d",
    tests="e2e-golden optional ERP spec behind env.",
    acceptance="At least one CI path renders ERP pages.",
    refs="Wave19 NEW",
)
add(
    title="No ADRs recorded for RLS design, manufacturing movement types, or multi-GSTIN filing identity",
    category="Architecture",
    subcategory="ADR gap",
    severity="Low",
    priority="P3",
    module="Docs",
    feature="ADRs",
    files="docs/reviews/ARCHITECTURAL_DECISIONS.md",
    problem="Major Wave 16–19 designs landed without ADRs. Future refactors will relitigate SET LOCAL vs SESSION, SALE-vs-issue types, and GSTIN-as-org-unit.",
    evidence="ARCHITECTURAL_DECISIONS.md stops at earlier ADRs; no RLS/mfg/GSTIN entries.",
    root_cause="Delivery velocity over design capture.",
    business="Rework cost.",
    technical="Tribal knowledge.",
    customer="N/A",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Oscillating implementations.",
    fix_immediate="Add ADR-A19 RLS, A20 stock event types, A21 filing GSTIN.",
    fix_short="ADR required in PR template for cross-module changes.",
    fix_long="Architecture guild.",
    effort="0.75d",
    tests="N/A",
    acceptance="ADRs exist and are linked from register issues.",
    refs="Wave19 NEW",
)
