# -*- coding: utf-8 -*-
"""Wave 19 missed-findings (subagent residual pass) — BB-000599+."""

ISSUES: list[dict] = []


def add(**kwargs):
    ISSUES.append(kwargs)


add(
    title="Sales GL tax drift check reads nonexistent cgst_amount — GST Complete fails when accounting_enabled",
    category="Accounting",
    subcategory="GL posting",
    severity="Critical",
    priority="P0",
    module="Accounting",
    feature="post_sales_invoice",
    files="backend/accounting/services.py PostingService.post_sales_invoice; backend/core/models.py DocumentLineModel",
    problem="Guard sums getattr(li, 'cgst_amount'|'sgst_amount'|'igst_amount', 0). Line fields are cgst/sgst/igst. Sum is always 0. Any GST invoice with header tax > ₹0.05 raises BusinessRuleError and aborts Complete inside the posting transaction. Enabling books breaks GST sales.",
    evidence="accounting/services.py L203-223 getattr cgst_amount; DocumentLineModel fields cgst/sgst/igst/cess.",
    root_cause="BB-000448 guard used wrong attribute names; no integration test with real SalesItem rows + accounting_enabled.",
    business="Cannot run books and billing together.",
    technical="Complete rolls back; AR/output tax never post.",
    customer="Pilot with accounting_enabled cannot issue GST invoices.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Output tax never in GL.",
    risk="First accounting_enabled customer cannot bill.",
    fix_immediate="Read li.cgst/sgst/igst/cess; add complete+books test.",
    fix_short="Shared tax-total helper for billing/GL/GSTR/e-invoice.",
    fix_long="Single money DTO.",
    effort="0.5d",
    tests="GST invoice complete with accounting_enabled posts balanced journal.",
    acceptance="No false header/line tax mismatch on valid invoices.",
    refs="Wave19 missed; GST/accounting audit",
)
add(
    title="Cess is computed on documents and GSTR but never posted to GL (inflates sales / disappears on purchases)",
    category="Accounting",
    subcategory="Cess GL",
    severity="Critical",
    priority="P0",
    module="Accounting",
    feature="Cess posting",
    files="backend/accounting/services.py post_sales_invoice post_purchase; CoA CHART; backend/sales/einvoice_payload.py ItemList",
    problem="cess_total is in grand_total. GL tax legs are CGST/SGST/IGST only. Sales Cr 4100 = grand - cgst - sgst - igst - round_off so cess inflates revenue. Purchases Input GST excludes cess while AP includes it. E-invoice header CesVal exists but ItemList has no CesRt/CesAmt. No Output/Input Cess accounts.",
    evidence="post_sales_invoice tax=sum(cgst,sgst,igst) only; einvoice_payload ItemList lacks CesAmt.",
    root_cause="Wave 18 cess on documents without CoA/posting/IRP lines.",
    business="Wrong P&L and GST payable; IRP reject on cess goods.",
    technical="Books ≠ GSTR ≠ e-invoice.",
    customer="Pan masala/tobacco/auto cess dealers unusable.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Compensation cess not in books.",
    risk="Any cess_rate>0 corrupts books.",
    fix_immediate="Add 2270/1370 cess accounts; post cess; IRP line CesAmt.",
    fix_short="RCM cess + inclusive extract (sibling issues).",
    fix_long="Qty-based cess schedules.",
    effort="3d",
    tests="Invoice cess_rate=12 → 2270 credited, 4100 excludes cess.",
    acceptance="Cess never in sales revenue.",
    refs="BB-000039 residual; Wave19 missed",
)
add(
    title="FIFO layers destroyed on cancel (ADJUSTMENT); transfer IN layers at ₹0; COGS GL uses pre-peel WAVG",
    category="Inventory",
    subcategory="FIFO correctness",
    severity="Critical",
    priority="P0",
    module="Inventory",
    feature="Cost layers",
    files="backend/inventory/services.py _apply_cost_layers; backend/sales/services.py cancel; backend/sales/cogs_service.py; StockTransferService.complete",
    problem="Cancel posts ADJUSTMENT +qty which does not recreate layers; outbound ADJUSTMENT consumes layers. Transfer IN creates layer with unit_cost=None→0. CogsService computes unit_cost via InventoryValuationService (blended remaining) BEFORE post_movement peels FIFO and stamps movement.unit_cost. Wave 16 'FIFO drives COGS' is false.",
    evidence="cancel uses MovementType.ADJUSTMENT; layer create list excludes ADJUSTMENT inbound; cogs_service unit_cost before post_movement.",
    root_cause="FIFO bolted onto movement types that cancel paths still treat as adjustments.",
    business="Wrong COGS; blocked resell (insufficient layers); zero-cost transfers.",
    technical="Layer ledger diverges from qty.",
    customer="FIFO company cannot cancel/resell.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Inventory valuation false.",
    risk="Enabling FIFO in prod corrupts COGS after first cancel.",
    fix_immediate="Cancel via typed reverse movements that restore layers; pass OUT cost into TRANSFER_IN; COGS from stamped movement after peel.",
    fix_short="Layer consumption audit table.",
    fix_long="Inventory event store.",
    effort="5d",
    tests="Buy@10,@20 sell1 cancel sell1 — layers consistent; transfer preserves cost; COGS equals peeled layers.",
    acceptance="Cancel/transfer/COGS preserve FIFO identity.",
    refs="BB-000465 residual; Wave19 missed",
)
add(
    title="Production cookie-JWT is incompatible with SPA — no CSRF cookie/header and login nulls access token",
    category="Security",
    subcategory="Cookie JWT + CSRF",
    severity="Critical",
    priority="P0",
    module="Accounts",
    feature="Auth",
    files="backend/core/authentication.py CookieJWTAuthentication; backend/accounts/views.py _access_in_json_body_allowed LoginView; web/src/api/auth.ts tokensFromBody; web/src (no X-CSRFToken)",
    problem="DEBUG=0 nulls JSON access. SPA tokensFromBody throws if !body.access. Cookie path calls SessionAuthentication.enforce_csrf but no view calls ensure_csrf_cookie and SPA never sends X-CSRFToken (zero matches in web/src). DRF views are CSRF-exempt so csrftoken is never set. Tests hide this (APIClient CSRF off; CI DEBUG=1).",
    evidence="auth.ts L20-23 throw; authentication.py L25-26 enforce_csrf; grep X-CSRFToken empty.",
    root_cause="Cookie+CSRF added on API without SPA bootstrap; dual-stack leftover.",
    business="Production SPA cannot login or mutate.",
    technical="Unshippable cookie-only mode.",
    customer="Hard down after DJANGO_DEBUG=0.",
    security="Ops will disable CSRF or put JWT back in JS.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Launch-day auth outage or insecure hotfix.",
    fix_immediate="CSRF cookie on GET /auth/csrf/; SPA sends X-CSRFToken; treat access:null + Set-Cookie as login success.",
    fix_short="Golden e2e with DJANGO_DEBUG=0.",
    fix_long="Single auth mode (BFF session XOR Bearer).",
    effort="3d",
    tests="Playwright production-settings login+create invoice with cookies+CSRF.",
    acceptance="DEBUG=0 SPA works; mutating cookie request without CSRF is 403.",
    refs="BB-000417/471 residual; Wave19 missed; auth audit",
)
add(
    title="CookieJWTAuthentication still accepts Authorization Bearer in production and skips CSRF",
    category="Security",
    subcategory="JWT dual stack",
    severity="High",
    priority="P0",
    module="Accounts",
    feature="Bearer",
    files="backend/core/authentication.py; backend/config/settings.py DEFAULT_AUTHENTICATION_CLASSES",
    problem="Settings remove JWTAuthentication class in prod but CookieJWTAuthentication.authenticate() prefers Authorization header and returns without CSRF. Stolen/leaked access JWT works as Bearer for up to JWT_ACCESS_MINUTES.",
    evidence="authentication.py L17-19 if header: return super().authenticate; settings comment claims Bearer disabled.",
    root_cause="Incomplete dual-stack removal (BB-000547).",
    business="CSRF controls bypassed.",
    technical="Comment lies.",
    customer="XSS/log leak becomes full API access.",
    security="High.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="False hardening.",
    fix_immediate="Reject Authorization when DJANGO_ENV in production/staging.",
    fix_short="Blacklist access JTI on logout.",
    fix_long="One authenticator.",
    effort="0.5d",
    tests="Prod settings Bearer → 401; cookie+CSRF → 200.",
    acceptance="No Bearer in production.",
    refs="BB-000547 residual; Wave19 missed",
)
add(
    title="PostgresRlsMiddleware runs before DRF JWT auth — GUC never set even if SET SESSION were used",
    category="Security",
    subcategory="RLS request lifecycle",
    severity="Critical",
    priority="P0",
    module="Core",
    feature="RLS middleware order",
    files="backend/config/settings.py MIDDLEWARE; backend/core/middleware.py PostgresRlsMiddleware",
    problem="Middleware stack runs PostgresRlsMiddleware after Django AuthenticationMiddleware (session only). Cookie/JWT auth happens in the view. Middleware almost always sees AnonymousUser → company_id None → set_rls_company no-op. Distinct from SET LOCAL autocommit bug (BB-000551): fixing SET SESSION alone still fails.",
    evidence="MIDDLEWARE order; DRF auth in view; middleware get_company_user on anonymous request.",
    root_cause="RLS hooked at wrong lifecycle point.",
    business="RLS cannot work in DRF.",
    technical="Wrong layer.",
    customer="False isolation.",
    security="Critical with 551/552.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Enable RLS → empty datasets or superuser bypass only.",
    fix_immediate="Set GUC after DRF authentication inside atomic() (view mixin / authentication hook), not middleware.",
    fix_short="ATOMIC_REQUESTS or per-request atomic wrapper.",
    fix_long="DB role + connection checkout hook with known company from trusted gateway.",
    effort="2d",
    tests="Inside view, current_setting('app.company_id') equals tenant.",
    acceptance="GUC set for authenticated DRF requests.",
    refs="BB-000551 sibling; Wave19 missed; auth audit",
)
add(
    title="nginx CSP style-src/font-src 'self' only — MUI Emotion + Google Fonts blocked in Docker edge",
    category="DevOps",
    subcategory="CSP",
    severity="Critical",
    priority="P0",
    module="DevOps",
    feature="CSP",
    files="nginx/default.conf; web/index.html; web/nginx.conf",
    problem="CSP: style-src 'self'; font-src 'self' data:; script-src 'self'; no nonce. MUI/Emotion injects runtime styles. index.html loads fonts.googleapis.com / fonts.gstatic.com. Docker deploy ships unstyled/broken UI. Prior CSP tightening made the app worse.",
    evidence="nginx/default.conf CSP header; index.html Google Fonts links.",
    root_cause="Security checkbox without Emotion nonce or self-hosted fonts.",
    business="Pilot UI unusable behind nginx.",
    technical="CSP vs framework mismatch.",
    customer="Blank/unstyled screens.",
    security="N/A (over-strict).",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Support storm on first compose prod overlay.",
    fix_immediate="Nonce/hash for Emotion OR self-host DM Sans + extract MUI CSS at build; allow font origins or remove GF.",
    fix_short="Playwright CSP violation listener in compose e2e.",
    fix_long="Strict CSP with build-time nonces.",
    effort="2-3d",
    tests="Headed Chromium against nginx: zero CSP violations; MUI styled.",
    acceptance="Compose UI matches vite preview visually.",
    refs="BB-000464 residual; Wave19 missed; FE audit",
)
add(
    title="AA ingest writes mock FIU transactions when payload empty or use_mock_fiu — matches them to real receipts",
    category="Accounting",
    subcategory="Banking AA",
    severity="Critical",
    priority="P0",
    module="Banking",
    feature="AA ingest",
    files="backend/banking/views.py AaIngestView; backend/banking/fiu_adapter.py; backend/banking/services.py match_aa_to_receipts",
    problem="POST /banking/aa/ingest/: if use_mock_fiu OR transactions empty, deterministic fake UPI/NEFT rows are persisted then match_aa_to_receipts runs (amount-only, BB-000570). Any Owner in any env can inject fake bank money onto real AR.",
    evidence="views.py L40-52 if use_mock_fiu or not rows: fetch mock; then match_aa_to_receipts.",
    root_cause="Dev convenience left on production path.",
    business="Corrupt bank recon and AR.",
    technical="Fake FIU in prod API.",
    customer="Phantom receipts matched.",
    security="Fraud/test-data pollution.",
    performance="N/A",
    scalability="N/A",
    compliance="Books integrity.",
    risk="AA-enabled pilot instantly dirty.",
    fix_immediate="Mock only DJANGO_ENV in (development,test) AND explicit flag; empty rows → 400.",
    fix_short="Separate sandbox tenant.",
    fix_long="Real FIU adapter only.",
    effort="0.5d",
    tests="Prod settings ingest without rows → 400; no AaTransaction created.",
    acceptance="No mock FIU outside test/dev.",
    refs="BB-000570 sibling; Wave19 missed; FE/devops audit",
)
add(
    title="Company.is_gst_registered lives on CompanyGstin (wrong class) — purchase GST gates AttributeError; __str__ uses missing name",
    category="GST",
    subcategory="Registration model",
    severity="Critical",
    priority="P0",
    module="Accounts",
    feature="is_gst_registered",
    files="backend/accounts/models.py CompanyGstin; backend/purchases/notes_services.py; backend/purchases/services.py complete_return; backend/accounts/serializers.py CompanySerializer",
    problem="Property is_gst_registered and broken __str__ (self.name, self.registration_type) are on CompanyGstin which has neither. Company no longer has the property. Purchase CN/DN/return complete call company.is_gst_registered → AttributeError. Serializer read-only field silently omits missing attr → FE thinks unregistered.",
    evidence="accounts/models.py L178-183 on CompanyGstin; Company class ends earlier without property.",
    root_cause="Bad cut-paste during Wave 16D multi-GSTIN.",
    business="Purchase notes/returns crash for GST dealers when path hit; UI registration flag wrong.",
    technical="Runtime AttributeError / silent serializer skip.",
    customer="Cannot complete purchase adjustments.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="GST gates dead.",
    risk="Any purchase CN after Wave 16D is a landmine.",
    fix_immediate="Restore property on Company; CompanyGstin.__str__ → gstin/legal_name; delete bogus property.",
    fix_short="Unit tests for both models.",
    fix_long="Registration policy object.",
    effort="0.5d",
    tests="company.is_gst_registered True for REGULAR+GSTIN; purchase CN complete works; Gstin.__str__ no error.",
    acceptance="Property on Company only; no AttributeError.",
    refs="Wave19 missed; GST audit",
)
add(
    title="SOFT_CLOSED GST periods do not block money docs — period_complete_warning is never called",
    category="GST",
    subcategory="Period close",
    severity="High",
    priority="P0",
    module="Reporting",
    feature="GST periods",
    files="backend/reporting/gst_periods.py period_complete_warning assert_period_allows_money_amend; sales/purchases complete paths",
    problem="assert_period_allows_money_amend hard-blocks CLOSED only. period_complete_warning is defined and never invoked (definition-only grep). Tests still expect hard block on SOFT_CLOSED complete. Soft-close is a status flag + health warning at best; new invoices/notes/journals proceed.",
    evidence="gst_periods.py L53-83; warning unused; tests test_*_soft_closed_period disagree with code.",
    root_cause="BB-000396 'warn on complete' never wired.",
    business="Filed months remain mutable.",
    technical="Tests vs code split-brain.",
    customer="GSTR after 'close' still changes.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Period immutability false.",
    risk="CA signs closed books that still move.",
    fix_immediate="Call warning on Complete and/or hard-block SOFT_CLOSED money mutate; align tests.",
    fix_short="Reopen workflow with reason.",
    fix_long="Snapshot diff on reopen.",
    effort="1.5d",
    tests="Soft-close → complete returns warning header or 400 per chosen product rule; tests match code.",
    acceptance="SOFT_CLOSED is either warn-wired or hard-blocked — not a no-op.",
    refs="BB-000396 residual; Wave19 missed",
)
add(
    title="Journal reverse drops customer/supplier FKs — GL control nets to 0 while party AR/AP and credit limit remain",
    category="Accounting",
    subcategory="Dual ledger",
    severity="High",
    priority="P0",
    module="Accounting",
    feature="Journal reverse",
    files="backend/accounting/services.py PostingService.reverse; ledgers customer_outstanding",
    problem="reverse() copies account/debit/credit/cost_center/dimension only — not customer/supplier. Cancel invoice reverses 1200 untagged. Control 1200 nets 0; party-tagged outstanding and credit-limit exposure stay. Receipt allocation journals use localdate not doc date.",
    evidence="services.py L592-593 lines dict without customer/supplier.",
    root_cause="Reverse helper incomplete vs tagged posting.",
    business="Customer statements and credit limits wrong after cancel.",
    technical="GL-first AR broken.",
    customer="Cancelled invoice still 'due' on party ledger.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Books not true and fair.",
    risk="accounting_enabled + cancel corrupts AR control vs party.",
    fix_immediate="Copy party FKs on reverse; allocation entry_date = source date.",
    fix_short="BooksHealth recon Σ party-tagged 1200 vs control.",
    fix_long="Event-sourced AR.",
    effort="1.5d",
    tests="Complete+cancel GST invoice → customer_outstanding 0 and 1200 tagged+control 0.",
    acceptance="Reverse preserves party tags.",
    refs="BB-000016 residual; Wave19 missed",
)
add(
    title="Idempotency-Key is cache-only — concurrent POSTs duplicate invoices/receipts (TOCTOU)",
    category="API",
    subcategory="Idempotency",
    severity="High",
    priority="P0",
    module="Sales",
    feature="Idempotency-Key",
    files="backend/core/idempotency.py; backend/sales/views.py create; purchases/views.py; payments/views.py; web offline outbox",
    problem="24h cache lookup with no unique DB constraint. Two parallel requests with same key both miss cache → duplicate documents. Offline outbox depends on this. Distinct from import shadowing (BB-000586).",
    evidence="cache.get/set pattern; no IdempotencyRecord model.",
    root_cause="Redis memo instead of durable uniqueness.",
    business="Duplicate tax invoices / double receipts.",
    technical="TOCTOU.",
    customer="POS double-tap / flaky network duplicates GST invoices.",
    security="N/A",
    performance="N/A",
    scalability="Multi-replica worsens race.",
    compliance="Duplicate invoice serials.",
    risk="Production POS outbox flush storms.",
    fix_immediate="Table unique (company, key) + select_for_update insert.",
    fix_short="Shared mixin all money creates.",
    fix_long="Idempotency middleware.",
    effort="2d",
    tests="Parallel double-post same key → one row.",
    acceptance="No duplicate on concurrent idempotent create.",
    refs="BB-000189/586 residual; Wave19 missed; FE audit",
)
add(
    title="Inclusive price extraction ignores cess — taxable base and cess both wrong",
    category="GST",
    subcategory="Inclusive pricing",
    severity="High",
    priority="P0",
    module="Core",
    feature="billing extract",
    files="backend/core/services/billing.py extract_exclusive_from_inclusive_line apply_inclusive_prices_to_items",
    problem="Denominator is GST rate only. Inclusive MRP embedding GST+cess is under-extracted; cess then applied again on that taxable. No tests with cess_rate on inclusive lines.",
    evidence="billing.py L204-208 taxable = net * 100/(100+rate) without cess.",
    root_cause="Inclusive math predates cess.",
    business="Wrong invoice value/GSTR/ITC.",
    technical="Identity broken for cess goods.",
    customer="Over/under tax on MRP-inclusive SKUs.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Incorrect tax base.",
    risk="Any inclusive+cess product.",
    fix_immediate="Extract with (100+gst+cess); tests.",
    fix_short="Shared inclusive helper with e-invoice.",
    fix_long="Price-mode policy object.",
    effort="1d",
    tests="Inclusive 140 @28%+12% cess matches 140×100/140 identity.",
    acceptance="Inclusive+cess round-trips.",
    refs="Wave19 missed; GST audit",
)
add(
    title="Runtime feature flags fetched once at boot (usually 401) and never after login",
    category="Frontend",
    subcategory="Feature flags",
    severity="High",
    priority="P0",
    module="Web",
    feature="featureFlags",
    files="web/src/main.tsx; web/src/config/featureFlags.ts; backend/core/views.py FeatureFlagsView; AuthContext",
    problem="fetchFeatureFlags() only in main.tsx before auth. Endpoint requires IsAuthenticated+HasCompany. Cache stays false until full reload with cookies. ENABLE_POS/ERP runtime flags ignored in-session. Dual Vite vs runtime system lies.",
    evidence="main.tsx import fetchFeatureFlags; AuthContext does not refetch; FeatureFlagsView auth-gated.",
    root_cause="Boot-time anonymous fetch.",
    business="Paid flags don't appear after login.",
    technical="Stale cache.",
    customer="POS/ERP missing until hard refresh.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Support 'flag not working'.",
    fix_immediate="Refetch after /auth/me; clear on logout/company switch.",
    fix_short="React Query key companyId.",
    fix_long="Push flags in /me payload.",
    effort="0.5d",
    tests="Login with ENABLE_POS=1 shows /pos without reload.",
    acceptance="Flags after auth match API.",
    refs="BB-000563 sibling; Wave19 missed; FE audit",
)
add(
    title="fetchMoneyListFirstPage silently returns page 1 only — UIs present incomplete books as complete",
    category="Frontend",
    subcategory="Pagination correctness",
    severity="High",
    priority="P0",
    module="Web",
    feature="Money lists",
    files="web/src/api/legacy/common.ts fetchMoneyListFirstPage; legacy/sales.ts purchases.ts payments.ts misc.ts",
    problem="listSalesInvoices/quotations/receipts/journals/payment-links via first-page helper drop count/truncated. Editors using array helpers undercount AR/AP documents (e.g. CN source invoice picker).",
    evidence="common.ts L119-125 return page.results only.",
    root_cause="Stop-fetch-all without forcing paged UI.",
    business="Wrong document selection; missed invoices.",
    technical="Silent truncation.",
    customer="CN against 'missing' invoice on page 2.",
    security="N/A",
    performance="N/A",
    scalability="Breaks >PAGE_SIZE.",
    compliance="Incomplete registers in UI.",
    risk="Any tenant with >50 docs.",
    fix_immediate="Return {results,count,truncated}; migrate callers to *Page.",
    fix_short="Delete array money helpers.",
    fix_long="Typed paged client only.",
    effort="2d",
    tests="61 invoices → UI shows count 61 not 50.",
    acceptance="No money array helper without truncation signal.",
    refs="BB-000578 sibling; Wave19 missed; FE audit",
)
add(
    title="GSTR-3B ITC defaults CLAIMABLE and is not enforced — CN/2B heuristics over-claim",
    category="GST",
    subcategory="ITC",
    severity="High",
    priority="P0",
    module="Reporting",
    feature="GSTR-3B ITC",
    files="backend/purchases/models.py itc_eligibility; backend/reporting/gst_returns.py build_gstr3b; gstr2b.py",
    problem="itc_eligibility default CLAIMABLE. No Sec 17(5)/R36/37 engine. Purchase CN/DN always net into ITC ignoring original eligibility. claimable_itc_from_2b ignores purchase flag. has_2b inferred from tax sum not row presence. Cess ITC absent. RCM ITC not 2B-gated like non-RCM.",
    evidence="PurchaseInvoice.itc_eligibility default; build_gstr3b CN net 674-683 area (audit).",
    root_cause="Flags labeled as enforcement.",
    business="Over-claimed ITC → notices.",
    technical="Provisional presented as claimable.",
    customer="3B aid unsafe to file from.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="ITC rules not implemented.",
    risk="BB-000009 'resolved' was labeling only.",
    fix_immediate="Default UNREVIEWED; never claim without explicit flag AND 2B match; net notes with same eligibility.",
    fix_short="Sec 17(5) blockers on ineligible HSN.",
    fix_long="Full ITC engine.",
    effort="5d",
    tests="Default purchase not in 3B ITC; INELIGIBLE stays out after 2B match.",
    acceptance="No automatic CLAIMABLE ITC.",
    refs="BB-000009 residual; Wave19 missed",
)
add(
    title="Serial/lot state machine asymmetric on cancel/return — ghost serials and unsellable RETURNED units",
    category="Inventory",
    subcategory="Serials",
    severity="High",
    priority="P1",
    module="Inventory",
    feature="Serial cancel",
    files="backend/sales/services.py cancel; backend/sales/return_service.py; backend/purchases/services.py",
    problem="Sales cancel restores serials only if invoice posted SALE; challan-stocked cancel adjusts qty without serial restore. Sales return cancel leaves serials RETURNED forever. Purchase cancel does not retire received serials. Purchase return has no serial handling. FEFO may persist only allocations[0].",
    evidence="cancel ADJUSTMENT paths; SerialNumber.Status.RETURNED not reverted on return cancel.",
    root_cause="Serial transitions not paired with stock reverses.",
    business="Unsellable stock; ghost available serials.",
    technical="Qty vs serial mismatch.",
    customer="Cannot resell returned serial.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Traceability broken.",
    risk="Serialized MSME inventory unusable after returns.",
    fix_immediate="Symmetric serial SM on every cancel; persist full FEFO allocations.",
    fix_short="Invariant tests qty==serial counts.",
    fix_long="Identity ledger.",
    effort="3d",
    tests="Sale→return→cancel return → serial AVAILABLE and sellable.",
    acceptance="No orphan serial statuses vs qty.",
    refs="Wave19 missed; GST/inventory audit",
)
add(
    title="Invite tokens are cache-only single-use and reset passwords without revoking sessions",
    category="Security",
    subcategory="Invitations",
    severity="High",
    priority="P1",
    module="Accounts",
    feature="Accept invite",
    files="backend/accounts/views.py AcceptInviteView _make_invite_token",
    problem="Consumed jti stored in cache only — flush/restart allows replay. Invite works as 7-day password reset without checking usable password. Unlike ChangePasswordView, refresh tokens not blacklisted. invite_token returned in API JSON.",
    evidence="cache.get/set invite_jti; set_password without blacklist.",
    root_cause="Cache memo as security control.",
    business="Account takeover + concurrent victim session.",
    technical="Non-durable single-use.",
    customer="Stolen invite email after accept still works post-redis-flush.",
    security="High.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Invite = standing password-reset token.",
    fix_immediate="Persist jti on CompanyUser; reject if password usable; blacklist refresh; email-only token.",
    fix_short="Audit invite accept.",
    fix_long="Dedicated reset vs invite flows.",
    effort="1.5d",
    tests="Replay after cache.clear fails; sessions revoked.",
    acceptance="Durable single-use; no leftover sessions.",
    refs="Wave19 missed; auth audit",
)
add(
    title="Login with no active membership returns refresh+access in JSON body even in production",
    category="Security",
    subcategory="Token leakage",
    severity="High",
    priority="P1",
    module="Accounts",
    feature="Login",
    files="backend/accounts/views.py LoginView.post",
    problem="Cookie rewrite only if membership. Deactivated-only users / superusers without CompanyUser get TokenObtainPairView body with both tokens. Breaks cookie-only and non-enumeration.",
    evidence="if membership: strip access; else fall through with full body.",
    root_cause="Membership gate after token mint.",
    business="XSS-readable refresh for edge accounts.",
    technical="Inconsistent login shape.",
    customer="Disabled staff still get tokens.",
    security="High.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Orphan users are a token oracle.",
    fix_immediate="Never return tokens without membership (403); always strip refresh from JSON.",
    fix_short="Same response shape always.",
    fix_long="Session only after tenant bind.",
    effort="0.5d",
    tests="No-membership login: no tokens in body.",
    acceptance="Tokens only after active membership.",
    refs="Wave19 missed; auth audit",
)
add(
    title="StockMovement, low-stock, warehouse retrieve, and AA lists are HasCompany-only — VIEWER reads stock costs and bank AA",
    category="Security",
    subcategory="RBAC reads",
    severity="High",
    priority="P1",
    module="Inventory",
    feature="Read ACL",
    files="backend/inventory/views.py StockMovementViewSet LowStockAlertsView; backend/banking/views.py AaListView",
    problem="StockBalance uses CanViewInventorySurfaces (denies VIEWER). Movements, low-stock, warehouse list, and AA consents/transactions do not. VIEWER/sales without financial caps see qty/cost and bank AA amounts.",
    evidence="permission_classes = [IsAuthenticated, HasCompany] on those views.",
    root_cause="Inconsistent surface ACL.",
    business="PII/financial leak to viewers.",
    technical="RBAC holes.",
    customer="Salary-adjacent: bank feeds visible.",
    security="High.",
    performance="N/A",
    scalability="N/A",
    compliance="Least privilege fail.",
    risk="Multi-role pilot data leak.",
    fix_immediate="CanViewInventorySurfaces / CanViewFinancialReports / IsOwner as appropriate.",
    fix_short="Audit all HasCompany-only GETs.",
    fix_long="Policy engine.",
    effort="1d",
    tests="VIEWER 403 on movements and AA list.",
    acceptance="VIEWER cannot read stock costs or bank AA.",
    refs="BB-000553 sibling; Wave19 missed; auth audit",
)
add(
    title="Auto credit notes on sales/purchase returns omit cess_rate — CDNR understates cess",
    category="GST",
    subcategory="Returns",
    severity="High",
    priority="P1",
    module="Sales",
    feature="Return auto CN",
    files="backend/sales/return_service.py; backend/purchases/services.py auto CN lines",
    problem="Return complete builds CN lines with qty/price/gst only — no cess_rate. Stock+AR relief without cess. GSTR CDNR and GL miss cess (also BB cess GL).",
    evidence="CN item dicts without cess_rate in return services.",
    root_cause="Return CN builder predates cess.",
    business="Incomplete credit notes.",
    technical="Return ≠ original tax.",
    customer="Cess not reversed to customer.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="CDNR wrong.",
    risk="Cess goods returns.",
    fix_immediate="Copy cess_rate/HSN/UQC; fail return if CN incomplete.",
    fix_short="Shared line snapshot clone.",
    fix_long="Return as amendment document.",
    effort="1d",
    tests="Return cess line → CN cess_total matches.",
    acceptance="CN tax vector equals returned portion.",
    refs="Wave19 missed; GST audit",
)
add(
    title="RCM memo does not zero/move cess — header cess_total inconsistent with grand_total",
    category="GST",
    subcategory="RCM",
    severity="High",
    priority="P1",
    module="Purchases",
    feature="RCM cess",
    files="backend/core/services/billing.py apply_rcm_memo_after_tax; post_purchase RCM; build_gstr3b",
    problem="RCM copies CGST/SGST/IGST to rcm_* and zeros charged GST. Does not zero item.cess or document.cess_total. Line totals reset to taxable; header cess_total can remain. No rcm_cess. 3.1(d)/GL miss RCM cess.",
    evidence="RCM memo GST-only; no rcm_cess field.",
    root_cause="RCM predates cess.",
    business="Dirty RCM docs; wrong 3B.",
    technical="Header/line invariant break.",
    customer="RCM+cess purchases unusable.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="RCM cess liability missing.",
    risk="Any RCM cess invoice.",
    fix_immediate="rcm_cess + zero charged cess; 3B+GL.",
    fix_short="Invariant tests header==lines.",
    fix_long="Tax component matrix.",
    effort="2d",
    tests="RCM+cess → rcm_cess set, cess_total 0, grand consistent.",
    acceptance="RCM documents balanced including cess.",
    refs="Wave19 missed; GST audit",
)
add(
    title="GSTR-1 AT is rate-unknown zeros; no ATADJ/TXPD; nil conflates exempt/zero-rated; charges drop invoices from sections",
    category="GST",
    subcategory="GSTR-1 depth",
    severity="High",
    priority="P1",
    module="Reporting",
    feature="GSTR-1",
    files="backend/reporting/gst_returns.py _gstr1_at_table invoice_value_mismatch; gst_returns_sections.py",
    problem="AT rows hardcode rate=0 taxes 0. Unallocated receipts listed without GST on advance; no ATADJ when invoiced → double count if CA treats AT as taxable. 0% lines dumped to nil mixing nil/exempt/zero-rated. additional_charges≠0 → invoice_value_mismatch True → dropped from B2B sections while still completed. Filing adapter remains stub.",
    evidence="AT table tax_status rate_unknown; invoice_value_mismatch charges branch; nil bucket.",
    root_cause="Aids labeled complete after partial sections.",
    business="Unsafe filing pack.",
    technical="Schema ≠ GSTN.",
    customer="Freight invoices vanish from GSTR-1 B2B.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="GSTR-1 incomplete.",
    risk="CA uploads aid as-if portal file.",
    fix_immediate="Honesty watermarks; block Complete on B2B+untaxed charges OR tax charges; drop AT until rates exist or implement ATADJ.",
    fix_short="Split nil/exempt; taxable charge lines.",
    fix_long="GSTN-shaped exporter.",
    effort="8d",
    tests="Charges invoice either in B2B with taxed freight or Complete blocked; ATADJ on allocation.",
    acceptance="No silent section drops; AT not double-count bait.",
    refs="BB-000568 sibling; Wave19 missed",
)
add(
    title="SEZ/export/sales RCM incomplete — einvoice is_reverse_charge always false; DEXP dumped into SEZ list",
    category="GST",
    subcategory="Supply types",
    severity="High",
    priority="P1",
    module="Sales",
    feature="supply_type",
    files="backend/sales/models.py; backend/sales/einvoice_payload.py; backend/reporting/gst_returns.py",
    problem="SalesInvoice has supply_type but no is_reverse_charge; e-invoice getattr always False. SEZ/EXP lack shipping bill/LUT/currency; IgstOnIntra always N. Zero-tax SEZWOP/EXPWOP still use normal GST complete unless user zeros rates. DEXP lumped into SEZ GSTR list.",
    evidence="einvoice_payload is_reverse_charge getattr; supply_type routing.",
    root_cause="Enum without tax treatment rules.",
    business="Export/SEZ IRP/GSTR wrong.",
    technical="Incomplete supply taxonomy.",
    customer="Exporters cannot file from BizBoard.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Export/SEZ rules.",
    risk="Wrong IGST on SEZ.",
    fix_immediate="Block SEZ/EXP complete without treatment rules; sales RCM flag; don't dump DEXP into SEZ.",
    fix_short="LUT/shipping bill fields.",
    fix_long="Full supply-type tax engine.",
    effort="6d",
    tests="SEZWOP complete requires 0 GST; DEXP not in SEZ section.",
    acceptance="Each supply_type has explicit tax+GSTR+IRP rules.",
    refs="Wave19 missed; GST audit",
)
add(
    title="CMP-08 aggregates all COMPLETED sales without type/opening/CN filters; GSTR-4 tables empty; gate copy stale",
    category="GST",
    subcategory="Composition",
    severity="High",
    priority="P1",
    module="Reporting",
    feature="CMP-08",
    files="backend/reporting/gst_returns.py build_cmp08 build_gstr4; registration_gates.py",
    problem="CMP-08 sums all completed sales in calendar quarter — no invoice_type filter, no opening exclusion, no CN net, no composition rate/tax payable. GSTR-4 tables {}. Gate still says CMP returns not supported while endpoint exists.",
    evidence="build_cmp08 query; build_gstr4 empty tables; gate message.",
    root_cause="Unsafe aid + stale copy.",
    business="Composition dealer mis-files turnover tax.",
    technical="Aid ≠ law.",
    customer="Wrong CMP-08.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Composition scheme.",
    risk="Composition pilots.",
    fix_immediate="Filter supplies; net CNs; or 404 with honest empty; fix gate string.",
    fix_short="Notified rate engine.",
    fix_long="Full CMP product.",
    effort="3d",
    tests="Openings/returns excluded; tax payable computed or aid refused.",
    acceptance="CMP-08 not a raw sales dump.",
    refs="BB-000050 residual; Wave19 missed",
)
add(
    title="LiveIrpAdapter is generic HTTP JSON POST, not NIC/IRP protocol; async references missing EInvoiceStatus.QUEUED",
    category="Integration",
    subcategory="GSP/IRP",
    severity="High",
    priority="P1",
    module="Integrations",
    feature="e-invoice live",
    files="backend/core/services/gsp_adapters.py LiveIrpAdapter; backend/sales/einvoice_eway_actions.py",
    problem="Live adapter POSTs plaintext JSON to {GSP_LIVE_BASE_URL}/irp/invoice with Bearer key. No GSP handshake, encryption, or signed QR validation. E-way validity hardcoded now+1 day. Async path references EInvoiceStatus.QUEUED which does not exist — status never updates. Calling this 'live' is dishonest.",
    evidence="gsp_adapters.py LiveIrpAdapter; status enum gap.",
    root_cause="HTTP stub named Live.",
    business="False live IRP confidence.",
    technical="Protocol mismatch.",
    customer="IRN failures / fake success locally.",
    security="Plaintext invoice payloads to random URL.",
    performance="N/A",
    scalability="N/A",
    compliance="NIC protocol.",
    risk="GSP_LIVE_ENABLED pointed at wrong host leaks invoices.",
    fix_immediate="Rename stub; persist QUEUED/FAILED correctly; don't enable outside certified GSP.",
    fix_short="Certified GSP SDK.",
    fix_long="IRP certification.",
    effort="S honesty / XL real",
    tests="Missing QUEUED does not crash; live flag off in prod without waiver.",
    acceptance="No 'live' label without protocol conformance tests.",
    refs="BB-000384 residual; Wave19 missed",
)
add(
    title="CORS wildcard/credentials guard only fires when ADMIN_ENABLED; CORS_ALLOW_ALL_ORIGINS env is dead",
    category="Security",
    subcategory="CORS",
    severity="High",
    priority="P1",
    module="Config",
    feature="CORS",
    files="backend/config/settings.py",
    problem="CORS_ALLOW_CREDENTIALS=True always. Wildcard check raises only if ADMIN_ENABLED. Prod default ADMIN_ENABLED=0. CORS_ALLOW_ALL_ORIGINS env never assigned to django-cors-headers setting. Ops think the knob works; prod+admin-off can set *.",
    evidence="settings.py ADMIN_ENABLED and CORS block; no CORS_ALLOW_ALL_ORIGINS assignment.",
    root_cause="Incomplete guard.",
    business="Credentialed CORS * in prod.",
    technical="Dead env var.",
    customer="CSRF/CORS confusion.",
    security="High.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Mis-set * with cookies.",
    fix_immediate="Always refuse * with credentials; wire or delete env var.",
    fix_short="Boot test.",
    fix_long="Explicit origin allowlist only.",
    effort="0.5d",
    tests="CORS * + credentials → ImproperlyConfigured regardless of ADMIN.",
    acceptance="No credentialed wildcard.",
    refs="BB-000500 residual; Wave19 missed; FE audit",
)
add(
    title="Unauthenticated /health/?ready=1 discloses db/cache/celery/beat/pdf_queue_depth; pdf_queue_depth probe is wrong",
    category="Security",
    subcategory="Information disclosure",
    severity="High",
    priority="P1",
    module="Core",
    feature="Health",
    files="backend/core/views.py HealthView; docker-compose.yml",
    problem="ready=1 is AllowAny and returns topology. pdf_queue_depth uses Redis LLEN('celery') which is not modern Celery transport → usually 0. Worker has no healthcheck; API ready requires beat with start_period 20s → flap. Distinct from beat ISO bug (closed).",
    evidence="HealthView ready payload; compose healthcheck ready=1 public.",
    root_cause="Debug readiness exposed publicly.",
    business="Attackers map internals / detect outages.",
    technical="Wrong queue metric.",
    customer="Flappy deploys.",
    security="Medium-High disclosure.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Public scrape of ready.",
    fix_immediate="Bind ready to localhost/shared secret; fix queue via inspect; don't require beat until first pulse.",
    fix_short="Worker healthcheck.",
    fix_long="Separate liveness/readiness/admin status.",
    effort="1.5d",
    tests="External ready without secret omits topology or 401.",
    acceptance="Public health is liveness only.",
    refs="Wave19 missed; FE/devops + auth audits",
)
add(
    title="AI assistant tax refusal is regex theater — indirect GST questions bypass",
    category="AI",
    subcategory="Tax advice",
    severity="High",
    priority="P1",
    module="Insights",
    feature="Assistant",
    files="backend/insights/assistant.py TAX_PATTERNS TAX_OUTPUT_STRIP",
    problem="Input/output regex + scrub. Indirect prompts ('rate for soap sold to Pune') bypass. LLM can still invent numbers. Daily 'insights' are template KPIs.",
    evidence="TAX_PATTERNS list; no classifier/tool-only mode.",
    root_cause="Keyword filter as safety.",
    business="Unlicensed tax advice risk.",
    technical="Bypassable guard.",
    customer="Bad GST decisions.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Tax advice liability.",
    risk="AI enabled pilots.",
    fix_immediate="Tool-only numeric answers with citations OR expand classifier; refuse POS/state rate questions.",
    fix_short="Allowlist tools only.",
    fix_long="No free-prose tax path.",
    effort="3d",
    tests="Indirect GST prompt refused.",
    acceptance="No free-text tax rates.",
    refs="BB-000405 residual; Wave19 missed; FE audit",
)
add(
    title="Tally HTTP 'sync' is a truncated one-shot XML dump (500 masters / 5000 sales vouchers, ACTION=Create)",
    category="Integration",
    subcategory="Tally",
    severity="High",
    priority="P1",
    module="Integrations",
    feature="Tally push",
    files="backend/integrations/tally/adapter.py; README.md",
    problem="Masters capped 500 names; vouchers 5000 sales only; ACTION=Create duplicates on retry; no purchases/payments/CNs; not bidirectional. README Wave 17 calls HTTP sync MVP-complete.",
    evidence="adapter caps; Create action.",
    root_cause="Export named sync.",
    business="Duplicate masters in Tally; incomplete books push.",
    technical="Not idempotent.",
    customer="Broken Tally company after retry.",
    security="N/A",
    performance="Timeouts on large orgs.",
    scalability="Hard caps.",
    compliance="N/A",
    risk="Tally migration damage.",
    fix_immediate="Honest copy 'one-shot export'; GUID idempotent vouchers or hide push.",
    fix_short="Include purchases/notes.",
    fix_long="Real sync protocol.",
    effort="Honesty 0.25d / real XL",
    tests="Retry does not duplicate if GUID used.",
    acceptance="No 'sync' label without idempotency.",
    refs="Wave19 missed; FE audit",
)
add(
    title="OCR _normalize_payload drops confidence; UI defaults include=True with no confidence warning",
    category="AI",
    subcategory="OCR UX",
    severity="High",
    priority="P1",
    module="Imports",
    feature="Bill OCR",
    files="backend/core/services/llm.py _normalize_payload; web/src/pages/purchases/PurchaseBillUploadPage.tsx",
    problem="Human commit path exists but confidence is stripped. Combined with gst_rate default 18 (BB-000557) and include:True, rubber-stamp commit is easy. UI shows no extraction-confidence warning.",
    evidence="normalize drops confidence; FE include default true.",
    root_cause="JSON shape convenience.",
    business="Wrong ITC on committed bills.",
    technical="Lost signal.",
    customer="Silent bad rates.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="ITC evidence.",
    risk="OCR pilots.",
    fix_immediate="Persist+display confidence; require confirm below threshold; no auto-18 (557).",
    fix_short="Per-line confidence.",
    fix_long="Overlay review UI.",
    effort="1.5d",
    tests="Low confidence blocks commit without ack.",
    acceptance="Confidence visible and gated.",
    refs="BB-000557 sibling; Wave19 missed",
)
add(
    title="Accounting/reports/gateway/warehouse pages are re-exports of PhasePages.tsx god dump (~1389 lines)",
    category="Frontend",
    subcategory="God modules",
    severity="High",
    priority="P1",
    module="Web",
    feature="PhasePages",
    files="web/src/pages/phase/PhasePages.tsx; web/src/pages/accounting/*.tsx re-exports; NewInvoicePage.tsx ~1578; NewPurchasePage.tsx ~1532",
    problem="Journals/P&L/TB/bank recon/gateway/warehouses re-export PhasePages. Invoice/purchase editors still monoliths. Untestable, a11y/i18n holes, high regression risk. BB-000114 was closed as 'extracts exist' while Phase dump remains the real app.",
    evidence="export { JournalsPage } from '@/pages/phase/PhasePages'; file sizes.",
    root_cause="Wave closure by extraction theater.",
    business="Slow feature delivery; bugs cluster.",
    technical="Undiffable god file.",
    customer="Inconsistent UX.",
    security="N/A",
    performance="Large JS parse.",
    scalability="N/A",
    compliance="N/A",
    risk="Every accounting UI change is a landmine.",
    fix_immediate="Split PhasePages by domain; ban new exports from it.",
    fix_short="Extract invoice hooks.",
    fix_long="Delete PhasePages.",
    effort="10d",
    tests="Per-page RTL as split.",
    acceptance="No page re-exports PhasePages.",
    refs="BB-000114 residual; Wave19 missed; FE audit",
)
add(
    title="ClamAV fail-open on any daemon error when CLAMAV_HOST is set",
    category="Security",
    subcategory="Uploads",
    severity="Medium",
    priority="P2",
    module="Core",
    feature="Malware scan",
    files="backend/core/services/files.py",
    problem="except Exception: log warning; allow upload. If CLAMAV_HOST set for compliance and daemon down, malware succeeds.",
    evidence="files.py fail-open comment Wave 17A.",
    root_cause="Availability over security.",
    business="Compliance control false.",
    technical="Fail-open.",
    customer="Malware in media.",
    security="Medium.",
    performance="N/A",
    scalability="N/A",
    compliance="AV control.",
    risk="ClamAV outage = open door.",
    fix_immediate="Fail-closed in production/staging when host set.",
    fix_short="Quarantine + alert.",
    fix_long="Async scan pipeline.",
    effort="0.5d",
    tests="CLAMAV_HOST set + connection error → 503 upload.",
    acceptance="No fail-open in prod when AV required.",
    refs="Wave19 missed; auth audit",
)
add(
    title="Cashfree webhook timestamp is signed but never freshness-checked (replay)",
    category="Security",
    subcategory="Webhooks",
    severity="Medium",
    priority="P2",
    module="Payments",
    feature="Cashfree webhook",
    files="backend/payments/gateway.py CashfreeGateway.verify_webhook",
    problem="HMAC over ts+body verified; |now-ts| not checked. Replay forever. finalize somewhat idempotent but FAILED→CAPTURED replays matter.",
    evidence="verify_webhook uses ts in signature only.",
    root_cause="Partial HMAC impl.",
    business="Stale webhook replay.",
    technical="No event id store.",
    customer="Payment state flicker.",
    security="Medium.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="If Cashfree enabled later.",
    fix_immediate="Reject |now-ts|>5m; persist webhook event ids.",
    fix_short="Provider event ledger.",
    fix_long="Outbox consumer.",
    effort="0.5d",
    tests="Old ts → 401/400.",
    acceptance="Stale webhooks rejected.",
    refs="Wave19 missed; auth audit",
)
add(
    title="OTP phone not E.164-normalized; VerifyOtpView not gated on OTP_ENABLED",
    category="Security",
    subcategory="OTP",
    severity="Medium",
    priority="P2",
    module="Accounts",
    feature="OTP",
    files="backend/accounts/views.py VerifyOtpView RequestOtpView; models User.phone",
    problem="Phone unique on raw string — 9876543210 vs +91… are different users. Verify does not check OTP_ENABLED (only request does). Throttle IP-scoped not per-phone.",
    evidence="VerifyOtpView vs RequestOtpView gates.",
    root_cause="Incomplete OTP hardening.",
    business="Duplicate users; SMS cost abuse.",
    technical="Identity split.",
    customer="Can't login with +91 prefix.",
    security="Medium.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="OTP_ENABLED=0 still verifiable if challenges exist.",
    fix_immediate="E.164 normalize; gate verify; per-phone cooldown.",
    fix_short="Merge duplicate phones.",
    fix_long="Phone as verified identity.",
    effort="1d",
    tests="Verify with OTP_ENABLED=0 → 404; +91 and 10-digit same user.",
    acceptance="Normalized phones; verify gated.",
    refs="Wave19 missed; auth audit",
)
add(
    title="DJANGO_DEBUG only accepts literal '1'; .env.example uses true → silent DEBUG=False locally",
    category="Configuration",
    subcategory="Env parsing",
    severity="Medium",
    priority="P2",
    module="Config",
    feature="DEBUG",
    files="backend/config/settings.py; .env.example; web/.env.example VITE_API_BASE vs VITE_API_BASE_URL",
    problem="DEBUG = env == '1'. Example DJANGO_DEBUG=true → False → cookie-only auth locally (exposes BB-000602). Web Dockerfile sets VITE_API_BASE but client reads VITE_API_BASE_URL. features.ts accounting 'defaults on' copy vs === 'true'.",
    evidence="settings.py L21; .env.example true.",
    root_cause="Inconsistent boolean parsing.",
    business="Local/docker surprise; broken SPA.",
    technical="Footgun.",
    customer="Dev friction.",
    security="Low-Medium (hides auth bugs).",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Ship broken cookie auth unnoticed.",
    fix_immediate="Accept 1/true/yes; fail unrecognized; align Vite env names.",
    fix_short="Env linter.",
    fix_long="Typed settings.",
    effort="0.5d",
    tests="DJANGO_DEBUG=true enables DEBUG; unknown value boot-fails.",
    acceptance="Documented booleans parse consistently.",
    refs="Wave19 missed; auth+FE audits",
)
add(
    title="VirtualizedTable only windows the current 50-row page and ignores vRow.start positioning",
    category="Performance",
    subcategory="Virtualization theater",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="VirtualizedTable",
    files="web/src/components/VirtualizedTable.tsx; DocumentListPage.tsx",
    problem="Lists paginate 50 then 'virtualize' those 50. Rows use vRow.size not vRow.start/absolute layout. DocumentListPage is plain MUI table. Does not solve large lists (BB-000117 closed as virtualized).",
    evidence="VirtualizedTable implementation; DocumentListPage no virtualizer.",
    root_cause="Wrapper theater.",
    business="Perf claim false.",
    technical="Scroll bugs.",
    customer="No benefit.",
    security="N/A",
    performance="Negligible.",
    scalability="N/A",
    compliance="N/A",
    risk="False perf closure.",
    fix_immediate="Fix positioning or delete wrapper; keep pager honesty.",
    fix_short="Real windowing without tiny pages if needed.",
    fix_long="TanStack table standard.",
    effort="1d",
    tests="Visual scroll alignment; or remove component.",
    acceptance="No theater virtualization.",
    refs="BB-000117 residual; Wave19 missed; FE audit",
)
add(
    title="Celery beat schedules duplicate health snapshots 15 minutes apart; no distributed beat lock",
    category="Reliability",
    subcategory="Beat jobs",
    severity="Medium",
    priority="P2",
    module="Insights",
    feature="Beat schedule",
    files="backend/config/settings.py CELERY_BEAT_SCHEDULE; insights/tasks.py",
    problem="generate_daily_summary already snapshots health; snapshot_health_scores_task repeats 15 min later. Two beat replicas double-enqueue (email mostly claimed; extra load).",
    evidence="CELERY_BEAT_SCHEDULE insights tasks; summary calls snapshot.",
    root_cause="Overlapping schedules.",
    business="Wasted worker $; possible duplicate emails under race.",
    technical="No redbeat/lock.",
    customer="N/A mostly.",
    security="N/A",
    performance="Extra DB.",
    scalability="Multi-beat unsafe.",
    compliance="N/A",
    risk="Compose scale-out beat.",
    fix_immediate="Remove duplicate snapshot schedule; single beat replica documented.",
    fix_short="Redbeat lock.",
    fix_long="Unified daily job.",
    effort="0.5d",
    tests="One snapshot per company per day in beat integration test.",
    acceptance="No duplicate snapshot task.",
    refs="Wave19 missed; FE/devops audit",
)
add(
    title="GSTR-2B match is weak (GSTIN+exact number) and mutates ingest rows as a side effect of report download",
    category="GST",
    subcategory="GSTR-2B",
    severity="Medium",
    priority="P2",
    module="Reporting",
    feature="2B match",
    files="backend/reporting/gstr2b.py match_gstr2b_to_purchases",
    problem="Match key supplier GSTIN + exact purchase number + tax within ₹1. Vendor numbers often differ from GSTN format. Matcher invoked from CA pack zip and writes MATCHED/PARTIAL during download. No IRN/date. Cess ignored.",
    evidence="gstr2b match + zip side effect (audit).",
    root_cause="Report download as writer.",
    business="Wrong ITC matches; non-idempotent downloads.",
    technical="GET/zip mutates DB.",
    customer="Re-download changes match state.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="2B integrity.",
    risk="CA pack download.",
    fix_immediate="Match is explicit POST; zip read-only; looser match + human confirm.",
    fix_short="IRN/date keys.",
    fix_long="Recon workspace.",
    effort="2d",
    tests="Zip download does not update match status.",
    acceptance="Reports are read-only.",
    refs="BB-000406 residual; Wave19 missed",
)
add(
    title="billing.is_intra_state treats blank party state as intra — draft/quote tax can be CGST+SGST for inter-state URP",
    category="GST",
    subcategory="Place of supply",
    severity="Medium",
    priority="P2",
    module="Core",
    feature="POS fallback",
    files="backend/core/services/billing.py is_intra_state",
    problem="if not b: return True (intra). Complete gate requires mappable POS when tax-enabled, but drafts/quotations and assume_local_state_for_blank_party still default CGST+SGST. Inter-state unregistered buyer misclassified if assume-local on.",
    evidence="billing.py L158-164.",
    root_cause="Fail-open intra.",
    business="Wrong draft totals → completed if assume-local.",
    technical="POS heuristic.",
    customer="B2CL vs B2CS errors.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="POS rules.",
    risk="URP inter-state sales.",
    fix_immediate="Unknown POS → unknown tax split not intra; require state before tax preview.",
    fix_short="Unify with place_of_supply service.",
    fix_long="POS engine.",
    effort="1d",
    tests="Blank party state does not yield CGST+SGST preview unless assume-local explicit.",
    acceptance="No silent intra default without flag.",
    refs="Wave19 missed; GST audit",
)
