# -*- coding: utf-8 -*-
"""Wave 21 — residual passes after Wave 20. Start BB-000650.
Duplicates skipped: 648 paid-CN, 639 IRP stamp, 640-642 e-way payload, 643 file path,
649 CN charges/POS, 570/646 FY series scan, 606 AA mock, 556 WA token, 558 VIEWER ERP write,
561 payroll deductions, 553 WO SALE, 555 OCR 18 / WO cost, 615 serial cancel, 560 flags.
"""

ISSUES: list[dict] = []


def add(**kwargs):
    ISSUES.append(kwargs)


add(
    title="Unallocated receipt/payment DELETE leaves posted GL journals",
    category="Accounting",
    subcategory="Hard delete vs ledger",
    severity="Critical",
    priority="P0",
    module="Payments",
    feature="Receipt/payment destroy",
    files="backend/payments/views.py CustomerReceiptViewSet.perform_destroy SupplierPaymentViewSet.perform_destroy; backend/payments/services.py create_receipt create_supplier_payment",
    problem="Unallocated receipts/payments can be hard-deleted. Create posts cash/bank GL immediately. Destroy only catches ProtectedError — no PostingService.reverse. Cashbook and advances stay posted against a missing document.",
    evidence="perform_destroy → super().perform_destroy; create_receipt posts when accounting_enabled.",
    root_cause="Destroy treated as row delete, not document void.",
    business="Silent cash/books corruption.",
    technical="Orphan CREATE journals.",
    customer="Bank vs books never reconcile.",
    security="Audit trail erased while GL remains.",
    performance="N/A",
    scalability="N/A",
    compliance="Money documents must not hard-delete.",
    risk="Users delete 'mistakes' and corrupt FY cash.",
    fix_immediate="Forbid DELETE; cancel action reverses JE and sets VOID.",
    fix_short="Status CANCELLED on money docs.",
    fix_long="No hard delete of posted money.",
    effort="1d",
    tests="Create receipt → delete → cash JE reversed or delete 400.",
    acceptance="No posted JE without surviving source doc.",
    refs="Wave 21; [Find more audit issues](b068e323-842d-410f-9ea4-ce7d7be094e9)",
)
add(
    title="Allocation DELETE does not reverse ALLOCATE journals",
    category="Accounting",
    subcategory="Payment allocation",
    severity="Critical",
    priority="P0",
    module="Payments",
    feature="PaymentAllocation.destroy",
    files="backend/payments/views.py PaymentAllocationViewSet.perform_destroy; backend/accounting/services.py post_receipt_allocation",
    problem="Deleting an allocation removes the row (invoice looks unpaid) but leaves ALLOCATE_RECEIPT/ALLOCATE_PAYMENT JEs. Gateway refund path reverses; manual destroy does not. Users will do this to work around paid-invoice CN block (BB-000648).",
    evidence="perform_destroy: instance.delete() + audit only.",
    root_cause="Asymmetry with refund unwind.",
    business="AR/AP and advances diverge from documents.",
    technical="GL ≠ open items.",
    customer="Statement vs books mismatch.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Period books rewrite without reversing entry.",
    risk="Every 'unallocate' corrupts GL.",
    fix_immediate="Reverse ALLOCATE JE then delete, or disallow destroy.",
    fix_short="Unallocate action with reverse.",
    fix_long="Allocation is immutable; reverse-allocation document.",
    effort="0.5d",
    tests="Allocate → delete → AR and advances match pre-allocation.",
    acceptance="Destroy either forbidden or GL-neutral.",
    refs="Wave 21; BB-000648",
)
add(
    title="GSTR-1 dumps all unregistered notes into CDNUR — B2CS notes must net Table 7",
    category="GST",
    subcategory="GSTR-1 CDNR/CDNUR/B2CS",
    severity="Critical",
    priority="P0",
    module="Reporting",
    feature="GSTR-1 notes",
    files="backend/reporting/gst_returns_sections.py build_note_rate_rows; backend/reporting/gst_returns.py",
    problem="target = cdnr if _is_b2b(ctin) else cdnur. GSTN CDNUR is only B2CL (inter-state URP > ₹1L). Intra-state and small B2C CNs/DNs must net in Table 7 B2CS. Retail/POS CNs will fail portal or misstate outward tax.",
    evidence="gst_returns_sections.py L181 binary registered/unregistered.",
    root_cause="No B2CL vs B2CS split on notes.",
    business="GSTR-1 unusable for B2C-heavy MSMEs.",
    technical="Wrong return section.",
    customer="CA notices / portal reject.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="GSTR-1 schema.",
    risk="Every intra B2C CN is a filing defect.",
    fix_immediate="CDNUR only when original invoice is B2CL; else signed b2cs_buckets.",
    fix_short="Share classifier with invoice tables.",
    fix_long="Return builder from supply classification engine.",
    effort="2d",
    tests="Intra B2C CN → B2CS net; inter >1L URP CN → CDNUR; B2B → CDNR.",
    acceptance="No intra B2C note in CDNUR.",
    refs="Wave 21",
)
add(
    title="e-Way cancel sets CANCELLED but leaves eway_bill_no on the document",
    category="GST",
    subcategory="e-Way cancel",
    severity="High",
    priority="P1",
    module="Sales",
    feature="cancel_eway",
    files="backend/sales/einvoice_eway_actions.py cancel_eway (invoice + challan)",
    problem="Adapter cancel is called and status becomes CANCELLED, but eway_bill_no and eway_valid_upto are not cleared. UI/PDF/GSTR aids still show an active-looking bill number. Distinct from payload URP/distance/taxonomy (BB-000640–642).",
    evidence="cancel_eway save(update_fields=['eway_status']) only.",
    root_cause="Status flip without clearing identifiers.",
    business="Stale e-way numbers on cancelled docs.",
    technical="Status vs number inconsistency.",
    customer="Transporter uses cancelled EWB.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Cancelled EWB must not be presented as live.",
    risk="Dispatch on cancelled bill.",
    fix_immediate="Clear or archive eway_bill_no; keep cancelled_no audit field.",
    fix_short="PDF/UI hide cancelled numbers.",
    fix_long="Statutory event is source of truth.",
    effort="0.5d",
    tests="After cancel_eway, status CANCELLED and bill no not shown as active.",
    acceptance="Cancelled EWB not treated as live.",
    refs="Wave 21; BB-000640-642",
)
add(
    title="Receipts and supplier payments post into CLOSED GST/accounting periods",
    category="Accounting",
    subcategory="Period lock bypass",
    severity="High",
    priority="P0",
    module="Payments",
    feature="create_receipt / create_supplier_payment",
    files="backend/payments/services.py; backend/reporting/gst_periods.py assert_period_allows_money_amend",
    problem="Invoice/note complete calls assert_period_allows_money_amend. Receipt/payment create and allocation never do. Cash can be posted into a CLOSED month.",
    evidence="create_receipt has no period assert; sales complete does.",
    root_cause="Period gate only on invoice/note complete.",
    business="Period lock is theater for cash.",
    technical="GST snapshot dirtied after close.",
    customer="Closed-month cash appears after filing.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Books/GST period integrity.",
    risk="Post-close cash backdating.",
    fix_immediate="Gate create + allocation on doc date; mark period dirty.",
    fix_short="Same gate on bank recon matches.",
    fix_long="Central money-amend policy.",
    effort="0.5d",
    tests="CLOSED period receipt → 400.",
    acceptance="No cash JE in CLOSED period.",
    refs="Wave 21; BB-000608",
)
add(
    title="Allocation journal date is today, not receipt/payment date",
    category="Accounting",
    subcategory="JE dating",
    severity="High",
    priority="P1",
    module="Accounting",
    feature="post_receipt_allocation",
    files="backend/accounting/services.py post_receipt_allocation post_supplier_payment_allocation",
    problem="entry_date=timezone.localdate(). Backdated receipts allocated later hit the wrong month. Receipt CREATE uses receipt_date.",
    evidence="post_receipt uses receipt.receipt_date; allocation uses localdate().",
    root_cause="Convenience date.",
    business="Wrong month P&L/BS and bank recon.",
    technical="Split dating policy.",
    customer="CA period packs wrong.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Matching principle / period lock.",
    risk="Month-end allocations rewrite next month.",
    fix_immediate="Use receipt/payment date or explicit allocation_date.",
    fix_short="allocation_date field.",
    fix_long="Open-item engine with value date.",
    effort="0.5d",
    tests="M1 receipt allocated in M2 → JE policy documented and tested.",
    acceptance="Allocation date is deterministic, not 'today'.",
    refs="Wave 21",
)
add(
    title="Purchase debit notes have no cumulative headroom vs source invoice",
    category="Accounting",
    subcategory="Purchase DN",
    severity="High",
    priority="P1",
    module="Purchases",
    feature="complete_debit_note",
    files="backend/purchases/notes_services.py; backend/sales/notes_services.py complete_debit_note",
    problem="Sales DN checks invoice − prior DNs + CNs. Purchase DN complete has no equivalent — AP can be inflated arbitrarily.",
    evidence="Purchase complete_debit_note: GST/HSN warnings + post only.",
    root_cause="Sales BB-000303 not mirrored.",
    business="AP fraud / fat-finger unbounded DN.",
    technical="Asymmetric note guards.",
    customer="Vendor AP explodes.",
    security="Internal fraud vector.",
    performance="N/A",
    scalability="N/A",
    compliance="ITC/GSTR-2 distortion.",
    risk="Unlimited AP via DNs.",
    fix_immediate="Mirror sales headroom.",
    fix_short="Policy exception with owner reason.",
    fix_long="Shared note headroom service.",
    effort="0.5d",
    tests="DN > invoice + CNs rejected.",
    acceptance="Purchase DN bounded like sales DN.",
    refs="Wave 21; BB-000303",
)
add(
    title="Price lists are UI-only — API/POS/import ignore them",
    category="Business Logic",
    subcategory="Pricing",
    severity="High",
    priority="P1",
    module="Sales",
    feature="Price lists",
    files="web/src/pages/sales/NewInvoicePage.tsx; backend/sales/services.py _build_items; backend/masters/models.py",
    problem="Customer.price_list exists; New Invoice applies it in React. Backend uses client unit_price or product.selling_price. POS, imports, convert, mobile, direct API bypass lists.",
    evidence="No PriceList references in backend/sales.",
    root_cause="Display helper, not pricing engine.",
    business="Margin leakage / contract breach.",
    technical="FE enforcement only.",
    customer="Staff underprice via API/POS.",
    security="Authz hiding vs enforcing.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Price list product is fake.",
    fix_immediate="Resolve server-side unless override role.",
    fix_short="POS/import same engine.",
    fix_long="Pricing service + audit overrides.",
    effort="3d",
    tests="List price 90, API unit_price 10 → 90 or 403.",
    acceptance="Server is source of price.",
    refs="Wave 21",
)
add(
    title="Company switch race: X-Company-Id overrides active_company without audit",
    category="Security",
    subcategory="Multi-company concurrency",
    severity="High",
    priority="P1",
    module="Core",
    feature="Company switcher",
    files="web/src/api/client.ts; web/src/hooks/useCompanySwitcher.ts; backend/core/permissions.py get_company_user; backend/accounts/views.py SwitchCompanyView",
    problem="Interceptor always sends localStorage X-Company-Id. Backend prefers header over user.active_company_id. persistActiveCompanyId runs after switch API. In-flight requests and other tabs can write company A while UI shows B. Header path skips SwitchCompanyView audit.",
    evidence="get_company_user header branch first; switcher persist after POST.",
    root_cause="Dual source of truth.",
    business="Cross-company data entry (still membership-scoped).",
    technical="Race + unaudited tenant context.",
    customer="Wrong books updated.",
    security="Confused deputy within user's memberships.",
    performance="N/A",
    scalability="Breaks multi-company UX.",
    compliance="Audit incomplete.",
    risk="CA with two firms misposts.",
    fix_immediate="Header must match active_company or 409; pause traffic during switch.",
    fix_short="Generation token; tab sync.",
    fix_long="Session company only server-side.",
    effort="2d",
    tests="Concurrent request during switch; two-tab switch.",
    acceptance="No write with stale X-Company-Id after switch.",
    refs="Wave 21",
)
add(
    title="SO / challan stock always uses default warehouse — invoice warehouse can differ",
    category="Inventory",
    subcategory="Multi-warehouse",
    severity="High",
    priority="P1",
    module="Sales",
    feature="Orders / challans",
    files="backend/sales/notes_services.py confirm_sales_order complete_challan; backend/sales/services.py complete",
    problem="Confirm/convert/challan complete always InventoryService.default_warehouse. Invoice may use another warehouse. Reservations release from default; SALE can hit another WH. SO/challan have no warehouse FK.",
    evidence="confirm_sales_order / complete_challan default only; SalesService.complete uses invoice.warehouse.",
    root_cause="SO/challan predate multi-WH.",
    business="Wrong WH stock / phantom shortages.",
    technical="Reservation ≠ issue location.",
    customer="Branch stock lies.",
    security="N/A",
    performance="N/A",
    scalability="Multi-WH unusable.",
    compliance="N/A",
    risk="Every non-default WH order is wrong.",
    fix_immediate="Warehouse on SO/challan; copy to invoice; reserve there.",
    fix_short="Block invoice WH ≠ reserved WH.",
    fix_long="Location-aware ATP.",
    effort="2d",
    tests="Reserve WH-A, invoice WH-B blocked or consistent.",
    acceptance="One warehouse per fulfillment chain.",
    refs="Wave 21",
)
add(
    title="Opening stock uniqueness ignores batch — second lot of same SKU blocked",
    category="Inventory",
    subcategory="Opening balances",
    severity="High",
    priority="P1",
    module="Inventory",
    feature="Opening stock",
    files="backend/inventory/services.py",
    problem="Duplicate opening check is company+warehouse+product, not batch. First opening lot blocks all other batches.",
    evidence="already_has_opening filter movement_type=OPENING_STOCK without batch.",
    root_cause="Pre-batch uniqueness.",
    business="Cannot open multi-lot inventory.",
    technical="Batch feature vs opening guard.",
    customer="Migration blocked.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Opening valuation incomplete.",
    risk="Pharma/chemical MSMEs cannot go live.",
    fix_immediate="Include batch (and null-batch) in uniqueness.",
    fix_short="Opening wizard per lot.",
    fix_long="Opening journal + layers API.",
    effort="0.5d",
    tests="Two batches opening same SKU/WH succeed; duplicate same batch fails.",
    acceptance="Per-batch opening allowed.",
    refs="Wave 21",
)
add(
    title="Purchase return values outbound stock at return unit_price, not purchase cost",
    category="Inventory",
    subcategory="Valuation",
    severity="High",
    priority="P1",
    module="Purchases",
    feature="Purchase returns",
    files="backend/purchases/services.py complete_return",
    problem="PURCHASE_RETURN posts unit_cost=item.unit_price. WAVG uses return/selling price, not historical purchase cost.",
    evidence="unit_cost=item.unit_price on batched and simple post.",
    root_cause="Line price reused as cost.",
    business="Inventory BS wrong; COGS later wrong.",
    technical="Valuation ≠ purchase history.",
    customer="Stock value jumps on returns.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Inventory disclosure.",
    risk="Any priced-differently PR corrupts WAVG.",
    fix_immediate="Use original PURCHASE movement unit_cost.",
    fix_short="FIFO peel on PR outbound.",
    fix_long="Unified return costing.",
    effort="1d",
    tests="Buy @100, return priced @80 → inventory down by 100/unit.",
    acceptance="PR does not revalue remaining stock via return price.",
    refs="Wave 21; BB-000601",
)
add(
    title="Unlinked purchase return issues stock with no AP/GL when accounting_enabled",
    category="Accounting",
    subcategory="Purchase return GL",
    severity="High",
    priority="P1",
    module="Purchases",
    feature="Unlinked PR",
    files="backend/purchases/services.py complete_return",
    problem="Unregistered path may return without invoice. Stock is issued; auto CN (only GL path) skipped when invoice is None. Inventory falls with no 1400/2100 posting.",
    evidence="if not existing_linked and invoice is not None before auto CN; no PostingService on return itself.",
    root_cause="GL only via CN; CN requires invoice.",
    business="Books vs stock mismatch.",
    technical="Return is stock-only.",
    customer="Mystery inventory drop.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Perpetual inventory vs GL.",
    risk="accounting_enabled + unlinked PR silently unbalances.",
    fix_immediate="Require invoice when accounting_enabled, or post return GL.",
    fix_short="Always post PR JE.",
    fix_long="Return as first-class GL event.",
    effort="1d",
    tests="Unlinked PR + accounting_enabled → error or balanced JE.",
    acceptance="No stock movement without matching books when books on.",
    refs="Wave 21",
)
add(
    title="Auto return CN ignores invoice header discount and round-off",
    category="GST",
    subcategory="Returns → auto CN",
    severity="High",
    priority="P1",
    module="Sales",
    feature="complete_return auto CN",
    files="backend/sales/return_service.py; backend/purchases/services.py; backend/sales/models.py SalesReturn",
    problem="SalesReturn has no discount fields; set_return_items totals lines only. Auto CN created without invoice_discount / auto_round_off. Full return CN can exceed net invoice (then hit BB-000648) or leave residual AR. Distinct from header charges=0 on manual notes (BB-000649).",
    evidence="SalesCreditNote.objects.create without discount fields.",
    root_cause="Return ≠ financial mirror of invoice.",
    business="AR leftovers / GSTR mismatch.",
    technical="Incomplete auto-CN mapping.",
    customer="Full return still shows balance due.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="CDNR value ≠ original net.",
    risk="Discounted invoices cannot be fully returned cleanly.",
    fix_immediate="Pro-rate header discount/round-off onto auto CN.",
    fix_short="Return mirrors invoice financials.",
    fix_long="Single amendment engine.",
    effort="2d",
    tests="BEFORE_TAX discount invoice → full return CN = invoice net.",
    acceptance="Full return zeros net AR (subject to 648 fix).",
    refs="Wave 21; BB-000648; BB-000649",
)
add(
    title="close_financial_year posts a wrong plug JE and is not exposed via API/UI",
    category="Accounting",
    subcategory="FY close",
    severity="High",
    priority="P1",
    module="Accounting",
    feature="Year close",
    files="backend/accounting/reports.py close_financial_year; backend/accounting/views.py",
    problem="On profit: Dr 4100 / Cr 3100 (zeros sales only). On loss: Dr 3100 / Cr 5400 (fakes COGS credit). Expenses/other income remain open. Function unwired — AccountingReportView is TB/P&L/BS/health only.",
    evidence="close_financial_year lines; no view action.",
    root_cause="Placeholder close (BB-000433 incomplete).",
    business="Cannot close books commercially.",
    technical="P&L accounts never zero.",
    customer="Next FY opening BS wrong.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Indian FY close.",
    risk="Any 'year close' button later would corrupt books.",
    fix_immediate="Do not expose until real close; document as unsafe.",
    fix_short="Close all IS codes to RE; lock FY; Owner API; idempotent.",
    fix_long="Closing worksheet + audit.",
    effort="5d",
    tests="Multi-account P&L → all IS 0; RE = net; second close no-op.",
    acceptance="FY close zeros income statement.",
    refs="Wave 21; BB-000433 residual",
)
add(
    title="Supplier payment allocation rejects RETURNED purchases with remaining AP",
    category="Accounting",
    subcategory="Supplier allocation",
    severity="Medium",
    priority="P2",
    module="Payments",
    feature="allocate_supplier_payment",
    files="backend/payments/services.py allocate_supplier_payment allocate_receipt",
    problem="Receipts allow COMPLETED and RETURNED. Supplier alloc requires status == COMPLETED — RETURNED blocked even if AP remains after partial return.",
    evidence="purchase status != COMPLETED fail vs sales not in (COMPLETED, RETURNED).",
    root_cause="Sales/purchase asymmetry.",
    business="Cannot settle remainder after PR.",
    technical="Stuck AP.",
    customer="Vendor payment deadlock.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Partial returns leave unpayable AP.",
    fix_immediate="Allow RETURNED when outstanding > 0.",
    fix_short="Unify alloc eligibility helper.",
    fix_long="Open-item status independent of doc status.",
    effort="0.25d",
    tests="Partial PR → allocate remainder.",
    acceptance="RETURNED + outstanding is allocatable.",
    refs="Wave 21",
)
add(
    title="date.today() used instead of timezone.localdate() on money/recon paths",
    category="Correctness",
    subcategory="IST vs UTC",
    severity="Medium",
    priority="P2",
    module="Accounting",
    feature="Dispose / recon / reports",
    files="backend/accounting/views.py; backend/accounting/reports.py; backend/reporting/services.py; backend/banking/fiu_adapter.py",
    problem="TIME_ZONE=Asia/Kolkata + USE_TZ=True, but FA dispose, recon match, some reports use date.today() (OS TZ). UTC hosts date docs on the wrong IST day around midnight.",
    evidence="entry_date=date.today(); disposed_at = date.today(); reconciled_at = date.today().",
    root_cause="Naive date.today().",
    business="Wrong GST/books day.",
    technical="TZ split brain.",
    customer="Midnight IST filings off-by-one.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Return period boundaries.",
    risk="Cloud UTC deploy dates wrong.",
    fix_immediate="timezone.localdate() everywhere.",
    fix_short="Lint ban date.today().",
    fix_long="Clock service.",
    effort="0.5d",
    tests="Fake UTC near IST midnight.",
    acceptance="No date.today() on money paths.",
    refs="Wave 21",
)
add(
    title="Serial uniqueness is company-wide, not per product",
    category="Inventory",
    subcategory="Serials",
    severity="Medium",
    priority="P2",
    module="Inventory",
    feature="Serial numbers",
    files="backend/inventory/models.py uniq_serial_per_company",
    problem="Unique (company, serial_number). Two SKUs cannot share SN001 (common vendor serials). Distinct from cancel asymmetry BB-000615.",
    evidence="constraint fields company + serial_number.",
    root_cause="Over-broad unique.",
    business="Cannot track vendor serials across SKUs.",
    technical="False unique conflicts.",
    customer="Second product serial rejected.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Electronics/auto MSMEs blocked.",
    fix_immediate="Unique (company, product, serial_number).",
    fix_short="Data migration.",
    fix_long="Optional global unique flag per company.",
    effort="1d",
    tests="Same serial on two products allowed.",
    acceptance="Per-product serial uniqueness.",
    refs="Wave 21; BB-000615",
)
add(
    title="No tenant backup/restore API or product recovery path",
    category="Reliability",
    subcategory="Backup / restore",
    severity="Medium",
    priority="P2",
    module="Ops",
    feature="Tenant DR",
    files="backend/core/permissions.py CanExport docstring; no backup views",
    problem="CanExport mentions backup exports but there is no backup/restore API, snapshot, or tenant recovery. Commercial SMEs have no self-serve DR.",
    evidence="rg backup|restore in backend hits docstring / unrelated helpers.",
    root_cause="Ops gap never productized.",
    business="Ransomware/bad import is existential.",
    technical="No tenant export contract.",
    customer="Cannot leave or recover.",
    security="No encrypted export control.",
    performance="N/A",
    scalability="Shared-DB blast radius.",
    compliance="Data portability.",
    risk="One bad delete = lost company.",
    fix_immediate="Ops runbook + nightly DB backups (deferred ops).",
    fix_short="Encrypted company export.",
    fix_long="Restore into sandbox company.",
    effort="8d",
    tests="Export A, wipe, restore, totals match.",
    acceptance="Documented recovery RPO/RTO.",
    refs="Wave 21",
)
add(
    title="No recurring invoice templates or scheduler",
    category="Product",
    subcategory="Recurring sales",
    severity="Medium",
    priority="P2",
    module="Sales",
    feature="Recurring invoices",
    files="none — no model/task/UI",
    problem="Rent/AMC/SaaS MSMEs must recreate invoices monthly. Easy to miss GST periods. No beat job.",
    evidence="No recurring matches in backend/web sales.",
    root_cause="Out of MVP scope but claimed full sales suite.",
    business="Churn vs Zoho/Tally recurring.",
    technical="N/A",
    customer="Manual monthly billing.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Missed tax invoices.",
    risk="Segment cannot launch.",
    fix_immediate="Honesty: not supported.",
    fix_short="Template + beat + period lock.",
    fix_long="Subscription billing engine.",
    effort="8d",
    tests="Monthly template one SI per period, idempotent.",
    acceptance="Or unclaim recurring.",
    refs="Wave 21",
)
add(
    title="No TDS/TCS engine — 194C/194J/TCS receipts impossible",
    category="Compliance",
    subcategory="TDS/TCS",
    severity="High",
    priority="P1",
    module="Accounting",
    feature="TDS/TCS",
    files="backend/insights/assistant.py (keyword only)",
    problem="No TDS/TCS fields, sections, GL, or 26Q/27EQ aids. Many SMEs require 194C/194J and TCS on receipts. Distinct from payroll PF/ESI (BB-000561).",
    evidence="No tds/tcs models outside insights regex.",
    root_cause="Never built.",
    business="Books incomplete for contractor-heavy MSMEs.",
    technical="N/A",
    customer="Must keep Excel/Tally for TDS.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="IT Act TDS/TCS.",
    risk="Cannot replace Tally for those firms.",
    fix_immediate="Honesty gate: no TDS claim.",
    fix_short="TDS on purchases/payments + TCS on sales; GL 226x/136x.",
    fix_long="Return aids 26Q/27EQ.",
    effort="10d",
    tests="194C 1% on contractor bill; payment net of TDS; liability GL.",
    acceptance="Or unclaim TDS.",
    refs="Wave 21; BB-000561",
)
add(
    title="No BizBoard SaaS subscription / entitlement billing",
    category="Product",
    subcategory="Platform billing",
    severity="High",
    priority="P1",
    module="Accounts",
    feature="Commercial entitlements",
    files="backend/accounts/models.py; backend/core/services/billing.py is document tax math",
    problem="No plan, trial, seat limits, subscription status, or metering. Feature flags exist but nothing enforces paid entitlements. Cannot bill or suspend tenants.",
    evidence="No plan/subscription/trial on Company/User.",
    root_cause="Product billing never scoped.",
    business="Cannot commercially launch as SaaS.",
    technical="No entitlement layer.",
    customer="N/A (operator).",
    security="Unpaid tenants keep full access.",
    performance="N/A",
    scalability="No plan tiers.",
    compliance="N/A",
    risk="Revenue leak / cannot GA.",
    fix_immediate="Manual ops suspend flag.",
    fix_short="Plan + Razorpay/Cashfree subscriptions; gate modules.",
    fix_long="Usage metering.",
    effort="10d",
    tests="Unpaid tenant blocked from complete; paid plan allows.",
    acceptance="Entitlement enforced.",
    refs="Wave 21",
)
add(
    title="Manufacturing and CRM FK fields accept other tenants’ PKs",
    category="Security",
    subcategory="Tenant isolation",
    severity="Critical",
    priority="P0",
    module="Manufacturing",
    feature="BOM / WO / CRM serializers",
    files="backend/manufacturing/serializers.py; backend/crm/serializers.py; backend/accounting/serializers.py CompanyPrimaryKeyRelatedField",
    problem="ERP serializers use unscoped ModelSerializer FKs. Accounting has CompanyPrimaryKeyRelatedField (BB-000085). A member can attach another company’s product/BOM/warehouse/customer/lead PK.",
    evidence="BomLineSerializer/WorkOrderSerializer plain PK fields; CRM same.",
    root_cause="Wave 17 ERP serializers skipped tenant PK pattern.",
    business="Cross-tenant stock/CRM linkage.",
    technical="FK graph breakout.",
    customer="Silent corruption.",
    security="Tenant breakout via PK oracle — two trial accounts.",
    performance="N/A",
    scalability="N/A",
    compliance="Multi-tenant isolation failure.",
    risk="P0 isolation bug.",
    fix_immediate="CompanyPrimaryKeyRelatedField on all ERP FKs.",
    fix_short="validate() company_id checks.",
    fix_long="Mixin + CI grep.",
    effort="1d",
    tests="Cross-tenant BOM product / WO warehouse / lead customer → 400.",
    acceptance="Foreign PKs rejected.",
    refs="Wave 21; BB-000085 residual; [Audit payroll mfg CRM](9d174bcc-11c0-45d7-b87c-03d9f1810cd1)",
)
add(
    title="Existing users cannot join a second company — multi-company invite hard-fails",
    category="Product",
    subcategory="Multi-company",
    severity="Critical",
    priority="P0",
    module="Accounts",
    feature="Invite + switch-company",
    files="backend/accounts/views.py invite",
    problem="Switch-company UI exists, but invite errors if email already has a user. No add-membership/consent flow. Multi-company unreachable in product.",
    evidence="User.objects.filter(email__iexact).exists() → ValidationError contact support.",
    root_cause="BUG-109 blocked silent attach; no consent invite shipped.",
    business="CA/owner with two firms cannot use feature.",
    technical="Switcher is dead UI.",
    customer="Contact support.",
    security="N/A (correctly avoids silent attach).",
    performance="N/A",
    scalability="Admin-only memberships.",
    compliance="N/A",
    risk="Multi-company claim is false.",
    fix_immediate="Hide switcher unless >1 membership; honesty docs.",
    fix_short="Email-consent invite creating CompanyUser only.",
    fix_long="Org directory + audit.",
    effort="4d",
    tests="Existing user invite → pending membership; accept → switch works.",
    acceptance="Same email two companies with consent.",
    refs="Wave 21",
)
add(
    title="CompanyGstin has no API or settings UI — branches cannot be managed",
    category="GST",
    subcategory="Multi-branch GSTIN",
    severity="Critical",
    priority="P0",
    module="Accounts",
    feature="CompanyGstin CRUD",
    files="backend/accounts/models.py CompanyGstin; backend/accounts/urls_company.py; web/src/pages/settings/GstSettingsPage.tsx",
    problem="Branch GSTINs exist as model and stamp on invoices, but company routes only detail + users + verify-gstin. Settings edit only company.gstin. Operators cannot create/activate branches. Distinct from IRP ignoring stamp (BB-000639) and GSTR mix (BB-000556).",
    evidence="urls_company has no gstins route; GstSettingsPage edits primary only.",
    root_cause="Model shipped without ViewSet/UI.",
    business="Multi-GSTIN SMEs cannot onboard branches.",
    technical="Stamp source unmanageable.",
    customer="Django admin only.",
    security="N/A",
    performance="N/A",
    scalability="Multi-state blocked.",
    compliance="Additional GSTIN inoperable.",
    risk="Multi-branch claim false in product.",
    fix_immediate="Owner CRUD + settings page.",
    fix_short="Invoice GSTIN picker.",
    fix_long="Warehouse↔GSTIN binding.",
    effort="3d",
    tests="Create second GSTIN; stamp; deactivate.",
    acceptance="Branch GSTINs without admin.",
    refs="Wave 21; BB-000639; BB-000556",
)
add(
    title="Users settings UI cannot grant sales/purchase/payment/journal/AI capabilities",
    category="Security",
    subcategory="RBAC UI",
    severity="Critical",
    priority="P0",
    module="Web",
    feature="UsersSettingsPage invite/patch",
    files="web/src/pages/settings/UsersSettingsPage.tsx; web/src/api/legacy/company.ts",
    problem="Backend has can_create_sales|purchases|payments, can_post_journals, AI flags. Invite/patch UI only inventory/import/cancel/reports/export. Invited SALES_STAFF cannot invoice; owners cannot grant write caps in product.",
    evidence="inviteCompanyUser body omits write/AI caps; form state L35–45.",
    root_cause="UI frozen at pre–BB-000227 cap set.",
    business="Staff onboarding broken.",
    customer="Permission denied after invite.",
    technical="Caps exist but unreachable.",
    security="Owners use API/admin inconsistently.",
    performance="N/A",
    scalability="N/A",
    compliance="SoD unconfigurable.",
    risk="Multi-user commercial use blocked.",
    fix_immediate="Expose all caps + snake_case map.",
    fix_short="Role presets matching capability_defaults_for_role.",
    fix_long="SoD matrix component.",
    effort="1.5d",
    tests="Invite staff, grant canCreateSales, create invoice.",
    acceptance="All CompanyUser caps editable within role invariants.",
    refs="Wave 21",
)
add(
    title="Production invite UI requires a password the API rejects and never shows invite_token",
    category="Security",
    subcategory="Onboarding",
    severity="Critical",
    priority="P0",
    module="Web",
    feature="Invite user",
    files="web/src/pages/settings/UsersSettingsPage.tsx; backend/accounts/views.py",
    problem="Save disabled without password (!form.password) even though helper text says optional. Prod/staging reject invite passwords. Token-only API exists but UI never displays/emails invite_token.",
    evidence="Button disabled without password; API ValidationError passwords disabled in production.",
    root_cause="FE never updated after BB-000366/418.",
    business="Cannot add staff in production from UI.",
    technical="Token flow unused.",
    customer="Invite always 400 or button dead.",
    security="Dev still encourages shared passwords.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Launch blocker for multi-user.",
    fix_immediate="Password optional; copy invite_token; hide password in prod.",
    fix_short="Email invite link.",
    fix_long="Magic-link + expiry UX.",
    effort="1d",
    tests="Prod-env invite without password returns token; with password → 400.",
    acceptance="Owner onboards staff in prod UI.",
    refs="Wave 21",
)
add(
    title="Invite form defaults canViewFinancialReports ON against backend least privilege",
    category="Security",
    subcategory="RBAC defaults",
    severity="High",
    priority="P0",
    module="Web",
    feature="Invite defaults",
    files="web/src/pages/settings/UsersSettingsPage.tsx",
    problem="Backend default False. Form initializes canViewFinancialReports: true so every SALES_STAFF invite gets AR/AP/P&L unless unchecked. Distinct from resolved BB-000408 !== false checkbox.",
    evidence="UsersSettingsPage.tsx canViewFinancialReports: true.",
    root_cause="Opposite of least privilege.",
    business="Revenue visibility by default.",
    technical="FE default ≠ BE default.",
    customer="Staff see P&L unintentionally.",
    security="Privilege creep.",
    performance="N/A",
    scalability="N/A",
    compliance="SoD.",
    risk="Every invite over-privileged.",
    fix_immediate="Default false.",
    fix_short="Warn when granting reports.",
    fix_long="Preset roles.",
    effort="0.25d",
    tests="Invite without touching checkbox → can_view_financial_reports=false.",
    acceptance="Opt-in only.",
    refs="Wave 21",
)
add(
    title="WhatsApp IntegrationConnection has no product API — Cloud creds unconfigurable",
    category="Integration",
    subcategory="WhatsApp",
    severity="High",
    priority="P0",
    module="Integrations",
    feature="WhatsApp connection",
    files="backend/integrations/models.py; backend/integrations/urls.py; backend/core/services/whatsapp.py",
    problem="Send path reads IntegrationConnection.WHATSAPP but integrations routes are Tally-only. No settings page. Tenants cannot store encrypted WA creds in-app. Distinct from FE token leak BB-000556.",
    evidence="urls.py only tally/*; Provider.WHATSAPP on model.",
    root_cause="Cloud client without connection CRUD.",
    business="Cloud send never tenant-configurable.",
    technical="Always env/wa.me.",
    customer="Feature appears shipped, is not operable.",
    security="Env global token (logged) remains only path.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="WhatsApp Cloud claim false.",
    fix_immediate="Owner upsert/delete WA connection write-only.",
    fix_short="Test-send.",
    fix_long="Per-template mapping.",
    effort="2d",
    tests="Store creds → cloud send uses them; clear → link mode.",
    acceptance="No Django admin required.",
    refs="Wave 21; BB-000556",
)
add(
    title="WhatsApp Cloud ignores ENABLE_WHATSAPP_CLOUD and uses invoice text as template name",
    category="Integration",
    subcategory="WhatsApp templates",
    severity="High",
    priority="P1",
    module="Core",
    feature="send_whatsapp_template",
    files="backend/core/services/notifications.py; backend/core/services/whatsapp.py; backend/config/settings.py",
    problem="ENABLE_WHATSAPP_CLOUD never checked. Share uses template_name=subject or bizboard_message and params=[body]. Meta templates 4xx; code falls back to wa.me while looking Cloud-enabled. Language hardcoded en.",
    evidence="notifications.py L40-58; flag only in settings/feature_flags.",
    root_cause="Adapter pretends freeform body is approved template.",
    business="Messages not delivered.",
    technical="Silent fallback.",
    customer="Thinks WhatsApp sent.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Meta policy.",
    risk="Cloud mode is theater.",
    fix_immediate="Gate on flag; fail closed if Cloud on and template missing.",
    fix_short="Map invoice_share / payment_reminder templates.",
    fix_long="Template registry per company.",
    effort="2d",
    tests="Flag off → no Graph call; flag on + bad template → error not LINK_READY success.",
    acceptance="Cloud send only with approved template + flag.",
    refs="Wave 21",
)
add(
    title="AA banking endpoints ignore ENABLE_ACCOUNT_AGGREGATOR kill-switch",
    category="Security",
    subcategory="Feature flags",
    severity="High",
    priority="P0",
    module="Banking",
    feature="AA ingest/list",
    files="backend/banking/views.py; backend/core/services/feature_flags.py; backend/config/settings.py",
    problem="Flag exists for FE but ingest/list always mounted with IsAuthenticated+HasCompany (+IsOwner on ingest). Any owner can POST bank-shaped rows. Distinct from mock FIU auto-ingest BB-000606.",
    evidence="banking/views.py no flag assert.",
    root_cause="Scaffold routed without kill-switch.",
    business="Fake bank data in prod.",
    technical="Dark feature is live.",
    customer="Accidental AA surface.",
    security="Bank-shaped injection.",
    performance="N/A",
    scalability="N/A",
    compliance="AA consent theater.",
    risk="Default prod not dark.",
    fix_immediate="404 unless flag + company override.",
    fix_short="Real FIU webhook auth.",
    fix_long="AA consent ledger.",
    effort="0.5d",
    tests="Flag off → 404; on → 201.",
    acceptance="Dark in default prod.",
    refs="Wave 21; BB-000606",
)
add(
    title="Work order release ignores BOM status — DRAFT/ARCHIVED BOMs consume stock",
    category="Manufacturing",
    subcategory="BOM lifecycle",
    severity="High",
    priority="P0",
    module="Manufacturing",
    feature="release_work_order",
    files="backend/manufacturing/services.py release_work_order; backend/manufacturing/models.py",
    problem="Release checks tenant + non-empty lines only. Archived/draft BOMs still consume stock. Distinct from SALE movement type BB-000553 and FG costing BB-000555.",
    evidence="release_work_order status check only on WO DRAFT, not bom.status == ACTIVE.",
    root_cause="Status enum never enforced.",
    business="Obsolete BOM issues live stock.",
    technical="BOM SM unused.",
    customer="Irreversible wrong issues.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Any archived BOM is live.",
    fix_immediate="Require ACTIVE.",
    fix_short="Freeze lines onto WO at release.",
    fix_long="BOM versioning.",
    effort="0.5d",
    tests="ARCHIVED BOM → 400.",
    acceptance="Only ACTIVE BOMs release.",
    refs="Wave 21; BB-000553",
)
add(
    title="Completed pay runs remain mutable and deletable without GL reverse",
    category="Accounting",
    subcategory="Payroll immutability",
    severity="High",
    priority="P0",
    module="Payroll",
    feature="PayRunViewSet",
    files="backend/payroll/serializers.py; backend/payroll/views.py; backend/core/viewsets.py",
    problem="period writable after COMPLETED. Default destroy deletes run + CASCADE slips; PayRun GL not reversed. Distinct from deductions=0 BB-000561.",
    evidence="read_only_fields omit period; no perform_destroy restriction.",
    root_cause="MVP CRUD left open on money docs.",
    business="Books/audit rewrite.",
    technical="Posted source deleted.",
    customer="Payroll JE orphan or deleted history.",
    security="Audit gap.",
    performance="N/A",
    scalability="N/A",
    compliance="Payroll records retention.",
    risk="Delete completed run = silent GL orphan or cascade mess.",
    fix_immediate="Lock period; block DELETE/PATCH when completed; reverse on cancel.",
    fix_short="Pay run cancel workflow.",
    fix_long="Immutable payslips.",
    effort="1d",
    tests="PATCH/DELETE completed → 400; GL unchanged.",
    acceptance="Completed runs immutable.",
    refs="Wave 21; BB-000561",
)
add(
    title="Payroll journal dated today, not pay-period month-end",
    category="Accounting",
    subcategory="Payroll GL dating",
    severity="High",
    priority="P1",
    module="Payroll",
    feature="complete_pay_run",
    files="backend/payroll/services.py",
    problem="Completing July payroll on 5 Aug posts entry_date=localdate() (Aug), not period month-end.",
    evidence="entry_date=timezone.localdate() in complete_pay_run.",
    root_cause="No period→date mapping.",
    business="P&L/cash by month wrong.",
    technical="Period field unused for JE date.",
    customer="July salary in August books.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Period matching.",
    risk="Every late complete misdates payroll.",
    fix_immediate="Last day of YYYY-MM.",
    fix_short="Respect open accounting period.",
    fix_long="Payroll calendar.",
    effort="0.5d",
    tests="Period 2026-07 completed in Aug → JE 2026-07-31.",
    acceptance="Books land in payroll month.",
    refs="Wave 21",
)
add(
    title="PayRun.period and Employee.salary are unvalidated",
    category="Business Logic",
    subcategory="Payroll validation",
    severity="High",
    priority="P1",
    module="Payroll",
    feature="Employee / PayRun",
    files="backend/payroll/models.py; backend/payroll/serializers.py",
    problem="period is any 7-char string; salary has no MinValueValidator. Negative salary → negative expense/cash. Garbage periods break uniqueness.",
    evidence="CharField max_length=7 help_text only; salary unconstrained.",
    root_cause="Help text mistaken for validation.",
    business="Corrupt payroll periods/cash.",
    technical="Invalid unique keys.",
    customer="2026-13 pay run exists.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Negative payroll posts negative cash.",
    fix_immediate="Regex YYYY-MM; salary >= 0.",
    fix_short="Reject empty active employee set.",
    fix_long="Payroll calendar master.",
    effort="0.5d",
    tests="2026-13, abcd, salary -1 → 400.",
    acceptance="Only calendar months and non-negative salary.",
    refs="Wave 21",
)
add(
    title="Pay-run complete is not concurrency-safe — double JE possible",
    category="Concurrency",
    subcategory="Payroll complete",
    severity="High",
    priority="P1",
    module="Payroll",
    feature="complete action",
    files="backend/payroll/services.py; backend/payroll/views.py",
    problem="Status check then post GL then save without select_for_update. Double-click / parallel complete can double-post journals.",
    evidence="if status==COMPLETED raise then post then save — no row lock.",
    root_cause="Missing money-doc locking pattern.",
    business="Duplicate cash/expense.",
    technical="Race.",
    customer="Double salary GL.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="UI double-submit common.",
    fix_immediate="select_for_update; unique (source_type, source_id, purpose) on journals.",
    fix_short="Idempotent complete.",
    fix_long="Outbox posting.",
    effort="1d",
    tests="Concurrent complete → one JE.",
    acceptance="Idempotent complete.",
    refs="Wave 21",
)
add(
    title="Assistant AP aging sums purchase grand_total, not outstanding",
    category="AI",
    subcategory="Payables aging",
    severity="High",
    priority="P0",
    module="Insights",
    feature="get_payables_aging",
    files="backend/insights/assistant.py",
    problem="Buckets sum grand_total for all COMPLETED purchases. payables_total nets payments/CNs. Aging can exceed true AP. Distinct from tax-regex BB-000627.",
    evidence="L227–257 amt = inv.grand_total; comment Approximate.",
    root_cause="Shortcut vs ReportService.receivables_aging.",
    business="Wrong cash advice.",
    technical="Inconsistent KPIs.",
    customer="Overstated overdue AP.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Founders pay wrong vendors first.",
    fix_immediate="Reuse outstanding logic.",
    fix_short="One aging service.",
    fix_long="AI reads reports only.",
    effort="1d",
    tests="Paid bill excluded; partial payment reduces bucket.",
    acceptance="Sum(aging) ≈ payables_total.",
    refs="Wave 21; BB-000627",
)
add(
    title="Business health ‘payables pressure’ uses MTD customer receipts vs AP",
    category="AI",
    subcategory="Health score",
    severity="High",
    priority="P1",
    module="Insights",
    feature="Business health",
    files="backend/insights/services.py",
    problem="Score compares AP to MTD customer receipts, not supplier payments. Strong collections improve payables pressure even if vendors unpaid.",
    evidence="mtd_receipts = CustomerReceipt...; ratio = mtd_receipts / payables.",
    root_cause="Wrong ledger side.",
    business="Misleading health grade.",
    technical="Nonsensical ratio.",
    customer="False 'healthy payables'.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Bad growth hints.",
    fix_immediate="Use posted supplier payments or AP days.",
    fix_short="Document factor definitions.",
    fix_long="CA-signed KPI dictionary.",
    effort="0.5d",
    tests="Receipts-only vs payments-only fixtures.",
    acceptance="Factor moves with vendor payments.",
    refs="Wave 21",
)
add(
    title="Sales KPIs include RETURNED invoices and never net returns",
    category="Reporting",
    subcategory="Dashboard / AI sales totals",
    severity="High",
    priority="P0",
    module="Reporting",
    feature="sales_today / MTD / product sales",
    files="backend/reporting/services.py; backend/insights/services.py; backend/insights/assistant.py",
    problem="OPEN_SALES = (COMPLETED, RETURNED). Fully returned invoices keep grand_total in sales_today/MTD/product/customer sales and assistant get_sales_totals. Returns not subtracted.",
    evidence="reporting/services.py OPEN_SALES; insights same tuple.",
    root_cause="RETURNED treated as still-sold.",
    business="Inflated revenue vs GST/net sales.",
    technical="KPI ≠ books.",
    customer="Distrust dashboard/AI.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Misstated management reports.",
    risk="Every full return inflates sales forever.",
    fix_immediate="COMPLETED only; subtract returns/CNs.",
    fix_short="Net sales helper.",
    fix_long="Semantic layer.",
    effort="1d",
    tests="Full return → sales KPI drops.",
    acceptance="Dashboard sales = net of returns.",
    refs="Wave 21",
)
add(
    title="Inventory valuation report uses list purchase_price, not WAVG/FIFO layers",
    category="Reporting",
    subcategory="Stock valuation",
    severity="High",
    priority="P0",
    module="Reporting",
    feature="inventory_summary",
    files="backend/reporting/services.py inventory_summary",
    problem="stock_value = on_hand * product.purchase_price ignores inventory_valuation_method. Distinct from WO FG list-price receipt BB-000555.",
    evidence="L396–413 inventory_summary.",
    root_cause="List price shortcut.",
    business="BS/stock report ≠ books.",
    technical="Valuation method unused in report.",
    customer="Wrong stock value to banker/CA.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Inventory disclosure.",
    risk="Price change without movement changes reported value.",
    fix_immediate="Value via layer/WAVG service.",
    fix_short="Warehouse filter.",
    fix_long="As-of valuation report.",
    effort="1.5d",
    tests="Price change without movement does not change value; FIFO matches layers.",
    acceptance="Report matches valuation method.",
    refs="Wave 21; BB-000555",
)
add(
    title="Management reports have no warehouse / GSTIN / branch slice",
    category="Reporting",
    subcategory="Multi-branch analytics",
    severity="High",
    priority="P1",
    module="Reporting",
    feature="Registers + dashboard",
    files="backend/reporting/services.py; backend/reporting/views.py",
    problem="Company-wide aggregates only. No warehouse, company_gstin, or branch query params. Distinct from GSTR multi-GSTIN statutory filter BB-000556.",
    evidence="sales_register / inventory_summary signatures; views pass date/customer/supplier/status only.",
    root_cause="Reports predate stamps/warehouses-as-branches.",
    business="Unusable for multi-location SMEs.",
    technical="No dimensional slice.",
    customer="Branch manager sees whole company.",
    security="Over-disclosure within company.",
    performance="N/A",
    scalability="Multi-branch ops blocked.",
    compliance="N/A",
    risk="Multi-branch analytics claim false.",
    fix_immediate="Filter + group-by warehouse and company_gstin_id.",
    fix_short="RBAC by warehouse.",
    fix_long="OLAP dims.",
    effort="2d",
    tests="Two warehouses → filtered totals.",
    acceptance="Branch slice works.",
    refs="Wave 21; BB-000556",
)
add(
    title="CanViewPaymentSurfaces does not hard-block VIEWER",
    category="Security",
    subcategory="RBAC payments",
    severity="High",
    priority="P0",
    module="Payments",
    feature="Payment list ACL",
    files="backend/core/permissions.py CanViewPaymentSurfaces CanViewSalesSurfaces",
    problem="Sales/purchase surface ACLs hard-block VIEWER. Payment surfaces allow VIEWER if can_view_financial_reports (not in _VIEWER_FORBIDDEN_CAPS). VIEWER+reports sees receipts/payments PII. Distinct from VIEWER ERP write BB-000558.",
    evidence="CanViewPaymentSurfaces: no VIEWER hard-block; sales has one.",
    root_cause="BB-000297 applied inconsistently.",
    business="SoD hole.",
    technical="Inconsistent ACL family.",
    customer="Read-only role sees payment instruments/UTRs.",
    security="PII / bank refs to viewers.",
    performance="N/A",
    scalability="N/A",
    compliance="Least privilege.",
    risk="Invite+reports default (BB-000677) compounds this.",
    fix_immediate="Hard-block VIEWER; reports via summary APIs.",
    fix_short="Align all CanView* helpers.",
    fix_long="Capability matrix tests.",
    effort="0.5d",
    tests="VIEWER+reports → payments 403.",
    acceptance="VIEWER cannot list payment documents.",
    refs="Wave 21; BB-000558",
)
add(
    title="OCR invents quantity 1 when unread and still auto-includes the line",
    category="AI",
    subcategory="OCR defaults",
    severity="High",
    priority="P1",
    module="Core",
    feature="Purchase bill extraction",
    files="backend/core/services/llm.py",
    problem="Missing quantity becomes '1', include: True. Silent extra unit on the bill. Distinct from gst_rate=18 BB-000555 and confidence drop BB-000629.",
    evidence="quantity: str(item.get('quantity') or '1') ... include True.",
    root_cause="Fail-open normalizer.",
    business="Overstated purchase qty/ITC/stock.",
    technical="Invented facts.",
    customer="Wrong GRN from OCR.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="ITC on invented qty.",
    risk="Every unread qty becomes 1.",
    fix_immediate="Empty qty → exclude or force review.",
    fix_short="Per-field confidence.",
    fix_long="Human confirm gate.",
    effort="0.5d",
    tests="Line without qty not auto-included.",
    acceptance="No invented quantities.",
    refs="Wave 21; BB-000555; BB-000629",
)
add(
    title="AI settings treat missing aiFeaturesEnabled as ON",
    category="Security",
    subcategory="AI settings",
    severity="High",
    priority="P1",
    module="Web",
    feature="AiSettingsPage",
    files="web/src/pages/settings/AiSettingsPage.tsx; backend/accounts/models.py",
    problem="Form defaults aiFeaturesEnabled: true and reset uses !== false. Staff serializer may omit budget fields; undefined becomes enabled. Saving can turn AI on unintentionally. Same anti-pattern as old BB-000408.",
    evidence="AiSettingsPage L33–34, L45; model default False.",
    root_cause="!== false fail-open.",
    business="Unexpected LLM spend / data egress.",
    technical="FE default ≠ model.",
    customer="AI on after open+save.",
    security="Unintended third-party data send.",
    performance="N/A",
    scalability="N/A",
    compliance="Data processing consent.",
    risk="Every settings visit can enable AI.",
    fix_immediate="=== true only; form default false.",
    fix_short="Patch only dirty fields.",
    fix_long="Explicit consent UX.",
    effort="0.25d",
    tests="AI off stays off after open+save with no toggle.",
    acceptance="Opt-in only.",
    refs="Wave 21",
)
add(
    title="Invite role dropdown still offers OWNER which API rejects",
    category="UX",
    subcategory="Invite form",
    severity="Low",
    priority="P3",
    module="Web",
    feature="UsersSettingsPage role select",
    files="web/src/pages/settings/UsersSettingsPage.tsx; backend/accounts/serializers.py InviteUserSerializer.validate_role",
    problem="UI lists OWNER; API rejects inviting OWNER. Dead option causes failed invites.",
    evidence="UsersSettingsPage role options include OWNER; validate_role rejects.",
    root_cause="FE/BE drift.",
    business="Support noise.",
    technical="Invalid option.",
    customer="Confusing error.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Low.",
    fix_immediate="Remove OWNER from invite dropdown.",
    fix_short="Transfer-ownership flow separate.",
    fix_long="Role catalog from API.",
    effort="0.1d",
    tests="Invite UI has no OWNER option.",
    acceptance="Only invitable roles listed.",
    refs="Wave 21",
)
