#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Wave 8 re-audit (2026-08-03): append NEW findings BB-000196+; reopen incomplete remediations.

Never regenerates BB-000001–195. Append-only. IDs permanent.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

TODAY = "2026-08-03"
OUT = Path(__file__).resolve().parent
REGISTER = OUT / "MASTER_ISSUE_REGISTER.md"
STATS = OUT / "_stats.json"
START_ID = 196

ISSUES: list[dict] = []


def add(**kwargs):
    ISSUES.append(kwargs)


# ─── CRITICAL / P0 ──────────────────────────────────────────────────────────
add(
    title="Empty payment gateway credentials fall back to SandboxAdapter (forgery)",
    category="Security",
    subcategory="Payments",
    severity="Critical",
    priority="P0",
    module="Payments",
    feature="Gateway webhooks",
    files="backend/payments/gateway.py; backend/payments/views.py",
    problem="get_adapter returns SandboxAdapter whenever credentials dict is empty for razorpay/cashfree/payu. Sandbox verify accepts X-Sandbox-Signature: ok. Combined with default payment_gateway_test_mode=True, webhooks can settle AR without real money.",
    evidence="gateway.py get_adapter L310-325: if not creds → SandboxAdapter(); Sandbox verify trivial; views.py webhook uses company credentials which may be empty.",
    root_cause="Test convenience path left on production webhook route after BB-000004 amount-match removal.",
    business="Fraudulent invoice settlement; cash/AR integrity collapse.",
    technical="Webhook authentication bypass when creds missing.",
    customer="Invoices marked paid without payment; disputes and revenue loss.",
    security="Critical payment forgery.",
    performance="N/A",
    scalability="Attack scales with exposed payment_link_id.",
    compliance="Fails payment integrity / PCI hygiene.",
    risk="Silent financial fraud in pilot/prod.",
    fix_immediate="Fail closed if provider≠sandbox and creds empty; reject sandbox adapter outside DJANGO_ENV=development/test.",
    fix_short="Per-company webhook secrets required; block test_mode in production.",
    fix_long="Provider account→company binding; mTLS; idempotency ledger.",
    effort="2d",
    tests="Adversarial: empty creds + X-Sandbox-Signature ok must 401/403; no CAPTURED.",
    acceptance="No settlement without cryptographically verified provider credentials.",
    status="Open",
    refs="BB-000004 residual; Wave8 re-audit",
)
add(
    title="PayU verify_webhook returns True when signature header absent",
    category="Security",
    subcategory="Payments",
    severity="Critical",
    priority="P0",
    module="Payments",
    feature="PayU webhooks",
    files="backend/payments/gateway.py",
    problem="PayUAdapter.verify_webhook: if salt configured but sig header missing, returns True (permissive for form posts).",
    evidence="gateway.py L282-289: if not sig: return True",
    root_cause="Adapter parity shortcut without form-hash validation path.",
    business="Forged PayU captures settle invoices.",
    technical="Missing signature accepted as valid.",
    customer="False paid status.",
    security="Critical webhook forgery.",
    performance="N/A",
    scalability="N/A",
    compliance="Payment integrity failure.",
    risk="Direct financial fraud.",
    fix_immediate="Require signature or validated form hash; never return True on missing sig.",
    fix_short="Implement official PayU reverse-hash check on form body.",
    fix_long="Dedicated PayU SDK + webhook IP allowlist.",
    effort="1d",
    tests="Missing sig → reject; wrong hash → reject; valid hash → accept.",
    acceptance="Unsigned PayU webhooks never settle.",
    status="Open",
    refs="Wave8; related BB-000004",
)
add(
    title="Razorpay create_payment_link stubs fake rzp.io URLs on missing keys or API error",
    category="Security",
    subcategory="Payments",
    severity="Critical",
    priority="P0",
    module="Payments",
    feature="Payment links",
    files="backend/payments/gateway.py",
    problem="Missing Razorpay keys or HTTP≥400 silently returns stub plink_rzp_* / rzp.io URLs (or callback_url). Customers receive non-collecting links; ops may believe money was requested.",
    evidence="gateway.py L137-163: stub on missing keys; stub fallback on status≥400",
    root_cause="Pilot convenience to not block billing on gateway outage.",
    business="Broken collections; trust damage; pairs with sandbox webhook forgery.",
    technical="Silent degradation hides integration failure.",
    customer="Cannot pay; support tickets; lost sales.",
    security="Fake collect URLs enable social-engineering / confusion attacks.",
    performance="N/A",
    scalability="N/A",
    compliance="Misleading payment artifact.",
    risk="Revenue ops blind spot.",
    fix_immediate="Raise BusinessRuleError; never stub in production/staging.",
    fix_short="Circuit breaker + operator alert; optional explicit STUB_PROVIDER flag for demos only.",
    fix_long="Multi-provider failover with honest status.",
    effort="0.5d",
    tests="No keys → 4xx; API 500 → 4xx; never return stub short_url in prod.",
    acceptance="Payment link API never returns non-provider URLs outside test.",
    status="Open",
    refs="Wave8; BB-000004 family",
)
add(
    title="Purchase H9 amend lacks period-close block and GL reverse/repost",
    category="Accounting",
    subcategory="Amendments",
    severity="Critical",
    priority="P0",
    module="Purchases",
    feature="H9 amend",
    files="backend/purchases/serializers.py; backend/sales/serializers.py",
    problem="Sales H9 calls assert_period_allows_money_amend and GL reverse/repost; purchase amend requires confirm_amend only — no period gate, no journal reverse/repost.",
    evidence="purchases/serializers.py ~L186-208 vs sales/serializers.py ~L193-234",
    root_cause="Incomplete parity when sales H9 was hardened (BB-000011 marked Resolved).",
    business="Closed-period purchase money edits; books/ITC diverge from documents.",
    technical="GL orphans / wrong ITC in 3B aid.",
    customer="CA restatement; GST mismatch.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Period integrity / GST books failure.",
    risk="Undetected books corruption after filing.",
    fix_immediate="Mirror sales path: period assert + reverse/repost journals.",
    fix_short="Shared amend service for sales+purchase.",
    fix_long="Event-sourced statutory amend ledger.",
    effort="3d",
    tests="Closed period reject; open period reverse+repost balances.",
    acceptance="Purchase amend identical controls to sales H9.",
    status="Open",
    refs="BB-000011 residual; Wave8",
)
add(
    title="Any company member can create/post/reverse journals (HasCompany only)",
    category="Security",
    subcategory="RBAC",
    severity="Critical",
    priority="P0",
    module="Accounting",
    feature="Journals",
    files="backend/accounting/views.py",
    problem="JournalViewSet permission_classes = [IsAuthenticated, HasCompany] — no owner/accountant gate on create/post/reverse.",
    evidence="accounting/views.py L68-110 area",
    root_cause="Accounting module shipped with coarse HasCompany after FE RoleRoute work.",
    business="Sales staff can fabricate cash/AR/equity journals.",
    technical="GL integrity compromised.",
    customer="Fraudulent books; audit failure.",
    security="Privilege escalation within tenant.",
    performance="N/A",
    scalability="N/A",
    compliance="SoD failure for books.",
    risk="Internal fraud.",
    fix_immediate="Restrict write/post/reverse to Owner or can_manage_accounting; reports need CanViewFinancialReports.",
    fix_short="Accountant role + approval workflow for reverse.",
    fix_long="Maker-checker for journals > threshold.",
    effort="1d",
    tests="SALES_STAFF post journal → 403; OWNER → 201.",
    acceptance="Only authorized roles mutate GL.",
    status="Open",
    refs="BB-000018/031 residual; Wave8",
)

# ─── HIGH / P1 ──────────────────────────────────────────────────────────────
add(
    title="Accounting TB/P&L/BS APIs lack CanViewFinancialReports",
    category="Security",
    subcategory="RBAC",
    severity="High",
    priority="P1",
    module="Accounting",
    feature="Reports",
    files="backend/accounting/views.py",
    problem="Trial balance / P&L / balance sheet endpoints require only HasCompany when accounting_enabled.",
    evidence="accounting/views.py ~L205-206",
    root_cause="Report views not wired to financial capability.",
    business="Staff without financial rights can read full books.",
    technical="Capability model bypassed.",
    customer="Confidential P&L leak to sales staff.",
    security="Authorization gap.",
    performance="N/A",
    scalability="N/A",
    compliance="Confidentiality failure.",
    risk="Internal data leak.",
    fix_immediate="Add CanViewFinancialReports to report views.",
    fix_short="Align FE allowAccounting with BE.",
    fix_long="Row-level report ACL.",
    effort="0.5d",
    tests="Staff without can_view_financial_reports → 403.",
    acceptance="Financial reports gated server-side.",
    status="Open",
    refs="Wave8; BB-000018",
)
add(
    title="Company logo/signature FileAsset FK lacks tenant check (IDOR)",
    category="Security",
    subcategory="IDOR",
    severity="High",
    priority="P1",
    module="Accounts",
    feature="Branding",
    files="backend/accounts/serializers.py; backend/accounts/models.py",
    problem="logo/signature accept any FileAsset PK without check_company_ref.",
    evidence="CompanySerializer fields logo/signature; no company_id validation on assign",
    root_cause="Missing check_company_ref pattern used elsewhere.",
    business="Cross-tenant branding / attachment leak via invoice PDF.",
    technical="IDOR on FileAsset.",
    customer="Another company's logo/signature on invoices.",
    security="Cross-tenant data exposure.",
    performance="N/A",
    scalability="N/A",
    compliance="Multi-tenant isolation failure.",
    risk="Tenant trust breach.",
    fix_immediate="Validate FileAsset.company_id == request company.",
    fix_short="Centralize FK tenant checks on all FileAsset refs.",
    fix_long="Signed asset tokens scoped to company.",
    effort="0.5d",
    tests="Cross-company FileAsset PK rejected.",
    acceptance="No cross-tenant FileAsset attach.",
    status="Open",
    refs="Wave8",
)
add(
    title="Bank recon match accepts bank_statement_line_id without company filter",
    category="Security",
    subcategory="IDOR",
    severity="High",
    priority="P1",
    module="Accounting",
    feature="Bank reconciliation",
    files="backend/accounting/views.py",
    problem="bank_statement_line_id set on journal without filtering BankStatementLine by company.",
    evidence="accounting/views.py ~L128-138",
    root_cause="Missing company-scoped get_object.",
    business="Cross-tenant bank line linkage corrupts recon.",
    technical="IDOR.",
    customer="Wrong bank matches; audit confusion.",
    security="Cross-tenant IDOR.",
    performance="N/A",
    scalability="N/A",
    compliance="Books integrity.",
    risk="Silent recon corruption.",
    fix_immediate="Resolve line via company=self.company.",
    fix_short="CompanyScoped get for all recon FKs.",
    fix_long="Recon service with strict tenancy.",
    effort="0.5d",
    tests="Foreign company line id → 404.",
    acceptance="Cannot attach foreign bank lines.",
    status="Open",
    refs="Wave8",
)
add(
    title="payment_gateway_test_mode defaults True for new companies",
    category="Configuration",
    subcategory="Payments",
    severity="High",
    priority="P1",
    module="Payments",
    feature="Gateway mode",
    files="backend/accounts/models.py; backend/payments/views.py",
    problem="New companies default payment_gateway_test_mode=True, steering webhooks toward sandbox settle path.",
    evidence="accounts/models.py ~L118; payments/views.py ~L487-488",
    root_cause="Dev-friendly default left for commercial path.",
    business="Accidental sandbox settlements in pilot.",
    technical="Test/prod mode confusion.",
    customer="Fake paid invoices.",
    security="Amplifies sandbox forgery (BB-000196).",
    performance="N/A",
    scalability="N/A",
    compliance="Payment mode hygiene.",
    risk="Pilot data integrity failure.",
    fix_immediate="Default False; refuse test_mode when DJANGO_ENV=production.",
    fix_short="Explicit enable + audit log.",
    fix_long="Separate sandbox tenant flag at platform level.",
    effort="0.5d",
    tests="New company test_mode False; prod boot rejects test_mode.",
    acceptance="Production never settles via sandbox mode by default.",
    status="Open",
    refs="Wave8; BB-000196",
)
add(
    title="Webhook probe always parses payload with sandbox adapter",
    category="Security",
    subcategory="Payments",
    severity="High",
    priority="P1",
    module="Payments",
    feature="Webhooks",
    files="backend/payments/views.py",
    problem="Probe path uses get_adapter(... sandbox) for all providers to extract payment_link_id before real verify.",
    evidence="payments/views.py ~L461-470",
    root_cause="Identity extraction coupled to sandbox JSON schema.",
    business="Mis-parse real provider payloads; wrong link binding.",
    technical="Incorrect adapter for probe.",
    customer="Failed or mis-applied settlements.",
    security="Weakens verify-before-lookup posture.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Settlement bugs under real traffic.",
    fix_immediate="Parse per provider; verify signature before link mutation.",
    fix_short="Typed provider envelope parsers.",
    fix_long="Provider SDK event objects.",
    effort="2d",
    tests="Razorpay/Cashfree/PayU probe each with native payload.",
    acceptance="No sandbox parse for live providers.",
    status="Open",
    refs="Wave8",
)
add(
    title="Backend Dockerfile runs as root without USER/healthcheck",
    category="DevOps",
    subcategory="Containers",
    severity="High",
    priority="P1",
    module="DevOps",
    feature="Docker",
    files="backend/Dockerfile",
    problem="Image runs as root; no HEALTHCHECK; unpinned base digest; single-worker gunicorn defaults.",
    evidence="backend/Dockerfile full file",
    root_cause="MVP container hardening deferred.",
    business="Higher blast radius on container escape.",
    technical="Non-compliant image baseline.",
    customer="Indirect via security incidents.",
    security="Privilege in container.",
    performance="Single worker under-utilizes CPU.",
    scalability="Poor horizontal readiness.",
    compliance="CIS Docker baseline fail.",
    risk="Prod compromise impact amplified.",
    fix_immediate="Add non-root USER + HEALTHCHECK.",
    fix_short="Multi-worker gunicorn; pin digest; --forwarded-allow-ips.",
    fix_long="Distroless / Chainguard base.",
    effort="1d",
    tests="Container runs as uid≠0; healthcheck green.",
    acceptance="Non-root production image.",
    status="Open",
    refs="Wave8",
)
add(
    title="requests package used by Razorpay adapter but missing from requirements.txt",
    category="DevOps",
    subcategory="Dependencies",
    severity="High",
    priority="P1",
    module="Payments",
    feature="Razorpay API",
    files="backend/payments/gateway.py; backend/requirements.txt",
    problem="import requests in Razorpay path but package not declared in requirements.txt.",
    evidence="gateway.py L147; requirements.txt lacks requests",
    root_cause="Implicit transitive dependency assumption.",
    business="Payment link creation crashes in clean Docker images when keys present.",
    technical="Runtime ImportError.",
    customer="Cannot create payment links.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Broken payments in prod deploy.",
    fix_immediate="Add requests (pinned) or switch to httpx already listed.",
    fix_short="CI import smoke for gateway adapters.",
    fix_long="Shared HTTP client module.",
    effort="0.25d",
    tests="Fresh venv import payments.gateway succeeds.",
    acceptance="Declared direct dependency present.",
    status="Open",
    refs="Wave8",
)
add(
    title="ADMIN_ENABLED defaults True — Django admin mounted by default",
    category="Security",
    subcategory="Surface",
    severity="High",
    priority="P1",
    module="Core",
    feature="Admin",
    files="backend/config/settings.py; backend/config/urls.py",
    problem="ADMIN_ENABLED defaults True; /admin/ exposed unless explicitly disabled.",
    evidence="settings.py ~L306; urls.py L47-48",
    root_cause="Dev convenience default.",
    business="Expanded attack surface if superuser weak.",
    technical="Admin mounted in prod by default.",
    customer="Indirect compromise risk.",
    security="Attack surface.",
    performance="N/A",
    scalability="N/A",
    compliance="Least privilege fail.",
    risk="Admin takeover.",
    fix_immediate="Default False outside DEBUG; require ADMIN_ENABLED=1.",
    fix_short="IP allowlist / SSO for admin.",
    fix_long="Remove admin from API image; ops-only sidecar.",
    effort="0.25d",
    tests="Prod settings matrix: admin 404 unless enabled.",
    acceptance="Production default has no /admin/.",
    status="Open",
    refs="BB-000072 residual; Wave8",
)
add(
    title="OTP verify lacks select_for_update — concurrent JWT issue race",
    category="Concurrency",
    subcategory="Auth",
    severity="High",
    priority="P1",
    module="Accounts",
    feature="OTP verify",
    files="backend/accounts/views.py",
    problem="Verify reads challenge, validates, marks consumed without row lock; concurrent requests may both succeed.",
    evidence="accounts/views.py ~L185-198",
    root_cause="Missing atomic consume pattern.",
    business="Duplicate sessions from one OTP.",
    technical="TOCTOU race.",
    customer="Unexpected multi-device sessions.",
    security="OTP reuse window.",
    performance="N/A",
    scalability="Worse under load.",
    compliance="OTP single-use expectation.",
    risk="Session sprawl / audit confusion.",
    fix_immediate="transaction.atomic + select_for_update; mark consumed first.",
    fix_short="Redis single-use jti for OTP.",
    fix_long="Provider-managed OTP.",
    effort="0.5d",
    tests="Concurrent verify → only one 200.",
    acceptance="OTP single-use under concurrency.",
    status="Open",
    refs="Wave8",
)
add(
    title="FE RoleRoute gaps on quotations/returns/payments/inventory mutate paths",
    category="Security",
    subcategory="RBAC",
    severity="High",
    priority="P1",
    module="Web",
    feature="Route guards",
    files="web/src/App.tsx; web/src/pages/*",
    problem="Mutating surfaces (quotations, sales returns, payment links/statements/recon, warehouses/transfers/serials) lack RoleRoute; VIEWER/staff can open create UIs; BE is only backstop.",
    evidence="App.tsx routes for sales/quotations, sales/returns, payments/*, inventory warehouses/transfers unguarded vs adjustments gated",
    root_cause="Incomplete FE capability wiring after coarse RBAC flags.",
    business="Unauthorized ops attempts; UX implies permission.",
    technical="Defense-in-depth gap.",
    customer="Confused errors; possible BE holes.",
    security="Client-side authz incomplete.",
    performance="N/A",
    scalability="N/A",
    compliance="SoD UI failure.",
    risk="Privilege confusion.",
    fix_immediate="Wrap mutate routes with canCreateSales / canCreatePayments / canManageInventory.",
    fix_short="Central route capability map tested.",
    fix_long="Generated route ACL from OpenAPI.",
    effort="2d",
    tests="VIEWER navigates → Forbidden for each mutate path.",
    acceptance="No mutate page reachable without capability.",
    status="Open",
    refs="BB-000031 residual; Wave8 FE",
)
add(
    title="PublicPayPage / invoice pay links use provider URLs without allowlist",
    category="Security",
    subcategory="Open redirect",
    severity="High",
    priority="P1",
    module="Web",
    feature="Public pay",
    files="web/src/pages/PublicPayPage.tsx; web/src/pages/InvoiceDetailPage.tsx; web/src/utils/safeUrl.ts",
    problem="providerShortUrl and UPI intentUrl from API injected into href without allowlist; safeUrl unused on these paths.",
    evidence="PublicPayPage.tsx ~L83-90; InvoiceDetailPage ~L520",
    root_cause="Trust of API URL fields.",
    business="Phishing via compromised/stub short_url.",
    technical="Open redirect / javascript: risk.",
    customer="Credential/payment phishing.",
    security="High if stub/malicious URL stored.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Account/payment phishing.",
    fix_immediate="Allowlist https payment hosts + upi: scheme; block javascript:.",
    fix_short="Reuse/extend safeUrl for payments.",
    fix_long="Server returns only relative pay path; FE builds provider redirect.",
    effort="1d",
    tests="javascript: and evil.com rejected; rzp.io/upi allowed.",
    acceptance="Only allowlisted schemes/hosts in href.",
    status="Open",
    refs="BB-000034 residual; Wave8",
)
add(
    title="Cashfree/PayU create_payment_link are stub URL generators (no HTTP)",
    category="Integration",
    subcategory="Payments",
    severity="High",
    priority="P1",
    module="Payments",
    feature="Gateways",
    files="backend/payments/gateway.py",
    problem="Cashfree and PayU adapters invent short URLs without calling provider APIs; UI presents them as live collection links.",
    evidence="Cashfree/PayU create_payment_link return fabricated payu.in/cashfree-style URLs",
    root_cause="Placeholder adapters shipped as product.",
    business="Broken collections if selected.",
    technical="Fake integration.",
    customer="Cannot pay.",
    security="Pairs with weak verify paths.",
    performance="N/A",
    scalability="N/A",
    compliance="Misleading payment claim.",
    risk="Pilot chooses PayU/Cashfree and fails silently.",
    fix_immediate="Disable providers in UI until live; raise NotImplemented in prod.",
    fix_short="Implement real APIs or remove from product.",
    fix_long="Certified gateway matrix.",
    effort="8d each or remove",
    tests="Selecting Cashfree/PayU in prod → clear error.",
    acceptance="No stub collect URLs in commercial builds.",
    status="Open",
    refs="Wave8; BB-000170 related",
)
add(
    title="GSTR-3B still computes net_payable_hint subtracting provisional ITC",
    category="GST",
    subcategory="GSTR-3B",
    severity="High",
    priority="P1",
    module="Reporting",
    feature="GSTR-3B",
    files="backend/reporting/gst_returns.py",
    problem="claimable:false labeling exists but net_payable_hint still subtracts purchase tax as ITC — operators may trust the number.",
    evidence="gst_returns.py ~L552-638",
    root_cause="Honesty flag incomplete; numeric hint still computed.",
    business="Misfiling GSTR-3B / wrong cash planning.",
    technical="Provisional ITC in payable math.",
    customer="Penalty risk if filed from hint.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="GST compliance critical.",
    risk="Incorrect statutory payment.",
    fix_immediate="Remove net_payable_hint or hard-zero ITC until 2B match.",
    fix_short="Separate cash-planning view clearly non-statutory.",
    fix_long="Full 2B engine (BB-000009).",
    effort="1d",
    tests="Response has no payable that subtracts unmatched ITC.",
    acceptance="No numeric net payable using books-only ITC.",
    status="Open",
    refs="BB-000009 residual; Wave8",
)
add(
    title="Manual mark-einvoice-generated accepts client IRN without GSP proof",
    category="GST",
    subcategory="E-Invoice",
    severity="High",
    priority="P1",
    module="Sales",
    feature="E-Invoice",
    files="backend/sales/einvoice_eway_actions.py; backend/sales/views.py",
    problem="Owner can stamp arbitrary IRN/ack via mark-generated; status GENERATED indistinguishable from sandbox/live.",
    evidence="einvoice_eway_actions.py ~L133-161",
    root_cause="Manual escape hatch without distinct status.",
    business="Fake IRN on PDFs/books.",
    technical="Compliance false positive.",
    customer="Invalid e-invoice claims.",
    security="Integrity of statutory fields.",
    performance="N/A",
    scalability="N/A",
    compliance="GST e-invoice integrity.",
    risk="Department scrutiny / buyer rejection.",
    fix_immediate="Status MANUAL_IRN + watermark; audit attestation required.",
    fix_short="Separate permission; disallow on filed periods.",
    fix_long="Only GSP-verified IRNs as GENERATED.",
    effort="1d",
    tests="Manual mark → MANUAL_IRN; PDF watermark.",
    acceptance="GENERATED only after verified GSP response.",
    status="Open",
    refs="BB-000005 residual; Wave8",
)
add(
    title="einvoice_enabled / aato_turnover still client-writable on CompanySerializer",
    category="GST",
    subcategory="Mass assignment",
    severity="High",
    priority="P1",
    module="Accounts",
    feature="E-Invoice enablement",
    files="backend/accounts/serializers.py",
    problem="Owner PATCH can enable e-invoice and set AATO without portal proof — still present after Scope C.",
    evidence="accounts/serializers.py CompanySerializer fields ~L39-54",
    root_cause="Client-controlled enablement not server-gated.",
    business="Mandate bypass / false readiness.",
    technical="Mass assignment of compliance flags.",
    customer="Incorrect e-invoice obligation handling.",
    security="Integrity.",
    performance="N/A",
    scalability="N/A",
    compliance="AATO honesty failure.",
    risk="Wrong IRN path enabled.",
    fix_immediate="Read-only from client; enable via verified GSP/AATO job.",
    fix_short="Admin-only ops tool.",
    fix_long="Portal-synced turnover.",
    effort="2d",
    tests="PATCH einvoice_enabled ignored/403.",
    acceptance="Client cannot enable e-invoice unilaterally.",
    status="Open",
    refs="BB-000027 STILL OPEN; Wave8",
)
add(
    title="accounting_enabled writable via Company PATCH bypassing seed_chart path",
    category="Accounting",
    subcategory="Mass assignment",
    severity="Medium",
    priority="P2",
    module="Accounts",
    feature="Accounting enable",
    files="backend/accounts/serializers.py; backend/accounting/views.py",
    problem="Owner can PATCH accounting_enabled without AccountingSettingsView seed_chart_of_accounts.",
    evidence="CompanySerializer includes accounting_enabled; dedicated settings view seeds CoA",
    root_cause="Dual enable paths.",
    business="Posting failures / incomplete chart.",
    technical="Inconsistent enablement.",
    customer="Broken journals.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Books setup integrity.",
    risk="Partial accounting mode.",
    fix_immediate="Remove from CompanySerializer; only AccountingSettingsView.",
    fix_short="Idempotent ensure_chart on enable.",
    fix_long="Provisioning workflow.",
    effort="0.5d",
    tests="Company PATCH cannot enable accounting alone.",
    acceptance="Enable always seeds CoA.",
    status="Open",
    refs="Wave8",
)
add(
    title="Redis unauthenticated in docker-compose; default Postgres password bizboard",
    category="DevOps",
    subcategory="Secrets",
    severity="High",
    priority="P1",
    module="DevOps",
    feature="Compose",
    files="docker-compose.yml",
    problem="Redis has no requirepass; Postgres password defaults to bizboard if .env omitted.",
    evidence="docker-compose.yml redis service; POSTGRES_PASSWORD default",
    root_cause="Local-dev defaults.",
    business="LAN exposure steals sessions/queues/DB.",
    technical="Weak defaults.",
    customer="Data breach.",
    security="High on shared networks.",
    performance="N/A",
    scalability="N/A",
    compliance="Secret hygiene.",
    risk="Pilot LAN compromise.",
    fix_immediate="Require .env secrets; redis password; fail compose without them.",
    fix_short="Compose secrets: / Docker secrets.",
    fix_long="Managed Redis/Postgres.",
    effort="1d",
    tests="Compose without secrets fails.",
    acceptance="No default password in compose for shared deploy.",
    status="Open",
    refs="BB-000146 residual; Wave8",
)
add(
    title="Celery health probe true when Redis up but no worker consuming",
    category="DevOps",
    subcategory="Observability",
    severity="High",
    priority="P1",
    module="Core",
    feature="Health",
    files="backend/core/views.py",
    problem="_probe_celery_and_queue treats Redis PING+LLEN as celery:true even if no worker process; HTTP 200 when degraded.",
    evidence="core/views.py L30-95",
    root_cause="Queue reachability ≠ worker liveness.",
    business="PDF/email/insights silently stall while LB healthy.",
    technical="False-positive health.",
    customer="Stuck PDFs / notifications.",
    security="N/A",
    performance="N/A",
    scalability="Hidden backlog.",
    compliance="N/A",
    risk="Ops blind outage.",
    fix_immediate="Separate liveness/readiness; ping celery inspect ping; fail readiness if workers=0.",
    fix_short="Worker heartbeat key in Redis.",
    fix_long="APM + queue lag SLOs.",
    effort="1d",
    tests="Stop worker → readiness fails.",
    acceptance="Health distinguishes Redis vs worker.",
    status="Open",
    refs="BB-000047 residual; Wave8",
)
add(
    title="No CD pipeline — CI builds images but never pushes/deploys",
    category="DevOps",
    subcategory="CD",
    severity="High",
    priority="P1",
    module="CI",
    feature="Deploy",
    files=".github/workflows/ci.yml",
    problem="Only ci.yml; no registry push, staging deploy, or image tagging automation despite RUNBOOKS policy.",
    evidence=".github/workflows only ci.yml; docker build job no push",
    root_cause="CD deferred.",
    business="Manual insecure deploys; drift.",
    technical="No reproducible release path.",
    customer="Longer outages / wrong versions.",
    security="Manual secret handling risk.",
    performance="N/A",
    scalability="N/A",
    compliance="Change control weak.",
    risk="Failed releases.",
    fix_immediate="Add GHCR push on main tags.",
    fix_short="Staging CD with approvals.",
    fix_long="GitOps.",
    effort="5d",
    tests="Workflow pushes sha-tagged images.",
    acceptance="Every main merge produces immutable image tag.",
    status="Open",
    refs="BB-000126 residual; Wave8",
)
add(
    title="No Dependabot/Renovate/CodeQL/Trivy in repository",
    category="DevOps",
    subcategory="Supply chain",
    severity="Medium",
    priority="P2",
    module="CI",
    feature="Security scanning",
    files=".github/",
    problem="Zero automated dependency update or container/SAST scanning beyond pip-audit/npm audit in CI.",
    evidence="No dependabot.yml; no CodeQL workflow",
    root_cause="MVP CI scope.",
    business="Known CVEs linger.",
    technical="Supply-chain lag.",
    customer="Indirect exploit risk.",
    security="Medium ongoing.",
    performance="N/A",
    scalability="N/A",
    compliance="SOC2-ish gap.",
    risk="Unpatched critical CVE.",
    fix_immediate="Enable Dependabot + CodeQL.",
    fix_short="Trivy on docker build.",
    fix_long="SBOM + continuous monitoring.",
    effort="2d",
    tests="PR opened by Dependabot; CodeQL runs.",
    acceptance="Weekly dependency PRs + SAST on PR.",
    status="Open",
    refs="Wave8",
)
add(
    title="e2e job runs without API/Postgres — smoke can pass against mocks",
    category="Testing",
    subcategory="E2E",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="CI e2e",
    files=".github/workflows/ci.yml",
    problem="e2e job lacks API/Postgres services unlike e2e-golden; can green without full stack.",
    evidence="ci.yml e2e L72-88 vs e2e-golden L90-139",
    root_cause="Split jobs; light smoke incomplete.",
    business="False CI confidence.",
    technical="Coverage hole.",
    customer="Regressions ship.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Broken auth/UI ship.",
    fix_immediate="Require e2e-golden for merge; mark light e2e optional or wire stack.",
    fix_short="Unify e2e against compose.",
    fix_long="Nightly full suite.",
    effort="2d",
    tests="Light e2e fails if API down when required.",
    acceptance="Merge gate includes real API e2e.",
    status="Open",
    refs="Wave8; BB-000130",
)
add(
    title="fetchNextPage follows absolute next URL host without allowlist",
    category="Security",
    subcategory="SSRF-ish client",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="Pagination",
    files="web/src/api/resources.ts",
    problem="fetchNextPage strips path from any next URL and calls apiClient — if next were attacker-controlled, Bearer hits wrong host.",
    evidence="resources.ts ~L140-151",
    root_cause="Trust DRF absolute next.",
    business="Token exfil if next poisoned.",
    technical="Client open request.",
    customer="Session theft.",
    security="Medium (requires next poisoning).",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Token leak.",
    fix_immediate="Allowlist API origin before follow.",
    fix_short="Use relative next only.",
    fix_long="Cursor pagination without host.",
    effort="0.5d",
    tests="Evil host next rejected.",
    acceptance="Only configured API origin followed.",
    status="Open",
    refs="Wave8",
)
add(
    title="VITE_PILOT_ADVANCED can over-enable GSTR/AI/Tally/einvoice in prod builds",
    category="Configuration",
    subcategory="Feature flags",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="Flags",
    files="web/src/config/features.ts; web/vite.config.ts",
    problem="VITE_PILOT_ADVANCED supersets advanced modules; unlike VITE_USE_MOCKS, no prod hard-stop.",
    evidence="features.ts L16-33; vite mocks hard-stop exists but not for PILOT_ADVANCED",
    root_cause="Demo convenience flag.",
    business="Over-claim UI in commercial build.",
    technical="Flag hygiene gap.",
    customer="Sees non-GA compliance features.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Honesty gate bypass.",
    risk="BB-000014 class overclaim.",
    fix_immediate="Forbid VITE_PILOT_ADVANCED in production builds.",
    fix_short="CI assert prod artifact flags.",
    fix_long="Server-driven entitlements.",
    effort="0.5d",
    tests="Prod build with PILOT_ADVANCED fails.",
    acceptance="Prod bundles cannot embed PILOT_ADVANCED=true.",
    status="Open",
    refs="BB-000014 residual; Wave8",
)
add(
    title="e-Way submit buttons not honesty-gated (unlike e-invoice submit)",
    category="GST",
    subcategory="E-Way",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="E-Way",
    files="web/src/components/EinvoiceEwayPanel.tsx; web/src/components/ChallanEwayPanel.tsx",
    problem="E-invoice submit gated by isEinvoiceSubmitEnabled; e-Way submit always shown.",
    evidence="EinvoiceEwayPanel e-Way ~L326-332; ChallanEwayPanel ~L103-109",
    root_cause="Partial honesty gate implementation.",
    business="Sandbox e-way treated as live.",
    technical="Inconsistent flags.",
    customer="False EWB claims.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="E-way honesty.",
    risk="Invalid transport documents.",
    fix_immediate="Reuse einvoice/eway submit flag for all Submit buttons.",
    fix_short="Server reject when live GSP off.",
    fix_long="Live GSP.",
    effort="0.5d",
    tests="Flag off → no e-Way submit button.",
    acceptance="Parity with e-invoice honesty gate.",
    status="Open",
    refs="BB-000005 residual; Wave8",
)
add(
    title="GSTIN verify provider is Null-only — never VALID",
    category="GST",
    subcategory="GSTIN",
    severity="Medium",
    priority="P2",
    module="Core",
    feature="GSTIN verify",
    files="backend/core/services/gstin_verify.py",
    problem="get_gstin_provider always returns Null provider; verify never marks VALID.",
    evidence="gstin_verify.py L29-59",
    root_cause="Provider not wired.",
    business="False confidence or ignored verify status.",
    technical="Dead integration.",
    customer="Cannot trust GSTIN check.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Master data quality.",
    risk="Wrong GSTIN on invoices.",
    fix_immediate="UI label Unverified only; remove Verify claim.",
    fix_short="Wire ClearTax/GSTN public API.",
    fix_long="Cached portal sync.",
    effort="3-5d",
    tests="Null path never returns VALID.",
    acceptance="VALID only from real provider.",
    status="Open",
    refs="Wave8",
)
add(
    title="OTP_PEPPER falls back to SECRET_KEY",
    category="Security",
    subcategory="Secrets",
    severity="Medium",
    priority="P2",
    module="Accounts",
    feature="OTP",
    files="backend/config/settings.py",
    problem="OTP_PEPPER = env or SECRET_KEY — SECRET_KEY leak enables offline OTP brute if DB leaked.",
    evidence="settings.py ~L300-301",
    root_cause="Convenience fallback.",
    business="Account takeover facilitation.",
    technical="Key coupling.",
    customer="OTP brute after dual leak.",
    security="Defense-in-depth fail.",
    performance="N/A",
    scalability="N/A",
    compliance="Secret separation.",
    risk="Combined DB+SECRET_KEY breach worse.",
    fix_immediate="Require OTP_PEPPER in prod/staging.",
    fix_short="Separate KMS secret.",
    fix_long="Provider OTP.",
    effort="0.25d",
    tests="Prod boot fails without OTP_PEPPER.",
    acceptance="OTP pepper ≠ SECRET_KEY in prod.",
    status="Open",
    refs="Wave8",
)
add(
    title="CompanyUser capability mass assignment can escalate VIEWER inconsistently",
    category="Security",
    subcategory="RBAC",
    severity="Medium",
    priority="P2",
    module="Accounts",
    feature="Invites/users",
    files="backend/accounts/serializers.py; backend/accounts/models.py",
    problem="Owner PATCH can set can_* freely including invite role=OWNER; staff write flags default True.",
    evidence="CompanyUserSerializer ~L111-142; model defaults ~L203-207",
    root_cause="Capability model without role invariants.",
    business="Privilege sprawl; accidental second owner.",
    technical="Inconsistent role/capability.",
    customer="Over-privileged staff.",
    security="Authorization model drift.",
    performance="N/A",
    scalability="N/A",
    compliance="SoD.",
    risk="Internal fraud.",
    fix_immediate="Reject illegal role/capability combos; default write flags False for staff.",
    fix_short="Separate promote-owner flow.",
    fix_long="Policy engine.",
    effort="1d",
    tests="VIEWER+can_create_sales rejected; invite OWNER blocked.",
    acceptance="Role invariants enforced.",
    status="Open",
    refs="BB-000018 residual; Wave8",
)
add(
    title="Auth boot uses stale localStorage user before /auth/me completes",
    category="Security",
    subcategory="Auth UX",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="AuthContext",
    files="web/src/auth/AuthContext.tsx",
    problem="Initializes from getStoredUser(); RoleRoute may allow/deny on stale capabilities until me returns.",
    evidence="AuthContext.tsx ~L34, L91-113",
    root_cause="Optimistic hydrate without loading gate.",
    business="Brief wrong menu/access flash.",
    technical="Stale ACL.",
    customer="Flicker / confusing Forbidden.",
    security="Low (BE enforces) but UX ACL flash.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Confused deputy UI.",
    fix_immediate="authStatus loading gate before protected routes.",
    fix_short="Don't hydrate caps from localStorage.",
    fix_long="Cookie session.",
    effort="0.5d",
    tests="Protected tree not rendered until me settles.",
    acceptance="No capability flash from stale storage.",
    status="Open",
    refs="BB-000053 residual; Wave8",
)
add(
    title="401 interceptor may refresh on failed login when leftover refresh token exists",
    category="Security",
    subcategory="Auth client",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="Axios",
    files="web/src/api/client.ts",
    problem="401 retry/refresh applies broadly; failed login with leftover refresh can trigger refresh + session-expired side effects.",
    evidence="client.ts ~L55-71",
    root_cause="Global 401 interceptor without auth-path exclusions.",
    business="Confusing login UX.",
    technical="Wrong refresh attempts.",
    customer="Forced logout loops.",
    security="Low.",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Support noise.",
    fix_immediate="Skip refresh for /auth/login|register|otp|refresh.",
    fix_short="Auth-aware interceptor.",
    fix_long="BFF session.",
    effort="0.5d",
    tests="Login 401 does not call refresh.",
    acceptance="Auth endpoints excluded from refresh retry.",
    status="Open",
    refs="Wave8",
)
add(
    title="Backup export route/nav gated on canManageUsers instead of canExport",
    category="Frontend",
    subcategory="RBAC",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="Backup",
    files="web/src/App.tsx; web/src/config/menu.ts; web/src/pages/BackupExportPage.tsx",
    problem="Page checks canExport but route/nav use canManageUsers — exporters without user-admin cannot reach UI.",
    evidence="App.tsx ~L316-321; menu.ts; BackupExportPage canExport check",
    root_cause="Capability mismatch.",
    business="Operational backup blocked.",
    technical="ACL inconsistency.",
    customer="Cannot export when entitled.",
    security="N/A (over-restrictive).",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Missed backups.",
    fix_immediate="Route+nav on canExport.",
    fix_short="Capability matrix test.",
    fix_long="Generated ACL.",
    effort="0.5d",
    tests="canExport-only user reaches backup page.",
    acceptance="Route matches page capability.",
    status="Open",
    refs="BB-000113 residual; Wave8",
)
add(
    title="Accounting GL report routes not gated on accountingEnabled",
    category="Frontend",
    subcategory="RBAC",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="Accounting reports",
    files="web/src/App.tsx",
    problem="TB/P&L/BS under canViewFinancialReports only; CoA/journals require accountingEnabled.",
    evidence="App.tsx ~L296-307",
    root_cause="Inconsistent allowAccounting wrapper.",
    business="Reports opened when books disabled → empty/errors.",
    technical="Flag inconsistency.",
    customer="Broken pages.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Support load.",
    fix_immediate="Nest reports under allowAccounting.",
    fix_short="Shared accounting route group.",
    fix_long="Entitlement service.",
    effort="0.5d",
    tests="accountingEnabled false → Forbidden on TB.",
    acceptance="Parity with journals gate.",
    status="Open",
    refs="Wave8",
)
add(
    title="Blank company state still resolves POS as intra in FE tax preview",
    category="GST",
    subcategory="Place of supply",
    severity="Medium",
    priority="P1",
    module="Web",
    feature="Tax preview",
    files="web/src/utils/tax.ts",
    problem="if (!a) return 'intra' for company state — wrong CGST/SGST preview when company GSTIN/state missing.",
    evidence="tax.ts ~L283",
    root_cause="Default-intra residual after party-unknown work.",
    business="Wrong draft tax display.",
    technical="Preview ≠ BE complete gate.",
    customer="Confusion at invoice create.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="GST preview honesty.",
    risk="User completes with wrong expectation.",
    fix_immediate="Return unknown when company code blank.",
    fix_short="Block complete UI until POS known.",
    fix_long="Server-driven preview endpoint.",
    effort="0.5d",
    tests="Empty company state → unknown not intra.",
    acceptance="No silent intra default for blank company.",
    status="Open",
    refs="BB-000032 residual; Wave8",
)
add(
    title="DocumentNumberService.sync_next/peek unlocked vs next_number",
    category="Concurrency",
    subcategory="Document numbers",
    severity="Medium",
    priority="P2",
    module="Core",
    feature="Number series",
    files="backend/core/services/document_numbers.py",
    problem="next_number uses select_for_update; sync_next/peek do not — rare skip/duplicate under concurrency.",
    evidence="document_numbers.py L98-107 vs L145-159",
    root_cause="Inconsistent locking.",
    business="Duplicate invoice numbers under load.",
    technical="Race.",
    customer="Statutory numbering failure.",
    security="N/A",
    performance="N/A",
    scalability="Appears under concurrency.",
    compliance="Invoice numbering rules.",
    risk="GST numbering disputes.",
    fix_immediate="Always select_for_update on series row.",
    fix_short="Single allocate API.",
    fix_long="DB sequence per series.",
    effort="0.5d",
    tests="Concurrent sync_next+complete no duplicate.",
    acceptance="All series mutations locked.",
    status="Open",
    refs="Wave8",
)
add(
    title="CELERY_TIMEZONE unset while Django TIME_ZONE=Asia/Kolkata",
    category="DevOps",
    subcategory="Scheduling",
    severity="Medium",
    priority="P2",
    module="Config",
    feature="Celery beat",
    files="backend/config/settings.py",
    problem="Beat crontab comments assume UTC; Django TIME_ZONE Asia/Kolkata; CELERY_TIMEZONE undeclared.",
    evidence="settings.py L155, L261-278",
    root_cause="Timezone ambiguity.",
    business="Insights/depreciation at wrong wall clock.",
    technical="Schedule drift.",
    customer="Stale overnight jobs.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Period jobs timing.",
    risk="Missed month-end depreciation.",
    fix_immediate="Set CELERY_TIMEZONE and CELERY_ENABLE_UTC explicitly.",
    fix_short="Document IST vs UTC schedule table.",
    fix_long="Timezone-aware beat calendar UI.",
    effort="0.5d",
    tests="Assert settings CELERY_TIMEZONE set in CI.",
    acceptance="Documented unambiguous schedule.",
    status="Open",
    refs="Wave8",
)
add(
    title="No CSRF_TRUSTED_ORIGINS; secure cookies only if USE_TLS=1",
    category="Security",
    subcategory="Cookies/CSRF",
    severity="Medium",
    priority="P2",
    module="Config",
    feature="HTTP security",
    files="backend/config/settings.py",
    problem="CSRF_TRUSTED_ORIGINS unset; HSTS/secure cookies gated on USE_TLS which compose often leaves off behind TLS terminator.",
    evidence="settings.py ~L226-234, L308-315",
    root_cause="TLS flag not auto-detected from proxy.",
    business="CSRF / cookie theft if HTTPS without USE_TLS.",
    technical="Misconfig class.",
    customer="Session risks.",
    security="Medium.",
    performance="N/A",
    scalability="N/A",
    compliance="Hardening.",
    risk="Session hijack.",
    fix_immediate="Set CSRF origins from env; enable secure cookies when DJANGO_ENV=production.",
    fix_short="Trust X-Forwarded-Proto with allowlist.",
    fix_long="Terminate TLS in compose with certs.",
    effort="0.5d",
    tests="Prod settings include CSRF trusted origins.",
    acceptance="Production secure cookie flags on by default.",
    status="Open",
    refs="BB-000015 related; Wave8",
)
add(
    title="StockBalance get_or_create then lock — first-movement race",
    category="Concurrency",
    subcategory="Inventory",
    severity="Low",
    priority="P3",
    module="Inventory",
    feature="Stock",
    files="backend/inventory/services.py",
    problem="Concurrent first movement can IntegrityError on unique balance after get_or_create.",
    evidence="inventory/services.py ~L82-86",
    root_cause="Classic get_or_create race.",
    business="Rare failed stock post.",
    technical="Unhandled IntegrityError path.",
    customer="Retry required.",
    security="N/A",
    performance="N/A",
    scalability="Appears under concurrency.",
    compliance="N/A",
    risk="Failed invoice complete.",
    fix_immediate="Catch IntegrityError and re-fetch.",
    fix_short="insert … on conflict.",
    fix_long="Balance always pre-created.",
    effort="0.5d",
    tests="Concurrent first movement succeeds.",
    acceptance="No unhandled IntegrityError on first move.",
    status="Open",
    refs="Wave8",
)
add(
    title="AI assistant truncates tool JSON to 800 chars then re-feeds LLM",
    category="AI",
    subcategory="Assistant",
    severity="Low",
    priority="P3",
    module="Insights",
    feature="Assistant",
    files="backend/insights/assistant.py",
    problem="Tool results truncated to 800 chars; model may hallucinate missing fields.",
    evidence="assistant.py ~L417-450",
    root_cause="Token budget shortcut.",
    business="Misleading founder insights.",
    technical="Lossy tool channel.",
    customer="Wrong business advice.",
    security="N/A",
    performance="Saves tokens.",
    scalability="N/A",
    compliance="Honesty of AI.",
    risk="Bad decisions.",
    fix_immediate="Summarize server-side; mark truncated.",
    fix_short="Chunked tool reading.",
    fix_long="Structured tool schema only.",
    effort="1d",
    tests="Truncation flag visible to user.",
    acceptance="No silent truncation without marker.",
    status="Open",
    refs="Wave8",
)
add(
    title="Public payment link leaks customer/invoice metadata to unauthenticated holders",
    category="Security",
    subcategory="Privacy",
    severity="Low",
    priority="P3",
    module="Payments",
    feature="Public pay",
    files="backend/payments/views.py",
    problem="Token holder learns customer name, invoice number, company, amount without auth (expected for pay pages but undocumented risk).",
    evidence="payments/views.py ~L402-443; token_urlsafe(24)",
    root_cause="Pay-page product design.",
    business="Metadata disclosure on token leak.",
    technical="Unauthenticated PII.",
    customer="Privacy concern.",
    security="Low given entropy; document.",
    performance="N/A",
    scalability="N/A",
    compliance="DPDP minimize.",
    risk="Link forwarding leaks.",
    fix_immediate="Document; minimize fields; short TTL.",
    fix_short="Optional OTP to view details.",
    fix_long="Hosted fields tokenization.",
    effort="1d",
    tests="Response field allowlist reviewed.",
    acceptance="Privacy review signed for public pay payload.",
    status="Open",
    refs="BB-000066 related; Wave8",
)
add(
    title="RUNBOOKS restore omits stopping celery beat",
    category="DevOps",
    subcategory="Runbooks",
    severity="Medium",
    priority="P2",
    module="Ops",
    feature="Restore",
    files="docs/pilot/RUNBOOKS.md",
    problem="Restore stops api/worker but not beat — beat can keep writing after restore stop.",
    evidence="RUNBOOKS.md ~L45-47",
    root_cause="Docs lag after beat service added.",
    business="Corrupt post-restore state.",
    technical="Incomplete stop set.",
    customer="Data loss on restore.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="DR integrity.",
    risk="Failed restore drill.",
    fix_immediate="Stop beat in runbook; add to checklist.",
    fix_short="Single compose profile stop-all-app.",
    fix_long="Automated restore script.",
    effort="0.25d",
    tests="Restore drill includes beat.",
    acceptance="Runbook lists api worker beat.",
    status="Open",
    refs="BB-000045 residual; Wave8",
)
add(
    title="docs/reviews/12_DEVOPS_REVIEW.md stale vs fixed beat/pip-audit",
    category="Documentation",
    subcategory="Audit drift",
    severity="Low",
    priority="P3",
    module="Docs",
    feature="Reviews",
    files="docs/reviews/12_DEVOPS_REVIEW.md",
    problem="Still claims pip-audit || true and no beat after fixes — splits truth from register.",
    evidence="12_DEVOPS_REVIEW.md L12-26 vs compose/ci",
    root_cause="Review doc not refreshed post Wave7.",
    business="Wrong ops priorities.",
    technical="Doc drift.",
    customer="N/A",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Mis-prioritized remediation.",
    fix_immediate="Refresh 12_DEVOPS_REVIEW against Wave8.",
    fix_short="Auto-generate status from register.",
    fix_long="Single source of truth dashboard.",
    effort="0.5d",
    tests="N/A",
    acceptance="DevOps review matches compose/CI.",
    status="Open",
    refs="Wave8",
)
add(
    title="Root MVP_IMPLEMENTATION_PLAN / PERFORMANCE / UX reports contradict shipped Phase 3+",
    category="Documentation",
    subcategory="Stale reports",
    severity="Medium",
    priority="P2",
    module="Docs",
    feature="Root reports",
    files="MVP_IMPLEMENTATION_PLAN.md; PERFORMANCE_REPORT.md; UX_REVIEW.md",
    problem="Root plans still claim no gateway / CN missing while Phase 3 payments and notes exist; PERFORMANCE/UX dated July without supersession banner.",
    evidence="MVP plan vs payments app; report dates 2026-07",
    root_cause="Historical docs not bannered.",
    business="Stakeholder confusion.",
    technical="Doc debt.",
    customer="N/A",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Wrong roadmap decisions.",
    fix_immediate="Add Historical/Superseded banners pointing to docs/reviews.",
    fix_short="Archive root reports to docs/archive.",
    fix_long="Docs site with versions.",
    effort="0.5d",
    tests="N/A",
    acceptance="Stale root docs bannered.",
    status="Open",
    refs="BB-000051 residual; Wave8",
)
add(
    title="Mobile drawer stays open after navigation",
    category="UX",
    subcategory="Mobile",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="AppShell",
    files="web/src/layout/AppShell.tsx",
    problem="setMobileOpen(false) not called on NavLink click; drawer remains open after route change.",
    evidence="AppShell.tsx mobile drawer handlers",
    root_cause="Missing location effect.",
    business="Clumsy mobile UX.",
    technical="State leak.",
    customer="Frustration on phone.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Adoption friction.",
    fix_immediate="Close drawer on location change.",
    fix_short="Shared NavLink wrapper.",
    fix_long="Native app.",
    effort="0.25d",
    tests="RTL: nav click closes drawer.",
    acceptance="Drawer closes after navigate.",
    status="Open",
    refs="Wave8; BB-000179",
)
add(
    title="AppShell mobile menu IconButton missing aria-label",
    category="UX",
    subcategory="Accessibility",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="a11y",
    files="web/src/layout/AppShell.tsx",
    problem="Menu IconButton has no aria-label; nav sections lack aria-expanded.",
    evidence="AppShell.tsx ~L111-117",
    root_cause="Incomplete a11y pass.",
    business="Screen reader users blocked.",
    technical="a11y gap.",
    customer="Inaccessible nav.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="WCAG 4.1.2.",
    risk="Accessibility complaints.",
    fix_immediate="aria-label Open navigation; aria-expanded on collapsibles.",
    fix_short="axe CI on shell.",
    fix_long="Full a11y program BB-000110.",
    effort="0.5d",
    tests="axe critical=0 on AppShell.",
    acceptance="Labeled menu control.",
    status="Open",
    refs="BB-000110 residual; Wave8",
)
add(
    title="No skip-to-content link in SPA shell",
    category="UX",
    subcategory="Accessibility",
    severity="Low",
    priority="P3",
    module="Web",
    feature="a11y",
    files="web/src/layout/AppShell.tsx; web/index.html",
    problem="main landmark exists but no skip link.",
    evidence="AppShell main; no skip link in index/shell",
    root_cause="a11y backlog.",
    business="Keyboard UX weaker.",
    technical="WCAG 2.4.1.",
    customer="Keyboard users tab through nav every page.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="a11y.",
    risk="Audit fail.",
    fix_immediate="Add skip link targeting main.",
    fix_short="Focus styles audit.",
    fix_long="Design system a11y.",
    effort="0.25d",
    tests="Skip link present and focuses main.",
    acceptance="Skip link works.",
    status="Open",
    refs="Wave8",
)
add(
    title="fetchAllPages silent truncation after 50 pages presents incomplete data as complete",
    category="Performance",
    subcategory="Pagination",
    severity="Medium",
    priority="P2",
    module="Web",
    feature="Lists",
    files="web/src/api/resources.ts",
    problem="Cap reduced to 50 pages but UI only console.warns — users see incomplete masters/invoices as full set.",
    evidence="resources.ts ~L162-182",
    root_cause="Partial BB-000033 mitigation.",
    business="Wrong picks / missing invoices in UI.",
    technical="Silent data loss.",
    customer="Operational errors.",
    security="N/A",
    performance="Still heavy up to cap.",
    scalability="Fails at scale.",
    compliance="N/A",
    risk="Missed AR items.",
    fix_immediate="Surface blocking banner/error when capped.",
    fix_short="Server search + listPage only.",
    fix_long="Remove fetchAllPages for documents.",
    effort="1d",
    tests="Cap hit → user-visible error.",
    acceptance="Never silently truncate.",
    status="Open",
    refs="BB-000033 residual; Wave8",
)
add(
    title="Invoice editor loads all customers via fetchAllPages",
    category="Performance",
    subcategory="Editors",
    severity="High",
    priority="P1",
    module="Web",
    feature="New invoice",
    files="web/src/pages/NewInvoicePage.tsx; web/src/api/resources.ts",
    problem="NewInvoicePage loads all customers into memory for picker; returns pages load all completed invoices.",
    evidence="NewInvoicePage ~L176; SalesReturnsPage ~L43-46",
    root_cause="fetchAllPages default pattern.",
    business="Slow invoice create for larger MSMEs.",
    technical="Client memory blowup.",
    customer="UI freeze.",
    security="N/A",
    performance="High impact.",
    scalability="Blocks growth past few thousand parties.",
    compliance="N/A",
    risk="Unusable at target scale.",
    fix_immediate="Async search Autocomplete with server q=.",
    fix_short="Infinite query pickers everywhere.",
    fix_long="Virtualized combobox design system.",
    effort="3d",
    tests="Invoice page does not call fetchAll customers.",
    acceptance="Pickers page/search server-side.",
    status="Open",
    refs="BB-000033 residual; Wave8",
)
add(
    title=".env.production.example incomplete for payments/GSP live/LLM/Celery",
    category="Configuration",
    subcategory="Env docs",
    severity="Medium",
    priority="P2",
    module="Docs",
    feature="Env",
    files=".env.production.example; backend/.env.example",
    problem="Production example misses payment gateway, GSP_LIVE_*, LLM, CELERY vars; root vs backend examples diverge on DEBUG defaults.",
    evidence=".env.production.example vs features in code",
    root_cause="Docs lag features.",
    business="Misconfigured prod deploys.",
    technical="Missing knobs.",
    customer="Broken SMS/AI/payments.",
    security="Debug defaults confusion.",
    performance="N/A",
    scalability="N/A",
    compliance="Config management.",
    risk="Insecure/incomplete prod.",
    fix_immediate="Sync production example with ENV_CHECKLIST.",
    fix_short="Single generated env schema.",
    fix_long="Settings validation at boot listing missing keys.",
    effort="1d",
    tests="Boot checklist CI for required prod keys.",
    acceptance="Production example covers all shipped integrations.",
    status="Open",
    refs="Wave8",
)
add(
    title="Fernet/gateway secrets still SECRET_KEY-derived outside production",
    category="Security",
    subcategory="Secrets",
    severity="High",
    priority="P1",
    module="Core",
    feature="GSP/gateway crypto",
    files="backend/core/services/gsp_secrets.py; backend/config/settings.py",
    problem="Staging/dev still derive Fernet from SECRET_KEY; gateway shares helper — Scope C only forced GSP_FERNET_KEY in production.",
    evidence="gsp_secrets.py L14-21; settings L359-363",
    root_cause="Partial BB-000023 fix.",
    business="Staging secret rotation/leak decrypts stored gateway/GSP creds.",
    technical="Key coupling.",
    customer="Credential exposure.",
    security="High for staging with real keys.",
    performance="N/A",
    scalability="N/A",
    compliance="Secret separation.",
    risk="Staging→prod key reuse patterns.",
    fix_immediate="Require GSP_FERNET_KEY (+ separate gateway key) for staging.",
    fix_short="Per-purpose keys.",
    fix_long="KMS.",
    effort="1d",
    tests="Staging boot fails without dedicated Fernet.",
    acceptance="No SECRET_KEY-derived Fernet outside local DEBUG.",
    status="Open",
    refs="BB-000023 residual; Wave8",
)
add(
    title="DEBUG/SECRET fail-open residual when DJANGO_ENV=development on public hosts",
    category="Security",
    subcategory="Configuration",
    severity="High",
    priority="P1",
    module="Core",
    feature="Boot",
    files="backend/config/settings.py",
    problem="Explicit DJANGO_ENV=development with public ALLOWED_HOSTS still boots DEBUG default and weak secret — Scope C fail-closed only for production/staging/non-local unset.",
    evidence="settings.py L17-74",
    root_cause="Mislabeled env escape hatch.",
    business="Public DEBUG deploy.",
    technical="Stack traces / weak JWT.",
    customer="Data leak.",
    security="High.",
    performance="N/A",
    scalability="N/A",
    compliance="Hardening.",
    risk="Misconfig prod-as-dev.",
    fix_immediate="Refuse DEBUG on non-local hosts regardless of DJANGO_ENV label.",
    fix_short="settings_prod.py only path for images.",
    fix_long="Immutable prod config.",
    effort="1d",
    tests="Non-local host + development env + DEBUG=1 fails boot.",
    acceptance="Public hosts cannot run DEBUG.",
    status="Open",
    refs="BB-000001 residual; Wave8",
)
add(
    title="Login lockout still LocMem when REDIS_URL empty (multi-worker bypass)",
    category="Security",
    subcategory="Auth",
    severity="Medium",
    priority="P1",
    module="Accounts",
    feature="Lockout",
    files="backend/config/settings.py; backend/accounts/views.py",
    problem="REDIS_URL='' → LocMem; lockout ineffective across gunicorn workers — residual of BB-000029.",
    evidence="settings.py L240-254; login lockout uses cache",
    root_cause="Redis optional.",
    business="Credential stuffing across workers.",
    technical="Per-process counters.",
    customer="Account brute force.",
    security="High under multi-worker.",
    performance="N/A",
    scalability="Worse with more workers.",
    compliance="Auth hardening.",
    risk="Account takeover.",
    fix_immediate="Fail boot in prod/staging without Redis.",
    fix_short="Redis required in compose profiles prod.",
    fix_long="Edge WAF rate limits.",
    effort="0.5d",
    tests="Prod settings require Redis.",
    acceptance="No LocMem auth cache in prod.",
    status="Open",
    refs="BB-000029 residual; Wave8",
)
add(
    title="Register email enumeration still explicit",
    category="Security",
    subcategory="Privacy",
    severity="Low",
    priority="P3",
    module="Accounts",
    feature="Register",
    files="backend/accounts/serializers.py",
    problem="Explicit 'email already exists' enables account enumeration (known tradeoff).",
    evidence="Register serializer ~L15-27",
    root_cause="UX vs privacy tradeoff.",
    business="Attacker learns registered emails.",
    technical="Oracle.",
    customer="Privacy.",
    security="Low.",
    performance="N/A",
    scalability="N/A",
    compliance="DPDP minimize.",
    risk="Targeted phishing list.",
    fix_immediate="Generic response + verification email.",
    fix_short="Rate limit register.",
    fix_long="Magic-link only signup.",
    effort="3d",
    tests="Duplicate email same message as success path.",
    acceptance="No email oracle.",
    status="Open",
    refs="BUG-114; Wave8",
)
add(
    title="web/nginx.conf lacks security headers present on edge nginx",
    category="Security",
    subcategory="Headers",
    severity="Low",
    priority="P3",
    module="Web",
    feature="nginx",
    files="web/nginx.conf; nginx/default.conf",
    problem="Outer nginx has CSP/XFO; web container nginx has none — direct exposure skips headers.",
    evidence="Compare web/nginx.conf vs nginx/default.conf",
    root_cause="Defense only at edge.",
    business="Weaker if web port exposed.",
    technical="Header inconsistency.",
    customer="XSS impact higher.",
    security="Defense-in-depth.",
    performance="N/A",
    scalability="N/A",
    compliance="Header baseline.",
    risk="Mis-published web port.",
    fix_immediate="Mirror security headers in web/nginx.conf.",
    fix_short="Shared snippet.",
    fix_long="CDN headers.",
    effort="0.5d",
    tests="curl -I web:80 shows CSP.",
    acceptance="Same headers at web and edge.",
    status="Open",
    refs="Wave8",
)
add(
    title="No scripts/ automation for backup/uptime despite empty scripts folder expectations",
    category="DevOps",
    subcategory="Automation",
    severity="Medium",
    priority="P2",
    module="Ops",
    feature="Backups",
    files="scripts/; docs/pilot/RUNBOOKS.md",
    problem="Backup/uptime left to undocumented host ops; no compose backup service; scripts sparse.",
    evidence="No backup cron in compose; RUNBOOKS manual pg_dump",
    root_cause="Ops deferred (BB-000045).",
    business="No automated DR.",
    technical="Manual only.",
    customer="Data loss risk.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Backup controls.",
    risk="Unrecoverable pilot DB.",
    fix_immediate="Add backup.sh + cron compose service.",
    fix_short="S3 upload + restore drill CI.",
    fix_long="Managed PITR.",
    effort="3d",
    tests="Backup artifact produced in CI job.",
    acceptance="Daily backup job documented and runnable.",
    status="Open",
    refs="BB-000045 residual; Wave8",
)
add(
    title="Scope C marked BB-000004/011/047 Resolved but residual defects remain (meta)",
    category="Process",
    subcategory="Audit integrity",
    severity="High",
    priority="P1",
    module="Product",
    feature="Remediation process",
    files="docs/reviews/MASTER_ISSUE_REGISTER.md; docs/reviews/CHANGELOG.md",
    problem="Wave 7 closed register to zero Open; re-audit found incomplete remediations still in code (webhooks, purchase H9, observability). Closure overstated.",
    evidence="History: Wave7 zero Open; Wave8 code evidence for BB-000196+ residuals",
    root_cause="Status closed on partial mitigations without adversarial re-verify.",
    business="False production readiness signal.",
    technical="Audit process gap.",
    customer="Risk of launching on false green.",
    security="Process.",
    performance="N/A",
    scalability="N/A",
    compliance="Quality gate failure.",
    risk="Repeated false closure.",
    fix_immediate="Reopen residual parents with notes; require code evidence for Resolved.",
    fix_short="Definition of Done checklist per severity.",
    fix_long="Independent re-audit gate before GA.",
    effort="1d process",
    tests="Re-audit script / adversarial suite for P0.",
    acceptance="Resolved requires failing-test-then-pass evidence link.",
    status="Open",
    refs="Wave8 meta; BB-000004/011/047",
)
add(
    title="Production readiness checklist still unchecked for APM while BB-000047 Resolved",
    category="Documentation",
    subcategory="Inconsistency",
    severity="Low",
    priority="P3",
    module="Docs",
    feature="Prod readiness",
    files="docs/reviews/21_PRODUCTION_READINESS.md",
    problem="21_PRODUCTION_READINESS still lists deep health/Sentry/beat unchecked while register marked BB-000047 Resolved — split brain.",
    evidence="21_PRODUCTION_READINESS.md ~L30 vs register status",
    root_cause="Status vs checklist desync.",
    business="Unclear go/no-go.",
    technical="Doc inconsistency.",
    customer="N/A",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="N/A",
    risk="Wrong launch decision.",
    fix_immediate="Align checklist with Wave8 scores; reopen BB-000047 residual as BB-000218 family.",
    fix_short="Generate checklist from Open P0/P1.",
    fix_long="Automated readiness score.",
    effort="0.5d",
    tests="N/A",
    acceptance="No Resolved claim without checklist green.",
    status="Open",
    refs="Wave8; BB-000047",
)
add(
    title="Zod still absent — react-hook-form without schema resolvers",
    category="Frontend",
    subcategory="Validation",
    severity="High",
    priority="P1",
    module="Web",
    feature="Forms",
    files="web/package.json; web/src/pages/LoginPage.tsx; web/src/pages/RegisterPage.tsx",
    problem="No zod/@hookform/resolvers in package.json; auth/billing forms use required:true only — BB-000054 still open in practice.",
    evidence="package.json deps; Login/Register RHF",
    root_cause="Deferred frontend validation.",
    business="Bad data reaches API; weak password/GSTIN UX.",
    technical="Client validation debt.",
    customer="Cryptic 400s.",
    security="Weaker input hygiene.",
    performance="N/A",
    scalability="N/A",
    compliance="Data quality.",
    risk="Garbage masters.",
    fix_immediate="Add Zod for auth + invoice critical fields.",
    fix_short="Shared schemas with BE OpenAPI.",
    fix_long="Generated forms.",
    effort="3d",
    tests="Invalid GSTIN blocked client-side.",
    acceptance="Critical forms schema-validated.",
    status="Open",
    refs="BB-000054 STILL OPEN; Wave8",
)
add(
    title="JWT localStorage storage remains (httpOnly migration not done)",
    category="Security",
    subcategory="Auth",
    severity="High",
    priority="P1",
    module="Web",
    feature="Session",
    files="web/src/auth/session.ts",
    problem="Access+refresh still in localStorage — XSS exfiltrates full session. Deferred as roadmap but still Critical commercial risk.",
    evidence="session.ts L7-17",
    root_cause="SPA JWT pattern.",
    business="Account takeover via XSS.",
    technical="Token in JS-accessible storage.",
    customer="Full account compromise.",
    security="High.",
    performance="N/A",
    scalability="N/A",
    compliance="Auth best practice.",
    risk="Tenant takeover.",
    fix_immediate="CSP + XSS hardening; short access TTL.",
    fix_short="httpOnly cookie BFF.",
    fix_long="Session cookies + refresh rotation.",
    effort="5d",
    tests="Tokens not in localStorage in new auth mode.",
    acceptance="No JWT in localStorage for GA.",
    status="Open",
    refs="BB-000030 STILL OPEN; Wave8",
)

# Ensure count
assert len(ISSUES) >= 55, len(ISSUES)


def fmt_issue(n: int, d: dict) -> str:
    iid = f"BB-{n:06d}"
    return f"""
## {iid} — {d['title']}

| Field | Value |
|-------|-------|
| **Issue ID** | {iid} |
| **Title** | {d['title']} |
| **Category** | {d['category']} |
| **Subcategory** | {d['subcategory']} |
| **Severity** | {d['severity']} |
| **Priority** | {d['priority']} |
| **Module** | {d['module']} |
| **Feature** | {d['feature']} |
| **Affected Files** | {d['files']} |
| **Affected Classes** | See files |
| **Affected Functions** | See files |
| **Affected APIs** | See files / related endpoints |
| **Affected Database Tables** | See models in files |
| **Status** | {d['status']} |
| **Owner** | Unassigned |
| **Review Date** | {TODAY} |
| **Estimated Effort** | {d['effort']} |
| **Breaking Change** | Possibly — assess per fix |
| **Regression Risk** | Medium unless tests added |
| **Dependencies** | See Cross References |
| **Cross References** | {d['refs']} |
| **References** | Wave 8 re-audit {TODAY}; code evidence |

### Problem Description
{d['problem']}

### Evidence
{d['evidence']}

### Code Snippet
See affected files at `{TODAY}` tree.

### Root Cause
{d['root_cause']}

### Business Impact
{d['business']}

### Technical Impact
{d['technical']}

### Customer Impact
{d['customer']}

### Security Impact
{d['security']}

### Performance Impact
{d['performance']}

### Scalability Impact
{d['scalability']}

### Compliance Impact
{d['compliance']}

### Risk if ignored
{d['risk']}

### Steps to reproduce
1. Inspect affected files listed above.
2. Exercise the related API/UI path with a pilot company fixture.
3. Observe the failure mode described in Problem Description.

### Recommended Fix
{d['fix_short']}

### Immediate Fix
{d['fix_immediate']}

### Short-term Fix
{d['fix_short']}

### Long-term Refactor
{d['fix_long']}

### Alternative Solutions
Defer behind feature flag; or remove UI claim until fixed.

### Required Tests
{d['tests']}

### Acceptance Criteria
{d['acceptance']}

---
"""


RESIDUAL_REOPENS = {
    "BB-000004": """
### Re-audit (2026-08-03 Wave 8)
**Status → Reopened (Open).** Amount-only matching removed, but empty credentials still route to SandboxAdapter with trivial signature (`X-Sandbox-Signature: ok`). See **BB-000196**, **BB-000197**, **BB-000198**.
""",
    "BB-000011": """
### Re-audit (2026-08-03 Wave 8)
**Status → Partially Open.** Sales H9 has period block + GL repost; **purchase H9 still missing both**. See **BB-000199**.
""",
    "BB-000047": """
### Re-audit (2026-08-03 Wave 8)
**Status → Reopened (Open).** Deep health JSON improved, but celery probe is false-positive without workers; no Sentry/APM. See **BB-000218**.
""",
    "BB-000018": """
### Re-audit (2026-08-03 Wave 8)
**Residual Open.** Write flags exist, but journals/reports still HasCompany-only and FE RoleRoute gaps remain. See **BB-000200**, **BB-000201**, **BB-000209**.
""",
}


def reopen_parents(text: str) -> str:
    for iid, note in RESIDUAL_REOPENS.items():
        pattern = rf"(## {iid} —[\s\S]*?\|\s*\*\*Status\*\*\s*\|\s*)Resolved(\s*\|)"
        text, n = re.subn(pattern, r"\1Open\2", text, count=1)
        try:
            after_title = text.split(f"## {iid} —", 1)[1]
            block_only = after_title.split("## BB-", 1)[0]
        except IndexError:
            continue
        if "Re-audit (2026-08-03 Wave 8)" in block_only:
            continue
        parts = re.split(rf"(## {re.escape(iid)} —[^\n]*\n)", text, maxsplit=1)
        if len(parts) < 3:
            continue
        head, title, rest = parts[0], parts[1], parts[2]
        nxt = re.search(r"\n## BB-\d+", rest)
        if nxt:
            block, after = rest[: nxt.start()], rest[nxt.start() :]
        else:
            block, after = rest, ""
        if not block.endswith("\n"):
            block += "\n"
        text = head + title + block + note + after
    return text


def update_header_totals(text: str, new_issues: list, start_id: int) -> str:
    banner = (
        f"\n## Wave 8 re-audit ({TODAY})\n\n"
        f"Appended **{len(new_issues)}** new issues "
        f"`BB-{start_id:06d}` … `BB-{start_id + len(new_issues) - 1:06d}` "
        f"from independent code re-verification. Prior IDs unchanged. "
        f"Several Scope C Resolved items reopened with residual notes.\n"
    )
    if f"Wave 8 re-audit ({TODAY})" not in text:
        text = text.replace("## How to use\n", "## How to use\n" + banner + "\n", 1)
    return text


def rebuild_stats(existing_issues: list, new_issues: list, start_id: int) -> dict:
    all_issues = list(existing_issues)
    for i, d in enumerate(new_issues):
        all_issues.append(
            {
                "id": f"BB-{start_id + i:06d}",
                "title": d["title"],
                "severity": d["severity"],
                "priority": d["priority"],
                "category": d["category"],
                "module": d["module"],
                "effort": d["effort"],
                "status": d["status"],
            }
        )
    reopen_ids = set(RESIDUAL_REOPENS.keys())
    for item in all_issues:
        if item["id"] in reopen_ids:
            item["status"] = "Open"

    sev, pri, cat, mod, status = {}, {}, {}, {}, {}
    for item in all_issues:
        sev[item["severity"]] = sev.get(item["severity"], 0) + 1
        pri[item["priority"]] = pri.get(item["priority"], 0) + 1
        cat[item["category"]] = cat.get(item["category"], 0) + 1
        mod[item["module"]] = mod.get(item["module"], 0) + 1
        status[item["status"]] = status.get(item["status"], 0) + 1
    return {
        "total": len(all_issues),
        "severity": sev,
        "priority": pri,
        "category": cat,
        "module": mod,
        "status": status,
        "wave8_new": len(new_issues),
        "wave8_start": f"BB-{start_id:06d}",
        "wave8_end": f"BB-{start_id + len(new_issues) - 1:06d}",
        "audit_date": TODAY,
        "issues": all_issues,
    }


def patch_register_totals(text: str, stats: dict) -> str:
    sev = stats["severity"]
    pri = stats["priority"]
    total = stats["total"]
    new_totals = f"""## Totals (this register)

| Metric | Count |
|--------|------:|
| **Total issues** | {total} |
| Critical | {sev.get('Critical', 0)} |
| High | {sev.get('High', 0)} |
| Medium | {sev.get('Medium', 0)} |
| Low | {sev.get('Low', 0)} |

### By Priority

| Priority | Count |
|----------|------:|
| P0 | {pri.get('P0', 0)} |
| P1 | {pri.get('P1', 0)} |
| P2 | {pri.get('P2', 0)} |
| P3 | {pri.get('P3', 0)} |
"""
    cat_rows = "".join(
        f"| {c} | {n} |\n" for c, n in sorted(stats["category"].items(), key=lambda x: -x[1])
    )
    mod_rows = "".join(
        f"| {m} | {n} |\n" for m, n in sorted(stats["module"].items(), key=lambda x: -x[1])
    )
    new_block = (
        new_totals
        + "\n### By Category\n\n| Category | Count |\n|----------|------:|\n"
        + cat_rows
        + "\n### By Module\n\n| Module | Count |\n|--------|------:|\n"
        + mod_rows
    )
    pattern = r"## Totals \(this register\)[\s\S]*?(?=\n## BB-000001)"
    text2, n = re.subn(pattern, new_block + "\n", text, count=1)
    if n != 1:
        raise SystemExit(f"Failed to patch totals header (replacements={n})")
    return text2


def main():
    if not REGISTER.exists():
        raise SystemExit(f"Missing {REGISTER}")
    text = REGISTER.read_text(encoding="utf-8")
    if f"## BB-{START_ID:06d}" in text:
        raise SystemExit(f"BB-{START_ID:06d} already present — refuse double-append")

    existing = []
    if STATS.exists():
        existing = json.loads(STATS.read_text(encoding="utf-8")).get("issues", [])

    if len(existing) < 195:
        have = {x["id"] for x in existing}
        for i in range(1, 196):
            iid = f"BB-{i:06d}"
            if iid not in have:
                existing.append(
                    {
                        "id": iid,
                        "title": "(legacy)",
                        "severity": "Medium",
                        "priority": "P2",
                        "category": "Technical Debt",
                        "module": "Cross-cutting",
                        "effort": "?",
                        "status": "Resolved",
                    }
                )
        existing.sort(key=lambda x: x["id"])

    text = reopen_parents(text)
    text = update_header_totals(text, ISSUES, START_ID)
    body = "".join(fmt_issue(START_ID + i, d) for i, d in enumerate(ISSUES))
    if not text.endswith("\n"):
        text += "\n"
    text = text + "\n# Wave 8 appended issues\n" + body
    stats = rebuild_stats(existing[:195], ISSUES, START_ID)
    text = patch_register_totals(text, stats)
    REGISTER.write_text(text, encoding="utf-8")
    STATS.write_text(json.dumps(stats, indent=2), encoding="utf-8")
    print(f"Appended {len(ISSUES)} issues BB-{START_ID:06d}..BB-{START_ID+len(ISSUES)-1:06d}")
    print(
        "New by severity:",
        {k: sum(1 for d in ISSUES if d["severity"] == k) for k in ("Critical", "High", "Medium", "Low")},
    )
    print("Totals now:", stats["total"], stats["severity"])
    print("Status:", stats.get("status"))


if __name__ == "__main__":
    main()
