# -*- coding: utf-8 -*-
"""Wave 20 independent live-code pass — BB-000639+."""

ISSUES: list[dict] = []


def add(**kwargs):
    ISSUES.append(kwargs)


add(
    title="IRP SellerDtls.Gstin and e-Way fromGstin ignore invoice.company_gstin stamp",
    category="GST",
    subcategory="Multi-GSTIN IRP/e-Way",
    severity="Critical",
    priority="P0",
    module="Sales",
    feature="e-Invoice / e-Way seller identity",
    files="backend/sales/einvoice_payload.py build_einvoice_payload; backend/sales/eway_payload.py build_eway_payload_from_invoice build_eway_payload_from_challan; backend/sales/models.py SalesInvoice.company_gstin",
    problem="Wave 17 stamps invoice.company_gstin for branch GSTIN. IRP SellerDtls.Gstin and e-Way fromGstin/fromStateCode always use company.gstin / company.state / company.pincode / company.address. A branch invoice IRN is requested under the HO GSTIN. NIC/IRP will reject (GSTIN mismatch vs auth token) or issue an IRN under the wrong taxpayer. Distinct from GSTR blending (BB-000556): this corrupts the statutory IRN/e-way identity itself.",
    evidence="einvoice_payload.py SellerDtls Gstin: company.gstin; eway_payload.py fromGstin: company.gstin. No read of invoice.company_gstin or CompanyGstin.state/address.",
    root_cause="Stamp added to documents; payload builders never switched off primary Company row.",
    business="Multi-branch MSMEs cannot e-invoice/e-way from additional GSTINs.",
    technical="IRN/e-way ≠ document stamp ≠ GSTR.",
    customer="Branch dispatches blocked or filed under HO.",
    security="Wrong taxpayer identity on government documents.",
    performance="N/A",
    scalability="Blocks multi-GSTIN scale-out.",
    compliance="Rule 48(4) / e-way Rule 138 seller GSTIN must match the supplying GSTIN.",
    risk="Live GSP launch immediately files wrong GSTIN.",
    fix_immediate="Resolve seller party from invoice.company_gstin (fallback primary). Fail if stamp missing when >1 GSTIN.",
    fix_short="Stamp address/PIN/state on CompanyGstin; use on PDF/IRP/e-way/GSTR.",
    fix_long="Per-GSTIN filing identity aggregate.",
    effort="2d",
    tests="Invoice stamped with secondary GSTIN → SellerDtls.Gstin and fromGstin equal that GSTIN, not company.gstin.",
    acceptance="No IRP/e-way payload uses HO GSTIN when stamp is set.",
    refs="BB-000556; BB-000607; Wave 20",
)
add(
    title="Delivery challan e-way ignores transport_distance_km and hardcodes transDistance=0",
    category="GST",
    subcategory="e-Way challan",
    severity="High",
    priority="P1",
    module="Sales",
    feature="e-Way from challan",
    files="backend/sales/eway_payload.py validate_eway_from_challan build_eway_payload_from_challan; backend/sales/models.py DeliveryChallan.transport_distance_km",
    problem="DeliveryChallan has transport_distance_km. validate_eway_from_challan passes distance_km=None (skips range check). build_eway_payload_from_challan sets transDistance to literal '0'. NIC validity period is distance-banded; 0 km yields wrong/invalid e-way or rejection. Invoice path reads invoice.transport_distance_km; challan path does not.",
    evidence="eway_payload.py validate distance_km=None; build return transDistance: '0'. Model field exists at DeliveryChallan.transport_distance_km.",
    root_cause="Challan builder copied invoice builder then stubbed distance.",
    business="Job-work/stock-transfer challans cannot obtain valid e-way.",
    technical="Stored distance unused.",
    customer="Warehouse dispatch compliance failure.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="e-Way validity depends on distance.",
    risk="Every challan e-way is legally defective.",
    fix_immediate="Pass challan.transport_distance_km into validate + payload; require >0 when vehicleNo set.",
    fix_short="Part-B update API for distance/vehicle.",
    fix_long="Transporter ID / multi-vehicle support.",
    effort="0.5d",
    tests="Challan with transport_distance_km=120 → payload transDistance '120'.",
    acceptance="Challan distance never silently 0 when field set.",
    refs="Wave 20; BB-000150 residual",
)
add(
    title="e-Way toGstin empty for URP and fromPincode becomes 0 when PIN is non-numeric",
    category="GST",
    subcategory="e-Way party fields",
    severity="High",
    priority="P1",
    module="Sales",
    feature="e-Way URP/PIN",
    files="backend/sales/eway_payload.py build_eway_payload_from_invoice build_eway_payload_from_challan _validate_customer_party",
    problem="URP/B2C customers are allowed without GSTIN (BB-000430). Payload sets toGstin to customer.gstin (empty string). NIC schema requires 'URP' for unregistered. fromPincode uses int(company.pincode) if isdigit() else 0 — spaces, '400 001', or empty become 0, which NIC rejects. Buyer PIN is required; seller PIN is not.",
    evidence="toGstin: customer.gstin; fromPincode: int(...) if isdigit else 0.",
    root_cause="No NIC enum normalization; asymmetric PIN validation vs einvoice_payload.",
    business="B2C e-way and messy PIN masters fail at GSP.",
    technical="Invoice e-invoice path validates 6-digit PIN; e-way does not for seller.",
    customer="Cash-and-carry / URP dispatch blocked.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="NIC e-way schema.",
    risk="All URP e-ways invalid.",
    fix_immediate="toGstin='URP' when blank; require 6-digit from/to PIN; never emit 0.",
    fix_short="Share party-normalizer with einvoice_payload.",
    fix_long="Address master with validated PIN directory.",
    effort="1d",
    tests="URP customer → toGstin URP; company.pincode '400001 ' → 400001 not 0.",
    acceptance="No empty toGstin or zero pincode in payload.",
    refs="Wave 20; BB-000430 residual",
)
add(
    title="e-Way payload always subSupplyType=1 and transMode=1 (road) for invoices and challans",
    category="GST",
    subcategory="e-Way supply/transport type",
    severity="High",
    priority="P1",
    module="Sales",
    feature="e-Way taxonomy",
    files="backend/sales/eway_payload.py; backend/sales/models.py DeliveryChallan SalesInvoice",
    problem="Every payload emits supplyType O, subSupplyType 1 (supply), transMode 1 (road). Delivery challans for job work (8), SKD/CKD (4), own use (5), exhibition, or line sales are misclassified. No rail/air/ship/in-transit transporter-ID-only (transMode 4) path. Wrong sub-type is a NIC reject or a false statutory document.",
    evidence="Hardcoded keys in both build_eway_payload_from_invoice and _from_challan.",
    root_cause="Sandbox happy-path only.",
    business="Job-work and multi-modal MSMEs cannot use product e-way.",
    technical="No fields for subSupplyType/transMode on documents.",
    customer="Must generate e-way outside BizBoard.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Rule 138 sub-supply types.",
    risk="100% of non-sale challan e-ways wrong.",
    fix_immediate="Add sub_supply_type + trans_mode on invoice/challan; default invoice=1/road; challan required explicit.",
    fix_short="UI + validation matrix.",
    fix_long="E-way wizard with Part-A/B.",
    effort="2d",
    tests="Challan subSupplyType=8 appears in payload; invoice default remains 1.",
    acceptance="No silent job-work-as-supply.",
    refs="Wave 20",
)
add(
    title="file_upload_path interpolates raw filename — cross-tenant overwrite inside MEDIA_ROOT",
    category="Security",
    subcategory="Path traversal / tenant isolation",
    severity="Critical",
    priority="P0",
    module="Core",
    feature="FileAsset storage",
    files="backend/core/models.py file_upload_path; backend/core/services/files.py store_upload store_bytes",
    problem="upload_to returns f'company_{id}/{kind}/{filename}' with the client-supplied name. Django FileSystemStorage safe_join blocks escape of MEDIA_ROOT but not escape of the company prefix. A name like '../../company_2/logo/x.png' or 'foo/../../../company_2/invoice_pdf/a.pdf' (after normpath) can overwrite another tenant's object. original_name is also stored unsanitized for download headers (header injection).",
    evidence="core/models.py file_upload_path; store_upload passes uploaded_file through unchanged.",
    root_cause="Assumed Django sanitizes full upload_to paths per tenant.",
    business="Tenant A replaces tenant B logo/PDF.",
    technical="Shared MEDIA_ROOT without object-store keys.",
    customer="Wrong invoices/logos served; data integrity incident.",
    security="Cross-tenant write. Content-Disposition injection via original_name.",
    performance="N/A",
    scalability="Local disk layout is not multi-tenant safe.",
    compliance="Multi-tenant isolation failure.",
    risk="Any authenticated uploader (IMPORT/ATTACHMENT) can attack siblings.",
    fix_immediate="basename + get_valid_filename; UUID object key; reject '..' and separators; strip original_name to basename.",
    fix_short="S3/minio keys company_id/uuid; signed download only.",
    fix_long="Per-tenant buckets.",
    effort="1d",
    tests="Upload name '../../company_999/logo/x.png' stores under caller company only; no file at company_999.",
    acceptance="Tenant prefix immutable; original_name header-safe.",
    refs="Wave 20; BB-000631 related",
)
add(
    title="FileService.store_bytes bypasses MIME, size, and ClamAV validation",
    category="Security",
    subcategory="Upload validation bypass",
    severity="High",
    priority="P1",
    module="Core",
    feature="store_bytes",
    files="backend/core/services/files.py store_bytes store_upload validate_upload",
    problem="store_upload calls validate_upload (size, MIME sniff, ClamAV). store_bytes writes ContentFile directly with caller-controlled filename and content_type. PDF generation, imports, and any internal caller can persist unsanned arbitrary bytes. If any code path exposes store_bytes to request data, validation is fully skipped.",
    evidence="store_bytes creates FileAsset without validate_upload / _clamav_scan.",
    root_cause="Internal helper assumed trusted; no single ingest gate.",
    business="Malware in 'trusted' PDFs/exports.",
    technical="Two ingest paths, one unguarded.",
    customer="Shared MSME PCs download infected invoice PDF.",
    security="AV bypass; MIME spoof on generated assets.",
    performance="N/A",
    scalability="N/A",
    compliance="If ClamAV is a control, it is incomplete.",
    risk="Control theater — scans only browser uploads.",
    fix_immediate="Route store_bytes through validate_upload on a BytesIO wrapper; cap size.",
    fix_short="Single ingest API.",
    fix_long="Async scan + quarantine status on FileAsset.",
    effort="0.5d",
    tests="store_bytes of exe-disguised-as-pdf rejected when kind=INVOICE_PDF.",
    acceptance="No FileAsset create without validation.",
    refs="Wave 20; BB-000631",
)
add(
    title="UTR duplicate detection only covers 90 days — same UTR can post twice after the window",
    category="Accounting",
    subcategory="Payment uniqueness",
    severity="High",
    priority="P1",
    module="Payments",
    feature="UTR duplicate check",
    files="backend/payments/services.py _check_utr_duplicate create_receipt create_supplier_payment",
    problem="Bank UTRs are globally unique for a payment. Check filters receipt_date/payment_date >= today-90 and status POSTED. After 91 days the same UTR posts a second receipt and a second GL cash/bank debit. warn_utr_duplicate can also be disabled by callers. No unique constraint on (company, utr).",
    evidence="_check_utr_duplicate since = localdate()-90 days; qs filter receipt_date__gte=since.",
    root_cause="Soft warning window instead of durable uniqueness.",
    business="Double cash, double AR relief if allocated.",
    technical="Books ≠ bank after year-end cleanup/re-entry.",
    customer="Reconciliation breaks; possible fraud.",
    security="Replay of old UTR as new receipt.",
    performance="N/A",
    scalability="N/A",
    compliance="Audit trail of bank refs.",
    risk="Year-end Tally/bank re-import duplicates cash.",
    fix_immediate="Unique (company, normalized_utr) where utr!=''; check all history.",
    fix_short="Dedupe UI with override + owner reason.",
    fix_long="Bank-statement-driven receipts only.",
    effort="1d",
    tests="Same UTR 100 days later → rejected.",
    acceptance="No second posted receipt with same UTR per company.",
    refs="Wave 20",
)
add(
    title="DocumentNumberService._max_existing_seq full-scans all numbers in Python on every allocate",
    category="Performance",
    subcategory="Document sequencing",
    severity="High",
    priority="P1",
    module="Core",
    feature="DocumentSeries",
    files="backend/core/services/document_numbers.py _max_existing_seq next_number sync_next peek",
    problem="Every next_number() calls sync_next then _max_existing_seq which values_list('number', flat=True) for the entire doc type and parses suffixes in Python. Invoice complete, CN complete, receipts, journals all hit this under row locks. At 100k invoices this is a table scan + lock hold on DocumentSeries per bill. Also races with FY-less unique(company, number) (BB-000570 class).",
    evidence="for num in qs.values_list('number', flat=True): regex parse. Called from next_number inside select_for_update.",
    root_cause="Defensive sync against manual/imported numbers without a DB max-seq index.",
    business="Billing latency and lock contention at MSME peak hours.",
    technical="O(n) in the hottest write path.",
    customer="Checkout/POS hangs.",
    security="N/A",
    performance="Linear scan per number.",
    scalability="Hard stop well before 10k-tenant shared DB.",
    compliance="N/A",
    risk="Pilot OK; growth melts Complete.",
    fix_immediate="Trust series.next_number; repair job for imports; regex index optional.",
    fix_short="SQL max(substring) for prefix; cache.",
    fix_long="FY-partitioned sequences (BB-000570).",
    effort="1d",
    tests="Allocate 1k numbers without scanning prior rows (query count assertion).",
    acceptance="next_number does not SELECT all historical numbers.",
    refs="Wave 20; BB-000570",
)
add(
    title="Credit/debit notes have no e-invoice builder — DocDtls.Typ is always INV; CN IRN impossible",
    category="GST",
    subcategory="e-Invoice credit notes",
    severity="Critical",
    priority="P0",
    module="Sales",
    feature="CN/DN IRN",
    files="backend/sales/einvoice_payload.py; backend/sales/einvoice_eway_actions.py; backend/sales/notes_services.py; backend/sales/models.py SalesCreditNote SalesDebitNote",
    problem="e-Invoice applicable taxpayers must IRN credit/debit notes (Typ CRN/DBN) referencing the original IRN. BizBoard only builds INV payloads from SalesInvoice. Notes services complete CNs without prepare/submit-einvoice actions. Cancelling a CN does not cancel/amend IRN. Post-sale returns and price adjustments cannot be reported on IRP.",
    evidence="build_einvoice_payload(invoice: SalesInvoice) only; DocDtls.Typ hardcoded INV; no CN mixin actions on note viewsets.",
    root_cause="Phase-1 notes shipped without IRP parity.",
    business="e-invoicing MSMEs cannot issue statutory CNs in-product.",
    technical="GSTR CDNR vs IRP mismatch.",
    customer="Must use NIC portal for every return/CN.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Rule 48(4) applies to notes.",
    risk="Unlaunchable for e-invoice-mandatory dealers (turnover threshold).",
    fix_immediate="build_einvoice_payload_from_note with Typ CRN/DBN + PrecDocDtls original IRN/number/date; Owner submit actions.",
    fix_short="Block CN complete when source has IRN until note IRN queued (or explicit offline ack).",
    fix_long="Full IRN lifecycle for notes + cancel.",
    effort="4d",
    tests="CN against IRN invoice produces Typ=CRN and PrecDocDtls.Irn=source.irn.",
    acceptance="e-invoice dealers can IRN a CN in-app.",
    refs="Wave 20; BB-000624",
)
add(
    title="Credit note complete is capped by invoice AR outstanding — paid invoices cannot be credited",
    category="Accounting",
    subcategory="Credit note eligibility",
    severity="Critical",
    priority="P0",
    module="Sales",
    feature="complete_credit_note",
    files="backend/sales/notes_services.py complete_credit_note; backend/ledgers/services.py sales_invoice_outstanding",
    problem="max_cn = LedgerService.sales_invoice_outstanding(inv). If the invoice is fully paid, outstanding is 0 and any CN is rejected. GST/accounting CNs for returns, rate difference, and post-sale discount are routinely issued after payment; cash is then refunded or left unallocated. BizBoard conflates AR open balance with maximum creditable invoice value. Auto-CN from sales return also fails when the bill is paid. Distinct from BB-000043 return/CN double-AR guard.",
    evidence="notes_services.py complete_credit_note: if note.grand_total > max_cn raise exceeds invoice outstanding.",
    root_cause="Used outstanding as a cheap over-credit guard instead of invoiced_value - prior_notes.",
    business="Cannot process returns/discounts on paid bills — core MSME flow.",
    technical="AR/CN/receipt state machine wrong.",
    customer="POS + UPI prepaid invoices cannot be returned in-system.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="CN must be issuable independent of collection status.",
    risk="Every prepaid/GST-paid invoice return is a support escalations + books workaround.",
    fix_immediate="Cap against original grand_total (or taxable+tax) minus completed CNs + DNs; allow negative outstanding (prepayment) after CN; refund/unallocate flow.",
    fix_short="Return + CN + refund wizard.",
    fix_long="Open item ledger with CN as originating document.",
    effort="2d",
    tests="Fully paid invoice + CN for full value succeeds; AR goes negative or receipt unallocated; second CN blocked at invoiced value.",
    acceptance="Paid invoices are creditable up to net invoiced value.",
    refs="Wave 20; BB-000043",
)
add(
    title="Credit note totals recompute intra/inter from live customer state and force additional_charges=0",
    category="GST",
    subcategory="Credit note tax basis",
    severity="High",
    priority="P1",
    module="Sales",
    feature="set_credit_note_items",
    files="backend/sales/notes_services.py set_credit_note_items complete_credit_note; backend/core/services/place_of_supply.py",
    problem="CN line taxes use party_intra_state(company, customer.state, customer.gstin) at edit time, not the source invoice's place of supply / tax split / company_gstin stamp. If the customer master state is edited after invoicing, the CN flips CGST+SGST vs IGST vs original. additional_charges is hardcoded Decimal('0'), so freight/packing on the invoice cannot be credited in the header charge channel. POS assert on complete also uses live customer, not invoice.filing_place_of_supply.",
    evidence="set_credit_note_items intra_state=party_intra_state(... customer.state ...); additional_charges=Decimal('0').",
    root_cause="Notes treated as independent drafts, not amendments of a frozen supply.",
    business="Wrong CDNR tax; uncreditable charges.",
    technical="Document amendment ≠ master snapshot.",
    customer="CA rejects GSTR-1 CDNR vs original B2B.",
    security="N/A",
    performance="N/A",
    scalability="N/A",
    compliance="Note must reverse the original supply's tax character.",
    risk="Any master-data edit silently corrupts open CNs.",
    fix_immediate="Freeze POS/tax split/GSTIN from source invoice; allow charging credit of invoice.additional_charges.",
    fix_short="CN from invoice clones lines + charges + POS.",
    fix_long="Amendment engine shared with DN/purchase notes.",
    effort="2d",
    tests="Invoice IGST; change customer.state to intra; CN still IGST. CN can credit invoice additional_charges.",
    acceptance="CN tax character matches source invoice, not live master.",
    refs="Wave 20; BB-000638 related",
)
