# Generated by Django 5.2.16 on 2026-07-25 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staff_financial_reports_default_false'),
        ('core', '0001_initial'),
        ('imports', '0002_purchase_bill_import'),
        ('masters', '0002_concurrency_and_uniqueness_batch2'),
        ('purchases', '0004_perf_indexes_batch6'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['company', 'status', 'created_at'], name='imports_imp_company_41ae64_idx'),
        ),
    ]
