# Generated by Django 5.2.16 on 2026-08-20 17:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_sprint_d_billing_override'),
        ('imports', '0003_perf_indexes_batch6'),
        ('masters', '0007_expensecategory_paymentmode'),
        ('sales', '0031_tax12_cess_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='clarifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='importjob',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.customer'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='kind',
            field=models.CharField(choices=[('CUSTOMERS', 'Customers'), ('SUPPLIERS', 'Suppliers'), ('PRODUCTS', 'Products'), ('OPENING_STOCK', 'Opening Stock'), ('PURCHASE_BILL', 'Purchase Bill'), ('SALES_BILL', 'Sales Bill')], max_length=16),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('EXTRACTING', 'Extracting'), ('NEEDS_CLARIFICATION', 'Needs Clarification'), ('PREVIEWED', 'Previewed'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
        migrations.CreateModel(
            name='SupplierBillTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gstin', models.CharField(db_index=True, max_length=15)),
                ('party_name', models.CharField(blank=True, max_length=255)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('line_total_formula', models.CharField(choices=[('SIMPLE', 'Simple'), ('CASE_UNITS_PLUS_LOOSE', 'Case Units Plus Loose')], default='SIMPLE', max_length=24)),
                ('tax_calculation_type', models.CharField(choices=[('EXCLUSIVE', 'Exclusive'), ('INCLUSIVE', 'Inclusive'), ('HEADER_LEVEL', 'Header Level')], default='EXCLUSIVE', max_length=16)),
                ('rounding_tolerance', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=6)),
                ('column_signature', models.JSONField(blank=True, default=list)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.AddField(
            model_name='importjob',
            name='bill_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='imports.supplierbilltemplate'),
        ),
        migrations.AddConstraint(
            model_name='supplierbilltemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('gstin', ''), _negated=True), fields=('company', 'gstin'), name='uniq_bill_template_company_gstin'),
        ),
    ]
