# Generated by Django 5.2.17 on 2026-08-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_column_mappings_voided_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='extra_sheets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importjob',
            name='file_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
