# Generated by Django 5.2.17 on 2026-08-29 08:12

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_importjob_cf_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='errors',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='extra_sheets',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='preview',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
