# Generated by Django 5.2.16 on 2026-07-25 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentallocation',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.customerreceipt'),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='supplier_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.supplierpayment'),
        ),
    ]
