# Generated by Django 5.2.16 on 2026-08-02 11:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_phase3_payments_cash_ops'),
        ('masters', '0003_phase2_gst_returns_readiness'),
        ('payments', '0002_concurrency_and_uniqueness_batch2'),
        ('sales', '0011_phase2_gap_line_hsn_uqc_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PREVIEW', 'Preview'), ('COMMITTED', 'Committed'), ('VOID', 'Void')], default='PREVIEW', max_length=16)),
                ('preset', models.CharField(blank=True, default='generic', max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('narration', models.CharField(blank=True, max_length=512)),
                ('utr', models.CharField(blank=True, db_index=True, max_length=64)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('SUGGESTED', 'Suggested'), ('MATCHED', 'Matched'), ('IGNORED', 'Ignored')], default='UNMATCHED', max_length=16)),
                ('line_hash', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['txn_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GatewayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=32)),
                ('provider_payment_id', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allow_partial', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='razorpay', max_length=32)),
                ('provider_link_id', models.CharField(blank=True, max_length=128)),
                ('provider_short_url', models.URLField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-matched_at'],
            },
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('GATEWAY', 'Gateway'), ('BANK_IMPORT', 'Bank Import'), ('PAYMENT_LINK', 'Payment Link')], default='MANUAL', max_length=16),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='utr',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('GATEWAY', 'Gateway'), ('BANK_IMPORT', 'Bank Import'), ('PAYMENT_LINK', 'Payment Link')], default='MANUAL', max_length=16),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='utr',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('account_number_masked', models.CharField(blank=True, max_length=32)),
                ('ifsc', models.CharField(blank=True, max_length=16)),
                ('account_type', models.CharField(choices=[('CURRENT', 'Current'), ('SAVINGS', 'Savings'), ('CASH_BOX', 'Cash Box')], default='CURRENT', max_length=16)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('opening_as_of', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='payments.bankaccount'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='payments.bankaccount'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['company', 'utr'], name='payments_su_company_5b14dc_idx'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='payments.bankaccount'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payments.bankstatement'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatewaypayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='gatewaypayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatewaypayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='gateway_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='payments.gatewaypayment'),
        ),
        migrations.AddIndex(
            model_name='customerreceipt',
            index=models.Index(fields=['company', 'utr'], name='payments_cu_company_ad093a_idx'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', to='masters.customer'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='paid_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.customerreceipt'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', to='sales.salesinvoice'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatewaypayment',
            name='payment_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_payments', to='payments.paymentlink'),
        ),
        migrations.AddField(
            model_name='reconmatch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='reconmatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconmatch',
            name='line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recon_match', to='payments.bankstatementline'),
        ),
        migrations.AddField(
            model_name='reconmatch',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconmatch',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recon_matches', to='payments.customerreceipt'),
        ),
        migrations.AddField(
            model_name='reconmatch',
            name='supplier_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recon_matches', to='payments.supplierpayment'),
        ),
        migrations.AddField(
            model_name='reconmatch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['company', 'is_active'], name='payments_ba_company_64ce10_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['company', 'match_status', 'txn_date'], name='payments_ba_company_00b322_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['company', 'status'], name='payments_pa_company_241020_idx'),
        ),
        migrations.AddConstraint(
            model_name='gatewaypayment',
            constraint=models.UniqueConstraint(fields=('company', 'provider', 'provider_payment_id'), name='uniq_gateway_payment_per_provider'),
        ),
    ]
