# Generated by Django 5.2.16 on 2026-08-02 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_otp_hash'),
        ('payments', '0003_phase3_payments_cash_ops'),
        ('purchases', '0011_purchaseinvoice_cost_center'),
        ('sales', '0014_salesinvoice_cost_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('receipt__isnull', False), ('supplier_payment__isnull', True)), models.Q(('receipt__isnull', True), ('supplier_payment__isnull', False)), _connector='OR'), name='alloc_xor_receipt_or_supplier_payment'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purchase_invoice__isnull', True), ('sales_invoice__isnull', False)), models.Q(('purchase_invoice__isnull', False), ('sales_invoice__isnull', True)), _connector='OR'), name='alloc_xor_sales_or_purchase_invoice'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt__isnull', False), ('sales_invoice__isnull', False)), fields=('receipt', 'sales_invoice'), name='uniq_alloc_receipt_sales_invoice'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('purchase_invoice__isnull', False), ('supplier_payment__isnull', False)), fields=('supplier_payment', 'purchase_invoice'), name='uniq_alloc_supplier_payment_purchase_invoice'),
        ),
    ]
