# Generated by Django 5.2.16 on 2026-08-03 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_wave2_capability_defaults_false'),
        ('masters', '0005_wave4_tenancy_rbac_constraints'),
        ('payments', '0005_wave4_tenancy_rbac_constraints'),
        ('sales', '0019_wave2_manual_irn_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentlink',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_link_id', ''), _negated=True), fields=('provider', 'provider_link_id'), name='uniq_payment_link_provider_link_id'),
        ),
    ]
