# Generated by Django 5.2.16 on 2026-08-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_wave14_receipt_refund_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerreceipt',
            new_name='payments_cu_company_cc6683_idx',
            old_name='payments_cu_company_status_idx',
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=16),
        ),
    ]
