# Generated by Django 5.2.16 on 2026-08-05 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_sprint3_fifo_gstin_series'),
        ('payments', '0009_sprint2_utr_unique'),
        ('purchases', '0018_sprint2_itc_rcm_cess'),
        ('sales', '0028_partial_closures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentallocation',
            name='uniq_alloc_receipt_sales_invoice',
        ),
        migrations.RemoveConstraint(
            model_name='paymentallocation',
            name='uniq_alloc_supplier_payment_purchase_invoice',
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Posted'), ('REFUNDED', 'Refunded'), ('VOIDED', 'Voided')], db_index=True, default='POSTED', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt__isnull', False), ('reversed_at__isnull', True), ('sales_invoice__isnull', False)), fields=('receipt', 'sales_invoice'), name='uniq_alloc_receipt_sales_invoice'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('purchase_invoice__isnull', False), ('reversed_at__isnull', True), ('supplier_payment__isnull', False)), fields=('supplier_payment', 'purchase_invoice'), name='uniq_alloc_supplier_payment_purchase_invoice'),
        ),
    ]
