# Generated by Django 5.2.16 on 2026-08-05 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_sprint3_fifo_gstin_series'),
        ('masters', '0006_wave17a_taxpayer_gstin_stamp'),
        ('payments', '0010_partial_closures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerreceipt',
            name='uniq_receipt_utr_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='supplierpayment',
            name='uniq_supplier_payment_utr_per_company',
        ),
        migrations.AddConstraint(
            model_name='customerreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('utr', ''), _negated=True), models.Q(('status', 'VOIDED'), _negated=True)), fields=('company', 'utr'), name='uniq_receipt_utr_per_company'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('utr', ''), _negated=True), models.Q(('status', 'VOIDED'), _negated=True)), fields=('company', 'utr'), name='uniq_supplier_payment_utr_per_company'),
        ),
    ]
