# Generated by Django 5.2.17 on 2026-09-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_refund_outbox_amount_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaypayment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CAPTURED', 'Captured'), ('CAPTURED_PENDING_BOOKS', 'Captured Pending Books'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='CREATED', max_length=32),
        ),
        migrations.AlterField(
            model_name='gatewayrefundoutbox',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16),
        ),
    ]
