# Generated by Django 5.2.17 on 2026-09-02 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_one_primary_gstin'),
        ('payments', '0022_alter_gatewaypayment_status_and_more'),
        ('purchases', '0027_credit_note_additional_charges'),
        ('sales', '0043_quotation_so_commercial_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gatewayrefundoutbox',
            name='uniq_refund_outbox_per_payment_amount',
        ),
        migrations.AddConstraint(
            model_name='gatewayrefundoutbox',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('gateway_payment', 'idempotency_key'), name='uniq_refund_outbox_per_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='gatewayrefundoutbox',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', '')), fields=('gateway_payment', 'amount'), name='uniq_refund_outbox_per_payment_amount'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='alloc_amount_positive'),
        ),
    ]
