# Generated by Django 5.2.17 on 2026-09-03 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_company_require_open_period_for_posting'),
        ('masters', '0014_seed_hsn_rate_catalog'),
        ('payments', '0023_remove_gatewayrefundoutbox_uniq_refund_outbox_per_payment_amount_and_more'),
        ('sales', '0044_alter_deliverychallan_round_off_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dunningreminder',
            name='uniq_dunning_invoice_per_day',
        ),
        migrations.AddConstraint(
            model_name='dunningreminder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SKIPPED'), _negated=True), fields=('invoice', 'sent_on'), name='uniq_dunning_invoice_per_day'),
        ),
    ]
