# Generated by Django 5.2.17 on 2026-09-04 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_company_require_open_period_for_posting'),
        ('payments', '0024_remove_dunningreminder_uniq_dunning_invoice_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedup_key', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='payments_pr_created_510fc8_idx')],
            },
        ),
    ]
