# Generated by Django 5.2.17 on 2026-09-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_processedwebhookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedwebhookevent',
            name='dedup_key',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
