# Generated by Django 5.2.17 on 2026-09-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0026_alter_processedwebhookevent_dedup_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="dunningreminder",
            name="last_attempt_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
