# Generated by Django 5.2.17 on 2026-09-21 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_telegram_notifications'),
        ('payments', '0028_payeememory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreceipt',
            name='cheque_bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='cheque_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_receipts', to='core.fileasset'),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='cheque_status',
            field=models.CharField(blank=True, choices=[('PENDING_CLEARANCE', 'Pending Clearance'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_supplier_payments', to='core.fileasset'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_status',
            field=models.CharField(blank=True, choices=[('PENDING_CLEARANCE', 'Pending Clearance'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'Upi'), ('BANK', 'Bank'), ('CARD', 'Card'), ('CREDIT', 'Credit'), ('CHEQUE', 'Cheque')], default='CASH', max_length=8),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'Upi'), ('BANK', 'Bank'), ('CARD', 'Card'), ('CREDIT', 'Credit'), ('CHEQUE', 'Cheque')], default='CASH', max_length=8),
        ),
    ]
