# Generated by Django 5.2.17 on 2026-09-21 17:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_cheque_mode_and_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreceipt',
            name='settlement_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
