# Generated by Django 5.2.17 on 2026-10-04 17:55
#
# EXPAND_CONTRACT_OK: BlockedCreditRule was created by planwave 0001 in this same release, so
# no deployed code reads or writes its company column yet. Dropping it here (the rules are
# global, not per tenant) leaves no old reader to break during a rolling deploy.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planwave', '0001_planwave_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedcreditrule',
            name='company',
        ),
    ]
