# Generated by Django 5.2.17 on 2026-08-29 17:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payslip_company_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='employee',
            name='da',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
