# Generated by Django 5.2.17 on 2026-08-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_employee_basic_da'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='paid_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='period_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
