# Generated by Django 5.2.17 on 2026-09-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payslip_paid_days_payslip_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tax_regime',
            field=models.CharField(choices=[('NEW', 'New regime (default)'), ('OLD', 'Old regime')], default='NEW', max_length=4),
        ),
        migrations.AddField(
            model_name='payslip',
            name='edli_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pf_admin_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pf_employer_epf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pf_employer_eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
