# Generated by Django 5.2.17 on 2026-10-04 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_cash_shift_and_depreciation_catchup'),
        ('accounts', '0059_user_session_version'),
        ('payroll', '0009_employee_tax_regime_payslip_edli_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrun',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_runs', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='payrun',
            name='pay_from_cash',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EarningDeductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ADVANCE', 'Advance'), ('ARREAR', 'Arrear'), ('BONUS', 'Bonus')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('pay_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.payslip')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
