# Generated by Django 5.2.16 on 2026-08-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_phase6_ai_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybusinesssummary',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
