# Generated by Django 5.2.16 on 2026-08-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0002_email_sent_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttentionRowState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dedupe_key", models.CharField(db_index=True, max_length=191)),
                ("first_seen", models.DateTimeField()),
                ("snooze_until", models.DateTimeField(blank=True, null=True)),
                ("snooze_reason", models.TextField(blank=True, default="")),
                ("dismissed", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="attentionrowstate",
            constraint=models.UniqueConstraint(
                fields=("company", "dedupe_key"),
                name="uniq_attention_row_state_per_company",
            ),
        ),
        migrations.AddIndex(
            model_name="attentionrowstate",
            index=models.Index(fields=["company", "snooze_until"], name="insights_at_company_snooze_idx"),
        ),
    ]
