# Generated by Django 5.2.17 on 2026-09-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0005_alter_shopfloorevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopfloorevent',
            name='event',
            field=models.CharField(choices=[('invoice_complete', 'Invoice Complete'), ('pos_line_added', 'Pos Line Added'), ('offline_enqueue', 'Offline Enqueue'), ('offline_flush_fail', 'Offline Flush Fail'), ('complete_duration_ms', 'Complete Duration Ms'), ('time_to_first_invoice_ms', 'Time To First Invoice Ms'), ('allocation_reconciled', 'Allocation Reconciled'), ('period_closed', 'Period Closed')], db_index=True, max_length=40),
        ),
    ]
