# Generated by Django 5.2.17 on 2026-09-26 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_roadmap_items'),
        ('support', '0001_growth_os'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTicketShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ticket_id', models.PositiveBigIntegerField()),
                ('source_number', models.CharField(blank=True, max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True)),
                ('shared_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_out_tickets', to='accounts.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_ticket_shares', to='accounts.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vendor_company', 'source_company', 'source_ticket_id'), name='uniq_vendor_ticket_share')],
            },
        ),
    ]
