/**
 * Longest-prefix / specific-first path → catalog id.
 * Opening Help never navigates; this map only chooses copy.
 */
export const CONTEXT_HELP_ROUTES: Array<{ test: RegExp; id: string; example: string }> = [
  { test: /^\/sales\/history\/[^/]+\/edit$/, id: 'sales-invoice', example: '/sales/history/12/edit' },
  { test: /^\/sales\/history\/[^/]+$/, id: 'sales-invoice-detail', example: '/sales/history/12' },
  { test: /^\/sales\/history$/, id: 'sales-history', example: '/sales/history' },
  { test: /^\/sales\/new$/, id: 'sales-invoice', example: '/sales/new' },
  { test: /^\/sales\/quick-entry$/, id: 'quick-entry', example: '/sales/quick-entry' },
  { test: /^\/sales\/bill-upload$/, id: 'sales-bill-upload', example: '/sales/bill-upload' },
  { test: /^\/sales\/quotations/, id: 'quotations', example: '/sales/quotations' },
  { test: /^\/sales\/orders\/(?:new|[^/]+)$/, id: 'sales-order-editor', example: '/sales/orders/new' },
  { test: /^\/sales\/orders$/, id: 'sales-orders', example: '/sales/orders' },
  { test: /^\/sales\/delivery-challans\/(?:new|[^/]+)$/, id: 'delivery-challan-editor', example: '/sales/delivery-challans/new' },
  { test: /^\/sales\/delivery-challans$/, id: 'delivery-challans', example: '/sales/delivery-challans' },
  { test: /^\/sales\/receipts$/, id: 'receipts', example: '/sales/receipts' },
  { test: /^\/sales\/customers$/, id: 'customers', example: '/sales/customers' },
  { test: /^\/sales\/returns/, id: 'sales-returns', example: '/sales/returns' },
  { test: /^\/sales\/credit-notes\/(?:new|[^/]+)$/, id: 'sales-credit-note-editor', example: '/sales/credit-notes/new' },
  { test: /^\/sales\/credit-notes$/, id: 'sales-credit-notes', example: '/sales/credit-notes' },
  { test: /^\/sales\/debit-notes\/(?:new|[^/]+)$/, id: 'sales-debit-note-editor', example: '/sales/debit-notes/new' },
  { test: /^\/sales\/debit-notes$/, id: 'sales-debit-notes', example: '/sales/debit-notes' },
  { test: /^\/sales\/recurring$/, id: 'recurring-invoices', example: '/sales/recurring' },

  { test: /^\/purchases\/history\/[^/]+\/edit$/, id: 'purchase-invoice', example: '/purchases/history/12/edit' },
  { test: /^\/purchases\/history\/[^/]+$/, id: 'purchase-invoice-detail', example: '/purchases/history/12' },
  { test: /^\/purchases\/history$/, id: 'purchase-history', example: '/purchases/history' },
  { test: /^\/purchases\/new$/, id: 'purchase-invoice', example: '/purchases/new' },
  { test: /^\/purchases\/orders\/(?:new|[^/]+)$/, id: 'purchase-order-editor', example: '/purchases/orders/new' },
  { test: /^\/purchases\/orders$/, id: 'purchase-orders', example: '/purchases/orders' },
  { test: /^\/purchases\/suppliers$/, id: 'suppliers', example: '/purchases/suppliers' },
  { test: /^\/purchases\/payments$/, id: 'supplier-payments', example: '/purchases/payments' },
  { test: /^\/purchases\/returns/, id: 'purchase-returns', example: '/purchases/returns' },
  { test: /^\/purchases\/credit-notes\/(?:new|[^/]+)$/, id: 'purchase-credit-note-editor', example: '/purchases/credit-notes/new' },
  { test: /^\/purchases\/credit-notes$/, id: 'purchase-credit-notes', example: '/purchases/credit-notes' },
  { test: /^\/purchases\/debit-notes\/(?:new|[^/]+)$/, id: 'purchase-debit-note-editor', example: '/purchases/debit-notes/new' },
  { test: /^\/purchases\/debit-notes$/, id: 'purchase-debit-notes', example: '/purchases/debit-notes' },
  { test: /^\/purchases\/bills-of-entry$/, id: 'bills-of-entry', example: '/purchases/bills-of-entry' },
  { test: /^\/purchases\/bill-upload$/, id: 'purchase-bill-upload', example: '/purchases/bill-upload' },

  { test: /^\/inventory\/products$/, id: 'products', example: '/inventory/products' },
  { test: /^\/inventory\/stock$/, id: 'current-stock', example: '/inventory/stock' },
  { test: /^\/inventory\/adjustments$/, id: 'stock-adjustment', example: '/inventory/adjustments' },
  { test: /^\/inventory\/transfers$/, id: 'stock-transfers', example: '/inventory/transfers' },
  { test: /^\/inventory\/warehouses$/, id: 'warehouses', example: '/inventory/warehouses' },
  { test: /^\/inventory\/stock-counts$/, id: 'stock-counts', example: '/inventory/stock-counts' },
  { test: /^\/inventory\/serials$/, id: 'serials', example: '/inventory/serials' },
  { test: /^\/inventory\/expiry-alerts$/, id: 'expiry-alerts', example: '/inventory/expiry-alerts' },
  { test: /^\/inventory\/low-stock$/, id: 'low-stock', example: '/inventory/low-stock' },
  { test: /^\/inventory\/labels$/, id: 'label-print', example: '/inventory/labels' },

  { test: /^\/pos$/, id: 'pos', example: '/pos' },
  { test: /^\/payments\/links$/, id: 'payment-links', example: '/payments/links' },
  { test: /^\/payments\/statements$/, id: 'bank-statements', example: '/payments/statements' },
  { test: /^\/payments\/reconciliation$/, id: 'bank-reconciliation', example: '/payments/reconciliation' },
  { test: /^\/payments\/account-aggregator$/, id: 'account-aggregator', example: '/payments/account-aggregator' },
  { test: /^\/offline-outbox$/, id: 'offline-outbox', example: '/offline-outbox' },

  { test: /^\/reports\/sales$/, id: 'sales-reports', example: '/reports/sales' },
  { test: /^\/reports\/purchases$/, id: 'purchase-reports', example: '/reports/purchases' },
  { test: /^\/reports\/inventory$/, id: 'inventory-reports', example: '/reports/inventory' },
  { test: /^\/reports\/stock-valuation$/, id: 'stock-valuation', example: '/reports/stock-valuation' },
  { test: /^\/reports\/customer-ledger$/, id: 'customer-ledger', example: '/reports/customer-ledger' },
  { test: /^\/reports\/supplier-ledger$/, id: 'supplier-ledger', example: '/reports/supplier-ledger' },
  { test: /^\/reports\/cash-book$/, id: 'cash-book', example: '/reports/cash-book' },
  { test: /^\/reports\/gstr2b$/, id: 'gstr-2b', example: '/reports/gstr2b' },
  { test: /^\/reports\/missing-documents$/, id: 'missing-documents', example: '/reports/missing-documents' },
  { test: /^\/ca-needs$/, id: 'ca-needs', example: '/ca-needs' },
  { test: /^\/reports\/statutory-events$/, id: 'statutory-events', example: '/reports/statutory-events' },
  { test: /^\/reports\/tds-tcs$/, id: 'tds-tcs', example: '/reports/tds-tcs' },
  { test: /^\/reports\/gstr1$/, id: 'gstr-1', example: '/reports/gstr1' },
  { test: /^\/reports\/gstr3b$/, id: 'gstr-3b', example: '/reports/gstr3b' },
  { test: /^\/reports\/gstr4$/, id: 'gstr-4', example: '/reports/gstr4' },
  { test: /^\/reports\/cmp08$/, id: 'cmp-08', example: '/reports/cmp08' },
  { test: /^\/reports\/gstr6$/, id: 'gstr-6', example: '/reports/gstr6' },
  { test: /^\/reports\/gstr7$/, id: 'gstr-7', example: '/reports/gstr7' },
  { test: /^\/reports\/gstr8$/, id: 'gstr-8', example: '/reports/gstr8' },
  { test: /^\/reports\/gstr9$/, id: 'gstr-9', example: '/reports/gstr9' },
  { test: /^\/reports\/gst-health$/, id: 'gst-health', example: '/reports/gst-health' },
  { test: /^\/reports\/gst-rate-exposure$/, id: 'gst-rate-exposure', example: '/reports/gst-rate-exposure' },
  { test: /^\/reports\/trial-balance$/, id: 'trial-balance', example: '/reports/trial-balance' },
  { test: /^\/reports\/profit-and-loss$/, id: 'profit-and-loss', example: '/reports/profit-and-loss' },
  { test: /^\/reports\/balance-sheet$/, id: 'balance-sheet', example: '/reports/balance-sheet' },
  { test: /^\/reports\/books-health$/, id: 'books-health', example: '/reports/books-health' },

  { test: /^\/insights\/alerts$/, id: 'insights-alerts', example: '/insights/alerts' },
  { test: /^\/insights\/health$/, id: 'insights-health', example: '/insights/health' },
  { test: /^\/insights\/cashflow$/, id: 'insights-cashflow', example: '/insights/cashflow' },
  { test: /^\/insights\/assistant$/, id: 'insights-assistant', example: '/insights/assistant' },
  { test: /^\/insights$/, id: 'insights', example: '/insights' },
  { test: /^\/attention$/, id: 'attention', example: '/attention' },
  { test: /^\/setup$/, id: 'setup', example: '/setup' },

  { test: /^\/settings\/company$/, id: 'company-settings', example: '/settings/company' },
  { test: /^\/settings\/gst$/, id: 'gst-settings', example: '/settings/gst' },
  { test: /^\/settings\/users$/, id: 'users-settings', example: '/settings/users' },
  { test: /^\/settings\/import$/, id: 'import-data', example: '/settings/import' },
  { test: /^\/settings\/tally$/, id: 'tally-migration', example: '/settings/tally' },
  { test: /^\/settings\/backup$/, id: 'backup-export', example: '/settings/backup' },
  { test: /^\/settings\/billing$/, id: 'subscription-billing', example: '/settings/billing' },
  { test: /^\/settings\/series$/, id: 'series-settings', example: '/settings/series' },
  { test: /^\/settings\/units$/, id: 'units-settings', example: '/settings/units' },
  { test: /^\/settings\/items$/, id: 'item-settings', example: '/settings/items' },
  { test: /^\/settings\/templates$/, id: 'invoice-templates', example: '/settings/templates' },
  { test: /^\/settings\/price-lists$/, id: 'price-lists', example: '/settings/price-lists' },
  { test: /^\/settings\/accounting$/, id: 'accounting-settings', example: '/settings/accounting' },
  { test: /^\/settings\/bank-accounts$/, id: 'bank-accounts', example: '/settings/bank-accounts' },
  { test: /^\/settings\/payment-gateway$/, id: 'payment-gateway', example: '/settings/payment-gateway' },
  { test: /^\/settings\/statutory-licences$/, id: 'statutory-licences', example: '/settings/statutory-licences' },
  { test: /^\/settings\/ai$/, id: 'ai-settings', example: '/settings/ai' },

  { test: /^\/accounting\/journals$/, id: 'journals', example: '/accounting/journals' },
  { test: /^\/accounting\/periods$/, id: 'accounting-periods', example: '/accounting/periods' },
  { test: /^\/accounting\/accounts$/, id: 'chart-of-accounts', example: '/accounting/accounts' },
  { test: /^\/accounting\/cost-centers$/, id: 'cost-centers', example: '/accounting/cost-centers' },
  { test: /^\/accounting\/fixed-assets$/, id: 'fixed-assets', example: '/accounting/fixed-assets' },
  { test: /^\/accounting\/bank-reconciliation$/, id: 'accounting-bank-reconciliation', example: '/accounting/bank-reconciliation' },

  { test: /^\/manufacturing\/boms/, id: 'manufacturing-boms', example: '/manufacturing/boms' },
  { test: /^\/manufacturing\/work-orders/, id: 'manufacturing-work-orders', example: '/manufacturing/work-orders' },
  { test: /^\/manufacturing$/, id: 'manufacturing-boms', example: '/manufacturing' },
  { test: /^\/payroll\/employees/, id: 'payroll-employees', example: '/payroll/employees' },
  { test: /^\/payroll\/pay-runs/, id: 'payroll-pay-runs', example: '/payroll/pay-runs' },
  { test: /^\/payroll$/, id: 'payroll-employees', example: '/payroll' },
  { test: /^\/crm\/leads/, id: 'crm-leads', example: '/crm/leads' },
  { test: /^\/crm\/opportunities/, id: 'crm-opportunities', example: '/crm/opportunities' },
  { test: /^\/crm$/, id: 'crm-leads', example: '/crm' },

  { test: /^\/$/, id: 'dashboard', example: '/' },
];

export function resolveContextHelpPage(pathname: string): string | undefined {
  const trimmed = pathname.replace(/\/+$/, '') || '/';
  if (trimmed === '/help' || trimmed.startsWith('/settings/help')) return undefined;
  for (const row of CONTEXT_HELP_ROUTES) {
    if (row.test.test(trimmed)) return row.id;
  }
  return undefined;
}
