# -*- coding: utf-8 -*-
"""Flows and tasks added after the 740-row register.

Each task is a 12-column register row. Flow placement lives in FLOW_BY_TASK.
Notes cite symbols that exist in the product. These modules are previews or
MVPs where the model docstring says so; the flow catalog records that limit.
"""

# task id, type, persona, category, action, actor, supporting, outcome, impact, priority, status, notes
ADDITIONAL_FLOW_TASKS = [
    (
        "F-0741", "F", "Accountant / GST Operator", "Payroll & Statutory Dues",
        "Register an employee with a unique code and contracted salary",
        "Payroll clerk", "Business owner",
        "The month can be paid only for people who are on the employee list",
        "Employee is stored once per company code and starts ACTIVE",
        "P1", "In product",
        "uniq_employee_code_per_company on Employee. Payroll is a preview, not a full HRMS.",
    ),
    (
        "F-0742", "F", "Accountant / GST Operator", "Payroll & Statutory Dues",
        "Set PF applicability, basic, DA, and the PF wage ceiling",
        "Payroll clerk", "External CA",
        "PF is calculated on basic plus DA when those amounts are set",
        "When basic and DA are both zero, PF falls back to the contracted gross",
        "P1", "In product",
        "compute_statutory uses Employee.basic, Employee.da, and pf_wage_ceiling.",
    ),
    (
        "F-0743", "F", "Accountant / GST Operator", "Payroll & Statutory Dues",
        "Set ESI, professional-tax state, and the section 192 tax regime",
        "Payroll clerk", "External CA",
        "ESI, PT, and TDS on the slip follow the employee flags",
        "New regime can project TDS from contracted gross. Old regime without a flat rate does not apply Chapter VI-A",
        "P1", "In product",
        "Employee.tax_regime and compute_statutory. Chapter VI-A declarations are not collected.",
    ),
    (
        "F-0744", "F", "Accountant / GST Operator", "Payroll & Statutory Dues",
        "Open one draft pay run for a calendar month",
        "Payroll clerk", "Business owner",
        "A month has a single pay run to complete",
        "PayRun.period is YYYY-MM and is unique per company",
        "P1", "In product",
        "uniq_payrun_period_per_company. PayRun status starts DRAFT.",
    ),
    (
        "F-0745", "F", "Accountant / GST Operator", "Payroll & Statutory Dues",
        "Enter paid days so a partial month prorates gross and statutory dues",
        "Payroll clerk", "Attendance keeper",
        "Loss of pay reduces the slip instead of paying a full month",
        "paid_days below the calendar days in the month prorates gross, PF, ESI, and PT",
        "P1", "In product",
        "PaySlip.paid_days. complete_pay_run starts from contracted salary so proration is applied once.",
    ),
    (
        "F-0746", "F", "Accountant / GST Operator", "Payroll & Statutory Dues",
        "Complete the pay run and keep one payslip per active employee",
        "Payroll clerk", "Business owner",
        "The month is closed for pay and can be reopened only through the pay-run actions",
        "complete_pay_run writes PaySlip rows and can pay from cash. A completed run cannot be completed again",
        "P0", "In product",
        "complete_pay_run. There are no bonus, arrear, advance, or one-off deduction lines on a slip.",
    ),
    (
        "F-0747", "F", "Accountant / GST Operator", "Payroll & Statutory Dues",
        "Read the employer PF split and employer ESI on the payslip",
        "Payroll clerk", "External CA",
        "The employer can see EPS, EPF, admin, and EDLI besides the employee deduction",
        "PaySlip stores pf_employer_eps, pf_employer_epf, pf_admin_charges, edli_charges, and esi_employer",
        "P1", "In product",
        "pf_employer_eps, pf_employer_epf, pf_admin_charges, and edli_charges are on PaySlip. This is not an EPFO return file.",
    ),
    (
        "F-0748", "F", "Workshop Supervisor", "Workshop Job",
        "Open a job card for a customer complaint",
        "Service advisor", "Customer",
        "The workshop has a numbered job before any parts are issued",
        "JobCard starts DRAFT and stores the complaint text",
        "P1", "In product",
        "uniq_jobcard_number_per_company on JobCard.",
    ),
    (
        "F-0749", "F", "Workshop Supervisor", "Workshop Job",
        "Assign a technician and mark the job in progress",
        "Service advisor", "Technician",
        "Someone owns the job while it is open",
        "JobCard.technician points at a company user. Status can move to IN_PROGRESS",
        "P1", "In product",
        "JobCard.technician is a CompanyUser. Status can be IN_PROGRESS.",
    ),
    (
        "F-0750", "F", "Workshop Supervisor", "Workshop Job",
        "Add part lines and labour lines, including a serial when the part is tracked",
        "Technician", "Stores",
        "The invoice can be built from the job instead of typed again",
        "JobCardLine kind is PART or LABOUR and can reference a serial",
        "P1", "In product",
        "JobCardLine. A job with no lines cannot be invoiced.",
    ),
    (
        "F-0751", "F", "Workshop Supervisor", "Workshop Job",
        "Convert the job card into a sales invoice",
        "Service advisor", "Cashier",
        "Parts and labour become a GST invoice linked back to the job",
        "convert_to_invoice creates a draft SalesInvoice and sets the job to INVOICED",
        "P1", "In product",
        "convert_to_invoice in backend/workshop/services.py. A second call returns the same invoice.",
    ),
    (
        "F-0752", "F", "Workshop Supervisor", "Workshop Job",
        "Cancel a job card that will not be billed",
        "Service advisor", "Customer",
        "Abandoned jobs stay out of the invoice list",
        "JobCard status CANCELLED. An invoiced job is not invoiced again",
        "P2", "In product",
        "JobCard.Status.CANCELLED. convert_to_invoice only accepts DRAFT or IN_PROGRESS.",
    ),
    (
        "F-0753", "F", "Assembly / Production Supervisor", "Manufacturing",
        "Activate a bill of materials before a work order can be released",
        "Production supervisor", "Inventory manager",
        "Release is refused while the BOM is still a draft",
        "Bom.status must be ACTIVE. More than one ACTIVE BOM per finished good is allowed",
        "P1", "In product",
        "release_work_order checks Bom status. The work order stores the BOM it was created from.",
    ),
    (
        "F-0754", "F", "Assembly / Production Supervisor", "Manufacturing",
        "Create a draft work order and snapshot the component quantities",
        "Production supervisor", "Stores",
        "A later BOM edit does not change a work order that already exists",
        "WorkOrder starts DRAFT. Component lines are copied when the order is created",
        "P1", "In product",
        "WorkOrder and WorkOrderLine. Snapshot is taken at creation, not at release.",
    ),
    (
        "F-0755", "F", "Assembly / Production Supervisor", "Manufacturing",
        "Complete the work order and receive the finished goods",
        "Production supervisor", "Stores",
        "Finished quantity, batch, and serials land in stock when the order is completed",
        "complete_work_order sets status COMPLETED. Batch and serial fields are stored on the work order when the product tracks them",
        "P1", "In product",
        "complete_work_order. BOM explosion is single-level. A component that is itself a sub-assembly is not exploded.",
    ),
    (
        "F-0756", "F", "Assembly / Production Supervisor", "Manufacturing",
        "Cancel a work order that will not be built",
        "Production supervisor", "Stores",
        "A draft or released order can be stopped without leaving it open",
        "Work order status becomes CANCELLED",
        "P2", "In product",
        "WorkOrder.Status.CANCELLED in backend/manufacturing/services.py.",
    ),
    (
        "F-0757", "F", "Business Owner", "Project Billing",
        "Open a project for a customer",
        "Project owner", "Customer",
        "Milestone bills have a project to hang on",
        "Project starts OPEN and has a number unique per company",
        "P1", "In product",
        "uniq_project_number_per_company on Project.",
    ),
    (
        "F-0758", "F", "Business Owner", "Project Billing",
        "Add a milestone with a sequence, amount, and service product",
        "Project owner", "Accountant",
        "Each billable stage has an amount before any invoice is raised",
        "ProjectMilestone starts PLANNED",
        "P1", "In product",
        "ProjectMilestone.service_product is required.",
    ),
    (
        "F-0759", "F", "Business Owner", "Project Billing",
        "Mark a milestone ready to invoice",
        "Project owner", "Accountant",
        "Invoicing is refused until the milestone is ready",
        "Status moves from PLANNED to READY",
        "P1", "In product",
        "invoice_milestone requires ProjectMilestone.Status.READY.",
    ),
    (
        "F-0760", "F", "Business Owner", "Project Billing",
        "Invoice a ready milestone",
        "Accountant", "Customer",
        "The stage amount becomes a sales invoice linked to the milestone",
        "invoice_milestone creates the invoice and sets the milestone to INVOICED. A closed project cannot be invoiced",
        "P1", "In product",
        "invoice_milestone in backend/projects/services.py.",
    ),
    (
        "F-0761", "F", "Business Owner", "Project Billing",
        "Close a project when no further milestones will be billed",
        "Project owner", "Accountant",
        "Closed work stops accepting new milestone invoices",
        "Project status CLOSED",
        "P2", "In product",
        "Project.Status.CLOSED blocks invoice_milestone.",
    ),
    (
        "F-0762", "F", "Salesperson", "Insurance Distribution",
        "Register an insurer product with tenure, sum insured, and premium",
        "Insurance advisor", "Insurer",
        "Quotes use a product master instead of a stock SKU",
        "PolicyProduct line is motor, health, life, or other",
        "P1", "In product",
        "PolicyProduct in backend/insurance/models.py. It is not an inventory item.",
    ),
    (
        "F-0763", "F", "Salesperson", "Insurance Distribution",
        "Offer a set of policy options on a lead and mark the chosen one",
        "Insurance advisor", "Customer",
        "The customer choice is stored before a policy number exists",
        "PolicyOptionSet hangs on a lead. PolicyOption.chosen marks the selection",
        "P1", "In product",
        "PolicyOptionSet and PolicyOption.",
    ),
    (
        "F-0764", "F", "Salesperson", "Insurance Distribution",
        "Issue a policy with a start date, end date, nominee, and premium",
        "Insurance advisor", "Customer",
        "The in-force policy is the record the renewal and claim flows use",
        "Policy status starts IN_FORCE and the number is unique per company",
        "P1", "In product",
        "uniq_policy_number_per_company on Policy.",
    ),
    (
        "F-0765", "F", "Salesperson", "Insurance Distribution",
        "Endorse or cancel a policy",
        "Insurance advisor", "Insurer",
        "A change after issue is a separate endorsement, not a silent edit",
        "PolicyEndorsement kind is ENDORSE or CANCEL",
        "P1", "In product",
        "PolicyEndorsement.",
    ),
    (
        "F-0766", "F", "Accountant / GST Operator", "Insurance Distribution",
        "Book the insurer commission receivable separately from the customer premium",
        "Accountant", "Insurance advisor",
        "Commission is not mixed into the customer's premium receipt",
        "CommissionReceivable starts OPEN against the policy",
        "P1", "In product",
        "CommissionReceivable. Status can move to RECEIVED.",
    ),
    (
        "F-0767", "F", "Accountant / GST Operator", "Insurance Distribution",
        "Mark insurer commission received",
        "Accountant", "Insurer",
        "Open commission can be cleared when the insurer pays",
        "CommissionReceivable status RECEIVED",
        "P1", "In product",
        "CommissionReceivable.Status.RECEIVED.",
    ),
    (
        "F-0768", "F", "Salesperson", "Insurance Distribution",
        "Lodge a policy claim against a support ticket",
        "Insurance advisor", "Customer",
        "The claim is tracked with the ticket. It does not post the ledger",
        "PolicyClaim links one policy to one ticket",
        "P1", "In product",
        "PolicyClaim. The model does not post an accounting entry.",
    ),
    (
        "F-0769", "F", "Salesperson", "Insurance Distribution",
        "Attach Aadhaar, PAN, or another KYC file to the policy",
        "Insurance advisor", "Customer",
        "KYC sits on the policy instead of in a side folder",
        "PolicyKyc stores the file kind and a file asset",
        "P1", "In product",
        "PolicyKyc.",
    ),
    (
        "F-0770", "F", "Salesperson", "Insurance Distribution",
        "Open one renewal lead for a policy",
        "Insurance advisor", "Customer",
        "Renewal follow-up is not created twice for the same policy",
        "PolicyRenewalLead is one-to-one with the policy and points at a lead",
        "P1", "In product",
        "PolicyRenewalLead. The policy link is the dedupe key.",
    ),
]

# Existing manufacturing tasks join the same flow. Step numbers sit beside the new ones.
FLOW_BY_TASK = {
    "P-0509": ("MFG", "Manufacture and assemble", "1", "manufacturing"),
    "F-0753": ("MFG", "Manufacture and assemble", "2", "manufacturing"),
    "F-0754": ("MFG", "Manufacture and assemble", "3", "manufacturing"),
    "P-0510": ("MFG", "Manufacture and assemble", "4", "manufacturing"),
    "F-0755": ("MFG", "Manufacture and assemble", "5", "manufacturing"),
    "P-0512": ("MFG", "Manufacture and assemble", "6", "manufacturing"),
    "F-0756": ("MFG", "Manufacture and assemble", "7", "manufacturing"),
}

_FLOW_META = {
    "PAY": ("Pay the month", "payroll"),
    "JOB": ("Run a workshop job", "workshop"),
    "PRJ": ("Bill a project by milestone", "projects"),
    "INS": ("Place and service a policy", "insurance"),
}
_FLOW_STEPS = {
    "F-0741": "PAY", "F-0742": "PAY", "F-0743": "PAY", "F-0744": "PAY",
    "F-0745": "PAY", "F-0746": "PAY", "F-0747": "PAY",
    "F-0748": "JOB", "F-0749": "JOB", "F-0750": "JOB", "F-0751": "JOB", "F-0752": "JOB",
    "F-0757": "PRJ", "F-0758": "PRJ", "F-0759": "PRJ", "F-0760": "PRJ", "F-0761": "PRJ",
    "F-0762": "INS", "F-0763": "INS", "F-0764": "INS", "F-0765": "INS",
    "F-0766": "INS", "F-0767": "INS", "F-0768": "INS", "F-0769": "INS", "F-0770": "INS",
}
_STEP = {
    "F-0741": "1", "F-0742": "2", "F-0743": "3", "F-0744": "4",
    "F-0745": "5", "F-0746": "6", "F-0747": "7",
    "F-0748": "1", "F-0749": "2", "F-0750": "3", "F-0751": "4", "F-0752": "5",
    "F-0757": "1", "F-0758": "2", "F-0759": "3", "F-0760": "4", "F-0761": "5",
    "F-0762": "1", "F-0763": "2", "F-0764": "3", "F-0765": "4",
    "F-0766": "5", "F-0767": "6", "F-0768": "7", "F-0769": "8", "F-0770": "9",
}
for _task_id, _flow_id in _FLOW_STEPS.items():
    _name, _module = _FLOW_META[_flow_id]
    FLOW_BY_TASK[_task_id] = (_flow_id, _name, _STEP[_task_id], _module)

# Coarse flow for tasks that were filed only by category.
CATEGORY_FLOWS = {
    "Customer-to-Cash": ("C2C", "Customer to cash", "sales"),
    "Payments & Reconciliation": ("PAYREC", "Payments and reconciliation", "payments"),
    "Inventory Lifecycle": ("INV", "Inventory lifecycle", "inventory"),
    "GST / Tax / Compliance": ("GST", "GST and tax compliance", "accounting"),
    "Receivables & Payables": ("ARAP", "Receivables and payables", "ledgers"),
    "Reporting & Business Intelligence": ("RPT", "Reporting and business intelligence", "reporting"),
    "Procure-to-Pay": ("P2P", "Procure to pay", "purchases"),
    "Import / Export / Period Close": ("CLOSE", "Import, export, and period close", "accounting"),
    "Master Data & Authorization": ("MASTER", "Master data and authorization", "masters"),
    "Multi-Godown / Multi-Store": ("WH", "Multi-godown and multi-store", "inventory"),
    "Communication & Integrations": ("INT", "Communication and integrations", "integrations"),
    "Returns / Complaints / After-Sales": ("RET", "Returns, complaints, and after-sales", "sales"),
    "Sales / CRM / Customer Lifecycle": ("CRM", "Sales and CRM lifecycle", "crm"),
    "Operations, Fleet & Delivery": ("FLEET", "Fleet and delivery", "sales"),
    "Finance & Fixed Assets": ("FA", "Finance and fixed assets", "accounting"),
    "Growth OS - Campaigns & Marketing": ("GOS-CAM", "Growth campaigns", "crm"),
    "Growth OS - Lead Ingestion & Pipeline": ("GOS-LEAD", "Growth leads", "crm"),
    "Growth OS - Opportunity Management": ("GOS-OPP", "Growth opportunities", "crm"),
    "Growth OS - Referral & Advocate Engine": ("GOS-REF", "Growth referrals", "crm"),
    "Growth OS - Service Contracts & AMC": ("GOS-AMC", "Service contracts", "contracts"),
    "Growth OS - Customer Care & Dispute Loop": ("GOS-CARE", "Customer care", "complaints"),
    "Growth OS - Customer Intelligence": ("GOS-360", "Customer intelligence", "insights"),
}

# flow id, name, module, what it covers, limit
FLOW_CATALOG = [
    (
        "PAY", "Pay the month", "payroll",
        "Employee, PF/ESI/PT/TDS flags, one pay run per month, paid days, payslip, employer PF split.",
        "Preview payroll. No bonus, arrear, advance recovery, or one-off deduction lines. Not an EPFO return.",
    ),
    (
        "JOB", "Run a workshop job", "workshop",
        "Complaint, technician, part and labour lines, invoice, cancel.",
        "Invoicing creates a draft sales invoice from the job lines. It does not schedule bays or capture labour time.",
    ),
    (
        "MFG", "Manufacture and assemble", "manufacturing",
        "BOM, activate, work order snapshot, issue components, complete finished goods, unit cost, cancel.",
        "Single-level BOM. More than one ACTIVE BOM per finished good is allowed. The work order keeps the BOM it was created from.",
    ),
    (
        "PRJ", "Bill a project by milestone", "projects",
        "Open project, milestones, mark ready, invoice, close.",
        "A milestone needs a service product. Invoicing a closed project is refused.",
    ),
    (
        "INS", "Place and service a policy", "insurance",
        "Insurer product, options on a lead, issue, endorse or cancel, commission, claim, KYC, one renewal lead.",
        "A claim is linked to a support ticket and does not post the ledger. The product is not a stock SKU.",
    ),
]
