# -*- coding: utf-8 -*-
"""
Generate Full Master Task Register for BizBoard
Contains comprehensive, domain-authentic mapping for all 494 tasks:
- 188 Persona Tasks (P-0001 to P-0188)
- 306 Cross-Persona Tasks (X-0189 to X-0494)
Outputs:
- Bizboard_Master_Task_Register_Filled.csv
- Bizboard_Master_Task_Register_Filled.xlsx
"""

import csv
import sys
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# Raw task definitions
RAW_TASKS = [
    # Gully Vendor / Small Retailer (P-0001 to P-0017)
    ("P-0001", "P", "Gully Vendor / Small Retailer", "", "Create a quick bill for a walk-in customer", "P0"),
    ("P-0002", "P", "Gully Vendor / Small Retailer", "", "Record a cash sale", "P0"),
    ("P-0003", "P", "Gully Vendor / Small Retailer", "", "Record a UPI/digital payment", "P0"),
    ("P-0004", "P", "Gully Vendor / Small Retailer", "", "Find an item's price instantly", "P1"),
    ("P-0005", "P", "Gully Vendor / Small Retailer", "", "Check today's total sales", "P1"),
    ("P-0006", "P", "Gully Vendor / Small Retailer", "", "Check cash/UPI collected", "P1"),
    ("P-0007", "P", "Gully Vendor / Small Retailer", "", "See low-stock items", "P1"),
    ("P-0008", "P", "Gully Vendor / Small Retailer", "", "Add a new item while making a sale", "P2"),
    ("P-0009", "P", "Gully Vendor / Small Retailer", "", "Record a customer credit sale", "P1"),
    ("P-0010", "P", "Gully Vendor / Small Retailer", "", "Record payment from a customer", "P1"),
    ("P-0011", "P", "Gully Vendor / Small Retailer", "", "See outstanding customer dues", "P1"),
    ("P-0012", "P", "Gully Vendor / Small Retailer", "", "Send invoice/receipt", "P1"),
    ("P-0013", "P", "Gully Vendor / Small Retailer", "", "Cancel or correct a wrongly created bill", "P1"),
    ("P-0014", "P", "Gully Vendor / Small Retailer", "", "Process a sales return", "P1"),
    ("P-0015", "P", "Gully Vendor / Small Retailer", "", "Check today's profit/margin", "P2"),
    ("P-0016", "P", "Gully Vendor / Small Retailer", "", "See GST collected", "P2"),
    ("P-0017", "P", "Gully Vendor / Small Retailer", "", "Close the day's business", "P1"),

    # Kirana Shop Owner (P-0018 to P-0037)
    ("P-0018", "P", "Kirana Shop Owner", "", "Create a customer invoice", "P0"),
    ("P-0019", "P", "Kirana Shop Owner", "", "Create a supplier purchase entry", "P1"),
    ("P-0020", "P", "Kirana Shop Owner", "", "Receive purchased goods", "P1"),
    ("P-0021", "P", "Kirana Shop Owner", "", "Update purchase and selling prices", "P1"),
    ("P-0022", "P", "Kirana Shop Owner", "", "Track stock quantity", "P0"),
    ("P-0023", "P", "Kirana Shop Owner", "", "Identify low-stock items", "P1"),
    ("P-0024", "P", "Kirana Shop Owner", "", "Identify fast-moving items", "P2"),
    ("P-0025", "P", "Kirana Shop Owner", "", "Identify slow-moving/dead stock", "P2"),
    ("P-0026", "P", "Kirana Shop Owner", "", "Track customer credit", "P1"),
    ("P-0027", "P", "Kirana Shop Owner", "", "Collect customer payments", "P1"),
    ("P-0028", "P", "Kirana Shop Owner", "", "Track supplier outstanding", "P1"),
    ("P-0029", "P", "Kirana Shop Owner", "", "Record supplier payment", "P1"),
    ("P-0030", "P", "Kirana Shop Owner", "", "Process sales returns", "P1"),
    ("P-0031", "P", "Kirana Shop Owner", "", "Process purchase returns", "P1"),
    ("P-0032", "P", "Kirana Shop Owner", "", "Apply discounts correctly", "P2"),
    ("P-0033", "P", "Kirana Shop Owner", "", "Manage GST rates/HSN", "P1"),
    ("P-0034", "P", "Kirana Shop Owner", "", "Generate GST-compliant invoices", "P0"),
    ("P-0035", "P", "Kirana Shop Owner", "", "Review sales", "P1"),
    ("P-0036", "P", "Kirana Shop Owner", "", "Review gross margin", "P2"),
    ("P-0037", "P", "Kirana Shop Owner", "", "Reconcile cash and digital payments", "P1"),

    # Medical Shop (P-0038 to P-0051)
    ("P-0038", "P", "Medical Shop", "", "Sell medicines with batch information", "P0"),
    ("P-0039", "P", "Medical Shop", "", "Track batch-wise inventory", "P0"),
    ("P-0040", "P", "Medical Shop", "", "Track expiry dates", "P0"),
    ("P-0041", "P", "Medical Shop", "", "Flag/prevent expired-stock sales", "P0"),
    ("P-0042", "P", "Medical Shop", "", "Identify near-expiry inventory", "P1"),
    ("P-0043", "P", "Medical Shop", "", "Record purchases by batch", "P0"),
    ("P-0044", "P", "Medical Shop", "", "Track medicine stock", "P1"),
    ("P-0045", "P", "Medical Shop", "", "Handle medicine returns", "P1"),
    ("P-0046", "P", "Medical Shop", "", "Search medicines while billing", "P0"),
    ("P-0047", "P", "Medical Shop", "", "Maintain MRP and selling price", "P1"),
    ("P-0048", "P", "Medical Shop", "", "Track supplier-wise purchases", "P1"),
    ("P-0049", "P", "Medical Shop", "", "Generate GST-compliant medicine invoices", "P0"),
    ("P-0050", "P", "Medical Shop", "", "Identify expiry-risk stock", "P1"),
    ("P-0051", "P", "Medical Shop", "", "View profitability by item/category", "P2"),

    # Distributor (P-0052 to P-0067)
    ("P-0052", "P", "Distributor", "", "Create bulk sales invoices", "P0"),
    ("P-0053", "P", "Distributor", "", "Process retailer orders", "P1"),
    ("P-0054", "P", "Distributor", "", "Allocate inventory against orders", "P1"),
    ("P-0055", "P", "Distributor", "", "Generate delivery documents", "P1"),
    ("P-0056", "P", "Distributor", "", "Track pending customer orders", "P1"),
    ("P-0057", "P", "Distributor", "", "Track customer outstanding", "P0"),
    ("P-0058", "P", "Distributor", "", "Manage credit limits", "P0"),
    ("P-0059", "P", "Distributor", "", "Record customer collections", "P1"),
    ("P-0060", "P", "Distributor", "", "Track supplier purchases", "P1"),
    ("P-0061", "P", "Distributor", "", "Manage large inventory volumes", "P1"),
    ("P-0062", "P", "Distributor", "", "Transfer stock between warehouses", "P1"),
    ("P-0063", "P", "Distributor", "", "Track batch/serial inventory", "P1"),
    ("P-0064", "P", "Distributor", "", "Track expiry-risk stock", "P1"),
    ("P-0065", "P", "Distributor", "", "Analyze customer profitability", "P2"),
    ("P-0066", "P", "Distributor", "", "Analyze product profitability", "P2"),
    ("P-0067", "P", "Distributor", "", "Reconcile receivables and payments", "P1"),

    # Single-Godown Distributor (P-0068 to P-0078)
    ("P-0068", "P", "Single-Godown Distributor", "", "Receive stock into godown", "P1"),
    ("P-0069", "P", "Single-Godown Distributor", "", "Allocate stock to customer orders", "P1"),
    ("P-0070", "P", "Single-Godown Distributor", "", "Pick and dispatch customer orders", "P1"),
    ("P-0071", "P", "Single-Godown Distributor", "", "Track available and committed stock", "P1"),
    ("P-0072", "P", "Single-Godown Distributor", "", "Track damaged stock", "P1"),
    ("P-0073", "P", "Single-Godown Distributor", "", "Track returned stock", "P1"),
    ("P-0074", "P", "Single-Godown Distributor", "", "Perform physical stock verification", "P1"),
    ("P-0075", "P", "Single-Godown Distributor", "", "Identify inventory discrepancies", "P1"),
    ("P-0076", "P", "Single-Godown Distributor", "", "Generate stock valuation", "P2"),
    ("P-0077", "P", "Single-Godown Distributor", "", "Track FIFO inventory costing", "P2"),
    ("P-0078", "P", "Single-Godown Distributor", "", "Monitor reorder requirements", "P1"),

    # Multi-Godown Distributor (P-0079 to P-0088)
    ("P-0079", "P", "Multi-Godown Distributor", "", "View consolidated inventory", "P0"),
    ("P-0080", "P", "Multi-Godown Distributor", "", "Check stock by location", "P1"),
    ("P-0081", "P", "Multi-Godown Distributor", "", "Transfer stock between godowns", "P0"),
    ("P-0082", "P", "Multi-Godown Distributor", "", "Allocate orders to the appropriate godown", "P1"),
    ("P-0083", "P", "Multi-Godown Distributor", "", "Track inter-godown transfers", "P1"),
    ("P-0084", "P", "Multi-Godown Distributor", "", "Compare godown-wise sales", "P2"),
    ("P-0085", "P", "Multi-Godown Distributor", "", "Compare godown-wise profitability", "P2"),
    ("P-0086", "P", "Multi-Godown Distributor", "", "Identify stock imbalance", "P2"),
    ("P-0087", "P", "Multi-Godown Distributor", "", "Perform location-wise stock audits", "P1"),
    ("P-0088", "P", "Multi-Godown Distributor", "", "Track inventory movement across locations", "P1"),

    # Multi-Shop Owner (P-0089 to P-0099)
    ("P-0089", "P", "Multi-Shop Owner", "", "View all shops from one dashboard", "P0"),
    ("P-0090", "P", "Multi-Shop Owner", "", "Compare shop sales", "P1"),
    ("P-0091", "P", "Multi-Shop Owner", "", "Compare shop profitability", "P2"),
    ("P-0092", "P", "Multi-Shop Owner", "", "Transfer inventory between shops", "P1"),
    ("P-0093", "P", "Multi-Shop Owner", "", "Monitor shop-wise inventory", "P1"),
    ("P-0094", "P", "Multi-Shop Owner", "", "Monitor shop-wise cash collections", "P1"),
    ("P-0095", "P", "Multi-Shop Owner", "", "Monitor shop-wise outstanding", "P1"),
    ("P-0096", "P", "Multi-Shop Owner", "", "Consolidate business performance", "P1"),
    ("P-0097", "P", "Multi-Shop Owner", "", "Identify underperforming locations", "P2"),
    ("P-0098", "P", "Multi-Shop Owner", "", "Manage centralized product masters", "P1"),
    ("P-0099", "P", "Multi-Shop Owner", "", "Control user access by shop", "P0"),

    # Accountant / GST Operator (P-0100 to P-0115)
    ("P-0100", "P", "Accountant / GST Operator", "", "Review sales transactions", "P1"),
    ("P-0101", "P", "Accountant / GST Operator", "", "Review purchase transactions", "P1"),
    ("P-0102", "P", "Accountant / GST Operator", "", "Validate GST data", "P0"),
    ("P-0103", "P", "Accountant / GST Operator", "", "Identify missing GST information", "P1"),
    ("P-0104", "P", "Accountant / GST Operator", "", "Reconcile purchase records with GST data", "P0"),
    ("P-0105", "P", "Accountant / GST Operator", "", "Review GSTR-2B/IMS information", "P1"),
    ("P-0106", "P", "Accountant / GST Operator", "", "Accept/reject/pending invoice actions", "P1"),
    ("P-0107", "P", "Accountant / GST Operator", "", "Identify ITC at risk", "P0"),
    ("P-0108", "P", "Accountant / GST Operator", "", "Track Section 16(4) deadlines", "P1"),
    ("P-0109", "P", "Accountant / GST Operator", "", "Identify supplier invoice defects", "P1"),
    ("P-0110", "P", "Accountant / GST Operator", "", "Prepare GST returns", "P0"),
    ("P-0111", "P", "Accountant / GST Operator", "", "Export accounting data", "P1"),
    ("P-0112", "P", "Accountant / GST Operator", "", "Reconcile books with GST records", "P1"),
    ("P-0113", "P", "Accountant / GST Operator", "", "Identify duplicate transactions", "P1"),
    ("P-0114", "P", "Accountant / GST Operator", "", "Identify tax calculation errors", "P0"),
    ("P-0115", "P", "Accountant / GST Operator", "", "Maintain an audit trail", "P0"),

    # Business Owner (P-0116 to P-0128)
    ("P-0116", "P", "Business Owner", "", "See today's business performance", "P0"),
    ("P-0117", "P", "Business Owner", "", "See sales, purchases and profit together", "P1"),
    ("P-0118", "P", "Business Owner", "", "Identify outstanding receivables", "P0"),
    ("P-0119", "P", "Business Owner", "", "Identify overdue payments", "P0"),
    ("P-0120", "P", "Business Owner", "", "Identify low-stock products", "P1"),
    ("P-0121", "P", "Business Owner", "", "Identify profitable products", "P2"),
    ("P-0122", "P", "Business Owner", "", "Identify loss-making products", "P2"),
    ("P-0123", "P", "Business Owner", "", "Compare performance across periods", "P2"),
    ("P-0124", "P", "Business Owner", "", "Monitor GST liability", "P1"),
    ("P-0125", "P", "Business Owner", "", "Monitor cash flow", "P1"),
    ("P-0126", "P", "Business Owner", "", "Review business alerts", "P1"),
    ("P-0127", "P", "Business Owner", "", "Drill down from KPI to transactions", "P1"),
    ("P-0128", "P", "Business Owner", "", "Approve important business actions", "P0"),

    # Salesperson (P-0129 to P-0138)
    ("P-0129", "P", "Salesperson", "", "Create a customer/order", "P1"),
    ("P-0130", "P", "Salesperson", "", "Search customer history", "P1"),
    ("P-0131", "P", "Salesperson", "", "Create a quotation", "P1"),
    ("P-0132", "P", "Salesperson", "", "Convert quotation into an order", "P1"),
    ("P-0133", "P", "Salesperson", "", "Check product availability", "P0"),
    ("P-0134", "P", "Salesperson", "", "Record customer follow-up", "P2"),
    ("P-0135", "P", "Salesperson", "", "Track pending orders", "P1"),
    ("P-0136", "P", "Salesperson", "", "Record customer payment", "P1"),
    ("P-0137", "P", "Salesperson", "", "View customer outstanding", "P1"),
    ("P-0138", "P", "Salesperson", "", "Track sales performance", "P2"),

    # Purchase Manager (P-0139 to P-0148)
    ("P-0139", "P", "Purchase Manager", "", "Create a purchase order", "P1"),
    ("P-0140", "P", "Purchase Manager", "", "Send/order products from supplier", "P1"),
    ("P-0141", "P", "Purchase Manager", "", "Receive goods against purchase order", "P1"),
    ("P-0142", "P", "Purchase Manager", "", "Record GRN", "P1"),
    ("P-0143", "P", "Purchase Manager", "", "Compare ordered versus received quantities", "P1"),
    ("P-0144", "P", "Purchase Manager", "", "Record damaged/short stock", "P1"),
    ("P-0145", "P", "Purchase Manager", "", "Update supplier invoice", "P1"),
    ("P-0146", "P", "Purchase Manager", "", "Track supplier outstanding", "P1"),
    ("P-0147", "P", "Purchase Manager", "", "Identify best-priced suppliers", "P2"),
    ("P-0148", "P", "Purchase Manager", "", "Review supplier performance", "P2"),

    # Inventory Manager (P-0149 to P-0161)
    ("P-0149", "P", "Inventory Manager", "", "View current inventory", "P0"),
    ("P-0150", "P", "Inventory Manager", "", "Receive stock", "P1"),
    ("P-0151", "P", "Inventory Manager", "", "Transfer stock", "P1"),
    ("P-0152", "P", "Inventory Manager", "", "Adjust stock with authorization", "P0"),
    ("P-0153", "P", "Inventory Manager", "", "Record damaged stock", "P1"),
    ("P-0154", "P", "Inventory Manager", "", "Record returned stock", "P1"),
    ("P-0155", "P", "Inventory Manager", "", "Perform stock count", "P1"),
    ("P-0156", "P", "Inventory Manager", "", "Reconcile physical versus system stock", "P1"),
    ("P-0157", "P", "Inventory Manager", "", "Track batch/serial numbers", "P1"),
    ("P-0158", "P", "Inventory Manager", "", "Track expiry", "P0"),
    ("P-0159", "P", "Inventory Manager", "", "Calculate inventory valuation", "P2"),
    ("P-0160", "P", "Inventory Manager", "", "Investigate stock discrepancies", "P1"),
    ("P-0161", "P", "Inventory Manager", "", "Review inventory movement history", "P1"),

    # Customer (P-0162 to P-0169)
    ("P-0162", "P", "Customer", "", "Receive invoice", "P1"),
    ("P-0163", "P", "Customer", "", "View purchase history", "P2"),
    ("P-0164", "P", "Customer", "", "Receive dues information", "P1"),
    ("P-0165", "P", "Customer", "", "Make payment", "P1"),
    ("P-0166", "P", "Customer", "", "Request return", "P1"),
    ("P-0167", "P", "Customer", "", "Request replacement", "P2"),
    ("P-0168", "P", "Customer", "", "View outstanding balance", "P2"),
    ("P-0169", "P", "Customer", "", "Receive order/status updates", "P2"),

    # Supplier (P-0170 to P-0175)
    ("P-0170", "P", "Supplier", "", "Receive purchase/order information", "P1"),
    ("P-0171", "P", "Supplier", "", "Provide invoice", "P1"),
    ("P-0172", "P", "Supplier", "", "Track payment status", "P2"),
    ("P-0173", "P", "Supplier", "", "View outstanding amount", "P2"),
    ("P-0174", "P", "Supplier", "", "Handle purchase returns", "P1"),
    ("P-0175", "P", "Supplier", "", "Resolve invoice discrepancies", "P1"),

    # Admin / System Owner (P-0176 to P-0188)
    ("P-0176", "P", "Admin / System Owner", "", "Create and manage business users", "P0"),
    ("P-0177", "P", "Admin / System Owner", "", "Configure roles and permissions", "P0"),
    ("P-0178", "P", "Admin / System Owner", "", "Configure business settings", "P0"),
    ("P-0179", "P", "Admin / System Owner", "", "Configure GST information", "P0"),
    ("P-0180", "P", "Admin / System Owner", "", "Configure branches/godowns", "P0"),
    ("P-0181", "P", "Admin / System Owner", "", "Configure taxes and HSN", "P0"),
    ("P-0182", "P", "Admin / System Owner", "", "Configure invoice templates", "P2"),
    ("P-0183", "P", "Admin / System Owner", "", "Configure integrations", "P1"),
    ("P-0184", "P", "Admin / System Owner", "", "Review system activity", "P1"),
    ("P-0185", "P", "Admin / System Owner", "", "Review audit logs", "P0"),
    ("P-0186", "P", "Admin / System Owner", "", "Manage data imports/exports", "P1"),
    ("P-0187", "P", "Admin / System Owner", "", "Manage backups/recovery", "P0"),
    ("P-0188", "P", "Admin / System Owner", "", "Monitor system health", "P1"),
]

# Cross-Persona Task definitions: (Task ID, Task Type, Persona, Category, Action, Priority)
CROSS_TASKS = [
    # Customer-to-Cash (X-0189 to X-0210)
    ("X-0189", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Customer order → salesperson records order → inventory availability is checked", "P1"),
    ("X-0190", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Customer accepts quotation → quotation converts to sales order", "P1"),
    ("X-0191", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Sales order → inventory is reserved → available stock is updated", "P1"),
    ("X-0192", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Sales order → warehouse receives picking request", "P1"),
    ("X-0193", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Warehouse picks stock → order becomes ready for dispatch", "P1"),
    ("X-0194", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Order dispatched → delivery status is recorded", "P1"),
    ("X-0195", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Delivery completed → invoice is generated", "P1"),
    ("X-0196", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Invoice generated → inventory is reduced", "P1"),
    ("X-0197", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Invoice generated → customer receivable is created", "P1"),
    ("X-0198", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Invoice generated → GST liability is calculated", "P1"),
    ("X-0199", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Customer pays → payment is recorded", "P1"),
    ("X-0200", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Payment recorded → customer outstanding decreases", "P1"),
    ("X-0201", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Partial payment → remaining outstanding is maintained", "P1"),
    ("X-0202", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Customer exceeds credit limit → sale/order is flagged or blocked", "P1"),
    ("X-0203", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Invoice becomes overdue → receivable ageing changes", "P1"),
    ("X-0204", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Overdue invoice → owner receives business alert", "P1"),
    ("X-0205", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Customer requests return → return request is recorded", "P1"),
    ("X-0206", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Return approved → inventory is restored where applicable", "P1"),
    ("X-0207", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Return approved → customer credit/refund is created", "P1"),
    ("X-0208", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Sales return → GST impact is recalculated", "P1"),
    ("X-0209", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Refund processed → customer balance is updated", "P1"),
    ("X-0210", "X", "Multiple / Cross-persona", "Customer-to-Cash", "Invoice corrected → correction history remains auditable", "P1"),

    # Procure-to-Pay (X-0211 to X-0234)
    ("X-0211", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Purchase manager creates purchase order", "P1"),
    ("X-0212", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Purchase order → supplier receives order", "P1"),
    ("X-0213", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Supplier confirms order → order status changes", "P1"),
    ("X-0214", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Supplier ships goods → expected receipt is recorded", "P1"),
    ("X-0215", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Goods arrive → warehouse creates GRN", "P1"),
    ("X-0216", "X", "Multiple / Cross-persona", "Procure-to-Pay", "GRN → inventory quantity increases", "P1"),
    ("X-0217", "X", "Multiple / Cross-persona", "Procure-to-Pay", "GRN → batch/serial information is captured", "P1"),
    ("X-0218", "X", "Multiple / Cross-persona", "Procure-to-Pay", "GRN → damaged/short quantity is recorded", "P1"),
    ("X-0219", "X", "Multiple / Cross-persona", "Procure-to-Pay", "GRN → purchase order received quantity is updated", "P1"),
    ("X-0220", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Supplier invoice arrives → invoice is matched against PO/GRN", "P1"),
    ("X-0221", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Quantity mismatch → exception is generated", "P1"),
    ("X-0222", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Price mismatch → exception is generated", "P1"),
    ("X-0223", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Tax mismatch → exception is generated", "P1"),
    ("X-0224", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Supplier invoice accepted → payable is created", "P1"),
    ("X-0225", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Purchase → GST input tax is calculated", "P1"),
    ("X-0226", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Purchase → eligible ITC is identified", "P1"),
    ("X-0227", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Supplier payment recorded → payable decreases", "P1"),
    ("X-0228", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Partial supplier payment → remaining payable is maintained", "P1"),
    ("X-0229", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Supplier credit note → payable and tax impact are adjusted", "P1"),
    ("X-0230", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Purchase return → inventory decreases", "P1"),
    ("X-0231", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Purchase return → supplier balance is adjusted", "P1"),
    ("X-0232", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Purchase return → GST impact is adjusted", "P1"),
    ("X-0233", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Supplier invoice discrepancy → accountant is alerted", "P1"),
    ("X-0234", "X", "Multiple / Cross-persona", "Procure-to-Pay", "Supplier invoice correction → original transaction remains traceable", "P1"),

    # Inventory Lifecycle (X-0235 to X-0257)
    ("X-0235", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Purchase receipt → stock enters inventory", "P1"),
    ("X-0236", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Sale → stock leaves inventory", "P1"),
    ("X-0237", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Sales return → stock comes back into inventory", "P1"),
    ("X-0238", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Purchase return → stock leaves inventory", "P1"),
    ("X-0239", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Stock transfer → source location decreases", "P1"),
    ("X-0240", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Stock transfer → destination location increases", "P1"),
    ("X-0241", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Stock transfer → complete movement history is retained", "P1"),
    ("X-0242", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Stock adjustment → authorized user approves adjustment", "P1"),
    ("X-0243", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Stock adjustment → inventory ledger records adjustment", "P1"),
    ("X-0244", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Damaged stock → inventory is separated from saleable stock", "P1"),
    ("X-0245", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Lost stock → inventory adjustment is recorded", "P1"),
    ("X-0246", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Expired stock → sale is prevented/flagged", "P1"),
    ("X-0247", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Near-expiry stock → owner receives alert", "P1"),
    ("X-0248", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Batch sale → specific batch quantity decreases", "P1"),
    ("X-0249", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Serial-number sale → serial is marked as sold", "P1"),
    ("X-0250", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Serial-number return → serial becomes available/returned according to policy", "P1"),
    ("X-0251", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Physical stock count → system stock is compared", "P1"),
    ("X-0252", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Stock variance → discrepancy is created", "P1"),
    ("X-0253", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Discrepancy approval → inventory adjustment occurs", "P1"),
    ("X-0254", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Inventory adjustment → audit trail records who/why/when", "P1"),
    ("X-0255", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "FIFO costing → correct cost is assigned to sale", "P1"),
    ("X-0256", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Inventory valuation → owner sees current stock value", "P1"),
    ("X-0257", "X", "Multiple / Cross-persona", "Inventory Lifecycle", "Inventory movement → historical transaction remains immutable", "P1"),

    # Multi-Godown / Multi-Store (X-0258 to X-0277)
    ("X-0258", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Shop requests stock from godown", "P1"),
    ("X-0259", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Godown approves stock request", "P1"),
    ("X-0260", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Godown allocates stock", "P1"),
    ("X-0261", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Goods dispatched from godown", "P1"),
    ("X-0262", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Destination receives goods", "P1"),
    ("X-0263", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Source inventory decreases", "P1"),
    ("X-0264", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Destination inventory increases", "P1"),
    ("X-0265", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Transfer discrepancy is recorded", "P1"),
    ("X-0266", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Transfer damage is recorded", "P1"),
    ("X-0267", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Transfer cancellation reverses appropriate inventory state", "P1"),
    ("X-0268", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Owner views consolidated inventory", "P1"),
    ("X-0269", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Owner drills from consolidated stock to location", "P1"),
    ("X-0270", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Owner compares location-wise sales", "P1"),
    ("X-0271", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Owner compares location-wise inventory", "P1"),
    ("X-0272", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Owner compares location-wise profitability", "P1"),
    ("X-0273", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "One store requests stock from another store", "P1"),
    ("X-0274", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Inter-store transfer is authorized", "P1"),
    ("X-0275", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Stock is moved between stores", "P1"),
    ("X-0276", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Location-specific user sees only authorized inventory", "P1"),
    ("X-0277", "X", "Multiple / Cross-persona", "Multi-Godown / Multi-Store", "Central accountant sees consolidated accounting", "P1"),

    # GST / Tax / Compliance (X-0278 to X-0306)
    ("X-0278", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Sales invoice → GST calculation", "P1"),
    ("X-0279", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Purchase invoice → input GST calculation", "P1"),
    ("X-0280", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "HSN selection → appropriate tax treatment", "P1"),
    ("X-0281", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Customer GSTIN → invoice tax treatment", "P1"),
    ("X-0282", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Supplier GSTIN → purchase tax treatment", "P1"),
    ("X-0283", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Intra-state transaction → CGST/SGST treatment", "P1"),
    ("X-0284", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Inter-state transaction → IGST treatment", "P1"),
    ("X-0285", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "GST invoice → reporting dataset is updated", "P1"),
    ("X-0286", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Invoice cancellation → GST/reporting data is updated", "P1"),
    ("X-0287", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Sales return → tax adjustment", "P1"),
    ("X-0288", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Purchase return → input-tax adjustment", "P1"),
    ("X-0289", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Credit note → tax liability adjustment", "P1"),
    ("X-0290", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Debit note → tax liability adjustment", "P1"),
    ("X-0291", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Purchase data → IMS matching", "P1"),
    ("X-0292", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "IMS invoice → accept action", "P1"),
    ("X-0293", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "IMS invoice → reject action", "P1"),
    ("X-0294", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "IMS invoice → pending action", "P1"),
    ("X-0295", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Accepted invoice → ITC eligibility calculation", "P1"),
    ("X-0296", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Rejected invoice → ITC exclusion", "P1"),
    ("X-0297", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Missing supplier invoice → exception", "P1"),
    ("X-0298", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Invoice mismatch → exception", "P1"),
    ("X-0299", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Duplicate invoice → duplicate detection", "P1"),
    ("X-0300", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Supplier defect → supplier defect score updates", "P1"),
    ("X-0301", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "ITC deadline approaching → alert", "P1"),
    ("X-0302", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "ITC-at-risk invoice → credit-at-risk dashboard updates", "P1"),
    ("X-0303", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "GST data correction → audit trail maintained", "P1"),
    ("X-0304", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "GST return preparation → source transactions remain traceable", "P1"),
    ("X-0305", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "Accountant reviews GST exception → exception resolved", "P1"),
    ("X-0306", "X", "Multiple / Cross-persona", "GST / Tax / Compliance", "GST export → exported data reconciles with system", "P1"),

    # Receivables & Payables (X-0307 to X-0336)
    ("X-0307", "X", "Multiple / Cross-persona", "Receivables & Payables", "Customer purchases on credit", "P1"),
    ("X-0308", "X", "Multiple / Cross-persona", "Receivables & Payables", "Credit sale → customer ledger updated", "P1"),
    ("X-0309", "X", "Multiple / Cross-persona", "Receivables & Payables", "Customer payment → ledger updated", "P1"),
    ("X-0310", "X", "Multiple / Cross-persona", "Receivables & Payables", "Partial payment → balance maintained", "P1"),
    ("X-0311", "X", "Multiple / Cross-persona", "Receivables & Payables", "Advance payment → advance ledger maintained", "P1"),
    ("X-0312", "X", "Multiple / Cross-persona", "Receivables & Payables", "Payment allocation → payment applied to selected invoices", "P1"),
    ("X-0313", "X", "Multiple / Cross-persona", "Receivables & Payables", "Payment received → invoice status changes", "P1"),
    ("X-0314", "X", "Multiple / Cross-persona", "Receivables & Payables", "Invoice overdue → ageing bucket changes", "P1"),
    ("X-0315", "X", "Multiple / Cross-persona", "Receivables & Payables", "Customer crosses credit limit → alert generated", "P1"),
    ("X-0316", "X", "Multiple / Cross-persona", "Receivables & Payables", "Payment reminder → reminder generated", "P1"),
    ("X-0317", "X", "Multiple / Cross-persona", "Receivables & Payables", "Customer settles multiple invoices → allocation is maintained", "P1"),
    ("X-0318", "X", "Multiple / Cross-persona", "Receivables & Payables", "Credit note → customer balance changes", "P1"),
    ("X-0319", "X", "Multiple / Cross-persona", "Receivables & Payables", "Refund → customer balance changes", "P1"),
    ("X-0320", "X", "Multiple / Cross-persona", "Receivables & Payables", "Customer statement → all transactions are visible", "P1"),
    ("X-0321", "X", "Multiple / Cross-persona", "Receivables & Payables", "Owner reviews receivables → customer-level drill-down", "P1"),
    ("X-0322", "X", "Multiple / Cross-persona", "Receivables & Payables", "Accountant reconciles customer ledger → discrepancies identified", "P1"),
    ("X-0323", "X", "Multiple / Cross-persona", "Receivables & Payables", "Purchase creates supplier payable", "P1"),
    ("X-0324", "X", "Multiple / Cross-persona", "Receivables & Payables", "Supplier invoice updates payable", "P1"),
    ("X-0325", "X", "Multiple / Cross-persona", "Receivables & Payables", "Supplier payment reduces payable", "P1"),
    ("X-0326", "X", "Multiple / Cross-persona", "Receivables & Payables", "Partial supplier payment maintains balance", "P1"),
    ("X-0327", "X", "Multiple / Cross-persona", "Receivables & Payables", "Supplier advance is recorded", "P1"),
    ("X-0328", "X", "Multiple / Cross-persona", "Receivables & Payables", "Advance is adjusted against invoice", "P1"),
    ("X-0329", "X", "Multiple / Cross-persona", "Receivables & Payables", "Purchase return reduces payable", "P1"),
    ("X-0330", "X", "Multiple / Cross-persona", "Receivables & Payables", "Supplier credit note reduces payable", "P1"),
    ("X-0331", "X", "Multiple / Cross-persona", "Receivables & Payables", "Supplier statement is generated", "P1"),
    ("X-0332", "X", "Multiple / Cross-persona", "Receivables & Payables", "Supplier ageing is calculated", "P1"),
    ("X-0333", "X", "Multiple / Cross-persona", "Receivables & Payables", "Overdue supplier payment is identified", "P1"),
    ("X-0334", "X", "Multiple / Cross-persona", "Receivables & Payables", "Owner reviews supplier liabilities", "P1"),
    ("X-0335", "X", "Multiple / Cross-persona", "Receivables & Payables", "Accountant reconciles supplier ledger", "P1"),
    ("X-0336", "X", "Multiple / Cross-persona", "Receivables & Payables", "Supplier payment is linked to bank/cash transaction", "P1"),

    # Payments & Reconciliation (X-0337 to X-0352)
    ("X-0337", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Cash sale → cash balance increases", "P1"),
    ("X-0338", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "UPI sale → digital payment is recorded", "P1"),
    ("X-0339", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Bank payment → bank ledger updates", "P1"),
    ("X-0340", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Customer payment → receivable decreases", "P1"),
    ("X-0341", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Supplier payment → payable decreases", "P1"),
    ("X-0342", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Expense payment → expense ledger updates", "P1"),
    ("X-0343", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Payment reversal → original payment remains traceable", "P1"),
    ("X-0344", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Failed payment → invoice remains appropriately unpaid", "P1"),
    ("X-0345", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Partial payment → outstanding remains", "P1"),
    ("X-0346", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Multiple payments → invoice settlement is accurate", "P1"),
    ("X-0347", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Daily cash closing → expected versus actual cash is compared", "P1"),
    ("X-0348", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Cash discrepancy → variance is recorded", "P1"),
    ("X-0349", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Bank reconciliation → unmatched transactions are identified", "P1"),
    ("X-0350", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Payment reconciliation → business ledger matches payment records", "P1"),
    ("X-0351", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Owner reviews cash position", "P1"),
    ("X-0352", "X", "Multiple / Cross-persona", "Payments & Reconciliation", "Owner drills cash balance into transactions", "P1"),

    # Sales / CRM / Customer Lifecycle (X-0353 to X-0368)
    ("X-0353", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Create new customer", "P1"),
    ("X-0354", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Update customer profile", "P1"),
    ("X-0355", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Duplicate customer detection", "P1"),
    ("X-0356", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Customer inquiry → lead created", "P1"),
    ("X-0357", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Lead → follow-up task created", "P1"),
    ("X-0358", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Lead → quotation created", "P1"),
    ("X-0359", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Quotation → sales order", "P1"),
    ("X-0360", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Sales order → invoice", "P1"),
    ("X-0361", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Customer purchase → customer history updated", "P1"),
    ("X-0362", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Customer purchase history → salesperson sees context", "P1"),
    ("X-0363", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Customer complaint → support case created", "P1"),
    ("X-0364", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Support case → responsible employee assigned", "P1"),
    ("X-0365", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Complaint resolved → customer history updated", "P1"),
    ("X-0366", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Customer referral → referral recorded", "P1"),
    ("X-0367", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Customer becomes inactive → follow-up opportunity identified", "P1"),
    ("X-0368", "X", "Multiple / Cross-persona", "Sales / CRM / Customer Lifecycle", "Customer warranty/AMC → service obligation recorded", "P1"),

    # Returns / Complaints / After-Sales (X-0369 to X-0384)
    ("X-0369", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Customer requests return", "P1"),
    ("X-0370", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Salesperson creates return request", "P1"),
    ("X-0371", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Manager approves return", "P1"),
    ("X-0372", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Warehouse receives returned goods", "P1"),
    ("X-0373", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Returned goods inspected", "P1"),
    ("X-0374", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Good stock → inventory restored", "P1"),
    ("X-0375", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Damaged return → damaged inventory recorded", "P1"),
    ("X-0376", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Return → customer credit created", "P1"),
    ("X-0377", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Return → refund initiated", "P1"),
    ("X-0378", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Return → GST impact updated", "P1"),
    ("X-0379", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Customer complaint → support ticket", "P1"),
    ("X-0380", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Support ticket → owner/manager escalation", "P1"),
    ("X-0381", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Complaint resolution → customer notified", "P1"),
    ("X-0382", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Warranty claim → product/serial verified", "P1"),
    ("X-0383", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "Warranty claim → service action recorded", "P1"),
    ("X-0384", "X", "Multiple / Cross-persona", "Returns / Complaints / After-Sales", "AMC renewal → customer follow-up generated", "P1"),

    # Reporting & Business Intelligence (X-0385 to X-0406)
    ("X-0385", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Transaction → sales dashboard updates", "P1"),
    ("X-0386", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Transaction → purchase dashboard updates", "P1"),
    ("X-0387", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Transaction → inventory dashboard updates", "P1"),
    ("X-0388", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Transaction → GST dashboard updates", "P1"),
    ("X-0389", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Transaction → receivables dashboard updates", "P1"),
    ("X-0390", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Transaction → payables dashboard updates", "P1"),
    ("X-0391", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Transaction → profitability dashboard updates", "P1"),
    ("X-0392", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Owner drills KPI → underlying transaction", "P1"),
    ("X-0393", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Owner drills transaction → source document", "P1"),
    ("X-0394", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Salesperson sees personal sales performance", "P1"),
    ("X-0395", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Manager sees team performance", "P1"),
    ("X-0396", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Owner sees consolidated business performance", "P1"),
    ("X-0397", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Multi-shop owner compares locations", "P1"),
    ("X-0398", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Distributor compares customers", "P1"),
    ("X-0399", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Distributor compares products", "P1"),
    ("X-0400", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Owner identifies high-value customers", "P1"),
    ("X-0401", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Owner identifies low-margin products", "P1"),
    ("X-0402", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Owner identifies dead stock", "P1"),
    ("X-0403", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Owner identifies fast-moving products", "P1"),
    ("X-0404", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Owner identifies overdue receivables", "P1"),
    ("X-0405", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Owner identifies supplier concentration", "P1"),
    ("X-0406", "X", "Multiple / Cross-persona", "Reporting & Business Intelligence", "Owner reviews business trends", "P1"),

    # Master Data & Authorization (X-0407 to X-0421)
    ("X-0407", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Admin creates product → salesperson can sell it", "P1"),
    ("X-0408", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Admin creates product → purchase manager can purchase it", "P1"),
    ("X-0409", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Product HSN → invoice uses correct HSN", "P1"),
    ("X-0410", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Product tax rate → invoice uses configured tax", "P1"),
    ("X-0411", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Product unit → inventory quantities use correct unit", "P1"),
    ("X-0412", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Product batch configuration → GRN captures batch", "P1"),
    ("X-0413", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Product serial configuration → sale captures serial", "P1"),
    ("X-0414", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Customer master → sales invoice uses customer details", "P1"),
    ("X-0415", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Supplier master → purchase invoice uses supplier details", "P1"),
    ("X-0416", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Customer GSTIN → tax treatment uses GST status", "P1"),
    ("X-0417", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Supplier GSTIN → purchase tax treatment uses supplier status", "P1"),
    ("X-0418", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Price list → salesperson sees appropriate price", "P1"),
    ("X-0419", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Customer-specific pricing → correct price appears", "P1"),
    ("X-0420", "X", "Multiple / Cross-persona", "Master Data & Authorization", "User role → permitted actions are enforced", "P1"),
    ("X-0421", "X", "Multiple / Cross-persona", "Master Data & Authorization", "Location assignment → user sees authorized location data", "P1"),

    # Security / Exception / Recovery (X-0422 to X-0444)
    ("X-0422", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Salesperson creates invoice → cannot modify restricted accounting fields", "P1"),
    ("X-0423", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Inventory user adjusts stock → authorization is enforced", "P1"),
    ("X-0424", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Accountant modifies GST data → audit trail is created", "P1"),
    ("X-0425", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Manager approves adjustment → approval identity is recorded", "P1"),
    ("X-0426", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "User attempts unauthorized transaction → action is blocked", "P1"),
    ("X-0427", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "User changes role → permissions immediately reflect policy", "P1"),
    ("X-0428", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "User changes location → access follows assigned location", "P1"),
    ("X-0429", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Deactivated user → historical transactions remain intact", "P1"),
    ("X-0430", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Sensitive financial information → restricted users cannot access it", "P1"),
    ("X-0431", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Export data → export permissions are enforced", "P1"),
    ("X-0432", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Critical transaction → immutable audit trail exists", "P1"),
    ("X-0433", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Invalid invoice → actionable validation is shown", "P1"),
    ("X-0434", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Insufficient stock → sale is blocked/flagged appropriately", "P1"),
    ("X-0435", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Invalid GSTIN → invoice validation catches it", "P1"),
    ("X-0436", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Duplicate invoice → duplicate detection", "P1"),
    ("X-0437", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Network failure during save → no duplicate transaction is created", "P1"),
    ("X-0438", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Concurrent edits → conflict is handled", "P1"),
    ("X-0439", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Integration failure → transaction is not silently lost", "P1"),
    ("X-0440", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "GST integration failure → exception is visible", "P1"),
    ("X-0441", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Bulk operation failure → successful and failed records are separated", "P1"),
    ("X-0442", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Incorrect transaction → authorized correction mechanism exists", "P1"),
    ("X-0443", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "Cancellation → downstream impacts are correctly reversed", "P1"),
    ("X-0444", "X", "Multiple / Cross-persona", "Security / Exception / Recovery", "System recovery → financial/inventory integrity is preserved", "P1"),

    # Communication & Integrations (X-0445 to X-0461)
    ("X-0445", "X", "Multiple / Cross-persona", "Communication & Integrations", "Invoice generated → invoice sent to customer through WhatsApp", "P1"),
    ("X-0446", "X", "Multiple / Cross-persona", "Communication & Integrations", "Payment reminder → customer receives reminder", "P1"),
    ("X-0447", "X", "Multiple / Cross-persona", "Communication & Integrations", "Order confirmation → customer receives confirmation", "P1"),
    ("X-0448", "X", "Multiple / Cross-persona", "Communication & Integrations", "Delivery update → customer receives update", "P1"),
    ("X-0449", "X", "Multiple / Cross-persona", "Communication & Integrations", "Return confirmation → customer receives confirmation", "P1"),
    ("X-0450", "X", "Multiple / Cross-persona", "Communication & Integrations", "Payment receipt → customer receives receipt", "P1"),
    ("X-0451", "X", "Multiple / Cross-persona", "Communication & Integrations", "Failed message → delivery status is visible", "P1"),
    ("X-0452", "X", "Multiple / Cross-persona", "Communication & Integrations", "User resends failed message", "P1"),
    ("X-0453", "X", "Multiple / Cross-persona", "Communication & Integrations", "Communication history remains associated with transaction/customer", "P1"),
    ("X-0454", "X", "Multiple / Cross-persona", "Communication & Integrations", "Payment gateway → payment status", "P1"),
    ("X-0455", "X", "Multiple / Cross-persona", "Communication & Integrations", "Payment gateway → customer ledger", "P1"),
    ("X-0456", "X", "Multiple / Cross-persona", "Communication & Integrations", "Payment gateway → invoice settlement", "P1"),
    ("X-0457", "X", "Multiple / Cross-persona", "Communication & Integrations", "Accounting export → downstream accounting", "P1"),
    ("X-0458", "X", "Multiple / Cross-persona", "Communication & Integrations", "Accounting data → reconciliation", "P1"),
    ("X-0459", "X", "Multiple / Cross-persona", "Communication & Integrations", "Integration failure → retry", "P1"),
    ("X-0460", "X", "Multiple / Cross-persona", "Communication & Integrations", "Integration retry → idempotent result", "P1"),
    ("X-0461", "X", "Multiple / Cross-persona", "Communication & Integrations", "External reference ID → BizBoard transaction traceability", "P1"),

    # Import / Export / Period Close (X-0462 to X-0494)
    ("X-0462", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Import customer master", "P1"),
    ("X-0463", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Import supplier master", "P1"),
    ("X-0464", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Import product master", "P1"),
    ("X-0465", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Import opening stock", "P1"),
    ("X-0466", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Import opening customer balances", "P1"),
    ("X-0467", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Import opening supplier balances", "P1"),
    ("X-0468", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Import historical invoices", "P1"),
    ("X-0469", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Import GST data", "P1"),
    ("X-0470", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Validate imported records", "P1"),
    ("X-0471", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Identify duplicate imported records", "P1"),
    ("X-0472", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Reject invalid records without corrupting valid records", "P1"),
    ("X-0473", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Export sales data", "P1"),
    ("X-0474", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Export purchase data", "P1"),
    ("X-0475", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Export inventory data", "P1"),
    ("X-0476", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Export GST data", "P1"),
    ("X-0477", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Export customer ledger", "P1"),
    ("X-0478", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Export supplier ledger", "P1"),
    ("X-0479", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Export accounting data", "P1"),
    ("X-0480", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Imported data becomes available to downstream modules", "P1"),
    ("X-0481", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Exported data reconciles with on-screen business data", "P1"),
    ("X-0482", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Cashier closes day's sales", "P1"),
    ("X-0483", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Cashier reconciles cash", "P1"),
    ("X-0484", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Digital payments are reconciled", "P1"),
    ("X-0485", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Owner reviews daily sales", "P1"),
    ("X-0486", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Owner reviews daily gross margin", "P1"),
    ("X-0487", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Owner reviews outstanding collections", "P1"),
    ("X-0488", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Owner reviews inventory movements", "P1"),
    ("X-0489", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Owner reviews exceptions", "P1"),
    ("X-0490", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Accountant reconciles sales", "P1"),
    ("X-0491", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Accountant reconciles purchases", "P1"),
    ("X-0492", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Accountant reconciles payments", "P1"),
    ("X-0493", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Period closing prevents unauthorized historical modification", "P1"),
    ("X-0494", "X", "Multiple / Cross-persona", "Import / Export / Period Close", "Period reports remain reproducible", "P1")
]

ALL_TASKS_RAW = RAW_TASKS + CROSS_TASKS

print(f"Total tasks to enrich: {len(ALL_TASKS_RAW)}")
