#!/usr/bin/env bash
# Wave 16A / BB-000470: resolve GHCR image digests and rewrite compose image refs.
# Usage:
#   ./scripts/pin_image_digests.sh ghcr.io/org/bizboard-api:SHA ghcr.io/org/bizboard-web:SHA
# Requires: docker (or crane), write access to a deploy compose overlay.
set -euo pipefail

API_REF="${1:?api image ref required e.g. ghcr.io/org/bizboard-api:abc123}"
WEB_REF="${2:?web image ref required}"

resolve_digest() {
  local ref="$1"
  if command -v crane >/dev/null 2>&1; then
    crane digest "${ref}"
  else
    docker buildx imagetools inspect "${ref}" --format '{{.Manifest.Digest}}' 2>/dev/null \
      || docker inspect --format='{{index .RepoDigests 0}}' "${ref}" | awk -F@ '{print $2}'
  fi
}

API_DIGEST=$(resolve_digest "${API_REF}")
WEB_DIGEST=$(resolve_digest "${WEB_REF}")
API_REPO="${API_REF%%:*}"
WEB_REPO="${WEB_REF%%:*}"

OUT="${3:-docker-compose.digest.yml}"
cat > "${OUT}" <<EOF
# Auto-generated by pin_image_digests.sh — prefer digest pins over mutable tags.
# Host-side verify remains an ops Final Gate (BB-000470).
services:
  api:
    image: ${API_REPO}@${API_DIGEST}
  worker:
    image: ${API_REPO}@${API_DIGEST}
  beat:
    image: ${API_REPO}@${API_DIGEST}
  web:
    image: ${WEB_REPO}@${WEB_DIGEST}
EOF
echo "Wrote ${OUT}"
echo "api=${API_REPO}@${API_DIGEST}"
echo "web=${WEB_REPO}@${WEB_DIGEST}"
