# -*- coding: utf-8 -*-
"""
BizBoard Master Task & Persona Register Populator
Parses the 494 tasks (188 Persona tasks + 306 Cross-Persona tasks),
fills all missing fields (Category, Primary Actor, Supporting Persona(s),
Business Outcome, Downstream Impact, Priority, Validation Status, Notes),
and outputs both formatted CSV and styled Excel (.xlsx) workbooks.
"""

import csv
import os
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# Raw task definition tuples: (Task ID, Task Type, Persona / Scope, Category, Task / Business Action, Priority)
# Categories for P-0001 to P-0188 are inferred from domain logic.
RAW_TASKS = [
    # Gully Vendor / Small Retailer (P-0001 to P-0017)
    ("P-0001", "P", "Gully Vendor / Small Retailer", "Customer-to-Cash", "Create a quick bill for a walk-in customer", "P0"),
    ("P-0002", "P", "Gully Vendor / Small Retailer", "Payments & Reconciliation", "Record a cash sale", "P0"),
    ("P-0003", "P", "Gully Vendor / Small Retailer", "Payments & Reconciliation", "Record a UPI/digital payment", "P0"),
    ("P-0004", "P", "Gully Vendor / Small Retailer", "Customer-to-Cash", "Find an item's price instantly", "P1"),
    ("P-0005", "P", "Gully Vendor / Small Retailer", "Reporting & Business Intelligence", "Check today's total sales", "P1"),
    ("P-0006", "P", "Gully Vendor / Small Retailer", "Payments & Reconciliation", "Check cash/UPI collected", "P1"),
    ("P-0007", "P", "Gully Vendor / Small Retailer", "Inventory Lifecycle", "See low-stock items", "P1"),
    ("P-0008", "P", "Gully Vendor / Small Retailer", "Master Data & Authorization", "Add a new item while making a sale", "P2"),
    ("P-0009", "P", "Gully Vendor / Small Retailer", "Receivables & Payables", "Record a customer credit sale", "P1"),
    ("P-0010", "P", "Gully Vendor / Small Retailer", "Receivables & Payables", "Record payment from a customer", "P1"),
    ("P-0011", "P", "Gully Vendor / Small Retailer", "Receivables & Payables", "See outstanding customer dues", "P1"),
    ("P-0012", "P", "Gully Vendor / Small Retailer", "Communication & Integrations", "Send invoice/receipt", "P1"),
    ("P-0013", "P", "Gully Vendor / Small Retailer", "Security / Exception / Recovery", "Cancel or correct a wrongly created bill", "P1"),
    ("P-0014", "P", "Gully Vendor / Small Retailer", "Returns / Complaints / After-Sales", "Process a sales return", "P1"),
    ("P-0015", "P", "Gully Vendor / Small Retailer", "Reporting & Business Intelligence", "Check today's profit/margin", "P2"),
    ("P-0016", "P", "Gully Vendor / Small Retailer", "GST / Tax / Compliance", "See GST collected", "P2"),
    ("P-0017", "P", "Gully Vendor / Small Retailer", "Import / Export / Period Close", "Close the day's business", "P1"),

    # Kirana Shop Owner (P-0018 to P-0037)
    ("P-0018", "P", "Kirana Shop Owner", "Customer-to-Cash", "Create a customer invoice", "P0"),
    ("P-0019", "P", "Kirana Shop Owner", "Procure-to-Pay", "Create a supplier purchase entry", "P1"),
    ("P-0020", "P", "Kirana Shop Owner", "Procure-to-Pay", "Receive purchased goods", "P1"),
    ("P-0021", "P", "Kirana Shop Owner", "Master Data & Authorization", "Update purchase and selling prices", "P1"),
    ("P-0022", "P", "Kirana Shop Owner", "Inventory Lifecycle", "Track stock quantity", "P0"),
    ("P-0023", "P", "Kirana Shop Owner", "Inventory Lifecycle", "Identify low-stock items", "P1"),
    ("P-0024", "P", "Kirana Shop Owner", "Reporting & Business Intelligence", "Identify fast-moving items", "P2"),
    ("P-0025", "P", "Kirana Shop Owner", "Reporting & Business Intelligence", "Identify slow-moving/dead stock", "P2"),
    ("P-0026", "P", "Kirana Shop Owner", "Receivables & Payables", "Track customer credit", "P1"),
    ("P-0027", "P", "Kirana Shop Owner", "Receivables & Payables", "Collect customer payments", "P1"),
    ("P-0028", "P", "Kirana Shop Owner", "Receivables & Payables", "Track supplier outstanding", "P1"),
    ("P-0029", "P", "Kirana Shop Owner", "Receivables & Payables", "Record supplier payment", "P1"),
    ("P-0030", "P", "Kirana Shop Owner", "Returns / Complaints / After-Sales", "Process sales returns", "P1"),
    ("P-0031", "P", "Kirana Shop Owner", "Returns / Complaints / After-Sales", "Process purchase returns", "P1"),
    ("P-0032", "P", "Kirana Shop Owner", "Customer-to-Cash", "Apply discounts correctly", "P2"),
    ("P-0033", "P", "Kirana Shop Owner", "GST / Tax / Compliance", "Manage GST rates/HSN", "P1"),
    ("P-0034", "P", "Kirana Shop Owner", "GST / Tax / Compliance", "Generate GST-compliant invoices", "P0"),
    ("P-0035", "P", "Kirana Shop Owner", "Reporting & Business Intelligence", "Review sales", "P1"),
    ("P-0036", "P", "Kirana Shop Owner", "Reporting & Business Intelligence", "Review gross margin", "P2"),
    ("P-0037", "P", "Kirana Shop Owner", "Payments & Reconciliation", "Reconcile cash and digital payments", "P1"),

    # Medical Shop (P-0038 to P-0051)
    ("P-0038", "P", "Medical Shop", "Customer-to-Cash", "Sell medicines with batch information", "P0"),
    ("P-0039", "P", "Medical Shop", "Inventory Lifecycle", "Track batch-wise inventory", "P0"),
    ("P-0040", "P", "Medical Shop", "Inventory Lifecycle", "Track expiry dates", "P0"),
    ("P-0041", "P", "Medical Shop", "Inventory Lifecycle", "Flag/prevent expired-stock sales", "P0"),
    ("P-0042", "P", "Medical Shop", "Inventory Lifecycle", "Identify near-expiry inventory", "P1"),
    ("P-0043", "P", "Medical Shop", "Procure-to-Pay", "Record purchases by batch", "P0"),
    ("P-0044", "P", "Medical Shop", "Inventory Lifecycle", "Track medicine stock", "P1"),
    ("P-0045", "P", "Medical Shop", "Returns / Complaints / After-Sales", "Handle medicine returns", "P1"),
    ("P-0046", "P", "Medical Shop", "Customer-to-Cash", "Search medicines while billing", "P0"),
    ("P-0047", "P", "Medical Shop", "Master Data & Authorization", "Maintain MRP and selling price", "P1"),
    ("P-0048", "P", "Medical Shop", "Procure-to-Pay", "Track supplier-wise purchases", "P1"),
    ("P-0049", "P", "Medical Shop", "GST / Tax / Compliance", "Generate GST-compliant medicine invoices", "P0"),
    ("P-0050", "P", "Medical Shop", "Inventory Lifecycle", "Identify expiry-risk stock", "P1"),
    ("P-0051", "P", "Medical Shop", "Reporting & Business Intelligence", "View profitability by item/category", "P2"),

    # Distributor (P-0052 to P-0067)
    ("P-0052", "P", "Distributor", "Customer-to-Cash", "Create bulk sales invoices", "P0"),
    ("P-0053", "P", "Distributor", "Customer-to-Cash", "Process retailer orders", "P1"),
    ("P-0054", "P", "Distributor", "Inventory Lifecycle", "Allocate inventory against orders", "P1"),
    ("P-0055", "P", "Distributor", "Customer-to-Cash", "Generate delivery documents", "P1"),
    ("P-0056", "P", "Distributor", "Customer-to-Cash", "Track pending customer orders", "P1"),
    ("P-0057", "P", "Distributor", "Receivables & Payables", "Track customer outstanding", "P0"),
    ("P-0058", "P", "Distributor", "Receivables & Payables", "Manage credit limits", "P0"),
    ("P-0059", "P", "Distributor", "Receivables & Payables", "Record customer collections", "P1"),
    ("P-0060", "P", "Distributor", "Procure-to-Pay", "Track supplier purchases", "P1"),
    ("P-0061", "P", "Distributor", "Inventory Lifecycle", "Manage large inventory volumes", "P1"),
    ("P-0062", "P", "Distributor", "Multi-Godown / Multi-Store", "Transfer stock between warehouses", "P1"),
    ("P-0063", "P", "Distributor", "Inventory Lifecycle", "Track batch/serial inventory", "P1"),
    ("P-0064", "P", "Distributor", "Inventory Lifecycle", "Track expiry-risk stock", "P1"),
    ("P-0065", "P", "Distributor", "Reporting & Business Intelligence", "Analyze customer profitability", "P2"),
    ("P-0066", "P", "Distributor", "Reporting & Business Intelligence", "Analyze product profitability", "P2"),
    ("P-0067", "P", "Distributor", "Payments & Reconciliation", "Reconcile receivables and payments", "P1"),

    # Single-Godown Distributor (P-0068 to P-0078)
    ("P-0068", "P", "Single-Godown Distributor", "Procure-to-Pay", "Receive stock into godown", "P1"),
    ("P-0069", "P", "Single-Godown Distributor", "Inventory Lifecycle", "Allocate stock to customer orders", "P1"),
    ("P-0070", "P", "Single-Godown Distributor", "Customer-to-Cash", "Pick and dispatch customer orders", "P1"),
    ("P-0071", "P", "Single-Godown Distributor", "Inventory Lifecycle", "Track available and committed stock", "P1"),
    ("P-0072", "P", "Single-Godown Distributor", "Inventory Lifecycle", "Track damaged stock", "P1"),
    ("P-0073", "P", "Single-Godown Distributor", "Returns / Complaints / After-Sales", "Track returned stock", "P1"),
    ("P-0074", "P", "Single-Godown Distributor", "Inventory Lifecycle", "Perform physical stock verification", "P1"),
    ("P-0075", "P", "Single-Godown Distributor", "Inventory Lifecycle", "Identify inventory discrepancies", "P1"),
    ("P-0076", "P", "Single-Godown Distributor", "Inventory Lifecycle", "Generate stock valuation", "P2"),
    ("P-0077", "P", "Single-Godown Distributor", "Inventory Lifecycle", "Track FIFO inventory costing", "P2"),
    ("P-0078", "P", "Single-Godown Distributor", "Inventory Lifecycle", "Monitor reorder requirements", "P1"),

    # Multi-Godown Distributor (P-0079 to P-0088)
    ("P-0079", "P", "Multi-Godown Distributor", "Multi-Godown / Multi-Store", "View consolidated inventory", "P0"),
    ("P-0080", "P", "Multi-Godown Distributor", "Multi-Godown / Multi-Store", "Check stock by location", "P1"),
    ("P-0081", "P", "Multi-Godown Distributor", "Multi-Godown / Multi-Store", "Transfer stock between godowns", "P0"),
    ("P-0082", "P", "Multi-Godown Distributor", "Multi-Godown / Multi-Store", "Allocate orders to the appropriate godown", "P1"),
    ("P-0083", "P", "Multi-Godown Distributor", "Multi-Godown / Multi-Store", "Track inter-godown transfers", "P1"),
    ("P-0084", "P", "Multi-Godown Distributor", "Reporting & Business Intelligence", "Compare godown-wise sales", "P2"),
    ("P-0085", "P", "Multi-Godown Distributor", "Reporting & Business Intelligence", "Compare godown-wise profitability", "P2"),
    ("P-0086", "P", "Multi-Godown Distributor", "Multi-Godown / Multi-Store", "Identify stock imbalance", "P2"),
    ("P-0087", "P", "Multi-Godown Distributor", "Inventory Lifecycle", "Perform location-wise stock audits", "P1"),
    ("P-0088", "P", "Multi-Godown Distributor", "Multi-Godown / Multi-Store", "Track inventory movement across locations", "P1"),

    # Multi-Shop Owner (P-0089 to P-0099)
    ("P-0089", "P", "Multi-Shop Owner", "Multi-Godown / Multi-Store", "View all shops from one dashboard", "P0"),
    ("P-0090", "P", "Multi-Shop Owner", "Reporting & Business Intelligence", "Compare shop sales", "P1"),
    ("P-0091", "P", "Multi-Shop Owner", "Reporting & Business Intelligence", "Compare shop profitability", "P2"),
    ("P-0092", "P", "Multi-Shop Owner", "Multi-Godown / Multi-Store", "Transfer inventory between shops", "P1"),
    ("P-0093", "P", "Multi-Shop Owner", "Multi-Godown / Multi-Store", "Monitor shop-wise inventory", "P1"),
    ("P-0094", "P", "Multi-Shop Owner", "Payments & Reconciliation", "Monitor shop-wise cash collections", "P1"),
    ("P-0095", "P", "Multi-Shop Owner", "Receivables & Payables", "Monitor shop-wise outstanding", "P1"),
    ("P-0096", "P", "Multi-Shop Owner", "Reporting & Business Intelligence", "Consolidate business performance", "P1"),
    ("P-0097", "P", "Multi-Shop Owner", "Reporting & Business Intelligence", "Identify underperforming locations", "P2"),
    ("P-0098", "P", "Multi-Shop Owner", "Master Data & Authorization", "Manage centralized product masters", "P1"),
    ("P-0099", "P", "Multi-Shop Owner", "Security / Exception / Recovery", "Control user access by shop", "P0"),

    # Accountant / GST Operator (P-0100 to P-0115)
    ("P-0100", "P", "Accountant / GST Operator", "GST / Tax / Compliance", "Review sales transactions", "P1"),
    ("P-0101", "P", "Accountant / GST Operator", "GST / Tax / Compliance", "Review purchase transactions", "P1"),
    ("P-0102", "P", "Accountant / GST Operator", "GST / Tax / Compliance", "Validate GST data", "P0"),
    ("P-0103", "P", "Accountant / GST Operator", "GST / Tax / Compliance", "Identify missing GST information", "P1"),
    ("P-0104", "P", "Accountant / GST Operator", "GST / Tax / Compliance", "Reconcile purchase records with GST data", "P0"),
    ("P-0105", "P", "Accountant / GST Operator", "GST / Tax / Compliance", "Review GSTR-2B/IMS information", "P1"),
    ("P-0106", "P", "Accountant / GST Operator", "GST / Tax / Compliance", "Accept/reject/pending invoice actions", "P1"),
    ("P-0107", "P", "Accountant / GST Operator", "GST / Tax / Compliance", "Identify ITC at risk", "P0"),
    ("P-0108", "P", "Accountant / GST Operator", "GST / Tax / Compliance", "Track Section 16(4) deadlines", "P1"),
    ("P-0109", "P", "Accountant / GST Operator", "GST / Tax / Compliance", "Identify supplier invoice defects", "P1"),
    ("P-0110", "P", "Accountant / GST Operator", "GST / Tax / Compliance", "Prepare GST returns", "P0"),
    ("P-0111", "P", "Accountant / GST Operator", "Import / Export / Period Close", "Export accounting data", "P1"),
    ("P-0112", "P", "Accountant / GST Operator", "GST / Tax / Compliance", "Reconcile books with GST records", "P1"),
    ("P-0113", "P", "Accountant / GST Operator", "Security / Exception / Recovery", "Identify duplicate transactions", "P1"),
    ("P-0114", "P", "Accountant / GST Operator", "GST / Tax / Compliance", "Identify tax calculation errors", "P0"),
    ("P-0115", "P", "Accountant / GST Operator", "Security / Exception / Recovery", "Maintain an audit trail", "P0"),

    # Business Owner (P-0116 to P-0128)
    ("P-0116", "P", "Business Owner", "Reporting & Business Intelligence", "See today's business performance", "P0"),
    ("P-0117", "P", "Business Owner", "Reporting & Business Intelligence", "See sales, purchases and profit together", "P1"),
    ("P-0118", "P", "Business Owner", "Receivables & Payables", "Identify outstanding receivables", "P0"),
    ("P-0119", "P", "Business Owner", "Receivables & Payables", "Identify overdue payments", "P0"),
    ("P-0120", "P", "Business Owner", "Inventory Lifecycle", "Identify low-stock products", "P1"),
    ("P-0121", "P", "Business Owner", "Reporting & Business Intelligence", "Identify profitable products", "P2"),
    ("P-0122", "P", "Business Owner", "Reporting & Business Intelligence", "Identify loss-making products", "P2"),
    ("P-0123", "P", "Business Owner", "Reporting & Business Intelligence", "Compare performance across periods", "P2"),
    ("P-0124", "P", "Business Owner", "GST / Tax / Compliance", "Monitor GST liability", "P1"),
    ("P-0125", "P", "Business Owner", "Payments & Reconciliation", "Monitor cash flow", "P1"),
    ("P-0126", "P", "Business Owner", "Reporting & Business Intelligence", "Review business alerts", "P1"),
    ("P-0127", "P", "Business Owner", "Reporting & Business Intelligence", "Drill down from KPI to transactions", "P1"),
    ("P-0128", "P", "Business Owner", "Security / Exception / Recovery", "Approve important business actions", "P0"),

    # Salesperson (P-0129 to P-0138)
    ("P-0129", "P", "Salesperson", "Sales / CRM / Customer Lifecycle", "Create a customer/order", "P1"),
    ("P-0130", "P", "Salesperson", "Sales / CRM / Customer Lifecycle", "Search customer history", "P1"),
    ("P-0131", "P", "Salesperson", "Sales / CRM / Customer Lifecycle", "Create a quotation", "P1"),
    ("P-0132", "P", "Salesperson", "Sales / CRM / Customer Lifecycle", "Convert quotation into an order", "P1"),
    ("P-0133", "P", "Salesperson", "Inventory Lifecycle", "Check product availability", "P0"),
    ("P-0134", "P", "Salesperson", "Sales / CRM / Customer Lifecycle", "Record customer follow-up", "P2"),
    ("P-0135", "P", "Salesperson", "Customer-to-Cash", "Track pending orders", "P1"),
    ("P-0136", "P", "Salesperson", "Receivables & Payables", "Record customer payment", "P1"),
    ("P-0137", "P", "Salesperson", "Receivables & Payables", "View customer outstanding", "P1"),
    ("P-0138", "P", "Salesperson", "Reporting & Business Intelligence", "Track sales performance", "P2"),

    # Purchase Manager (P-0139 to P-0148)
    ("P-0139", "P", "Purchase Manager", "Procure-to-Pay", "Create a purchase order", "P1"),
    ("P-0140", "P", "Purchase Manager", "Procure-to-Pay", "Send/order products from supplier", "P1"),
    ("P-0141", "P", "Purchase Manager", "Procure-to-Pay", "Receive goods against purchase order", "P1"),
    ("P-0142", "P", "Purchase Manager", "Procure-to-Pay", "Record GRN", "P1"),
    ("P-0143", "P", "Purchase Manager", "Procure-to-Pay", "Compare ordered versus received quantities", "P1"),
    ("P-0144", "P", "Purchase Manager", "Inventory Lifecycle", "Record damaged/short stock", "P1"),
    ("P-0145", "P", "Purchase Manager", "Procure-to-Pay", "Update supplier invoice", "P1"),
    ("P-0146", "P", "Purchase Manager", "Receivables & Payables", "Track supplier outstanding", "P1"),
    ("P-0147", "P", "Purchase Manager", "Procure-to-Pay", "Identify best-priced suppliers", "P2"),
    ("P-0148", "P", "Purchase Manager", "Procure-to-Pay", "Review supplier performance", "P2"),

    # Inventory Manager (P-0149 to P-0161)
    ("P-0149", "P", "Inventory Manager", "Inventory Lifecycle", "View current inventory", "P0"),
    ("P-0150", "P", "Inventory Manager", "Inventory Lifecycle", "Receive stock", "P1"),
    ("P-0151", "P", "Inventory Manager", "Multi-Godown / Multi-Store", "Transfer stock", "P1"),
    ("P-0152", "P", "Inventory Manager", "Inventory Lifecycle", "Adjust stock with authorization", "P0"),
    ("P-0153", "P", "Inventory Manager", "Inventory Lifecycle", "Record damaged stock", "P1"),
    ("P-0154", "P", "Inventory Manager", "Returns / Complaints / After-Sales", "Record returned stock", "P1"),
    ("P-0155", "P", "Inventory Manager", "Inventory Lifecycle", "Perform stock count", "P1"),
    ("P-0156", "P", "Inventory Manager", "Inventory Lifecycle", "Reconcile physical versus system stock", "P1"),
    ("P-0157", "P", "Inventory Manager", "Inventory Lifecycle", "Track batch/serial numbers", "P1"),
    ("P-0158", "P", "Inventory Manager", "Inventory Lifecycle", "Track expiry", "P0"),
    ("P-0159", "P", "Inventory Manager", "Inventory Lifecycle", "Calculate inventory valuation", "P2"),
    ("P-0160", "P", "Inventory Manager", "Inventory Lifecycle", "Investigate stock discrepancies", "P1"),
    ("P-0161", "P", "Inventory Manager", "Inventory Lifecycle", "Review inventory movement history", "P1"),

    # Customer (P-0162 to P-0169)
    ("P-0162", "P", "Customer", "Customer-to-Cash", "Receive invoice", "P1"),
    ("P-0163", "P", "Customer", "Sales / CRM / Customer Lifecycle", "View purchase history", "P2"),
    ("P-0164", "P", "Customer", "Receivables & Payables", "Receive dues information", "P1"),
    ("P-0165", "P", "Customer", "Payments & Reconciliation", "Make payment", "P1"),
    ("P-0166", "P", "Customer", "Returns / Complaints / After-Sales", "Request return", "P1"),
    ("P-0167", "P", "Customer", "Returns / Complaints / After-Sales", "Request replacement", "P2"),
    ("P-0168", "P", "Customer", "Receivables & Payables", "View outstanding balance", "P2"),
    ("P-0169", "P", "Customer", "Customer-to-Cash", "Receive order/status updates", "P2"),

    # Supplier (P-0170 to P-0175)
    ("P-0170", "P", "Supplier", "Procure-to-Pay", "Receive purchase/order information", "P1"),
    ("P-0171", "P", "Supplier", "Procure-to-Pay", "Provide invoice", "P1"),
    ("P-0172", "P", "Supplier", "Receivables & Payables", "Track payment status", "P2"),
    ("P-0173", "P", "Supplier", "Receivables & Payables", "View outstanding amount", "P2"),
    ("P-0174", "P", "Supplier", "Returns / Complaints / After-Sales", "Handle purchase returns", "P1"),
    ("P-0175", "P", "Supplier", "Procure-to-Pay", "Resolve invoice discrepancies", "P1"),

    # Admin / System Owner (P-0176 to P-0188)
    ("P-0176", "P", "Admin / System Owner", "Master Data & Authorization", "Create and manage business users", "P0"),
    ("P-0177", "P", "Admin / System Owner", "Master Data & Authorization", "Configure roles and permissions", "P0"),
    ("P-0178", "P", "Admin / System Owner", "Master Data & Authorization", "Configure business settings", "P0"),
    ("P-0179", "P", "Admin / System Owner", "GST / Tax / Compliance", "Configure GST information", "P0"),
    ("P-0180", "P", "Admin / System Owner", "Multi-Godown / Multi-Store", "Configure branches/godowns", "P0"),
    ("P-0181", "P", "Admin / System Owner", "GST / Tax / Compliance", "Configure taxes and HSN", "P0"),
    ("P-0182", "P", "Admin / System Owner", "Customer-to-Cash", "Configure invoice templates", "P2"),
    ("P-0183", "P", "Admin / System Owner", "Communication & Integrations", "Configure integrations", "P1"),
    ("P-0184", "P", "Admin / System Owner", "Security / Exception / Recovery", "Review system activity", "P1"),
    ("P-0185", "P", "Admin / System Owner", "Security / Exception / Recovery", "Review audit logs", "P0"),
    ("P-0186", "P", "Admin / System Owner", "Import / Export / Period Close", "Manage data imports/exports", "P1"),
    ("P-0187", "P", "Admin / System Owner", "Security / Exception / Recovery", "Manage backups/recovery", "P0"),
    ("P-0188", "P", "Admin / System Owner", "Security / Exception / Recovery", "Monitor system health", "P1"),
]

# Next, we build the cross-persona task list (X-0189 to X-0494)
# We will read them directly from the provided specification.
CROSS_TASKS_DEFS = [
    # Customer-to-Cash (X-0189 to X-0210)
    ("X-0189", "Customer order → salesperson records order → inventory availability is checked"),
    ("X-0190", "Customer accepts quotation → quotation converts to sales order"),
    ("X-0191", "Sales order → inventory is reserved → available stock is updated"),
    ("X-0192", "Sales order → warehouse receives picking request"),
    ("X-0193", "Warehouse picks stock → order becomes ready for dispatch"),
    ("X-0194", "Order dispatched → delivery status is recorded"),
    ("X-0195", "Delivery completed → invoice is generated"),
    ("X-0196", "Invoice generated → inventory is reduced"),
    ("X-0197", "Invoice generated → customer receivable is created"),
    ("X-0198", "Invoice generated → GST liability is calculated"),
    ("X-0199", "Customer pays → payment is recorded"),
    ("X-0200", "Payment recorded → customer outstanding decreases"),
    ("X-0201", "Partial payment → remaining outstanding is maintained"),
    ("X-0202", "Customer exceeds credit limit → sale/order is flagged or blocked"),
    ("X-0203", "Invoice becomes overdue → receivable ageing changes"),
    ("X-0204", "Overdue invoice → owner receives business alert"),
    ("X-0205", "Customer requests return → return request is recorded"),
    ("X-0206", "Return approved → inventory is restored where applicable"),
    ("X-0207", "Return approved → customer credit/refund is created"),
    ("X-0208", "Sales return → GST impact is recalculated"),
    ("X-0209", "Refund processed → customer balance is updated"),
    ("X-0210", "Invoice corrected → correction history remains auditable"),

    # Procure-to-Pay (X-0211 to X-0234)
    ("X-0211", "Purchase manager creates purchase order"),
    ("X-0212", "Purchase order → supplier receives order"),
    ("X-0213", "Supplier confirms order → order status changes"),
    ("X-0214", "Supplier ships goods → expected receipt is recorded"),
    ("X-0215", "Goods arrive → warehouse creates GRN"),
    ("X-0216", "GRN → inventory quantity increases"),
    ("X-0217", "GRN → batch/serial information is captured"),
    ("X-0218", "GRN → damaged/short quantity is recorded"),
    ("X-0219", "GRN → purchase order received quantity is updated"),
    ("X-0220", "Supplier invoice arrives → invoice is matched against PO/GRN"),
    ("X-0221", "Quantity mismatch → exception is generated"),
    ("X-0222", "Price mismatch → exception is generated"),
    ("X-0223", "Tax mismatch → exception is generated"),
    ("X-0224", "Supplier invoice accepted → payable is created"),
    ("X-0225", "Purchase → GST input tax is calculated"),
    ("X-0226", "Purchase → eligible ITC is identified"),
    ("X-0227", "Supplier payment recorded → payable decreases"),
    ("X-0228", "Partial supplier payment → remaining payable is maintained"),
    ("X-0229", "Supplier credit note → payable and tax impact are adjusted"),
    ("X-0230", "Purchase return → inventory decreases"),
    ("X-0231", "Purchase return → supplier balance is adjusted"),
    ("X-0232", "Purchase return → GST impact is adjusted"),
    ("X-0233", "Supplier invoice discrepancy → accountant is alerted"),
    ("X-0234", "Supplier invoice correction → original transaction remains traceable"),

    # Inventory Lifecycle (X-0235 to X-0257)
    ("X-0235", "Purchase receipt → stock enters inventory"),
    ("X-0236", "Sale → stock leaves inventory"),
    ("X-0237", "Sales return → stock comes back into inventory"),
    ("X-0238", "Purchase return → stock leaves inventory"),
    ("X-0239", "Stock transfer → source location decreases"),
    ("X-0240", "Stock transfer → destination location increases"),
    ("X-0241", "Stock transfer → complete movement history is retained"),
    ("X-0242", "Stock adjustment → authorized user approves adjustment"),
    ("X-0243", "Stock adjustment → inventory ledger records adjustment"),
    ("X-0244", "Damaged stock → inventory is separated from saleable stock"),
    ("X-0245", "Lost stock → inventory adjustment is recorded"),
    ("X-0246", "Expired stock → sale is prevented/flagged"),
    ("X-0247", "Near-expiry stock → owner receives alert"),
    ("X-0248", "Batch sale → specific batch quantity decreases"),
    ("X-0249", "Serial-number sale → serial is marked as sold"),
    ("X-0250", "Serial-number return → serial becomes available/returned according to policy"),
    ("X-0251", "Physical stock count → system stock is compared"),
    ("X-0252", "Stock variance → discrepancy is created"),
    ("X-0253", "Discrepancy approval → inventory adjustment occurs"),
    ("X-0254", "Inventory adjustment → audit trail records who/why/when"),
    ("X-0255", "FIFO costing → correct cost is assigned to sale"),
    ("X-0256", "Inventory valuation → owner sees current stock value"),
    ("X-0257", "Inventory movement → historical transaction remains immutable"),

    # Multi-Godown / Multi-Store (X-0258 to X-0277)
    ("X-0258", "Shop requests stock from godown"),
    ("X-0259", "Godown approves stock request"),
    ("X-0260", "Godown allocates stock"),
    ("X-0261", "Goods dispatched from godown"),
    ("X-0262", "Destination receives goods"),
    ("X-0263", "Source inventory decreases"),
    ("X-0264", "Destination inventory increases"),
    ("X-0265", "Transfer discrepancy is recorded"),
    ("X-0266", "Transfer damage is recorded"),
    ("X-0267", "Transfer cancellation reverses appropriate inventory state"),
    ("X-0268", "Owner views consolidated inventory"),
    ("X-0269", "Owner drills from consolidated stock to location"),
    ("X-0270", "Owner compares location-wise sales"),
    ("X-0271", "Owner compares location-wise inventory"),
    ("X-0272", "Owner compares location-wise profitability"),
    ("X-0273", "One store requests stock from another store"),
    ("X-0274", "Inter-store transfer is authorized"),
    ("X-0275", "Stock is moved between stores"),
    ("X-0276", "Location-specific user sees only authorized inventory"),
    ("X-0277", "Central accountant sees consolidated accounting"),

    # GST / Tax / Compliance (X-0278 to X-0306)
    ("X-0278", "Sales invoice → GST calculation"),
    ("X-0279", "Purchase invoice → input GST calculation"),
    ("X-0280", "HSN selection → appropriate tax treatment"),
    ("X-0281", "Customer GSTIN → invoice tax treatment"),
    ("X-0282", "Supplier GSTIN → purchase tax treatment"),
    ("X-0283", "Intra-state transaction → CGST/SGST treatment"),
    ("X-0284", "Inter-state transaction → IGST treatment"),
    ("X-0285", "GST invoice → reporting dataset is updated"),
    ("X-0286", "Invoice cancellation → GST/reporting data is updated"),
    ("X-0287", "Sales return → tax adjustment"),
    ("X-0288", "Purchase return → input-tax adjustment"),
    ("X-0289", "Credit note → tax liability adjustment"),
    ("X-0290", "Debit note → tax liability adjustment"),
    ("X-0291", "Purchase data → IMS matching"),
    ("X-0292", "IMS invoice → accept action"),
    ("X-0293", "IMS invoice → reject action"),
    ("X-0294", "IMS invoice → pending action"),
    ("X-0295", "Accepted invoice → ITC eligibility calculation"),
    ("X-0296", "Rejected invoice → ITC exclusion"),
    ("X-0297", "Missing supplier invoice → exception"),
    ("X-0298", "Invoice mismatch → exception"),
    ("X-0299", "Duplicate invoice → duplicate detection"),
    ("X-0300", "Supplier defect → supplier defect score updates"),
    ("X-0301", "ITC deadline approaching → alert"),
    ("X-0302", "ITC-at-risk invoice → credit-at-risk dashboard updates"),
    ("X-0303", "GST data correction → audit trail maintained"),
    ("X-0304", "GST return preparation → source transactions remain traceable"),
    ("X-0305", "Accountant reviews GST exception → exception resolved"),
    ("X-0306", "GST export → exported data reconciles with system"),

    # Receivables & Payables (X-0307 to X-0336)
    ("X-0307", "Customer purchases on credit"),
    ("X-0308", "Credit sale → customer ledger updated"),
    ("X-0309", "Customer payment → ledger updated"),
    ("X-0310", "Partial payment → balance maintained"),
    ("X-0311", "Advance payment → advance ledger maintained"),
    ("X-0312", "Payment allocation → payment applied to selected invoices"),
    ("X-0313", "Payment received → invoice status changes"),
    ("X-0314", "Invoice overdue → ageing bucket changes"),
    ("X-0315", "Customer crosses credit limit → alert generated"),
    ("X-0316", "Payment reminder → reminder generated"),
    ("X-0317", "Customer settles multiple invoices → allocation is maintained"),
    ("X-0318", "Credit note → customer balance changes"),
    ("X-0319", "Refund → customer balance changes"),
    ("X-0320", "Customer statement → all transactions are visible"),
    ("X-0321", "Owner reviews receivables → customer-level drill-down"),
    ("X-0322", "Accountant reconciles customer ledger → discrepancies identified"),
    ("X-0323", "Purchase creates supplier payable"),
    ("X-0324", "Supplier invoice updates payable"),
    ("X-0325", "Supplier payment reduces payable"),
    ("X-0326", "Partial supplier payment maintains balance"),
    ("X-0327", "Supplier advance is recorded"),
    ("X-0328", "Advance is adjusted against invoice"),
    ("X-0329", "Purchase return reduces payable"),
    ("X-0330", "Supplier credit note reduces payable"),
    ("X-0331", "Supplier statement is generated"),
    ("X-0332", "Supplier ageing is calculated"),
    ("X-0333", "Overdue supplier payment is identified"),
    ("X-0334", "Owner reviews supplier liabilities"),
    ("X-0335", "Accountant reconciles supplier ledger"),
    ("X-0336", "Supplier payment is linked to bank/cash transaction"),

    # Payments & Reconciliation (X-0337 to X-0352)
    ("X-0337", "Cash sale → cash balance increases"),
    ("X-0338", "UPI sale → digital payment is recorded"),
    ("X-0339", "Bank payment → bank ledger updates"),
    ("X-0340", "Customer payment → receivable decreases"),
    ("X-0341", "Supplier payment → payable decreases"),
    ("X-0342", "Expense payment → expense ledger updates"),
    ("X-0343", "Payment reversal → original payment remains traceable"),
    ("X-0344", "Failed payment → invoice remains appropriately unpaid"),
    ("X-0345", "Partial payment → outstanding remains"),
    ("X-0346", "Multiple payments → invoice settlement is accurate"),
    ("X-0347", "Daily cash closing → expected versus actual cash is compared"),
    ("X-0348", "Cash discrepancy → variance is recorded"),
    ("X-0349", "Bank reconciliation → unmatched transactions are identified"),
    ("X-0350", "Payment reconciliation → business ledger matches payment records"),
    ("X-0351", "Owner reviews cash position"),
    ("X-0352", "Owner drills cash balance into transactions"),

    # Sales / CRM / Customer Lifecycle (X-0353 to X-0368)
    ("X-0353", "Create new customer"),
    ("X-0354", "Update customer profile"),
    ("X-0355", "Duplicate customer detection"),
    ("X-0356", "Customer inquiry → lead created"),
    ("X-0357", "Lead → follow-up task created"),
    ("X-0358", "Lead → quotation created"),
    ("X-0359", "Quotation → sales order"),
    ("X-0360", "Sales order → invoice"),
    ("X-0361", "Customer purchase → customer history updated"),
    ("X-0362", "Customer purchase history → salesperson sees context"),
    ("X-0363", "Customer complaint → support case created"),
    ("X-0364", "Support case → responsible employee assigned"),
    ("X-0365", "Complaint resolved → customer history updated"),
    ("X-0366", "Customer referral → referral recorded"),
    ("X-0367", "Customer becomes inactive → follow-up opportunity identified"),
    ("X-0368", "Customer warranty/AMC → service obligation recorded"),

    # Returns / Complaints / After-Sales (X-0369 to X-0384)
    ("X-0369", "Customer requests return"),
    ("X-0370", "Salesperson creates return request"),
    ("X-0371", "Manager approves return"),
    ("X-0372", "Warehouse receives returned goods"),
    ("X-0373", "Returned goods inspected"),
    ("X-0374", "Good stock → inventory restored"),
    ("X-0375", "Damaged return → damaged inventory recorded"),
    ("X-0376", "Return → customer credit created"),
    ("X-0377", "Return → refund initiated"),
    ("X-0378", "Return → GST impact updated"),
    ("X-0379", "Customer complaint → support ticket"),
    ("X-0380", "Support ticket → owner/manager escalation"),
    ("X-0381", "Complaint resolution → customer notified"),
    ("X-0382", "Warranty claim → product/serial verified"),
    ("X-0383", "Warranty claim → service action recorded"),
    ("X-0384", "AMC renewal → customer follow-up generated"),

    # Reporting & Business Intelligence (X-0385 to X-0406)
    ("X-0385", "Transaction → sales dashboard updates"),
    ("X-0386", "Transaction → purchase dashboard updates"),
    ("X-0387", "Transaction → inventory dashboard updates"),
    ("X-0388", "Transaction → GST dashboard updates"),
    ("X-0389", "Transaction → receivables dashboard updates"),
    ("X-0390", "Transaction → payables dashboard updates"),
    ("X-0391", "Transaction → profitability dashboard updates"),
    ("X-0392", "Owner drills KPI → underlying transaction"),
    ("X-0393", "Owner drills transaction → source document"),
    ("X-0394", "Salesperson sees personal sales performance"),
    ("X-0395", "Manager sees team performance"),
    ("X-0396", "Owner sees consolidated business performance"),
    ("X-0397", "Multi-shop owner compares locations"),
    ("X-0398", "Distributor compares customers"),
    ("X-0399", "Distributor compares products"),
    ("X-0400", "Owner identifies high-value customers"),
    ("X-0401", "Owner identifies low-margin products"),
    ("X-0402", "Owner identifies dead stock"),
    ("X-0403", "Owner identifies fast-moving products"),
    ("X-0404", "Owner identifies overdue receivables"),
    ("X-0405", "Owner identifies supplier concentration"),
    ("X-0406", "Owner reviews business trends"),

    # Master Data & Authorization (X-0407 to X-0421)
    ("X-0407", "Admin creates product → salesperson can sell it"),
    ("X-0408", "Admin creates product → purchase manager can purchase it"),
    ("X-0409", "Product HSN → invoice uses correct HSN"),
    ("X-0410", "Product tax rate → invoice uses configured tax"),
    ("X-0411", "Product unit → inventory quantities use correct unit"),
    ("X-0412", "Product batch configuration → GRN captures batch"),
    ("X-0413", "Product serial configuration → sale captures serial"),
    ("X-0414", "Customer master → sales invoice uses customer details"),
    ("X-0415", "Supplier master → purchase invoice uses supplier details"),
    ("X-0416", "Customer GSTIN → tax treatment uses GST status"),
    ("X-0417", "Supplier GSTIN → purchase tax treatment uses supplier status"),
    ("X-0418", "Price list → salesperson sees appropriate price"),
    ("X-0419", "Customer-specific pricing → correct price appears"),
    ("X-0420", "User role → permitted actions are enforced"),
    ("X-0421", "Location assignment → user sees authorized location data"),

    # Security / Exception / Recovery (X-0422 to X-0444)
    ("X-0422", "Salesperson creates invoice → cannot modify restricted accounting fields"),
    ("X-0423", "Inventory user adjusts stock → authorization is enforced"),
    ("X-0424", "Accountant modifies GST data → audit trail is created"),
    ("X-0425", "Manager approves adjustment → approval identity is recorded"),
    ("X-0426", "User attempts unauthorized transaction → action is blocked"),
    ("X-0427", "User changes role → permissions immediately reflect policy"),
    ("X-0428", "User changes location → access follows assigned location"),
    ("X-0429", "Deactivated user → historical transactions remain intact"),
    ("X-0430", "Sensitive financial information → restricted users cannot access it"),
    ("X-0431", "Export data → export permissions are enforced"),
    ("X-0432", "Critical transaction → immutable audit trail exists"),
    ("X-0433", "Invalid invoice → actionable validation is shown"),
    ("X-0434", "Insufficient stock → sale is blocked/flagged appropriately"),
    ("X-0435", "Invalid GSTIN → invoice validation catches it"),
    ("X-0436", "Duplicate invoice → duplicate detection"),
    ("X-0437", "Network failure during save → no duplicate transaction is created"),
    ("X-0438", "Concurrent edits → conflict is handled"),
    ("X-0439", "Integration failure → transaction is not silently lost"),
    ("X-0440", "GST integration failure → exception is visible"),
    ("X-0441", "Bulk operation failure → successful and failed records are separated"),
    ("X-0442", "Incorrect transaction → authorized correction mechanism exists"),
    ("X-0443", "Cancellation → downstream impacts are correctly reversed"),
    ("X-0444", "System recovery → financial/inventory integrity is preserved"),

    # Communication & Integrations (X-0445 to X-0461)
    ("X-0445", "Invoice generated → invoice sent to customer through WhatsApp"),
    ("X-0446", "Payment reminder → customer receives reminder"),
    ("X-0447", "Order confirmation → customer receives confirmation"),
    ("X-0448", "Delivery update → customer receives update"),
    ("X-0449", "Return confirmation → customer receives confirmation"),
    ("X-0450", "Payment receipt → customer receives receipt"),
    ("X-0451", "Failed message → delivery status is visible"),
    ("X-0452", "User resends failed message"),
    ("X-0453", "Communication history remains associated with transaction/customer"),
    ("X-0454", "Payment gateway → payment status"),
    ("X-0455", "Payment gateway → customer ledger"),
    ("X-0456", "Payment gateway → invoice settlement"),
    ("X-0457", "Accounting export → downstream accounting"),
    ("X-0458", "Accounting data → reconciliation"),
    ("X-0459", "Integration failure → retry"),
    ("X-0460", "Integration retry → idempotent result"),
    ("X-0461", "External reference ID → BizBoard transaction traceability"),

    # Import / Export / Period Close (X-0462 to X-0494)
    ("X-0462", "Import customer master"),
    ("X-0463", "Import supplier master"),
    ("X-0464", "Import product master"),
    ("X-0465", "Import opening stock"),
    ("X-0466", "Import opening customer balances"),
    ("X-0467", "Import opening supplier balances"),
    ("X-0468", "Import historical invoices"),
    ("X-0469", "Import GST data"),
    ("X-0470", "Validate imported records"),
    ("X-0471", "Identify duplicate imported records"),
    ("X-0472", "Reject invalid records without corrupting valid records"),
    ("X-0473", "Export sales data"),
    ("X-0474", "Export purchase data"),
    ("X-0475", "Export inventory data"),
    ("X-0476", "Export GST data"),
    ("X-0477", "Export customer ledger"),
    ("X-0478", "Export supplier ledger"),
    ("X-0479", "Export accounting data"),
    ("X-0480", "Imported data becomes available to downstream modules"),
    ("X-0481", "Exported data reconciles with on-screen business data"),
    ("X-0482", "Cashier closes day's sales"),
    ("X-0483", "Cashier reconciles cash"),
    ("X-0484", "Digital payments are reconciled"),
    ("X-0485", "Owner reviews daily sales"),
    ("X-0486", "Owner reviews daily gross margin"),
    ("X-0487", "Owner reviews outstanding collections"),
    ("X-0488", "Owner reviews inventory movements"),
    ("X-0489", "Owner reviews exceptions"),
    ("X-0490", "Accountant reconciles sales"),
    ("X-0491", "Accountant reconciles purchases"),
    ("X-0492", "Accountant reconciles payments"),
    ("X-0493", "Period closing prevents unauthorized historical modification"),
    ("X-0494", "Period reports remain reproducible")
]

print(f"Loaded {len(RAW_TASKS)} Persona tasks and {len(CROSS_TASKS_DEFS)} Cross-Persona tasks.")
print(f"Total: {len(RAW_TASKS) + len(CROSS_TASKS_DEFS)} tasks.")
