# Generated by Django 5.2.16 on 2026-08-02 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_phase2_gst_returns_readiness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GstReturnPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(db_index=True, max_length=7)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SOFT_CLOSED', 'Soft Closed'), ('CLOSED', 'Closed')], default='OPEN', max_length=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('dirty_after_snapshot', models.BooleanField(default=False)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_return_periods', to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'period', 'status'], name='reporting_g_company_070a39_idx')],
                'unique_together': {('company', 'period')},
            },
        ),
        migrations.CreateModel(
            name='GstReturnSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_type', models.CharField(choices=[('GSTR1', 'Gstr1'), ('GSTR3B', 'Gstr3B'), ('GSTR9', 'Gstr9')], max_length=8)),
                ('period', models.CharField(db_index=True, max_length=16)),
                ('payload', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('builder_version', models.CharField(max_length=32)),
                ('generated_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_return_snapshots', to='accounts.company')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
                'indexes': [models.Index(fields=['company', 'return_type', 'period'], name='reporting_g_company_ce441a_idx')],
            },
        ),
    ]
