# Generated by Django 5.2.16 on 2026-08-04 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_wave16_gl_fifo_gstr2b'),
        ('purchases', '0016_wave13_return_batch_serial'),
        ('reporting', '0003_wave11b_snapshot_unique_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gstr2bIngest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(db_index=True, max_length=7)),
                ('supplier_gstin', models.CharField(blank=True, db_index=True, max_length=15)),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('PARTIAL', 'Partial'), ('REJECTED', 'Rejected')], default='UNMATCHED', max_length=12)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gstr2b_rows', to='accounts.company')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gstr2b_matches', to='purchases.purchaseinvoice')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'period', 'match_status'], name='reporting_g_company_75337c_idx')],
            },
        ),
    ]
