# Generated by Django 5.2.16 on 2026-08-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_wave16_gl_fifo_gstr2b'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstr2bingest',
            name='itc_eligibility',
            field=models.CharField(choices=[('CLAIMABLE', 'Claimable'), ('INELIGIBLE', 'Ineligible'), ('REVERSED', 'Reversed')], default='CLAIMABLE', max_length=12),
        ),
    ]
