# Generated by Django 5.2.17 on 2026-08-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_gstr2b_cess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstr2bingest',
            name='itc_eligibility',
            field=models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('CLAIMABLE', 'Claimable'), ('INELIGIBLE', 'Ineligible'), ('REVERSED', 'Reversed')], default='UNREVIEWED', max_length=12),
        ),
    ]
