# Generated by Django 5.2 on 2026-08-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0008_alter_gstr2bingest_itc_eligibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gstr2bingest",
            name="match_class",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="gstr2bingest",
            name="ims_action",
            field=models.CharField(db_index=True, default="NO_ACTION", max_length=16),
        ),
        migrations.AddField(
            model_name="gstr2bingest",
            name="ims_remark",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="gstr2bingest",
            name="acted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gstr2bingest",
            name="acted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gstr2bingest",
            name="submitted_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="gstr2bingest",
            name="ims_response",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="gstr2bingest",
            name="section_16_4_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="gstr2bingest",
            index=models.Index(fields=["company", "period", "ims_action"], name="reporting_g_company_ims_idx"),
        ),
        migrations.CreateModel(
            name="ImsActionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=16)),
                ("remark", models.CharField(blank=True, default="", max_length=512)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ims_action_history",
                        to="accounts.company",
                    ),
                ),
                (
                    "ingest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_history",
                        to="reporting.gstr2bingest",
                    ),
                ),
                (
                    "acted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.AddIndex(
            model_name="imsactionhistory",
            index=models.Index(fields=["company", "ingest"], name="reporting_i_company_ingest_idx"),
        ),
    ]
