# Generated by Django 5.2 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0009_ims_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="gstr2bingest",
            name="chase_status",
            field=models.CharField(db_index=True, default="none", max_length=16),
        ),
        migrations.AddField(
            model_name="gstr2bingest",
            name="chase_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gstr2bingest",
            name="chase_import_job_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
