# Generated by Django 5.2.17 on 2026-09-17 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_fixedasset_block_key_fixedasset_method_and_more'),
        ('accounts', '0050_companystatutorylicence'),
        ('inventory', '0018_cr053_opening_stock_void_append_only'),
        ('masters', '0018_product_regulated_category'),
        ('reporting', '0013_gstr2b_blank_unique'),
        ('sales', '0049_cft_quotation_converted_qty_amend_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProfitSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=32)),
                ('invoice_date', models.DateField(db_index=True)),
                ('invoice_status', models.CharField(max_length=12)),
                ('revenue_pre_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cogs_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_margin', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cost_basis', models.CharField(choices=[('FIFO', 'FIFO cost layers'), ('VALUATION_FALLBACK', 'Inventory valuation fallback'), ('PURCHASE_PRICE_FALLBACK', 'Product purchase-price fallback'), ('ZERO_COST', 'No cost basis found'), ('NO_COGS', 'No stock-tracked lines')], default='NO_COGS', max_length=24)),
                ('has_cogs_lines', models.BooleanField(default=False)),
                ('is_backfilled', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.costcenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.customer')),
                ('sales_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_snapshot', to='sales.salesinvoice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'invoice_date'], name='reporting_i_company_b0850b_idx'), models.Index(fields=['company', 'customer'], name='reporting_i_company_f7b335_idx'), models.Index(fields=['company', 'cost_basis'], name='reporting_i_company_0a972f_idx')],
            },
        ),
    ]
