# Generated by Django 5.2.17 on 2026-09-26 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_whatsapp_webhook_token'),
        ('reporting', '0014_invoiceprofitsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GstPeriodFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_type', models.CharField(max_length=16)),
                ('period', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='QUEUED', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'return_type', 'period'], name='reporting_g_company_008a2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'return_type', 'period', 'reference'), name='uniq_gst_period_filing_attempt')],
            },
        ),
    ]
