# Generated by Django 5.2.16 on 2026-08-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileasset',
            name='kind',
            field=models.CharField(choices=[('LOGO', 'Logo'), ('INVOICE_PDF', 'Invoice Pdf'), ('CREDIT_NOTE_PDF', 'Credit Note Pdf'), ('DEBIT_NOTE_PDF', 'Debit Note Pdf'), ('CHALLAN_PDF', 'Challan Pdf'), ('ATTACHMENT', 'Attachment'), ('IMPORT', 'Import'), ('EXPORT', 'Export')], default='ATTACHMENT', max_length=16),
        ),
    ]
