# Generated by Django 5.2.16 on 2026-08-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wave18_statutory_document_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutorydocumentevent',
            name='event_type',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('AMEND', 'Amend'), ('CANCEL', 'Cancel'), ('IRN', 'Irn'), ('EWAY', 'Eway')], max_length=16),
        ),
    ]
