# Generated by Django 5.2.17 on 2026-09-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rls_refund_dunning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(max_length=64),
        ),
    ]
