# Generated by Django 5.2.17 on 2026-09-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_company_require_open_period_for_posting'),
        ('core', '0020_rls_all_tenant_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='moneyfieldaudit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='statutorydocumentevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statutory_events', to='accounts.company'),
        ),
    ]
