# Generated by Django 5.2.17 on 2026-09-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rls_invoice_profit_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'Whatsapp'), ('SMS', 'Sms'), ('PUSH', 'Push'), ('TELEGRAM', 'Telegram')], max_length=16),
        ),
    ]
