# Generated by Django 5.2.17 on 2026-09-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rls_policy_renewal_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'Whatsapp'), ('SMS', 'Sms'), ('PUSH', 'Push'), ('TELEGRAM', 'Telegram'), ('IN_APP', 'In App')], max_length=16),
        ),
    ]
