# Generated by Django 5.2.17 on 2026-10-02 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_roadmap_items'),
        ('core', '0042_notification_channel_in_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='chain_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='chain_prev',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='chain_seq',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='sealed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.UniqueConstraint(condition=models.Q(('chain_seq__isnull', False)), fields=('company', 'chain_seq'), name='uniq_audit_chain_seq_per_company'),
        ),
    ]
