# Generated by Django 5.2.17 on 2026-10-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auditevent_append_only_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencyrecord',
            name='request_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
