import type { HelpIntent } from './types';
import helpCodes from './helpCodes.json';

const REVIEWED = '2026-08-30';

export const HELP_INTENTS: HelpIntent[] = [
  {
    intentId: 'add-gstin',
    type: 1,
    canonicalQuestion: 'How do I add or change my GSTIN?',
    userQueries: [
      'add gstin',
      'how do i add gstin',
      'gst number kaha dalu',
      'GSTIN kaise add kare',
      'change gstin',
      'company gstin missing',
      'multiple gstin complete',
      'gstn',
      'gstin kahan likhe',
      'मेरा GST नंबर कैसे डालूँ',
    ],
    answer: {
      en: 'A GSTIN is your 15-character GST number. Tax bills need it so the tax office can match the sale. Add it once in **t:nav.settings** → **t:nav.gst**. If you have more than one GSTIN, pick the right one on the bill before you press **t:common.complete**.',
      hi: 'GSTIN आपका 15 अक्षर का GST नंबर है। टैक्स बिल के लिए यह **t:nav.settings** → **t:nav.gst** में एक बार डालें। एक से ज्यादा GSTIN हों तो **t:common.complete** से पहले बिल पर सही वाला चुनें।',
    },
    action: {
      en: 'Ask the Owner to open **t:nav.settings** → **t:nav.gst**, type the 15 characters, and save. Regular registration also needs a GSTIN before you make a GST bill.',
      hi: 'Owner से कहें **t:nav.settings** → **t:nav.gst** खोलें, 15 अक्षर टाइप करें, और सेव करें। Regular रजिस्ट्रेशन पर GST बिल से पहले GSTIN ज़रूरी है।',
    },
    resolution: {
      en: 'Owner: open GST settings now. Anyone else: send this page to the Owner — only they can change GSTIN.',
      hi: 'Owner: अभी GST सेटिंग खोलें। बाकी लोग: यह पेज Owner को भेजें — GSTIN सिर्फ वे बदल सकते हैं।',
    },
    errorCodes: ['company_gstin_required'],
    priority: 9,
    category: 'GST & tax',
    nextStep: {
      label: 'Open GST settings',
      destination: '/settings/gst',
      permission: 'owner',
      fallback: 'Ask the Owner to add your GSTIN in **t:nav.settings** → **t:nav.gst**.',
      escalation: 'Only the Owner can change GSTIN.',
    },
    relatedIntents: ['registration-type', 'cannot-complete-invoice'],
    citedKeys: ['nav.settings', 'nav.gst', 'common.complete'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'sell-blocked',
    type: 6,
    canonicalQuestion: "Why can't I add this item to a bill?",
    userQueries: [
      "why can't i sell this",
      'item nahi add ho raha',
      'cannot sell',
      'blocked item',
      'inactive product',
      'party blocked',
      'maal nahi ja raha',
      'reserved stock',
      'reserved quantity on this bill',
      'item blocked on bill',
      'ग्राहक ब्लॉक है',
    ],
    answer: {
      en: 'The bill is blocked for one of three reasons: no stock in the **t:inventory.godown** on this bill, the item is inactive, or this customer is blocked. Company-wide "available" on the Products list can still look fine if the stock sits in another **t:inventory.godown**.',
      hi: 'बिल तीन वजहों से रुकता है: इस बिल वाले **t:inventory.godown** में स्टॉक नहीं, आइटम inactive है, या ग्राहक ब्लॉक है। प्रोडक्ट लिस्ट पर कुल "available" ठीक दिख सकता है अगर माल दूसरे **t:inventory.godown** में है।',
    },
    action: {
      en: 'Read the error. It names the **t:inventory.godown** it checked. Pick that store on the bill, move stock with a **t:nav.stockTransfers**, ask the Owner to set the item **t:status.ACTIVE**, or unblock the customer.',
      hi: 'एरर पढ़ें — वह **t:inventory.godown** बताता है। बिल पर वही स्टोर चुनें, **t:nav.stockTransfers** से माल लाएँ, Owner से आइटम **t:status.ACTIVE** करवाएँ, या ग्राहक अनब्लॉक करवाएँ।',
    },
    resolution: {
      en: 'If the error names another **t:inventory.godown**, open stock and transfer — or change the **t:inventory.godown** on this bill.',
      hi: 'अगर एरर दूसरा **t:inventory.godown** बताए तो स्टॉक खोलकर ट्रांसफर करें, या इस बिल का **t:inventory.godown** बदलें।',
    },
    errorCodes: ['inactive_product', 'blocked_customer'],
    priority: 10,
    category: 'Stock & Godowns',
    diagnosis: [
      {
        id: 'no-stock-here',
        symptom: 'The error says there is not enough stock in this Godown',
        intentId: 'stock-in-another-godown',
      },
      {
        id: 'inactive',
        symptom: 'The item is inactive or stopped',
        answer: 'Inactive items cannot go on a new bill. That stops old SKUs from being sold by mistake.',
        action: 'Ask the Owner to open the item and set status to **t:status.ACTIVE** — only if you still sell it.',
        resolution: 'Owner: Products → the item → **t:status.ACTIVE**. Then add it to the bill again.',
      },
      {
        id: 'blocked-party',
        symptom: 'The customer is blocked',
        answer: 'A blocked customer cannot get a new bill. This is a credit or compliance hold set by the Owner.',
        action: 'Ask the Owner to unblock the customer, or pick a different customer.',
        resolution: 'Owner: Customers → the party → set status back to active.',
      },
      {
        id: 'login',
        symptom: 'The screen says your login cannot do this',
        intentId: 'login-cant-do-this',
      },
    ],
    nextStep: {
      label: 'Check stock by Godown',
      destination: '/inventory/stock',
      permission: 'can_manage_inventory',
      fallback: 'Ask the Owner to check stock or unblock the customer.',
    },
    relatedIntents: ['stock-in-another-godown', 'login-cant-do-this'],
    citedKeys: ['inventory.godown', 'nav.stockTransfers', 'status.ACTIVE'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'cannot-complete-invoice',
    type: 6,
    canonicalQuestion: 'Why is Complete greyed out or failing?',
    userQueries: [
      'cannot complete invoice',
      'complete button disabled',
      'complete fail ho raha',
      'save and complete error',
      'bill complete nahi ho raha',
      'greyed out complete',
      'nahi ban raha bill',
      'complete grey ho gaya',
      'बिल पूरा नहीं हो रहा',
      'credit limit exceeded',
      'place of supply missing',
    ],
    answer: {
      en: '**t:common.complete** (this marks the bill final — you cannot change it after) needs a customer, at least one item, and a known place of supply on GST bills. Stock, credit limit, registration type, a closed period, or an unticked reverse-charge box can also block it.',
      hi: '**t:common.complete** बिल को फाइनल करता है — बाद में लाइन नहीं बदल सकते। ग्राहक, कम से कम एक आइटम, और GST बिल पर जगह (place of supply) चाहिए। स्टॉक, क्रेडिट लिमिट, रजिस्ट्रेशन टाइप, बंद पीरियड, या बिना टिक reverse-charge भी रोक सकता है।',
    },
    action: {
      en: 'Read the red message on the bill. Use **t:help.why** for the exact fix. Common: add the customer **t:auth.state** or GSTIN, pick a **t:inventory.godown** that has stock, or switch to a non-GST bill type if you are Unregistered.',
      hi: 'बिल पर लाल मैसेज पढ़ें। ठीक वजह के लिए **t:help.why** दबाएँ। अक्सर: ग्राहक का **t:auth.state** या GSTIN भरें, स्टॉक वाले **t:inventory.godown** चुनें, या Unregistered हों तो नॉन-GST बिल टाइप लें।',
    },
    resolution: {
      en: 'Fix the named cause, then press **t:common.complete** again.',
      hi: 'जो वजह लिखी है उसे ठीक करें, फिर **t:common.complete** दबाएँ।',
    },
    errorCodes: [
      'registration_gate',
      'place_of_supply_unresolved',
      'credit_limit_exceeded',
      'sales_rcm_unconfirmed',
      'closed_period',
    ],
    priority: 10,
    category: 'Bills',
    diagnosis: [
      {
        id: 'pos',
        symptom: 'It asks for customer state or GSTIN',
        answer: 'GST needs to know which state the sale counts in (**Place of supply**).',
        action: 'Open the customer on the bill and fill **t:auth.state** or **GSTIN**, then save.',
        resolution: 'The warning box on the bill lets you add state/GSTIN without leaving.',
      },
      {
        id: 'stock',
        symptom: 'It says insufficient stock',
        intentId: 'stock-in-another-godown',
      },
      {
        id: 'reg',
        symptom: 'It says Unregistered or Composition cannot issue a GST bill',
        intentId: 'registration-type',
      },
      {
        id: 'credit',
        symptom: 'It says credit limit exceeded',
        answer: 'This customer already owes enough that this bill would go over the limit the Owner set.',
        action: 'Take a receipt, ask the Owner to raise the limit, or reduce the bill.',
        resolution: 'Receipts match money to old bills and free up the limit.',
      },
      {
        id: 'rcm',
        symptom: 'It asks to confirm sales reverse charge',
        answer: 'Reverse charge means the buyer pays the GST, not you. Bizboard will not **t:common.complete** until you tick the confirm box.',
        action: 'Tick **Confirm sales RCM** on the bill only if this sale is truly reverse charge.',
        resolution: 'If it is not reverse charge, turn that option off.',
      },
      {
        id: 'period',
        symptom: 'It says the GST or accounts period is closed',
        answer: 'A closed period means money on bills in that month is locked for GST or books.',
        action: 'Ask the Owner. They can reopen the period, or use a credit note in an open month.',
        resolution: 'Do not try to **t:common.complete** or amend money in a closed month.',
      },
    ],
    nextStep: {
      label: 'Open this bill',
      destination: '/sales/history/:id/edit',
      permission: 'can_create_sales',
      fallback: 'Open the bill from Sales history and read the red message.',
      escalation: 'Ask someone who can create sales to open this bill.',
    },
    prevention: [
      {
        slot: 'invoice-complete',
        appliesWhen: 'always',
        text: '**t:common.complete** marks this bill done. You cannot edit lines after. Need a change later? Use a credit note.',
      },
      {
        slot: 'invoice-complete',
        appliesWhen: 'multi-godown',
        text: 'This bill takes stock from one **t:inventory.godown** only. If stock sits in another store, change **t:inventory.godown** first or transfer stock.',
      },
    ],
    relatedIntents: ['stock-in-another-godown', 'registration-type', 'edit-completed-invoice', 'add-gstin'],
    citedKeys: ['common.complete', 'inventory.godown', 'help.why', 'auth.state'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'wrong-gst-on-invoice',
    type: 6,
    canonicalQuestion: 'Why is GST on this bill wrong?',
    userQueries: [
      'wrong gst',
      'cgst sgst vs igst',
      'gst rate galat',
      'tax inclusive',
      'same state igst',
      'GST split wrong',
      'tax galat pad raha',
      'CGST SGST गलत',
      'रेट गलत है',
    ],
    answer: {
      en: 'Same-state sales show **t:billing.cgst**+**t:billing.sgst**. Different-state sales show **t:billing.igst**. The split follows your company state (or the GSTIN on the bill) vs the customer **Place of supply**. The rate must be a real GST slab (0, 5, 12, 18, 28). **Tax inclusive** means the price you type already has GST inside it.',
      hi: 'एक ही राज्य की सेल पर **t:billing.cgst**+**t:billing.sgst**, दूसरे राज्य पर **t:billing.igst**। यह आपकी कंपनी के राज्य (या बिल के GSTIN) बनाम ग्राहक के **Place of supply** से तय होता है। रेट असली स्लैब होना चाहिए (0, 5, 12, 18, 28)। **Tax inclusive** का मतलब टाइप की कीमत में GST पहले से है।',
    },
    action: {
      en: 'Check customer **t:auth.state**/GSTIN and company GSTIN. If the price already includes GST, set **Price mode** to Tax inclusive. Do not type a made-up rate like 17%.',
      hi: 'ग्राहक का **t:auth.state**/GSTIN और कंपनी GSTIN चेक करें। कीमत में GST पहले से हो तो **Price mode** को Tax inclusive करें। 17% जैसी बनावटी रेट न लिखें।',
    },
    resolution: {
      en: 'Fix state or rate on the draft, then **t:common.complete**. A done bill needs a credit note to change tax.',
      hi: 'ड्राफ्ट पर राज्य या रेट ठीक करें, फिर **t:common.complete**। हो चुके बिल पर टैक्स बदलने के लिए credit note चाहिए।',
    },
    errorCodes: ['invalid_gst_rate'],
    priority: 8,
    category: 'GST & tax',
    diagnosis: [
      {
        id: 'rate',
        symptom: 'The rate is not in the GST slab list',
        answer: 'India GST only allows set slabs. A rate like 17% is rejected.',
        action: 'Pick 0, 5, 12, 18, or 28 on the line — the same as the item’s GST rate.',
        resolution: 'Change the line rate on the draft bill.',
      },
      {
        id: 'split',
        symptom: 'Same state shows IGST, or different state shows CGST+SGST',
        answer: 'The split follows which state the sale counts in, from GSTIN digits or **t:auth.state**.',
        action: 'Correct customer **t:auth.state** or GSTIN. If you have several company GSTINs, pick the branch that made the sale.',
        resolution: 'Save the party, then look at the tax preview again.',
      },
      {
        id: 'inclusive',
        symptom: 'The total looks too high — GST added on top of a tax-in price',
        answer: 'If the price you type already has GST inside it, the bill must be **Tax inclusive**.',
        action: 'Set **Price mode** to Tax inclusive on this bill.',
        resolution: 'The line total should then match what you quoted the customer.',
      },
    ],
    nextStep: {
      label: 'Open this bill',
      destination: '/sales/history/:id/edit',
      permission: 'can_create_sales',
      fallback: 'Open the draft bill and check **Price mode**, rate, and customer state.',
    },
    relatedIntents: ['add-gstin', 'registration-type'],
    citedKeys: ['common.complete', 'auth.state', 'billing.cgst', 'billing.sgst', 'billing.igst'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'stock-in-another-godown',
    type: 4,
    canonicalQuestion: 'The Products list shows stock, but billing says insufficient stock. Why?',
    userQueries: [
      'insufficient stock',
      'stock dikh raha hai but cannot sell',
      'available 0 godown',
      'stock in another godown',
      'warehouse mismatch',
      'maal dusre gudam me hai',
      'on hand vs available',
      'stock dusre store me',
      'गोडाउन में माल नहीं',
    ],
    answer: {
      en: '**Available** on the Products list is the total across every **t:inventory.godown** (your store or stock location). A bill takes stock from **one** **t:inventory.godown** — the one on the bill, or the default if none is chosen. **Available** on a bill is on hand minus reserved (already promised on open drafts/orders).',
      hi: 'प्रोडक्ट लिस्ट का **Available** हर **t:inventory.godown** का जोड़ है। बिल सिर्फ **एक** **t:inventory.godown** से माल काटता है — बिल वाला, या डिफ़ॉल्ट। बिल पर **Available** = हाथ में माल माइनस रिज़र्व (ड्राफ्ट/ऑर्डर पर बंधा)।',
    },
    action: {
      en: 'Change **t:inventory.godown** on the bill to the store that holds the stock, or move stock with **t:nav.stockTransfers** first.',
      hi: 'बिल का **t:inventory.godown** उस स्टोर पर बदलें जहाँ माल है, या पहले **t:nav.stockTransfers** करें।',
    },
    resolution: {
      en: 'The error names the **t:inventory.godown** it checked and lists where the stock actually is.',
      hi: 'एरर बताता है किस **t:inventory.godown** में चेक किया और माल कहाँ है।',
    },
    errorCodes: ['insufficient_stock'],
    priority: 10,
    category: 'Stock & Godowns',
    nextStep: {
      label: 'Open current stock',
      destination: '/inventory/stock',
      permission: 'can_manage_inventory',
      fallback: 'Ask the Owner to transfer stock or change the **t:inventory.godown** on the bill.',
    },
    relatedIntents: ['sell-blocked', 'cannot-complete-invoice'],
    citedKeys: ['inventory.godown', 'nav.stockTransfers'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'unit-conversion-rate',
    type: 1,
    canonicalQuestion: 'How do I set the conversion rate between a base unit and an alternate unit?',
    userQueries: [
      'conversion rate',
      'carton pieces',
      '1 carton = 50',
      'uom',
      'unit of measure',
      'alternate unit',
      'peti kitne piece',
      'box pcs',
      'unit field blank',
      'base vs alternate',
      'invioce unit',
      'carton me kitne piece',
      'यूनिट कैसे सेट करें',
    ],
    answer: {
      en: 'The **t:products.unit** is how stock is counted. An alternate unit is optional for billing — for example stock in PCS, sell by CARTON. The conversion rate is how many **base** units sit in **one** alternate unit. Example: 1 carton = 50 pieces → type `50`. After the first stock movement the base unit is locked so old quantities stay meaningful.',
      hi: '**t:products.unit** से स्टॉक गिना जाता है। अल्टरनेट यूनिट बिलिंग के लिए वैकल्पिक है — जैसे स्टॉक PCS में, सेल CARTON में। कन्वर्जन रेट: **एक** अल्टरनेट में कितने **base** यूनिट। उदाहरण: 1 कार्टन = 50 पीस → `50` लिखें। पहली स्टॉक एंट्री के बाद बेस यूनिट लॉक हो जाती है।',
    },
    action: {
      en: 'On the item, pick the smallest unit you count in as **t:products.unit**. Add the bulk unit as alternate. Type how many base units are in one alternate (`50`, not `0.02`, unless you really stock in cartons).',
      hi: 'आइटम पर सबसे छोटी गिनती **t:products.unit** चुनें। बल्क यूनिट अल्टरनेट में डालें। एक अल्टरनेट में कितने बेस हैं लिखें (`50`, न कि `0.02`, जब तक आप कार्टन में स्टॉक न रखते हों)।',
    },
    resolution: {
      en: 'Open the item. If the unit is grey, it already has stock history — reverse or adjust stock before changing the unit.',
      hi: 'आइटम खोलें। यूनिट ग्रे हो तो स्टॉक हिस्ट्री है — यूनिट बदलने से पहले रिवर्स या एडजस्ट करें।',
    },
    resolutionSteps: [
      'Open the item.',
      'Set **t:products.unit** to PCS (or your smallest unit).',
      'Set alternate unit to CARTON.',
      'Type `50` if one carton holds 50 pieces.',
    ],
    errorCodes: [],
    priority: 7,
    category: 'Items & Units',
    nextStep: {
      label: 'Open products',
      destination: '/inventory/products',
      permission: 'can_manage_inventory',
      fallback: 'Ask the Owner to set the conversion rate on the item.',
    },
    relatedIntents: ['sell-blocked'],
    citedKeys: ['products.unit'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'registration-type',
    type: 5,
    canonicalQuestion: 'Regular vs Composition vs Unregistered — what changes?',
    userQueries: [
      'registration type',
      'composition vs regular',
      'unregistered gst bill',
      'bill of supply',
      'regular taxpayer',
      'composition scheme',
      'composition kya hota',
      'अनरेजिस्टर्ड GST बिल',
    ],
    answer: {
      en: '**Regular** issues GST tax invoices (CGST+SGST or IGST). **Composition** issues a bill of supply — no GST split on the bill. **Unregistered** also cannot issue a GST/TAX bill with CGST/SGST/IGST. This is set at sign-up and in **t:nav.settings** → **t:nav.gst**.',
      hi: '**Regular** GST टैक्स इनवॉइस बनाता है (CGST+SGST या IGST)। **Composition** बिल ऑफ सप्लाई बनाता है — बिल पर GST स्प्लिट नहीं। **Unregistered** भी GST/TAX बिल नहीं काट सकता। यह साइन-अप और **t:nav.settings** → **t:nav.gst** में सेट होता है।',
    },
    action: {
      en: 'If you are Unregistered or Composition, use a **Non-GST** bill type. Only Regular should pick GST / Tax / Retail with tax.',
      hi: 'Unregistered या Composition हों तो **Non-GST** बिल टाइप चुनें। टैक्स वाला GST / Tax / Retail सिर्फ Regular के लिए है।',
    },
    resolution: {
      en: 'Owner: confirm **t:setup.registrationType** in **t:nav.settings** → **t:nav.gst**. Changing it later changes what bills you are allowed to make.',
      hi: 'Owner: **t:nav.settings** → **t:nav.gst** में **t:setup.registrationType** चेक करें। बाद में बदलने से बनने वाले बिल बदल जाते हैं।',
    },
    errorCodes: ['registration_gate'],
    priority: 8,
    category: 'GST & tax',
    nextStep: {
      label: 'Open GST settings',
      destination: '/settings/gst',
      permission: 'owner',
      fallback: 'Ask the Owner. Registration type is set in **t:nav.settings** → **t:nav.gst**.',
    },
    prevention: [
      {
        slot: 'signup-registration-type',
        appliesWhen: 'always',
        text: 'Pick carefully. **Regular** needs a GSTIN and issues tax invoices. **Composition** and **Unregistered** cannot issue GST tax invoices.',
      },
    ],
    relatedIntents: ['add-gstin', 'cannot-complete-invoice'],
    citedKeys: ['nav.settings', 'nav.gst', 'setup.registrationType'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'payment-wont-allocate',
    type: 6,
    canonicalQuestion: "Why won't a receipt attach to a bill?",
    userQueries: [
      'receipt not matching',
      'unapplied amount',
      'allocate payment',
      'payment wont allocate',
      'advance showing',
      'receipt bill match nahi ho raha',
      'recieve not applying',
      'payment allocate nahi ho raha',
      'रसीद बिल पर नहीं लग रही',
    ],
    answer: {
      en: 'Matching a receipt to a bill (what accounts call allocation) needs a **posted** receipt, a **t:common.complete**d bill, the same customer, and an amount no larger than what is still unapplied on the receipt or still unpaid on the bill.',
      hi: 'रसीद को बिल से मिलाने (allocation) के लिए रसीद **posted** हो, बिल **t:common.complete** हो, वही ग्राहक हो, और रकम रसीद की बची हुई या बिल की बाकी रकम से ज्यादा न हो।',
    },
    action: {
      en: 'Complete the bill first if it is still a draft. Check the customer matches. Lower the match amount to the leftover on the receipt.',
      hi: 'ड्राफ्ट हो तो पहले **t:common.complete** करें। ग्राहक एक ही हो। रकम रसीद की बची हुई तक घटाएँ।',
    },
    resolution: {
      en: 'Open Receipts, pick the receipt, and press **t:common.allocate** for only the leftover amount.',
      hi: 'Receipts खोलें, रसीद चुनें, और सिर्फ बची रकम मिलाएँ।',
    },
    errorCodes: ['allocation_exceeds_unallocated', 'allocation_party_mismatch'],
    priority: 8,
    category: 'Payments',
    diagnosis: [
      {
        id: 'party',
        symptom: 'It says the receipt customer must match the bill',
        answer: 'Money from one party cannot close another party’s bill.',
        action: 'Pick the receipt that belongs to this customer, or pick the right bill.',
        resolution: 'Open Receipts and filter by that customer.',
      },
      {
        id: 'amount',
        symptom: 'It says the amount is more than unapplied',
        answer: 'Part of this receipt is already matched to other bills.',
        action: 'Match only the leftover (unapplied) amount.',
        resolution: 'The receipt row shows how much is still unapplied.',
      },
      {
        id: 'draft',
        symptom: 'The bill is still a draft',
        answer: 'Only a **t:common.complete**d bill can take a receipt.',
        action: 'Press **t:common.complete** on the bill, then match the receipt.',
        intentId: 'cannot-complete-invoice',
      },
    ],
    nextStep: {
      label: 'Open receipts',
      destination: '/sales/receipts',
      permission: 'can_create_sales',
      fallback: 'Ask someone who can take receipts to match this payment to the bill.',
    },
    relatedIntents: ['cannot-complete-invoice'],
    citedKeys: ['common.complete', 'common.allocate'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'edit-completed-invoice',
    type: 8,
    canonicalQuestion: "Why can't I edit a bill I already marked Complete?",
    userQueries: [
      'cannot edit completed invoice',
      'change done bill',
      'credit note instead of edit',
      'invoice immutable',
      'complete ke baad edit',
      'done bill change nahi',
      'कंप्लीट बिल एडिट नहीं',
      'delete invoice',
      'void bill',
      'undo completed invoice',
    ],
    answer: {
      en: 'A bill you marked **t:common.complete** is done. You cannot change the customer. Money or tax changes need the Owner and may be blocked if the GST period is closed. For a wrong qty or rate, issue a **t:nav.creditNotes** (a bill that reduces what the customer owes) instead of rewriting history.',
      hi: '**t:common.complete** वाला बिल हो चुका। ग्राहक नहीं बदल सकते। पैसे या टैक्स बदलने के लिए Owner चाहिए, और GST पीरियड बंद हो तो रुक सकता है। गलत मात्रा/रेट पर **t:nav.creditNotes** बनाएँ — इतिहास न लिखें।',
    },
    action: {
      en: 'Open a **t:nav.creditNotes** against this bill, or a debit note if you under-billed. Do not try to unlock **t:common.complete**. The Owner can **t:common.cancel** the bill if it should never have been issued.',
      hi: 'इस बिल पर credit note खोलें, या कम बिल हो तो debit note। **t:common.complete** को अनलॉक न करें।',
    },
    resolution: {
      en: 'Sales → Credit notes → new, linked to this invoice.',
      hi: 'Sales → Credit notes → नया, इस इनवॉइस से लिंक।',
    },
    errorCodes: ['completed_immutable'],
    priority: 8,
    category: 'Bills',
    nextStep: {
      label: 'Create a credit note',
      destination: '/sales/credit-notes/new?invoiceId=:id',
      permission: 'can_create_sales',
      fallback: 'Ask the Owner. A done bill is changed with a credit note, not by editing.',
      escalation: 'Ask the Owner to issue a credit note or cancel this bill if it should not have been issued.',
      cancelDestination: '/sales/history/:id?helpAction=cancel',
    },
    prevention: [
      {
        slot: 'delete-with-history',
        appliesWhen: 'always',
        text: 'If this already has history, deleting it will fail. Reverse or cancel with the proper action instead.',
      },
    ],
    relatedIntents: ['cannot-complete-invoice'],
    citedKeys: ['common.complete', 'nav.creditNotes', 'common.cancel'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'import-row-errors',
    type: 6,
    canonicalQuestion: 'Why does my Excel or Tally import show red rows?',
    userQueries: [
      'import errors',
      'red rows import',
      'csv commit blocked',
      'excel import fail',
      'tally import error',
      'fix all errors before commit',
      'excel red rows kyun',
      'इम्पोर्ट में लाल लाइनें',
      'products import',
      'commit blocked',
    ],
    answer: {
      en: 'Preview lists every row that cannot be saved — missing name, bad GST rate, unknown SKU, and so on. For a **Products** file, one bad row blocks the whole commit so you do not get a half-imported catalogue.',
      hi: 'प्रीव्यू हर वो पंक्ति दिखाता है जो सेव नहीं हो सकती — नाम नहीं, गलत GST रेट, अनजान SKU। **Products** फाइल में एक खराब पंक्ति पूरा commit रोकती है ताकि आधा कैटलॉग न आए।',
    },
    action: {
      en: 'Download the error list, fix those cells, re-upload. Required columns: products need `name`; opening stock needs `sku` and `quantity`.',
      hi: 'एरर लिस्ट डाउनलोड करें, सेल ठीक करें, फिर अपलोड करें। प्रोडक्ट में `name` चाहिए; ओपनिंग स्टॉक में `sku` और `quantity`।',
    },
    resolution: {
      en: 'Stay on the preview step until the red count is 0, then commit.',
      hi: 'लाल गिनती 0 होने तक प्रीव्यू पर रहें, फिर commit करें।',
    },
    errorCodes: ['import_invalid_rows'],
    priority: 7,
    category: 'Import',
    nextStep: {
      label: 'Open import',
      destination: '/settings/import',
      permission: 'can_import',
      fallback: 'Ask the Owner. Import is an Owner or import-permission job.',
      escalation: 'Ask the Owner to open **t:nav.importData** and fix the red rows.',
    },
    diagnosis: [
      {
        id: 'missing-name',
        symptom: 'A row is missing a name or another required cell',
        answer: 'That column is required. Empty required cells cannot be saved.',
        action: 'Fill the named cell on those rows, save the file, and upload again.',
        resolution: 'Required columns are listed on the import page before you upload.',
      },
      {
        id: 'bad-rate',
        symptom: 'A GST rate is not a real slab',
        answer: 'Product GST must be a legal slab such as 0, 5, 12, 18, or 28 — not 17%.',
        action: 'Change the rate cell, re-upload, then commit.',
        resolution: 'The error list names the row and the bad rate.',
      },
      {
        id: 'unknown-sku',
        symptom: 'Opening stock names a SKU that is not in products',
        answer: 'Opening stock can only add quantity to items that already exist.',
        action: 'Import or create the product first, then import opening stock.',
        resolution: 'The error row shows the unknown SKU.',
      },
      {
        id: 'one-bad-row',
        symptom: 'One red row blocked the whole Products commit',
        answer: 'A Products file is all-or-nothing so you never get a half catalogue.',
        action: 'Fix every red row (or remove it), re-upload, then **t:common.commit**.',
        resolution: 'Commit stays blocked until the red count is 0.',
      },
    ],
    relatedIntents: ['login-cant-do-this', 'unit-conversion-rate'],
    citedKeys: ['nav.importData', 'common.commit'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'pdf-or-share-unavailable',
    type: 2,
    canonicalQuestion: 'Why is the invoice PDF or WhatsApp share missing?',
    userQueries: [
      'pdf not ready',
      'cannot share invoice',
      'whatsapp bill nahi ja raha',
      'share greyed out',
      'thermal receipt missing',
      'pdf nahi ban raha',
      'व्हाट्सएप बिल नहीं जा रहा',
      'pdf generating',
    ],
    answer: {
      en: 'PDF and **t:common.share** work after the bill is **t:common.complete**. The PDF can take a few seconds to build. Share also needs an email or mobile, including **t:common.whatsapp**.',
      hi: 'PDF और शेयर **t:common.complete** के बाद चलते हैं। PDF बनने में कुछ सेकंड लग सकते हैं। शेयर के लिए ग्राहक पर ईमेल या मोबाइल भी चाहिए।',
    },
    action: {
      en: '**t:common.complete** the bill first. Wait for PDF status to finish. Add phone or email on the customer, then share again.',
      hi: 'पहले बिल **t:common.complete** करें। PDF तैयार होने का इंतज़ार करें। ग्राहक पर फोन या ईमेल डालें, फिर शेयर करें।',
    },
    resolution: {
      en: 'Open the bill detail. When it is completed and PDF is ready, use **t:common.share**.',
      hi: 'बिल डिटेल खोलें। पूरा हो और PDF तैयार हो तो **t:common.share** दबाएँ।',
    },
    errorCodes: ['pdf_or_share_unavailable'],
    priority: 6,
    category: 'Bills',
    diagnosis: [
      {
        id: 'draft',
        symptom: 'The bill is still a draft',
        intentId: 'cannot-complete-invoice',
      },
      {
        id: 'building',
        symptom: 'It says the PDF is not ready yet',
        answer: 'Bizboard is still drawing the PDF. This usually takes a few seconds.',
        action: 'Wait, refresh the bill, then open PDF again.',
        resolution: 'If it stays queued, ask the Owner — the PDF worker may be down.',
      },
      {
        id: 'contact',
        symptom: 'No phone or email to send to',
        answer: 'WhatsApp needs a mobile number. Email needs an address on the customer.',
        action: 'Add phone or email on the customer, then share.',
        resolution: 'Customers → the party → phone / email.',
      },
    ],
    nextStep: {
      label: 'Open this bill',
      destination: '/sales/history/:id',
      permission: 'can_create_sales',
      fallback: 'Open the completed bill from Sales history to print or share.',
      escalation: 'Ask someone who can open sales bills to print or share this one.',
    },
    relatedIntents: ['cannot-complete-invoice'],
    citedKeys: ['common.complete', 'common.share', 'common.whatsapp'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'login-cant-do-this',
    type: 8,
    canonicalQuestion: 'Why does it say my login cannot do this?',
    userQueries: [
      'permission denied',
      'owner admin role required',
      'your login cannot',
      'insufficient permissions',
      'staff cannot open gst',
      'access denied',
      'login nahi kar sakta ye',
      'आपका लॉगिन यह नहीं कर सकता',
      'viewer cannot',
      'viewer cannot create invoice',
    ],
    answer: {
      en: 'Each login has a role: Owner, Sales Staff, Accountant, or Viewer, plus extra ticks (import, stock, cancel). GST settings, users, and many company changes are Owner-only. A red **t:billing.accessDenied** message is on purpose — not a bug.',
      hi: 'हर लॉगिन की भूमिका होती है: Owner, Sales Staff, Accountant, या Viewer, और अतिरिक्त टिक (import, stock, cancel)। GST सेटिंग, यूज़र, और कई कंपनी बदलाव सिर्फ Owner के हैं। यह जानबूझकर है — बग नहीं।',
    },
    action: {
      en: 'Ask the Owner. They can do the action, or tick the extra permission on **t:nav.settings** → **t:nav.users**.',
      hi: 'Owner से कहें। वे काम कर सकते हैं, या **t:nav.settings** → **t:nav.users** पर अनुमति टिक कर सकते हैं।',
    },
    resolution: {
      en: 'There is no self-serve override. Send the Owner this screen.',
      hi: 'खुद से ओवरराइड नहीं है। यह स्क्रीन Owner को भेजें।',
    },
    errorCodes: ['permission_denied'],
    priority: 6,
    category: 'Access',
    nextStep: {
      label: 'Open users',
      destination: '/settings/users',
      permission: 'owner',
      fallback: 'Ask the Owner. Your login does not include this action.',
      escalation: 'Only the Owner can change roles on **t:nav.settings** → **t:nav.users**.',
    },
    citedKeys: ['nav.settings', 'nav.users', 'billing.accessDenied'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'purchase-bill-blocked',
    type: 2,
    canonicalQuestion: 'Why is my purchase bill blocked or incomplete?',
    userQueries: [
      'cannot complete purchase bill',
      'purchase invoice nahi ban raha',
      'supplier bill complete fail',
      'purchase greyed out',
      'खरीद बिल पूरा नहीं हो रहा',
      'purchase complete nahi ho raha',
      'purchase bill',
      'supplier bill',
      'khareed bill',
    ],
    answer: {
      en: 'A purchase bill uses the same complete rules as a sales bill: supplier, date, lines, and GST must be filled. If stock or GST is wrong, **t:common.complete** stays blocked. Returns and debit notes are separate from editing a done purchase.',
      hi: 'खरीद बिल भी सेल्स की तरह **t:common.complete** से बंद होता है — सप्लायर, तारीख, लाइनें और GST पूरे हों। स्टॉक या GST गलत हो तो बटन रुकता है।',
    },
    action: {
      en: 'Open **t:nav.purchases** → **t:nav.purchaseHistory**. Fix the supplier and lines, then press **t:common.complete**. For a scanned paper bill use **t:nav.uploadBill**.',
      hi: '**t:nav.purchases** → **t:nav.purchaseHistory** खोलें। सप्लायर और लाइनें ठीक करें, फिर **t:common.complete** दबाएँ। कागज़ के बिल के लिए **t:nav.uploadBill**।',
    },
    resolution: {
      en: 'If Complete still fails, read the error and open Help from **Why?** — the same GST and stock fixes apply.',
      hi: 'Complete फिर भी फेल हो तो एरर पढ़ें और **Why?** से Help खोलें — GST और स्टॉक के वही हल लगते हैं।',
    },
    errorCodes: [],
    priority: 9,
    category: 'Purchases',
    nextStep: {
      label: 'Open purchases',
      destination: '/purchases/history',
      permission: 'can_create_purchases',
      fallback: 'Ask someone who can enter purchases to open **t:nav.purchases**.',
    },
    relatedIntents: ['cannot-complete-invoice', 'import-row-errors'],
    citedKeys: ['nav.purchases', 'nav.purchaseHistory', 'nav.uploadBill', 'common.complete'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'books-journal-blocked',
    type: 1,
    canonicalQuestion: 'How do I post a journal or open the books?',
    userQueries: [
      'how to post journal',
      'trial balance nahi khul raha',
      'accounting not enabled',
      'books health journal',
      'जर्नल कैसे डालें',
      'accounts nahi khul rahe',
      'journal entry',
      'trial balance menu',
    ],
    answer: {
      en: 'Journals, trial balance and P&L live under **t:nav.accounting**. The Owner must turn books on in accounting settings first. A journal must balance (debit = credit) before it posts.',
      hi: 'जर्नल, ट्रायल बैलेंस और P&L **t:nav.accounting** में हैं। पहले Owner अकाउंटिंग सेटिंग में बुक्स चालू करें। जर्नल तभी पोस्ट होता है जब डेबिट = क्रेडिट।',
    },
    action: {
      en: 'Owner: open **t:nav.accounting** → **t:nav.journals**. If the menu is missing, turn books on in accounting settings. Staff: ask the Owner — posting journals needs that permission.',
      hi: 'Owner: **t:nav.accounting** → **t:nav.journals** खोलें। मेनू न दिखे तो अकाउंटिंग सेटिंग में बुक्स चालू करें।',
    },
    resolution: {
      en: 'When books are on, **t:nav.trialBalance** and **t:nav.profitAndLoss** use the same posted journals.',
      hi: 'बुक्स चालू हों तो **t:nav.trialBalance** और **t:nav.profitAndLoss** उन्हीं जर्नल से बनते हैं।',
    },
    errorCodes: [],
    priority: 8,
    category: 'Accounting',
    nextStep: {
      label: 'Open journals',
      destination: '/accounting/journals',
      permission: 'can_post_journals',
      fallback: 'Ask the Owner to turn on books and post the journal in **t:nav.accounting**.',
    },
    relatedIntents: ['login-cant-do-this'],
    citedKeys: ['nav.accounting', 'nav.journals', 'nav.trialBalance', 'nav.profitAndLoss'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'trial-ended-readonly',
    type: 2,
    canonicalQuestion: 'Why is the workspace read-only after trial ended?',
    userQueries: [
      'trial ended',
      'subscription suspended',
      'workspace read only',
      'cannot save bill trial',
      'ट्रायल खत्म हो गया',
      'subscription band ho raha',
      'plan expired',
      'trial over',
      'workspace locked',
    ],
    answer: {
      en: 'When the trial ends or the subscription is paused, Bizboard blocks new saves so GST books stay consistent. You can still open reports. The banner says the workspace is read-only.',
      hi: 'ट्रायल खत्म या सब्सक्रिप्शन रुकने पर नई सेव बंद हो जाती है ताकि GST किताबें सुरक्षित रहें। रिपोर्ट खुलती हैं। बैनर read-only दिखाता है।',
    },
    action: {
      en: 'The Owner opens **t:nav.settings** → **t:nav.billing** and renews. Until then, do not expect **t:common.complete** or **t:common.save** to work.',
      hi: 'Owner **t:nav.settings** → **t:nav.billing** खोलकर रिन्यू करें। तब तक **t:common.complete** या **t:common.save** काम नहीं करेंगे।',
    },
    resolution: {
      en: 'After payment succeeds, refresh once. Writes return without reinstalling the app.',
      hi: 'पेमेंट सफल होने के बाद एक बार रिफ्रेश करें। ऐप फिर से इंस्टॉल करने की ज़रूरत नहीं।',
    },
    errorCodes: [],
    priority: 9,
    category: 'Billing',
    nextStep: {
      label: 'Open billing',
      destination: '/settings/billing',
      permission: 'owner',
      fallback: 'Ask the Owner to renew in **t:nav.settings** → **t:nav.billing**.',
    },
    relatedIntents: ['login-cant-do-this'],
    citedKeys: ['nav.settings', 'nav.billing', 'common.complete', 'common.save'],
    lastReviewed: REVIEWED,
  },
  {
    intentId: 'offline-outbox-stuck',
    type: 4,
    canonicalQuestion: 'Why are my offline drafts not syncing?',
    userQueries: [
      'offline outbox',
      'draft not syncing',
      'saved offline will sync',
      'outbox pending',
      'ऑफलाइन ड्राफ्ट नहीं जा रहा',
      'offline sync nahi ho raha',
      'offline drafts',
      'drafts on this phone',
    ],
    answer: {
      en: 'Bills started without internet are stored on this device in the **t:offlineOutbox.title**. They are not on the server until sync succeeds. Anyone with this browser profile can read them.',
      hi: 'बिना इंटरनेट शुरू बिल इस डिवाइस के **t:offlineOutbox.title** में रहते हैं। सिंक सफल होने तक सर्वर पर नहीं। इस ब्राउज़र प्रोफ़ाइल वाला कोई भी उन्हें पढ़ सकता है।',
    },
    action: {
      en: 'Go online, open **t:offlineOutbox.title**, press **t:offlineOutbox.syncNow**. Fix any red error on the row, then sync again.',
      hi: 'ऑनलाइन होकर **t:offlineOutbox.title** खोलें, **t:offlineOutbox.syncNow** दबाएँ। लाल एरर ठीक करके फिर सिंक करें।',
    },
    resolution: {
      en: 'After sync, the bill appears in **t:nav.salesHistory**. Do not duplicate it by creating a second bill.',
      hi: 'सिंक के बाद बिल **t:nav.salesHistory** में दिखेगा। दूसरा बिल बनाकर डुप्लीकेट न करें।',
    },
    errorCodes: [],
    priority: 8,
    category: 'Offline',
    nextStep: {
      label: 'Open offline outbox',
      destination: '/offline-outbox',
      permission: 'can_create_sales',
      fallback: 'Ask someone who bills on this device to open the offline outbox and press **t:offlineOutbox.syncNow**.',
    },
    relatedIntents: ['cannot-complete-invoice', 'pdf-or-share-unavailable'],
    citedKeys: ['offlineOutbox.title', 'offlineOutbox.syncNow', 'nav.salesHistory'],
    lastReviewed: REVIEWED,
  },
];

export const HELP_CATEGORIES = [
  'Bills',
  'Purchases',
  'Stock & Godowns',
  'Items & Units',
  'GST & tax',
  'Payments',
  'Accounting',
  'Billing',
  'Offline',
  'Import',
  'Access',
];

const BY_ID = new Map(HELP_INTENTS.map((intent) => [intent.intentId, intent]));

export function getHelpIntent(id: string | undefined | null): HelpIntent | undefined {
  if (!id) return undefined;
  return BY_ID.get(id);
}

export const ERROR_CODE_TO_INTENT: Record<string, string> = helpCodes.errorCodeToIntent;
export const ERROR_CODE_TO_LEAF: Record<string, string> = helpCodes.errorCodeToLeaf ?? {};

export function intentForErrorCode(code: string | null | undefined): string | undefined {
  if (!code) return undefined;
  return ERROR_CODE_TO_INTENT[code];
}

export function leafForErrorCode(code: string | null | undefined): string | undefined {
  if (!code) return undefined;
  return ERROR_CODE_TO_LEAF[code];
}
