/** Founder-owned fixture: real phrasings, kept apart from userQueries. */
export const RESOLVER_FIXTURES: { query: string; intentId: string }[] = [
  { query: "why can't i sell this", intentId: 'sell-blocked' },
  { query: 'item nahi add ho raha', intentId: 'sell-blocked' },
  { query: 'cannot sell', intentId: 'sell-blocked' },
  { query: 'blocked item', intentId: 'sell-blocked' },
  { query: 'inactive product', intentId: 'sell-blocked' },
  { query: 'party blocked', intentId: 'sell-blocked' },
  { query: 'maal nahi ja raha', intentId: 'sell-blocked' },
  { query: 'item blocked on bill', intentId: 'sell-blocked' },
  { query: 'ग्राहक ब्लॉक है', intentId: 'sell-blocked' },
  { query: 'reserved stock', intentId: 'sell-blocked' },
  { query: 'insufficient stock', intentId: 'stock-in-another-godown' },
  { query: 'stock dikh raha hai but cannot sell', intentId: 'stock-in-another-godown' },
  { query: 'maal dusre gudam me hai', intentId: 'stock-in-another-godown' },
  { query: 'available 0 godown', intentId: 'stock-in-another-godown' },
  { query: 'stock in another godown', intentId: 'stock-in-another-godown' },
  { query: 'warehouse mismatch', intentId: 'stock-in-another-godown' },
  { query: 'on hand vs available', intentId: 'stock-in-another-godown' },
  { query: 'stock dusre store me', intentId: 'stock-in-another-godown' },
  { query: 'गोडाउन में माल नहीं', intentId: 'stock-in-another-godown' },
  { query: 'how do i add gstin', intentId: 'add-gstin' },
  { query: 'GSTIN kaise add kare', intentId: 'add-gstin' },
  { query: 'gstn', intentId: 'add-gstin' },
  { query: 'add gstin', intentId: 'add-gstin' },
  { query: 'gst number kaha dalu', intentId: 'add-gstin' },
  { query: 'change gstin', intentId: 'add-gstin' },
  { query: 'company gstin missing', intentId: 'add-gstin' },
  { query: 'multiple gstin complete', intentId: 'add-gstin' },
  { query: 'gstin kahan likhe', intentId: 'add-gstin' },
  { query: 'मेरा GST नंबर कैसे डालूँ', intentId: 'add-gstin' },
  { query: 'cannot complete invoice', intentId: 'cannot-complete-invoice' },
  { query: 'complete button disabled', intentId: 'cannot-complete-invoice' },
  { query: 'bill complete nahi ho raha', intentId: 'cannot-complete-invoice' },
  { query: 'complete fail ho raha', intentId: 'cannot-complete-invoice' },
  { query: 'save and complete error', intentId: 'cannot-complete-invoice' },
  { query: 'greyed out complete', intentId: 'cannot-complete-invoice' },
  { query: 'nahi ban raha bill', intentId: 'cannot-complete-invoice' },
  { query: 'complete grey ho gaya', intentId: 'cannot-complete-invoice' },
  { query: 'बिल पूरा नहीं हो रहा', intentId: 'cannot-complete-invoice' },
  { query: 'wrong gst', intentId: 'wrong-gst-on-invoice' },
  { query: 'cgst sgst vs igst', intentId: 'wrong-gst-on-invoice' },
  { query: 'tax inclusive', intentId: 'wrong-gst-on-invoice' },
  { query: 'gst rate galat', intentId: 'wrong-gst-on-invoice' },
  { query: 'same state igst', intentId: 'wrong-gst-on-invoice' },
  { query: 'GST split wrong', intentId: 'wrong-gst-on-invoice' },
  { query: 'tax galat pad raha', intentId: 'wrong-gst-on-invoice' },
  { query: 'CGST SGST गलत', intentId: 'wrong-gst-on-invoice' },
  { query: 'conversion rate', intentId: 'unit-conversion-rate' },
  { query: '1 carton = 50', intentId: 'unit-conversion-rate' },
  { query: 'peti kitne piece', intentId: 'unit-conversion-rate' },
  { query: 'invioce unit', intentId: 'unit-conversion-rate' },
  { query: 'carton pieces', intentId: 'unit-conversion-rate' },
  { query: 'uom', intentId: 'unit-conversion-rate' },
  { query: 'unit of measure', intentId: 'unit-conversion-rate' },
  { query: 'alternate unit', intentId: 'unit-conversion-rate' },
  { query: 'box pcs', intentId: 'unit-conversion-rate' },
  { query: 'unit field blank', intentId: 'unit-conversion-rate' },
  { query: 'carton me kitne piece', intentId: 'unit-conversion-rate' },
  { query: 'यूनिट कैसे सेट करें', intentId: 'unit-conversion-rate' },
  { query: 'composition vs regular', intentId: 'registration-type' },
  { query: 'unregistered gst bill', intentId: 'registration-type' },
  { query: 'registration type', intentId: 'registration-type' },
  { query: 'bill of supply', intentId: 'registration-type' },
  { query: 'regular taxpayer', intentId: 'registration-type' },
  { query: 'composition scheme', intentId: 'registration-type' },
  { query: 'composition kya hota', intentId: 'registration-type' },
  { query: 'अनरेजिस्टर्ड GST बिल', intentId: 'registration-type' },
  { query: 'receipt not matching', intentId: 'payment-wont-allocate' },
  { query: 'unapplied amount', intentId: 'payment-wont-allocate' },
  { query: 'recieve not applying', intentId: 'payment-wont-allocate' },
  { query: 'allocate payment', intentId: 'payment-wont-allocate' },
  { query: 'payment wont allocate', intentId: 'payment-wont-allocate' },
  { query: 'advance showing', intentId: 'payment-wont-allocate' },
  { query: 'receipt bill match nahi ho raha', intentId: 'payment-wont-allocate' },
  { query: 'payment allocate nahi ho raha', intentId: 'payment-wont-allocate' },
  { query: 'रसीद बिल पर नहीं लग रही', intentId: 'payment-wont-allocate' },
  { query: 'cannot edit completed invoice', intentId: 'edit-completed-invoice' },
  { query: 'credit note instead of edit', intentId: 'edit-completed-invoice' },
  { query: 'change done bill', intentId: 'edit-completed-invoice' },
  { query: 'invoice immutable', intentId: 'edit-completed-invoice' },
  { query: 'complete ke baad edit', intentId: 'edit-completed-invoice' },
  { query: 'done bill change nahi', intentId: 'edit-completed-invoice' },
  { query: 'कंप्लीट बिल एडिट नहीं', intentId: 'edit-completed-invoice' },
  { query: 'import errors', intentId: 'import-row-errors' },
  { query: 'red rows import', intentId: 'import-row-errors' },
  { query: 'csv commit blocked', intentId: 'import-row-errors' },
  { query: 'excel import fail', intentId: 'import-row-errors' },
  { query: 'tally import error', intentId: 'import-row-errors' },
  { query: 'fix all errors before commit', intentId: 'import-row-errors' },
  { query: 'excel red rows kyun', intentId: 'import-row-errors' },
  { query: 'इम्पोर्ट में लाल लाइनें', intentId: 'import-row-errors' },
  { query: 'pdf not ready', intentId: 'pdf-or-share-unavailable' },
  { query: 'whatsapp bill nahi ja raha', intentId: 'pdf-or-share-unavailable' },
  { query: 'cannot share invoice', intentId: 'pdf-or-share-unavailable' },
  { query: 'share greyed out', intentId: 'pdf-or-share-unavailable' },
  { query: 'thermal receipt missing', intentId: 'pdf-or-share-unavailable' },
  { query: 'pdf nahi ban raha', intentId: 'pdf-or-share-unavailable' },
  { query: 'व्हाट्सएप बिल नहीं जा रहा', intentId: 'pdf-or-share-unavailable' },
  { query: 'permission denied', intentId: 'login-cant-do-this' },
  { query: 'staff cannot open gst', intentId: 'login-cant-do-this' },
  { query: 'owner admin role required', intentId: 'login-cant-do-this' },
  { query: 'your login cannot', intentId: 'login-cant-do-this' },
  { query: 'insufficient permissions', intentId: 'login-cant-do-this' },
  { query: 'access denied', intentId: 'login-cant-do-this' },
  { query: 'login nahi kar sakta ye', intentId: 'login-cant-do-this' },
  { query: 'आपका लॉगिन यह नहीं कर सकता', intentId: 'login-cant-do-this' },
  { query: 'available vs on hand', intentId: 'stock-in-another-godown' },
  { query: 'reserved quantity blocking this sale', intentId: 'sell-blocked' },
  { query: 'base vs alternate', intentId: 'unit-conversion-rate' },
  { query: 'tax inclusive price mode', intentId: 'wrong-gst-on-invoice' },
  { query: 'credit limit exceeded complete', intentId: 'cannot-complete-invoice' },
  { query: 'place of supply missing', intentId: 'cannot-complete-invoice' },
  { query: 'godown mismatch stock', intentId: 'stock-in-another-godown' },
  { query: 'how to add company gst number', intentId: 'add-gstin' },
  { query: 'why complete greyed', intentId: 'cannot-complete-invoice' },
  { query: 'igst showing same state', intentId: 'wrong-gst-on-invoice' },
  { query: 'how many pcs in carton', intentId: 'unit-conversion-rate' },
  { query: 'receipt unapplied leftover', intentId: 'payment-wont-allocate' },
  { query: 'cannot change completed bill customer', intentId: 'edit-completed-invoice' },
  { query: 'products import commit blocked', intentId: 'import-row-errors' },
  { query: 'invoice pdf generating', intentId: 'pdf-or-share-unavailable' },
  { query: 'viewer cannot create invoice', intentId: 'login-cant-do-this' },
  { query: 'supplier bill save and complete stuck', intentId: 'purchase-bill-blocked' },
  { query: 'khareed bill complete nahi', intentId: 'purchase-bill-blocked' },
  { query: 'where is journal entry screen', intentId: 'books-journal-blocked' },
  { query: 'trial balance menu missing', intentId: 'books-journal-blocked' },
  { query: 'plan expired cannot type invoice', intentId: 'trial-ended-readonly' },
  { query: 'billing page renew after trial', intentId: 'trial-ended-readonly' },
  { query: 'phone offline drafts waiting', intentId: 'offline-outbox-stuck' },
  { query: 'sync queued bills when wifi back', intentId: 'offline-outbox-stuck' },
  { query: 'nahi ban raha invoice', intentId: 'cannot-complete-invoice' },
  { query: "can't create this bill", intentId: 'cannot-complete-invoice' },
  { query: 'delete this invoice', intentId: 'edit-completed-invoice' },
  { query: 'void a completed bill', intentId: 'edit-completed-invoice' },
  { query: 'how units work', intentId: 'unit-conversion-rate' },
  { query: 'unit setup on product', intentId: 'unit-conversion-rate' },
  { query: 'reserved quantity blocking this sale', intentId: 'sell-blocked' },
  { query: 'godown on the bill has zero qty', intentId: 'stock-in-another-godown' },
  { query: 'type conversion between box and pcs', intentId: 'unit-conversion-rate' },
  { query: 'unregistered shop gst tax invoice', intentId: 'registration-type' },
  { query: 'advance leftover after receipt save', intentId: 'payment-wont-allocate' },
  { query: 'need credit note after complete', intentId: 'edit-completed-invoice' },
  { query: 'tally xml rows all red', intentId: 'import-row-errors' },
  { query: 'whatsapp share button still grey', intentId: 'pdf-or-share-unavailable' },
  { query: 'accountant login gst settings locked', intentId: 'login-cant-do-this' },
  { query: 'supplier GST bill will not finalise', intentId: 'purchase-bill-blocked' },
  { query: 'purchase complete button stays grey', intentId: 'purchase-bill-blocked' },
  { query: 'accountant menu journals grey', intentId: 'books-journal-blocked' },
  { query: 'enable books for trial balance page', intentId: 'books-journal-blocked' },
  { query: 'renew plan workspace typing blocked', intentId: 'trial-ended-readonly' },
  { query: 'banner says read only after trial', intentId: 'trial-ended-readonly' },
  { query: 'wifi back still drafts in outbox', intentId: 'offline-outbox-stuck' },
  { query: 'queued invoices waiting on this device', intentId: 'offline-outbox-stuck' },
  { query: 'gstin field empty on company', intentId: 'add-gstin' },
  { query: 'complete stays disabled missing party state', intentId: 'cannot-complete-invoice' },
  { query: 'igst on a local customer', intentId: 'wrong-gst-on-invoice' },
];

/** Unseen phrasings (not copied from userQueries) — field-test gate HR-2.1. */
export const FIELD_TEST_FIXTURES: { query: string; intentId: string }[] = [
  { query: 'gst number kahan likhu in settings', intentId: 'add-gstin' },
  { query: 'bill complete button grey', intentId: 'cannot-complete-invoice' },
  { query: 'maal dusre store mein pada hai', intentId: 'stock-in-another-godown' },
  { query: 'peti me kitne pcs hote hain', intentId: 'unit-conversion-rate' },
  { query: 'composition scheme se gst bill', intentId: 'registration-type' },
  { query: 'receipt bill pe apply nahi ho raha', intentId: 'payment-wont-allocate' },
  { query: 'complete ke baad line change', intentId: 'edit-completed-invoice' },
  { query: 'excel me red rows kyun aa rahe', intentId: 'import-row-errors' },
  { query: 'share pdf whatsapp nahi khul raha', intentId: 'pdf-or-share-unavailable' },
  { query: 'staff gst settings nahi khol sakta', intentId: 'login-cant-do-this' },
  { query: 'purchase bill button grey supplier', intentId: 'purchase-bill-blocked' },
  { query: 'turn on books to post journal', intentId: 'books-journal-blocked' },
  { query: 'trial over workspace locked', intentId: 'trial-ended-readonly' },
  { query: 'offline drafts sitting on this phone', intentId: 'offline-outbox-stuck' },
];

export const STATE_FIXTURES: { query: string; state: 'confident' | 'ambiguous' | 'diagnostic' | 'no-match' }[] = [
  { query: 'how do i add gstin', state: 'confident' },
  { query: "why can't i sell this", state: 'diagnostic' },
  { query: 'gst', state: 'ambiguous' },
  { query: 'invoice problem', state: 'ambiguous' },
  { query: 'stock issue', state: 'ambiguous' },
  { query: 'gst help', state: 'ambiguous' },
  { query: 'problem with invoice', state: 'ambiguous' },
  { query: 'my stock issue', state: 'ambiguous' },
  { query: 'zxqwertyasdfgh', state: 'no-match' },
];
